### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by StanleySong** [alibaba/BizCharts#100]
Can you guys translate to English?

**Comment by weepy3641** [comment]
@StanleySong 
Actually we are translating the documents into english now。
That‘s will be gradually released.
You can focus on the doc_en directory。

Plan to complete the doc translation before the Spring Festival。

https://github.com/alibaba/BizCharts/issues/52

**Comment by heiniuhaha** [comment]
great! 
I am looking forward to the English version.

**Comment by maracuja-juice** [comment]
How's it going with the English version?

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/tree/master/doc_en

We have been finished translate jobs and published [doc_en](https://github.com/alibaba/BizCharts/tree/master/doc_en
) directory.
Welcome to visit it and review the translation. Give us PR if you find any typos.

**Comment by maracuja-juice** [comment]
@weepy3641 Sounds good. I'll try it out!

**Comment by ouma-h** [comment]
Hello! the link you provided above is not working. where can i find the english version please?
thank you.

**Comment by vidhi998** [comment]
Same problem, the link provided for the English docs is not working!! Please provide the updated link.
