### ISSUE TITLE
关于BizCharts横坐标刻度的问题

### ISSUE THREAD

**Issue by Noa-p** [alibaba/BizCharts#1005]
- bizcharts Version: ^3.5.5
- Platform or react version: react ^16.8.5

我传过来的数据是：
![image](https://user-images.githubusercontent.com/43284700/68187135-d0a8ee80-ffe0-11e9-9636-84e97aec6cca.png)

显示成图表时不显示时间：
![image](https://user-images.githubusercontent.com/43284700/68187175-e9190900-ffe0-11e9-80be-bfaf4ad84c12.png)

请问是怎么回事？

**Comment by mzl980425** [comment]
https://bizcharts.alibaba-inc.com/products/bizCharts/api/scale?from=search#mask

**Comment by Leannechn** [comment]
设置padding属性 padding={['auto', 'auto', 'auto', 'auto']}

**Comment by Leannechn** [comment]
上 右 下 左，number | 'auto'
