### ISSUE TITLE
Legend 图例的默认显示和隐藏，缺少可用api

### ISSUE THREAD

**Issue by D-kylin** [alibaba/BizCharts#1015]
- bizcharts Version:3.5.4
- Platform or react version:16.8.6
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/23113263/68448029-1baf4580-021d-11ea-8c14-62f249e9690e.png)

- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

查找过G2的文档也没有找到对应的api，目前了解到的是echarts中Lengend中的selected属性是支持传入数组来控制默认值的。
![image](https://user-images.githubusercontent.com/23113263/68448117-69c44900-021d-11ea-9f62-7b902eea1781.png)

**Comment by D-kylin** [comment]
解决方案，结合 chart 组件的 filter 属性来实现预选功能。
具体细节：由于项目中使用了 React Hooks ，所以只贴出基于 React Hooks Api 的实现。
1、用变量保存图表实例，如果是使用 class 组件可直接保存在 this 上。
![image](https://user-images.githubusercontent.com/23113263/68575977-25001280-04a8-11ea-86c2-90ee957f4e2e.png)
2、动态设置图表实例的 filter 属性，这里 useEffect 函数第二个参数数组可看到有一个依赖，当依赖 selectedData 改变时，就重新赋值图表实例的 filter 属性。
![image](https://user-images.githubusercontent.com/23113263/68576100-6ee8f880-04a8-11ea-9195-200488df4fa4.png)
3、代码比较多，但是关键代码是红色箭头的一行，这个是控制图表的 loading 状态，false 时图表不显示，true 时显示。图表的 filter 属性的执行周期是发生在显示图表前，所以 filter 功能如果依赖数据，那依赖数据必须在图表显示前就存在值。
![image](https://user-images.githubusercontent.com/23113263/68577023-36e2b500-04aa-11ea-837f-b8daafc67941.png)

以上就是给 Legend 设置默认选中项的实现方式，如果您有更优雅的实现方式欢迎讨论，这个[issue](https://github.com/alibaba/BizCharts/issues/465) 你可以看到 class 组件的实现思路。希望后续官方能给出更好的解决方案，Legend 的预选是很常见的需求。

**Comment by pwq309** [comment]
查了半天文档发现不支持，希望官方能支持这个特性

**Comment by Leannechn** [comment]
https://bizcharts.net/product/bizcharts/category/7/page/24#filter 可以完成以上功能

**Comment by molee1905** [comment]
```jsx
const DEFAULT_LEGEND = ['18-24岁', '25-29岁'];
const [selectedData, setSelectedData] = useState(DEFAULT_LEGEND);// legend 默认展现的数据

const mockData = [
    {age: "18-24岁",time: 1584201600000,value: 0.1},
    {age: "25-29岁",time: 1584028800000,value: 0.5},
    {age: "30-34岁",time: 1585411200000,value: 0.75},
    {age: "35-39岁",time: 1586275200000,value: 0.99},
    ...
];
....
return <Chart
          data={mockData}
          forceFit
          placeholder
          padding='auto'
          filter={[// 通过filter 配合 Legend的 onClick 实现默认展现一部分数据，另一部分通过点击动态展示
            ['age', (val) => {
              return selectedData.includes(val);
            }]
          ]}
        >
          <Legend
            name='age' // data 里的age
            onClick={event => {// 通过filter 配合 Legend的 onClick 实现默认展现一部分数据，另一部分通过点击动态展示
              const { item, checked } = event;
              const index = selectedData.indexOf(item.value);
              if (checked) {
                if (index === -1) {// 不存在，则添加
                  setSelectedData([
                    ...selectedData,
                    item.value,
                  ]);
                }
              } else {
                if (index > -1) {// 存在，则移除
                  setSelectedData([
                    ...selectedData.slice().splice(index, 1)
                  ])
                }
              }
            }}
          />
          <Axis name='value' />
          <Axis name='time' />
          <Geom
            type='line'
            position='time*value'
            color={'name'}
          />
        </Chart>
```

**Comment by kyriejoshua** [comment]
> [bizcharts.net/product/bizcharts/category/7/page/24#filter](https://bizcharts.net/product/bizcharts/category/7/page/24#filter) 可以完成以上功能

链接失效了，请问方便直接贴出代码实现吗？目前 3.x 版本似乎还是不支持直接设置图例的显示隐藏。
