### ISSUE TITLE
legend使用useHtml的时候设置g2-legend的margin-top配置并不起效

### ISSUE THREAD

**Issue by ysyszrj** [alibaba/BizCharts#1017]
- bizcharts Version:
3.5.5
- Platform or react version:
16.11.0
- Mini Showcase(like screenshots):
https://bizcharts.net/products/bizCharts/api/legend#g2-legend 文档里面说的marginTop并不能生效，会默认使用margin-top: 6px
```
<Legend position='bottom'
  useHtml={true}
  g2-legend = {{
    marginLeft: '100px',
    marginTop: '-107px'
  }}
  g2-legend-list={{
    border: 'none'
  }}
/>
```
- CodePen Link:
https://codesandbox.io/s/g2-legendshezhimargintopwuxiao-bug-j2vsy
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by yuc8939** [comment]
Having the same issue here. Any solutions?

**Comment by yuc8939** [comment]
CSS properties marginTop and marginLeft in g2-legend does not work. Use [offsetX](https://bizcharts.net/products/bizCharts/api/legend#offsetx) and [offsetY](https://bizcharts.net/products/bizCharts/api/legend#offsety) as walkaround.

**Comment by ysyszrj** [comment]
感谢，文档还是有点误导人的。
