### ISSUE TITLE
饼图的填充颜色和color设置的颜色不同

### ISSUE THREAD

**Issue by lf75152798** [alibaba/BizCharts#1018]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/33650737/68633645-9c2bba00-052d-11ea-9c4d-0968347f2a7f.png)
饼图渲染的 图层颜色和设置的颜色有偏差  ，左边是我配置的颜色'#2775E3' 右边是实际饼图展示的颜色。柱状图也存在这样子的问题。
直接在你们的 基础实例https://bizcharts.net/products/bizCharts/demo/detail?id=pie-labelline&selectedKey=%E9%A5%BC%E5%9B%BE 中就能复现

**Comment by Leannechn** [comment]
是因为默认设置了opacity。可以在style中控制。
