### ISSUE TITLE
Is there support for multiple x or y axis hierarchy?

### ISSUE THREAD

**Issue by zach-ivoyant** [alibaba/BizCharts#1029]
- bizcharts Version: 3.5.5
- Platform or react version: 16.8

- Same question but for chartsjs: https://stackoverflow.com/questions/46977049/chartjs-2-multi-level-hierarchical-category-axis-in-chartjs

- CodePen Link: https://jsfiddle.net/6qsfkkn6/

I want to have the x-axis have a hierarchy as seen in the links above. Is this possible with BizCharts?

**Comment by weepy3641** [comment]
sorry，bizcharts don't support the x-axis have a hierarchy.
