### ISSUE TITLE
treemap没有完全填充canvas

### ISSUE THREAD

**Issue by preservance717** [alibaba/BizCharts#1037]
- bizcharts Version: 3.5.5
- Platform or react version:16.8.0
- Mini Showcase(like screenshots):

一开始是充满整个canvas：
![121574826781_ pic](https://user-images.githubusercontent.com/18299850/69692301-8660ec00-110c-11ea-8a2a-fadfc3692a60.jpg)

当数据进来时，则会有空白区域出现：
![111574825852_ pic_hd](https://user-images.githubusercontent.com/18299850/69692240-5ade0180-110c-11ea-8df6-c726412a76c2.jpg)

chart配置如下：
![image](https://user-images.githubusercontent.com/18299850/69692347-b14b4000-110c-11ea-9ee1-f396c3c88917.png)

这个是什么问题呢？

**Comment by qykingle** [comment]
同问

**Comment by qykingle** [comment]
> * bizcharts Version: 3.5.5
> * Platform or react version:16.8.0
> * Mini Showcase(like screenshots):
> 
> 一开始是充满整个canvas：
> ![121574826781_ pic](https://user-images.githubusercontent.com/18299850/69692301-8660ec00-110c-11ea-8a2a-fadfc3692a60.jpg)
> 
> 当数据进来时，则会有空白区域出现：
> ![111574825852_ pic_hd](https://user-images.githubusercontent.com/18299850/69692240-5ade0180-110c-11ea-8df6-c726412a76c2.jpg)
> 
> chart配置如下：
> ![image](https://user-images.githubusercontent.com/18299850/69692347-b14b4000-110c-11ea-9ee1-f396c3c88917.png)
> 
> 这个是什么问题呢？

你解决了么？

**Comment by preservance717** [comment]
嗯，将布局算法`treemapSquarify`改成`treemapBinary`就可以啦

**Comment by preservance717** [comment]
嗯，将布局算法treemapSquarify改成treemapBinary就可以啦
但至于为什么`treemapSquarify`不能正常使用，就不清楚啦

**Comment by preservance717** [comment]
嗯，将布局算法`treemapSquarify`改成`treemapBinary`就可以啦
但至于为什么`treemapSquarify`不能正常使用，就不清楚啦

**Comment by qykingle** [comment]
> 嗯，将布局算法`treemapSquarify`改成`treemapBinary`就可以啦
> 但至于为什么`treemapSquarify`不能正常使用，就不清楚啦

666，完美解决我的问题，感谢，回复的这么快！！！
