### ISSUE TITLE
forceFit goes out of div

### ISSUE THREAD

**Issue by bardiaheshmati** [alibaba/BizCharts#104]
What is the best way to fit a chart in a div, currently forceFit pushes the chart out of the div , make <Col></Col> scrollable ? is there anyway to fix this ?

**Comment by BambooSword** [comment]
If you use forceFit, the chart will inherit the width of the parent element, the width set by the user does not take effect.

**Comment by bardiaheshmati** [comment]
i guess that means width of the parent element without the consideration of padding ...

**Comment by weepy3641** [comment]
reference to
https://github.com/alibaba/BizCharts/issues/75
