### ISSUE TITLE
官方文档太坑爹了，看看highcharts的文档吧，做的什么玩意，坑死了

### ISSUE THREAD

**Issue by luo1994** [alibaba/BizCharts#1041]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by wangxingkang** [comment]
开源的东西 没必要这样吧 你觉得不好 可以去提PR完善啊

**Comment by luo1994** [comment]
喷不是为了喷，只是不是很友好，对于用到的人来说是一种很难受的体验，也是希望官方能够积极完善文档，并没有其它意思。

**Comment by wangxingkang** [comment]
那你按照你觉得友好的搞个 PR 不就可以了
