### ISSUE TITLE
BizCharts官方文档中国地图问题！

### ISSUE THREAD

**Issue by JonnyCheng** [alibaba/BizCharts#1046]
- bizcharts Version:3.5.4
- Platform or react version:16.9.0
- Mini Showcase(like screenshots):
![QQ20191211-0](https://user-images.githubusercontent.com/3041373/70585838-6b0fd980-1c00-11ea-8d5a-b04b6553005c.png)

官方文档的中国地图上，安徽省上有个未知的四边形，请问那是个bug吗？

**Comment by Leannechn** [comment]
是数据的问题，这份高德数据是测试接口。可以使用下面的地图数据
https://datav.aliyun.com/tools/atlas/#&lat=33.521903996156105&lng=104.29849999999999&zoom=4
