### ISSUE TITLE
折线图纵坐标显示bug

### ISSUE THREAD

**Issue by luqiyang123** [alibaba/BizCharts#1050]
使用官方例子， 代码如下：
import React from "react";
import {
  G2,
  Chart,
  Geom,
  Axis,
  Tooltip,
  Coord,
  Label,
  Legend,
  View,
  Guide,
  Shape,
  Facet,
  Util
} from "bizcharts";

class Basic extends React.Component {
  render() {
    const data = [
      {time: "20191117", number: 4888229},
{time: "20191118", number: 12728092},
{time: "20191119", number: 13983528},
{time: "20191120", number: 14322174},
{time: "20191121", number: 14656116},
{time: "20191122", number: 14851467},
{time: "20191123", number: 5783045},
{time: "20191124", number: 4822690},
{time: "20191125", number: 14140950},
{time: "20191126", number: 15651794},
{time: "20191127", number: 13968844},
{time: "20191128", number: 13141657},
{time: "20191129", number: 12550369},
{time: "20191130", number: 5237669},
{time: "20191201", number: 4950430},
{time: "20191202", number: 13100202},
{time: "20191203", number: 13782167},
{time: "20191204", number: 13168852},
{time: "20191205", number: 12966183},
{time: "20191206", number: 12461314},
{time: "20191207", number: 5797281},
{time: "20191208", number: 5142865},
{time: "20191209", number: 13647770},
{time: "20191210", number: 15232986},
{time: "20191211", number: 15098220},
{time: "20191212", number: 14447040},
{time: "20191213", number: 14786285},
{time: "20191214", number: 6929073},
{time: "20191215", number: 5800867},
{time: "20191216", number: 15569338}
    ];
    const cols = {
      number: {
        min: 0
      },
      time: {
        range: [0, 1]
      }
    };
    return (
      <div>
        <Chart height={400} data={data} scale={cols} forceFit>
          <Axis name="time" />
          <Axis name="number" />
          <Tooltip
            crosshairs={{
              type: "y"
            }}
          />
          <Geom type="line" position="time*number" size={2} />
          <Geom
            type="point"
            position="time*number"
            size={4}
            shape={"circle"}
            style={{
              stroke: "#fff",
              lineWidth: 1
            }}
          />
        </Chart>
      </div>
    );
  }
}

ReactDOM.render(<Basic />, mountNode)

纵坐标诡异的显示为1970-01-01，而且我添加一组数据或减少一组都显示正常

**Comment by ironicstone** [comment]
数据类型设置成time并设置正确的mask（YYYYMMDD）,可以参考scale相关文档
