### ISSUE TITLE
Facet的transpost属性哪去了？

### ISSUE THREAD

**Issue by abellee** [alibaba/BizCharts#1060]
- bizcharts Version: 3.5.6
- Platform or react version: ReactJS 16.8
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/707615/71427852-b09bce80-26f7-11ea-8a0b-fa7ddbe87058.png)

- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ironicstone** [comment]
facet有transpose属性吗，transpose作用在coord上。

**Comment by abellee** [comment]
> facet有transpose属性吗，transpose作用在coord上。

![image](https://user-images.githubusercontent.com/707615/71428061-42580b80-26f9-11ea-85a5-2ef79c474d28.png)

**Comment by ironicstone** [comment]
@abellee  哦，type为mirror的情况下是吧，如果是ts报的话，是目前的类型定义不完全。

**Comment by abellee** [comment]
> @abellee 哦，type为mirror的情况下是吧，如果是ts报的话，是目前的类型定义不完全。

那咋整

**Comment by ironicstone** [comment]
> > @abellee 哦，type为mirror的情况下是吧，如果是ts报的话，是目前的类型定义不完全。
> 
> 那咋整

@ts-ignore 一下

**Comment by abellee** [comment]
> > > @abellee 哦，type为mirror的情况下是吧，如果是ts报的话，是目前的类型定义不完全。
> > 
> > 
> > 那咋整
> 
> @ts-ignore 一下

![image](https://user-images.githubusercontent.com/707615/71428308-fdcd6f80-26fa-11ea-8a58-87d84cd096d1.png)
检测能通过 编译不通过

**Comment by abellee** [comment]
> > > @abellee 哦，type为mirror的情况下是吧，如果是ts报的话，是目前的类型定义不完全。
> > 
> > 
> > 那咋整
> 
> @ts-ignore 一下

[pie setSelected选中](https://bizcharts.net/products/bizCharts/demo/detail?id=pie-setselected&selectedKey=%E9%A5%BC%E5%9B%BE) 这个也是一样的 有一个issue里讨论的 也是一样 都没有定义的

**Comment by abellee** [comment]
> > > @abellee 哦，type为mirror的情况下是吧，如果是ts报的话，是目前的类型定义不完全。
> > 
> > 
> > 那咋整
> 
> @ts-ignore 一下

怎么说

**Comment by abellee** [comment]
自己在头文件里加了就好了
