### ISSUE TITLE
分组柱状图  两条柱子合并到一起了

### ISSUE THREAD

**Issue by kakkoisan** [alibaba/BizCharts#1063]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by kakkoisan** [comment]
![image](https://user-images.githubusercontent.com/46259097/71518142-5ca60b00-28ec-11ea-8dce-2002610295dd.png)

**Comment by Leannechn** [comment]
![Uploading image.png…]()
https://bizcharts.net/products/bizCharts/demo/detail?id=bar-grouped-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE
