### ISSUE TITLE
折线图数据越来越小，可是却呈现上升趋势

### ISSUE THREAD

**Issue by hanchenxu** [alibaba/BizCharts#1066]
- bizcharts Version:^3.5.6
- Platform or react version:^16.0.0
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/36257490/71567254-8e8bbd00-2af8-11ea-903a-f9fe598eb1ab.png)
- CodePen Link:
this.state.value=
[{"value": "1.76", "time": "2019-12-24"},
{"value": "2.40", "time": "2019-12-25"},
{"value": "1.11", "time": "2019-12-26"},
{"value": "0.97", "time": "2019-12-27"},
{"value": "0.83", "time": "2019-12-28"},
{"value": "0.83", "time": "2019-12-29"},
{"value": "1.00", "time": "2019-12-30"}]

const cols = {
  'value': { alias: 'Y轴' },
  'time': {range: [ 0 , 1],alias:'X轴' }
};

<Chart height={600} data={this.state.value} scale={cols} padding={['10%', '5%']} forceFit>
                            <Axis name="time" title />
                            <Axis name="value" title />
                            <Tooltip
                                crosshairs={{
                                    type: "y"
                                }}
                            />
                            <Geom type="line" position="time*value" size={2} />
                            <Geom
                                type="point"
                                position="time*value"
                                size={4}
                                shape={"circle"}
                                style={{
                                    stroke: "#fff",
                                    lineWidth: 1
                                }}
                            />
                        </Chart>
- you can fork CodePen template from this: https://codepen.io/chenxuhan/pen/VwYzOZE

**Comment by Leannechn** [comment]
需要将value map 处理成number类型
