### ISSUE TITLE
柱状图显示偏左

### ISSUE THREAD

**Issue by Jidahan** [alibaba/BizCharts#1067]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

柱状图显示的第一列数据压住了Y轴的文字，这该用哪个参数

**Comment by Jidahan** [comment]
![WX20191230-172245@2x](https://user-images.githubusercontent.com/32761059/71579602-4e4c2f00-2b38-11ea-90ef-7af885d48265.jpg)

**Comment by Leannechn** [comment]
可以使用scale的range 来控制，range的值范围为0-1，0为最左侧，1 为最右侧

**Comment by Jidahan** [comment]
<img width="652" alt="WX20200102-095113@2x" src="https://user-images.githubusercontent.com/32761059/71649285-41058f00-2d48-11ea-9d75-e1ec2102e991.png">
@Leannechn 我这里的写法有问题吗

**Comment by weepy3641** [comment]
将 x 轴 style type 配置为 timeCat
　
参考：
```
      x轴字段: {
        type: 'timeCat'
      }
    };
```
