### ISSUE TITLE
这文档也太垃圾了

### ISSUE THREAD

**Issue by wangfpp** [alibaba/BizCharts#1068]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by wangfpp** [comment]
配置项不清楚　各种组件堆砌带来的灵活性确实强　但是文档跟不上

**Comment by Leannechn** [comment]
> 配置项不清楚　各种组件堆砌带来的灵活性确实强　但是文档跟不上

文档缺少写的不太好，我们在努力改进。
可点击文档下方的编辑按钮，欢迎PR，共建社区。
也可以投简历，加入我们，就有更多力量一起建设。
