### ISSUE TITLE
柱状图X 轴 数据超出边界

### ISSUE THREAD

**Issue by Lubyam** [alibaba/BizCharts#1069]
- bizcharts Version: 3.1.2
- Platform or react version: 16.0.0
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/7630366/71650843-e8d48a00-2d53-11ea-893d-d9163919e1ed.png)

- CodePen Link:      https://codepen.io/laag/pen/MWYExgr

**Comment by weepy3641** [comment]
将 x 轴 scale type 配置为 timeCat
```
    const scale = {
      call: {
        min: 0
      },
      people: {
        min: 0
      },
      waiting: {
        min: 0
      },
      time: {
        type: 'timeCat'
      }
    };
```
