### ISSUE TITLE
保存为图片模糊

### ISSUE THREAD

**Issue by yingapp** [alibaba/BizCharts#1071]
window10 chrome79.0.3945.88
![下载](https://user-images.githubusercontent.com/47973401/71774373-3f3a0680-2fa8-11ea-957a-4ee661facb1b.png)

**Comment by weepy3641** [comment]
保存图片是 canvas 接口直接保存的，无法更清晰。
如果想要高清，可以保存为 svg。
https://bizcharts.net/products/bizCharts/api/chart?from=search#renderer

用 svg 渲染模式即可保存了。
