### ISSUE TITLE
关于x轴坐标点问题

### ISSUE THREAD

**Issue by lianglihao** [alibaba/BizCharts#1073]
假如x轴有连续的7个点，比如1月到7月，此时需要展示3个坐标点，需要展示2，4，6！请问这个能否实现，目前我看到若设置三个点，默认前后两个点是必须显示的，1月7月，然后会取中间的点

**Comment by ironicstone** [comment]
可以设置ticks: https://bizcharts.net/product/bizcharts/category/7/page/35#ticks
