### ISSUE TITLE
可以扩展折线图line的选中和高亮范围嘛？

### ISSUE THREAD

**Issue by ysyszrj** [alibaba/BizCharts#1077]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

在折线图的线可以点击的时候，只有在严格选中那根线的时候，才能高亮和选中，现在反馈就是线太难选中了，可以配置在线的附近就高亮和可点击嘛？

**Comment by ironicstone** [comment]
监听chart 的click时间，配合getSnapRecords（https://bizcharts.net/product/bizcharts/category/7/page/35#ticks）使用
