### ISSUE TITLE
选中点以后，回调中能提供前后点的数据信息嘛？

### ISSUE THREAD

**Issue by ysyszrj** [alibaba/BizCharts#1078]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

现在回调给的参数好像只有当前点的信息，能够提供更多的点的信息嘛？

**Comment by ironicstone** [comment]
可以根据getSnapRecords获取附近点信息（https://g2-v3.antv.vision/zh/docs/api/chart#getsnaprecords），或者直接根据源数据反查
