### ISSUE TITLE
bizcharts为3.5.6版本，图例legend的属性position设置为left，legend跟Y轴会重叠，不能自适应。 降低bizcharts版本无此问题

### ISSUE THREAD

**Issue by cuicui-coding** [alibaba/BizCharts#1080]
- bizcharts Version: 3.5.6
- Platform or react version: 16.9.0
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/18586881/72130445-85ca9f00-33b4-11ea-8e51-6a58665643d9.png)

- CodePen Link: https://codepen.io/kina-coding/pen/vYERMGo?editors=1000

**Comment by ironicstone** [comment]
chart padding设成auto
