### ISSUE TITLE
是否有公共的cdn可使用?

### ISSUE THREAD

**Issue by alexchen1875** [alibaba/BizCharts#1084]
- bizcharts Version:
^3.5.6
- Platform or react version: 
react:^16.12.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
是否可以放到诸如staticfile  cdnjs这样的公共cdn 上

**Comment by Suixinlei** [comment]
gw.alipayobjects.com/os/lib/bizcharts/{{version}}/umd/BizCharts.js

**Comment by alexchen1875** [comment]
> gw.alipayobjects.com/os/lib/bizcharts/{{version}}/umd/BizCharts.js

永久有效么?

**Comment by Suixinlei** [comment]
永久有效
