### ISSUE TITLE
chart 高度超过36408左右就会崩，请问是有什么设置吗

### ISSUE THREAD

**Issue by anbingyang** [alibaba/BizCharts#1086]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Leannechn** [comment]
为什么要设置这么高？

**Comment by anbingyang** [comment]
公司做数据采集，有很多的点位数据做排行，条形图每个柱子设置宽度，点位多了就会报错不显示。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"leanne"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 下午2:56
收件人:&nbsp;"alibaba/BizCharts"<BizCharts@noreply.github.com&gt;;
抄送:&nbsp;"912736000"<912736000@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/BizCharts] chart 高度超过36408左右就会崩，请问是有什么设置吗 (#1086)




为什么要设置这么高？

**Comment by ironicstone** [comment]
资源限制，不同浏览器会有区别，参考：https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element
