### ISSUE TITLE
BizCharts 官网打不开啦

### ISSUE THREAD

**Issue by guozhengzhongGit** [alibaba/BizCharts#1088]
2020年2月4日测试，官网打不开了，是临时维护还是这个项目要下掉啦？

**Comment by Leannechn** [comment]
您检测一下网络看看，https://bizcharts.net。
访问正常。2020.02.04

**Comment by Leannechn** [comment]
该项目会一直持续迭代的，🈶️任何问题欢迎提issue，或者直接提pr
