### ISSUE TITLE
百分比堆叠柱状图纵坐标超过了100%

### ISSUE THREAD

**Issue by RyanLiu0235** [alibaba/BizCharts#1089]
- bizcharts Version:3.5.6
- Platform or react version:16.12.0
- Mini Showcase(like screenshots):![alt](https://gw.alipayobjects.com/mdn/O2O_materi/afts/img/A*CHhSRIEYUI4AAAAAAAAAAABkARQnAQ)
- CodePen Link:https://codepen.io/ryanliu0235/pen/abObeep
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Leannechn** [comment]
因为百分比计算后总合不一定为1。所以这个时候应该超出了。
即，设置最大值为1即可。然后关闭bizhcharts默认开启是调优nice：false。
![Uploading image.png…]()

**Comment by RyanLiu0235** [comment]
@Leannechn 多谢，已解决。
