### ISSUE TITLE
基础面积图（有负值） ，在Chart, 设置padding={[35, 0, 35, 0]} 有异常。

### ISSUE THREAD

**Issue by PancakeLa** [alibaba/BizCharts#109]
antv 官网demo的显示正常，bizcharts 显示异常。望解决！

**Comment by weepy3641** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/area/basic
在这个图的基础上，加上负值及padding，并为发现异常啊。
你用的啥版本？ 能将具体的配置发出来么。

**Comment by PancakeLa** [comment]
@weepy3641 https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/area/with-negative z在这个图加，场景是有负值的基础面积图

**Comment by weepy3641** [comment]
@PancakeLa   在你说的图表中加 padding 并没有异常啊， warning 倒是有。
哪里没用对？ 你直接把代码贴出来看下。
