### ISSUE TITLE
Legend 组件修改 componentWillMount 

### ISSUE THREAD

**Issue by qiwang97** [alibaba/BizCharts#1090]
- bizcharts Version: 3.5.6 
- Platform or react version:  "react": "^16.12.0", "react-dom": "^16.12.0",
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

React 更新了  api，  Legend, TypedComponent 需要同步更新了

```
react-dom.development.js:12357 
Warning: componentWillMount has been renamed, and is not recommended for use. 
See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Legend, TypedComponent
```

**Comment by Leannechn** [comment]
这个是 Warning，在react-dom.production.js 中不会提示。 已在bizcharts@4.x后全面用户react 最新api。

**Comment by yoyo837** [comment]
> 这个是 Warning，在react-dom.production.js 中不会提示。 已在[bizcharts@4.x](mailto:bizcharts@4.x)后全面用户react 最新api。

拥护？
