### ISSUE TITLE
interval - chart 是否可以支持多个柱状图分组展示

### ISSUE THREAD

**Issue by radicalviva** [alibaba/BizCharts#110]
[演示地址](https://jsfiddle.net/z0utxcmb/)
期待效果：
`sales` 和 `a` 可以分组
姿势上有什么问题吗？

**Comment by weepy3641** [comment]
分组壮壮图  demo：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/grouped-column

不同列的数据想要做成分支柱状图需要用 geom color='dataField' 去做到。
所以需要先对数据拼接下，然后 color by。

``` js
dv.transform({
          type: 'fold',
          fields: [ 'Jan.','Feb.','Mar.','Apr.','May','Jun.','Jul.','Aug.' ], // 展开字段集
          key: '月份', // key字段
          value: '月均降雨量', // value字段
        });
```

**Comment by radicalviva** [comment]
@weepy3641 
3Q，那我就用 `date-set` 实现吧
