### ISSUE TITLE
对bizcharts配置external导致报错

### ISSUE THREAD

**Issue by NexxLuo** [alibaba/BizCharts#1104]
配置了webpack的external，导致报错`n.getDefaultCfg is not a function`；

` externals: {
            bizcharts: "window.G2"
        }`

![QQ图片20200313180819](https://user-images.githubusercontent.com/18549980/76611629-ce8a0a00-6555-11ea-9deb-50820941e4cd.png)

- bizcharts Version: 3.5.12

**Comment by qzhongyou** [comment]
解决了吗

**Comment by Leannechn** [comment]
```js
webpackConfig = {
  // ...
  externals: {
      bizcharts: 'BizCharts',
  },
}

```
https://bizcharts.net/product/bizcharts/category/12/page/7

**Comment by IceGogh** [comment]
> ```js
> webpackConfig = {
>   // ...
>   externals: {
>       bizcharts: 'BizCharts',
>   },
> }
> ```
> 
> https://bizcharts.net/product/bizcharts/category/12/page/7

https://github.com/alibaba/BizCharts/issues/1238
