### ISSUE TITLE
IE11，柱状图和雷达图报错

### ISSUE THREAD

**Issue by 530893915** [alibaba/BizCharts#1106]
- bizcharts Version: 3.5.7
- Platform or react version: 16
- Mini Showcase(like screenshots):
本人项目上的报错：
![image](https://user-images.githubusercontent.com/38284163/76724838-51de7200-6787-11ea-924c-c3510cf828e3.png)
官方图表示例的报错：
![image](https://user-images.githubusercontent.com/38284163/76724899-85b99780-6787-11ea-8b19-513b4f9b70d8.png)
- CodePen Link: 官方图表示例切换IE11可复现

请问这个问题能够解决吗？还是说此组件库不计划兼容IE11？

**Comment by Leannechn** [comment]
babel-plugin-array-includes 可解此问题。
下个版本会在bizcharts 层编译umd的时候加入
