### ISSUE TITLE
Stacked area chart可以自定义stack的顺序吗？

### ISSUE THREAD

**Issue by ljqx** [alibaba/BizCharts#111]
希望可以面积大的在上，面积小的在下。看了下stack好像是没有特殊的option的。
这个有预置的解决方案吗？
如果需要自己实现，主要应该关注哪部份的代码呢？

谢谢！

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#2adjust-----object-
配置 reverseOrder为true，会以数据的顺序进行堆叠，因此如果想要面积打的在上小的在下，自己对数据排序即可。
``` jsx
<Geom type='interval' adjust={[{type: stack, reverseOrder:true}]} />
```
