### ISSUE TITLE
如何自定义iconfont或者图片类型的legend图例

### ISSUE THREAD

**Issue by Wangerya** [alibaba/BizCharts#1111]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ironicstone** [comment]
html自定义图例：https://bizcharts.net/product/bizcharts/category/7/page/29#%E5%88%86%E7%B1%BB-html-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E4%BE%8B
