### ISSUE TITLE
混合图可以分开定制Tooltip吗？类似如下的展示？

### ISSUE THREAD

**Issue by huenchao** [alibaba/BizCharts#1114]
- bizcharts Version: 3.5.8
- Platform or react version: 16.8.6
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/14048126/77324455-be420e00-6d51-11ea-8c11-db23224f2d07.png)

- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Leannechn** [comment]
建议使用bx-tooltip定制。这样可以自己根据数据判断显示
