### ISSUE TITLE
tooltip不展示& X轴刻度值显示YYYY-MM-DD HH:mm:ss异常

### ISSUE THREAD

**Issue by wolfer717** [alibaba/BizCharts#1119]
- bizcharts Version: 3.5.6
- Platform or react version: React 16.12.0
- Mini Showcase(like screenshots):
1.鼠标放置线图的前半部分和后半部分皆有tip
![image](https://user-images.githubusercontent.com/7642286/77823789-b232c380-7138-11ea-9b9f-5c39b50f473a.png)
![image](https://user-images.githubusercontent.com/7642286/77823791-c5459380-7138-11ea-99c4-421fca6f6a24.png)
2.鼠标放置中间位置（红框内不显示tip）
![image](https://user-images.githubusercontent.com/7642286/77823807-d7bfcd00-7138-11ea-9ed4-6b988f721d16.png)
3.X轴刻度值显示异常，如果不在scale上添加mask:YYYY-MM-DD HH:mm:ss 属性则只显示 YYYY-MM-DD
![image](https://user-images.githubusercontent.com/7642286/77823814-f920b900-7138-11ea-8d34-a50e8ffbb8b3.png)

- CodePen Link: https://codesandbox.io/s/clever-glade-8xpdv

**Comment by BuggMaker** [comment]
了解一下scale api，详情见[文档](https://bizcharts.net/product/bizcharts/category/7/page/35)
把你的代码如下修改，就好了：
      queryDate: {
        type:'timeCat',
        range: [0, 1]
      }

**Comment by wolfer717** [comment]
加上type:'timeCat', 没办法解决不显示时分秒的bug
