### ISSUE TITLE
折线图展示与数据不相符

### ISSUE THREAD

**Issue by chocking** [alibaba/BizCharts#112]
https://codepen.io/chocking/pen/KZJMzo?editors=1000

x轴的"2018-01-18"没了  多了"2018-01-13"

**Comment by weepy3641** [comment]
@chocking 
日期被解析为连续日期格式，tick 是计算出来的，所以你觉得显示不对导致的，实际是对的。
将 日期 的 scale type 设置为 cat ，可以得到你想要的效果。
``` js
      chart.col('date', {
        alias: '日期',
        type: 'cat', //加上这行
      });
```

最后，同学你木有用 bizcharts 啊，issue 提错地方了，下次直接去 g2 问吧。

**Comment by chocking** [comment]
@weepy3641  噢噢谢了 我进了g2-react 里面指引到这来的   为啥api没有关于chart.col的使用方法 搜不到

**Comment by weepy3641** [comment]
@chocking 
找 scale 的文档。 chart.col 就是在配置 scale。

**Comment by chocking** [comment]
@weepy3641  ok
