### ISSUE TITLE
bizchart会支持 g2 4.x嘛？

### ISSUE THREAD

**Issue by ysyszrj** [alibaba/BizCharts#1120]
这边会计划支持吗？ 

- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Suixinlei** [comment]
预计4月底产出beta版本

**Comment by Leannechn** [comment]
4.0.0 内测版本已发布，欢迎尝鲜
