### ISSUE TITLE
一个双轴折线图，如何做到点击图例动态修改GEOM

### ISSUE THREAD

**Issue by yili1992** [alibaba/BizCharts#1122]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
如下图，我想点击图例隐藏一个折线图的时候，另外一个可以显示label的值在图上
这样的一个效果
<img width="769" alt="截屏2020-04-01下午5 00 05" src="https://user-images.githubusercontent.com/3176589/78119130-87978200-743a-11ea-9936-9c3c2f73bfb2.png">
<img width="758" alt="截屏2020-04-01下午5 00 52" src="https://user-images.githubusercontent.com/3176589/78119138-8cf4cc80-743a-11ea-9df2-892162aca06c.png">

**Comment by Suixinlei** [comment]
参考此 demo 实现即可 https://bizcharts.net/product/BizCharts/demo/264

**Comment by yili1992** [comment]
> 参考此 demo 实现即可 https://bizcharts.net/product/BizCharts/demo/264

"bizcharts": "^3.2.4", 我的版本里 Chart 并没有onLegendItemClick ，官方文档我看也没有onLegendItemClick，我用Legend 的onClick 来实现的话 就会报错
`BizCharts.js:16128 Uncaught TypeError: Cannot read property 'draw' of undefined
    at Category._onClick (BizCharts.js:16128)
    at Group.method (BizCharts.js:52309)
    at Group.emitEvent (BizCharts.js:13526)
    at Group.emit (BizCharts.js:13553)
    at Canvas._triggerEvent (BizCharts.js:45175)
    at HTMLCanvasElement.<anonymous> (BizCharts.js:45191)`

**Comment by Leannechn** [comment]
参考这个例子。https://bizcharts.net/product/BizCharts/demo/8
>  我用Legend 的onClick 来实现的话 就会报错
onClick 中执行的内容需要setTimeout(() => {...do something}, 0) 创建一个异步处理。
我们会在4.0.0中解决这个问题
