### ISSUE TITLE
Mirrored Facet内crosshairs丢了，而G2没问题，官方demo即可重现

### ISSUE THREAD

**Issue by ljqx** [alibaba/BizCharts#113]
BizCharts:
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/rain-and-flow
G2:
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/rain-and-flow.html

显然这两个应该是一模一样的demo，但G2版的有crosshairs，BizCharts的没有。
代码里的配置并无不同。应该是BizCharts的问题。

**Comment by weepy3641** [comment]
@ljqx  在 bizcharts 代码中加入 Tooltip 组件即可。
``` jsx
<Chart >
    <Tooltip />
     <Facet .../>
</Chart>
```
