### ISSUE TITLE
Geom属性Size较小时，adjust的marginRatio为0柱体还是会有间距

### ISSUE THREAD

**Issue by zym970213** [alibaba/BizCharts#1131]
- bizcharts Version: 3.5.6
- Platform or react version: 16.8.6
- Mini Showcase(like screenshots):  
![image](https://user-images.githubusercontent.com/40820228/79557351-fd574b00-80d4-11ea-9f56-5320bd2d49a5.png)

- CodePen Link:   https://bizcharts.alibaba-inc.com/gist/2eo6ol785t2

**Comment by ironicstone** [comment]
可以调成负间距，类比css margin： https://bizcharts.alibaba-inc.com/gist/2joENpIQ0sE
