### ISSUE TITLE
使用slider报错

### ISSUE THREAD

**Issue by zq2016211037** [alibaba/BizCharts#1135]
- bizcharts Version: 3.2.2
- Platform or react version: 16.2.0
- slider version: 2.1.1

报错： Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<Group>'
    at i (bizcharts-plugin-slider.min.js?2a5f:1)
之前未使用bizChart遇到相同的错误，后来将bizChart改变版本到3.2.2之后修复好，现在修改bizcharts-plugin-slider 版本还是报错， 希望解答

**Comment by Leannechn** [comment]
pugin-slider 和bizcharts 有版本对应的，升级到Bizcharts@3.5.9; bizcharts-plugin-slider@lasted
