### ISSUE TITLE
import报错  路径有问题

### ISSUE THREAD

**Issue by zl19921218** [alibaba/BizCharts#1137]
![image](https://user-images.githubusercontent.com/27911624/79959863-3b7ab300-84b7-11ea-875f-7deae4d4aacc.png)

![Uploading image.png…]()

**Comment by zl19921218** [comment]
![image](https://user-images.githubusercontent.com/27911624/79959988-6c5ae800-84b7-11ea-9bcc-f47428cfadea.png)

**Comment by Leannechn** [comment]
这里看不到你什么地方import的bizcharts，这个请求路径是什么。
请提供详细信息。
