### ISSUE TITLE
如何升级到4.x,直接更新包后大量异常.官网也没个文档.

### ISSUE THREAD

**Issue by joesdu** [alibaba/BizCharts#1140]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Leannechn** [comment]
https://bizcharts.net/product/BizCharts4/category/61/page/104

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/80300248-95d48600-87cd-11ea-890b-39e2fd3e5769.png)
