### ISSUE TITLE
堆叠柱状图g2已支持reverseOrder,请问bizcharts什么时候可以支持？

### ISSUE THREAD

**Issue by FightingJane** [alibaba/BizCharts#115]
如题，堆叠柱状图g2目前已支持reverseOrder,更换柱子堆叠的顺序，请问bizcharts什么时候可以支持呢？

**Comment by weepy3641** [comment]
@FightingJane  实际上已经支持了， G2 和 bizcharts 是互通的。
<Geom type='interval' adjust={[{type: stack, reverseOrder:true}]}>
