### ISSUE TITLE
 【尖底漏斗图】 可不可以实现展示的样式颠倒

### ISSUE THREAD

**Issue by Enigma1912** [alibaba/BizCharts#1151]
![image](https://user-images.githubusercontent.com/33351255/81470693-b285aa80-921e-11ea-93b2-dd11e55f225e.png)

**Comment by Leannechn** [comment]
配置坐标系翻转即可，你使用的是哪个版本？
Bizcharts 3.x：https://bizcharts.alibaba-inc.com/product/bizcharts/category/7/page/25
Bizcharts 4.x:  https://bizcharts.alibaba-inc.com/product/BizCharts4/category/62/page/82

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/81520224-4453fb80-9376-11ea-9f00-997b7e66ffa2.png)

**Comment by Leannechn** [comment]
<Coord reflect="y" />

**Comment by Enigma1912** [comment]
> `<Coord reflect="y" />`
ok! 谢谢
