### ISSUE TITLE
柱形图，柱形条数值很小，点击该柱形条(柱形条太小，根本点不到)，如何拿到originData，求解答

### ISSUE THREAD

**Issue by rookie-luochao** [alibaba/BizCharts#1153]
![image](https://user-images.githubusercontent.com/22948077/81519846-1d48fa00-9375-11ea-8e2e-8b8cc2920262.png)
图中1960年的柱形条点不到

**Comment by ironicstone** [comment]
尝试监听chart上click，然后配合getSnapRecords （https://g2-v3.antv.vision/zh/docs/api/chart#getsnaprecords） 使用
