### ISSUE TITLE
4.0.3的饼状图label下显示有重叠

### ISSUE THREAD

**Issue by Ropynn** [alibaba/BizCharts#1155]
[https://bizcharts.net/product/BizCharts4/demo/325](https://bizcharts.net/product/BizCharts4/demo/325)
将饼状图代码改成如下:
` 
import React from 'react';
import {
  Chart,
  Interval,
  Tooltip,
  Axis,
  Coordinate,
  Legend
} from 'bizcharts';

function Labelline() {
  const data = [
    {value: 154219, name: "测试1", percent: 0.6},
    {value: 47278, name: "测试2", percent: 0.18},
    {value: 29351, name: "测试3", percent: 0.11},
    {value: 9054, name: "测试4", percent: 0.03},
    {value: 6294, name: "测试5", percent: 0.02},
    {value: 3950, name: "测试6", percent: 0.01},
    {value: 1860, name: "测试7", percent: 0.0073},
    {value: 957, name: "测试8", percent: 0.0037},
    {value: 801, name: "测试9", percent: 0.0031},
    {value: 562, name: "测试10", percent: 0.0022},
    {value: 181, name: "测试11", percent: 0.0007}
  ];

  const cols = {
    percent: {
      formatter: val => {
        val = (val * 100).toFixed(2) + '%';
        return val;
      },
    },
  };

  return (
    <Chart  height={400} data={data} scale={cols} autoFit >
      <Coordinate type="theta" radius={0.75} />
      <Tooltip showTitle={false} />
      <Axis visible={false} />
      <Legend position="right" offsetX={-150} />
      <Interval
        position="percent"
        adjust="stack"
        color="name"
        style={{
          lineWidth: 1,
          stroke: '#fff',
        }}
        label={['percent', {
          content: (data) => {
            return `${data.name}: ${(data.percent * 100).toFixed(2)}%`;
          },
        }]}
      />
    </Chart>
  );
}
ReactDOM.render(<Labelline />, mountNode);
`
当这个情况的时候,label显示会重叠在一起；
请问这样的应该如何解决？

**Comment by Leannechn** [comment]
Bizcharts@4 支持使用g2Plot, 建议直接使用 g2-plot。
https://bizcharts.alibaba-inc.com/product/BizCharts4/category/61/page/105

**Comment by Leannechn** [comment]
或者使用 https://bizcharts.alibaba-inc.com/product/BizCharts4/category/61/page/107

**Comment by Ropynn** [comment]
> 或者使用 https://bizcharts.alibaba-inc.com/product/BizCharts4/category/61/page/107

这两个地址这边打不开呢

**Comment by Ropynn** [comment]
> Bizcharts@4 支持使用g2Plot, 建议直接使用 g2-plot 的蜘蛛脚饼图布局。
> https://bizcharts.alibaba-inc.com/product/BizCharts4/category/61/page/105

能照着上面的写个例子看看吗?

**Comment by zetianul** [comment]
> 或者使用 https://bizcharts.alibaba-inc.com/product/BizCharts4/category/61/page/107

这链接都打不开，不是你们内网链接吧
