### ISSUE TITLE
4.0.3饼状图点击标签增删，全部删除后， 饼状图无法恢复

### ISSUE THREAD

**Issue by Yukixieyuya821** [alibaba/BizCharts#1156]
![image](https://user-images.githubusercontent.com/53206696/81666476-a98e1680-9474-11ea-9079-ac31a76b4d9c.png)
当将下方标签全部点击删除后， 再次点击饼状图下方标签就没有了任何反应

**Comment by Leannechn** [comment]
4.0.5 已修复 #1181
