### ISSUE TITLE
横坐标展示不全

### ISSUE THREAD

**Issue by huizhang001** [alibaba/BizCharts#1159]
![image](https://user-images.githubusercontent.com/26496638/81910236-40d2a580-95fe-11ea-8fd3-0da71e8c8ea2.png)

https://bizcharts.net/product/bizcharts/demo/65

横坐标显示不全

**Comment by BuggMaker** [comment]
不是展示不全，是x轴为linear类型，展示不开做了取舍，隔一个取一个值，如果想全部展示出来，设置month 的scale类型为cat；具体参考[Scale文档](https://bizcharts.net/product/bizcharts/category/7/page/35#timecat)

**Comment by dwlinn** [comment]
> 不是展示不全，是x轴为linear类型，展示不开做了取舍，隔一个取一个值，如果想全部展示出来，设置month 的scale类型为cat；具体参考[Scale文档](https://bizcharts.net/product/bizcharts/category/7/page/35#timecat)

设置了类型是cat，但文本还是显示不全，被截断了
