### ISSUE TITLE
显示柱状图时,x轴数据的间距固定

### ISSUE THREAD

**Issue by clayerton** [alibaba/BizCharts#1161]
能够在x轴数据之间的间距固定,不是平均分配,
![WechatIMG144](https://user-images.githubusercontent.com/64089643/82167290-e2534300-98ed-11ea-8cbe-3150346db096.jpeg)

**Comment by yaorao2770** [comment]
解决了么？

**Comment by clayerton** [comment]
@yaorao2770 没有解决,
但是规避掉了,比如我现在需求是每页最多显示12条柱状图数据,x轴数据的间距固定,此时,我需要某一页不够12条数据时,进行补充到12条,在Axis中htmlTemplate再进行屏蔽显示补充的数据
![WeChat19f2833471ea37a79cbc4cff0af4c0fe](https://user-images.githubusercontent.com/64089643/83603705-7a685200-a5a7-11ea-8cea-b8af8a7b19cd.png)
![WeChat4de04c7a5a3d616c728cde7ddc394e61](https://user-images.githubusercontent.com/64089643/83603721-80f6c980-a5a7-11ea-98ad-d110c3e676a3.png)
