### ISSUE TITLE
折线图后端返回的数据经过dataset处理后就只渲染一个点

### ISSUE THREAD

**Issue by Luxiaoshi** [alibaba/BizCharts#1165]
如果我把后端返回的数据直接在页面中写死是可以渲染的，但是用后端返回的数据就会只渲染成一个点
![image](https://user-images.githubusercontent.com/8713879/82745801-ef26d980-9dba-11ea-8312-230a90c8b2bb.png)
bizcharts版本 4.0.3
这是我的代码
![image](https://user-images.githubusercontent.com/8713879/82745758-8b041580-9dba-11ea-8792-b39b7c08c36d.png)
这是后端返回的数据
![image](https://user-images.githubusercontent.com/8713879/82745765-99523180-9dba-11ea-924c-754ae4af628e.png)
这是我经过处理以后返回的数据格式
![image](https://user-images.githubusercontent.com/8713879/82745770-af5ff200-9dba-11ea-9e60-633f67e1f932.png)

**Comment by jokerComeBack** [comment]
能详细描述一下吗，比如你写死数据，正常渲染下的charts展示

**Comment by BuggMaker** [comment]
bizcharts 4.x不支持data传入DataView，需要用dv.rows
![image](https://user-images.githubusercontent.com/25820633/84123034-de898b00-aa6b-11ea-9dd6-7598af1bff0f.png)
