### ISSUE TITLE
There is link in site can't be opened

### ISSUE THREAD

**Issue by MuYunyun** [alibaba/BizCharts#1167]
Hey, I find there is link in site can't be opened. 

![image](https://user-images.githubusercontent.com/19354791/82859136-82414a00-9f48-11ea-966b-aea4c73d9bb9.png)

* [repetition site](https://bizcharts.net/product/bizgoblin/category/7/page/27#type-span-classlightstringspan)
* [几何标记和数据调整](https://bizcharts.alibaba-inc.com/product/bizcharts/category/12/page/57): this link fail.

**Comment by BuggMaker** [comment]
fixed, thanks for your warning
