### ISSUE TITLE
Packed bubble chart

### ISSUE THREAD

**Issue by naidu0531** [alibaba/BizCharts#1168]
Hi,

I need the following chart diagram. Is this possible to draw in biz.
![image](https://user-images.githubusercontent.com/57655779/82882691-0a324e80-9f5f-11ea-844e-6967418db398.png)

Please help.....

**Comment by Leannechn** [comment]
try @antv/g6 like this:  https://g6.antv.vision/zh/examples/net/forceDirected#forceBubbles

**Comment by naidu0531** [comment]
Is this not possible with  G2? i am using  G2 now.

**Comment by Leannechn** [comment]
They are the same series of products. Your chart is a force map. For this week's chart, g6 is recommended
