### ISSUE TITLE
Slider插件在使用时需要点击一下再拖动才会生效

### ISSUE THREAD

**Issue by joriewong** [alibaba/BizCharts#117]
首次拖动无效

**Comment by weepy3641** [comment]
什么浏览器，浏览器版本， bizcharts 什么版本啊？

**Comment by joriewong** [comment]
Google 版本 63.0.3239.132（正式版本）
"bizcharts": "^3.1.0"
"bizcharts-plugin-slider": "^2.0.1"

**Comment by weepy3641** [comment]
最新版本应该已经修复

**Comment by joriewong** [comment]
thx
