### ISSUE TITLE
如何实现饼图标签带颜色？

### ISSUE THREAD

**Issue by kaysonwu** [alibaba/BizCharts#1178]
![QQ截图20200606201902](https://user-images.githubusercontent.com/14865584/83944020-1b1e7200-a833-11ea-8e69-f10c61cf28b3.png)
 
如图显示的玫瑰型饼图非常好看，尝试许久不得门道，希望可以得到一点指点，感谢！

**Comment by Leannechn** [comment]
https://bizcharts.net/gist/2j7TZ0xezk1
