### ISSUE TITLE
关于自定义设置tooltip

### ISSUE THREAD

**Issue by GodzillaHe** [alibaba/BizCharts#118]
我想在一条预算折线上的tooltips，显示同比环比两条item，数据在data里都有相关字段。按照Geom的方法，设置回调之后，只能显示单调item，如何显示多条item呢？

**Comment by GodzillaHe** [comment]
代码中tooltips采用的是这个设置。![image](https://user-images.githubusercontent.com/13843799/35209348-66becd50-ff88-11e7-9400-325e8b349726.png)

**Comment by GodzillaHe** [comment]
找到方法了。。。用ontooltipchange可以解决。

**Comment by tttaotie** [comment]
请问是怎么解决的呀

**Comment by GodzillaHe** [comment]
用ontooltipchange， 你可以看下g2文档关于这个方法的介绍，用法还是比较灵活的@tttaotie
