### ISSUE TITLE
Invalid Regex While Using Firefox (v4.0.5)

### ISSUE THREAD

**Issue by souterjk** [alibaba/BizCharts#1185]
When using the latest build in Firefox, the user experiences an error due to a lookbehind REGEX being used. Firefox does not yet support these regex's, so any kind of import of BizCharts will cause the page render to immediately fail. 

Unfortunately no line number or stack trace is provided, so I cannot provide further details about where the error is. But this does not occur on build 4.0.4, so it must be in the changes from 4.0.5 somewhere.

![Screen Shot 2020-06-11 at 12 50 30 PM](https://user-images.githubusercontent.com/4010391/84422203-49f56900-abe2-11ea-9209-c081e9be54c3.png)

**Comment by Leannechn** [comment]
it fixed in 4.0.6 #1182
