### ISSUE TITLE
bizchart4.x中环图内的文字如何设置换行？

### ISSUE THREAD

**Issue by delaprada** [alibaba/BizCharts#1188]
3.x中有guide里的html可以设置换行，但是4.x只有content可以设置文字而且content只能是字符串，有什么解决办法么？这个是3.x中的效果：
<img width="671" alt="截屏2020-06-16 下午1 45 40" src="https://user-images.githubusercontent.com/40078051/84736149-c23f9e00-afd7-11ea-9c57-51ad1acf72a1.png">

**Comment by natsupan** [comment]
可以通过多个 **Annotation.Text** 来实现。
[demo](https://codesandbox.io/s/confident-napier-0dsd8)

**Comment by delaprada** [comment]
@natsupan 谢谢，解决了！
