### ISSUE TITLE
BizCharts@4 初始化的时候无法自动获取父组件宽度

### ISSUE THREAD

**Issue by EGBAR** [alibaba/BizCharts#1192]
Charts 无法正确初始化父组件宽度， 设置 autoFit 之后， 每次展开图都会从左到右边重新自适应一下。 这样的情况在一些业务场景中不是很能接受。
尝试过设置父组件的宽度， 不起作用， Plot图表中也不存在这种问题。 

想请问如何让Chart初始化就获取父组件的宽度， 而不是每次都从0->width 做一下动画。

**Comment by EGBAR** [comment]
Sorry, 补充一下信息， 我是把 Bizcharts放在了 可折叠的panel里面， 并且设置了autoFit。 
折叠的时候size会变成0， 展开的时候就会resize， 所以会有了这么一个拉宽的动画。 
我现在能想到的解决方案有两个：
1. 每次手工计算一个width传递给Bizcharts.
2. 每次Panel折叠的时候destroy Chart， panel展开的时候重新render。
感觉这些实现都有些tricky， 想要请问一下有没有更好的办法？ 谢谢

**Comment by Leannechn** [comment]
套一个固定高度的div ，这样他的父级容器就不是panel ，就不会随其变化而变化

**Comment by Leozhangshouhai** [comment]
> 套一个固定高度的div ，这样他的父级容器就不是panel ，就不会随其变化而

高度能直接固定 但是宽度不行， 所以回从左到右的展开。。这个很难受
