### ISSUE TITLE
4.x 版本 Legend 没有textStyle属性了，设置不了字体样式?

### ISSUE THREAD

**Issue by KyouSeki** [alibaba/BizCharts#1196]
文档中用
label={{
        style: {fill:'red'}
      }}
设置后不生效。

**Comment by BuggMaker** [comment]
连续图例使用label; 分类图例使用itemName

**Comment by Magic1012** [comment]
把 fill 换成 stroke 试试：
label={ {
      style: {
         stroke: '#DC4E41'
      }
}}

**Comment by Magic1012** [comment]
把 fill 换成 stroke 试试：

`label={{
    style: {
       stroke: '#DC4E41'
    }
}}`
