### ISSUE TITLE
scale 设置min不为0时，图像遮挡x轴

### ISSUE THREAD

**Issue by iwits** [alibaba/BizCharts#1198]
使用官网例子。 增加设置scale  y轴min 不为0 。 出现图像遮挡x轴的情况。
请问怎么解决。

-------代码如下---
import React from "react";
import {
  G2,
  Chart,
  Tooltip,
  Interval,
  Coord
} from "bizcharts";

const data = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
  { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
  { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
  { name: 'London', 月份: 'May', 月均降雨量: 47 },
  { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
  { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
  { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
  { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
  { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
  { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
  { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
  { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
  { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
  { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
  { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
];

const scale = { 月均降雨量: { min: 7, tickCount: 5 }} // 设置min 不为0

function Demo() {
  return (
    <Chart height={400} padding={[30, 85, 60, 60]} data={data} autoFit scale={scale}>
      <Interval
        adjust={[
         {
            type: 'stack',
          },
        ]}
        color="name"
        position="月份*月均降雨量"
      />
      <Tooltip shared />
    </Chart>
  );
}

ReactDOM.render(<Demo />, mountNode)

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/97395280-8cb0a700-191f-11eb-83a8-0b6db24a8233.png)

这里写的是7
![image](https://user-images.githubusercontent.com/6812138/97395260-828ea880-191f-11eb-9c58-e21e334285cb.png)

**Comment by iwits** [comment]
我需要的效果是x轴从7开始，不是从0。所以min需要设置成7 。但是一旦设置非0 ，柱子就发生错位。
