### ISSUE TITLE
demo站点访问速度好慢😆

### ISSUE THREAD

**Issue by yangbin1994** [alibaba/BizCharts#12]

**Comment by weepy3641** [comment]
en, 因为访问了 unpkg.com 上的资源，这周会将资源迁移到 cdn 上。

**Comment by mengchen007** [comment]
怎么正常启动啊

**Comment by enjoy-your-life** [comment]
demo好像访问不了。。。。。

**Comment by weepy3641** [comment]
@enjoy-your-life 
可以将 bizcharts 仓库down 下来，切换到  gh-pages 分支。
站点demo全部在里面，可以自己启静态服务器浏览。

近期会将站点上比较慢的 js 资源切换到国内的 cdn 上，应该会快点。

**Comment by weepy3641** [comment]
已经将 demo 中访问的资源都替换成了 alicdn 上的资源，速度应该会提升很多。
