### ISSUE TITLE
dodge is not support linear attribute, please use category attribute!

### ISSUE THREAD

**Issue by havywu** [alibaba/BizCharts#120]
![image](https://user-images.githubusercontent.com/29532857/35211887-3745cbf4-ff93-11e7-834e-1167cb978f5d.png)
![qq 20180122170229](https://user-images.githubusercontent.com/29532857/35212673-e3950fda-ff95-11e7-99cd-3fe2b72d5523.png)
![image](https://user-images.githubusercontent.com/29532857/35211948-7106585e-ff93-11e7-8911-4faeddc2011a.png)
Why not support '2018-01-22'?

**Comment by weepy3641** [comment]
Date like year-month-day will be parsed as linear date。
So you must set the date scale's type 'cat'.
``` jsx
cols = {
  genre:{
    type: 'cat'
  }
}
<Chart scale={cols} />
```

**Comment by carrollcai** [comment]
transform '2018-01-22' to '2018.01.22'

**Comment by qinyuhua** [comment]
我也遇到了这个问题 ，请问怎么改

**Comment by weiweiXue** [comment]
尝试从x轴坐标格式化
