### ISSUE TITLE
4.x 自定义Tooltip

### ISSUE THREAD

**Issue by CoderRui** [alibaba/BizCharts#1201]
自定义Tooltip 可以在官网中的例子中运行
但是在 Bizcharts @ ‘^4.0.6‘ 本地项目中 不起什么作用
请问是版本的问题吗？
```typescript
   <Tooltip>
          {
            (title: any, items: any) => {
              return <div>
                自定义Tooltip
              </div>
            }
          }
    </Tooltip>
```

**Comment by Leannechn** [comment]
官网例子就4.0.6 能提供一下你的整个demo代码吗

**Comment by CoderRui** [comment]
`
import { Chart, Interval, Axis, Tooltip, Coord, Legend } from 'bizcharts';

    <Chart
          forceFit
          height={400}
          data={data}
          padding={[0, 20, 0, 20]}
        >
          <Coord type={'theta'} radius={0.75} innerRadius={0.6} />
          <Axis name="percent" />
          <Legend
              flipPage={false}
              itemWidth={50}
              layout="horizontal"
              position="right"
              offsetY={0}
              offsetX={0}
            />
          <Tooltip>
            {
              (title: any, items: any) => {
                const item = items[0]
                return <div>
                  <h5>{title}</h5>
                  <span>占比: {(item.value * 100).toFixed(2)}%</span>
                </div>
              }
            }
          </Tooltip>
          <Interval 
            type="intervalStack"
            position="percent" 
            color="item"
            label={['percent', {
              content: (item: any) => {
                return  `${item.item}`;
              },
            }]}
          />
        </Chart>

`

**Comment by CoderRui** [comment]
`
(title: any, items: any) => {
            const item = items[0]
            return <div>
              <h5>{title}</h5>
              <span>占比: {(item.value * 100).toFixed(2)}%</span>
            </div>
          }
`
可以在函数内 获取到相关信息 但是 return html 无法覆盖到 chart 上

**Comment by CoderRui** [comment]
如果 我在官网中 codepen 链接预览时 Bizcharts 版本显示的是 @3.x

**Comment by Leannechn** [comment]
你可以直接用官网的demofrock一个。https://bizcharts.alibaba-inc.com/gist/2lnGs7R366C
![image](https://user-images.githubusercontent.com/6812138/86129131-cbbb2100-bb14-11ea-8865-b7be87f1d07a.png)
