### ISSUE TITLE
bizchart图表的自适应在发布到线上后，初始化总是超出设定的宽高

### ISSUE THREAD

**Issue by SandersXin** [alibaba/BizCharts#1208]
bizcharts版本：4.0.4、3.x

尝试过以下种3办法：
1、设置forceFit为true，并在onGetG2Instance中拿到实例，并执行实例的forceFit方法；
2、设置 Ver 4.x 的autoFit为true；
3、为图表组建增加window的resize监听，并在组件装载后手动触发resize事件；

发布到线上后，都会出现超出设定宽高的问题，而且频率非常高。

**Comment by Leannechn** [comment]
发布到线上才出现的问题，说明本地版本号和线上版本号不一致。
1. 本地执行npm update后，看是否和线上一致。
2. 你尝试多个版本都有这个问题，说明很可能是获取容器高度不是实现显示的容器高度。请在demo中套一个你外层容器的css 完整复刻的样式的容器。来还原这个问题。
ps 单纯的文字无法定位，尽量复现一下问题。并把结果截图带上。

**Comment by SandersXin** [comment]
问题已解决，确实是因为本地包版本不一致导致的，按照建议1更新本地包的版本，使用autoFit、设置宽高后实现了窗口自适应。
