### ISSUE TITLE
Legend selectedMode  single

### ISSUE THREAD

**Issue by EGBAR** [alibaba/BizCharts#121]
当使用 Single mode 的时候， 初始化所有的图例都是选中的， 点击过后才会变成单选。 
Single Mode有初始化的时候默认只选中第一个图例的方法吗？

**Comment by weepy3641** [comment]
可以。
chart filter 属性配置数据的初始状态即可。

https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#12filter---array

``` jsx
<Chart filter={[['x', (val) => {return val > 20;}]]}/>
```

也可以参考下 g2 的 demo，bizcharts 使用方式类似，换成相应 jsx 配置即可。
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%9B%BE%E4%BE%8B%E9%A1%B9%E7%9A%84%E5%88%9D%E5%A7%8B%E7%8A%B6%E6%80%81

**Comment by EGBAR** [comment]
@weepy3641 
谢谢！ 刚刚尝试了， 发现 <Chart /> 里面filter 确实有用， 但是<View /> 里面不管用， 虽然API上写了
```

7、filter * Object *

使用同 Chart 的 filer 属性。
```
不知道是不是我使用上的不对

**Comment by weepy3641** [comment]
@EGBAR  不好意思， view 上 filter 接口是有点问题，下个版本修复。

**Comment by weepy3641** [comment]
最新版本 3.1.3-beta.2已经支持
