### ISSUE TITLE
在飞冰（ice）项目中引用js报Cannot read property 'createContext' of undefined错误

### ISSUE THREAD

**Issue by myshanshan** [alibaba/BizCharts#1211]
BizCharts Version:4.0.7
Platform: ice （react）
Mini Showcase(like screenshots):

![3691d8945e74407794a212c8adaa5ca](https://user-images.githubusercontent.com/34647621/86882396-cc5e4380-c122-11ea-8bda-2207cbd6182c.png)

forck and create a demo:  null

**Comment by myshanshan** [comment]
![3691d8945e74407794a212c8adaa5ca](https://user-images.githubusercontent.com/34647621/86882490-e8fa7b80-c122-11ea-986d-0fe373314af3.png)

**Comment by Leannechn** [comment]
react 版本号需求16.8以上，升级react版本即可。
