### ISSUE TITLE
在饼状图中使用new DataView().userDv.source(data).transform() 转换百分比，总百分比不为100%

### ISSUE THREAD

**Issue by cpboom** [alibaba/BizCharts#1213]
BizCharts Version:^4.0.6
Platform:
Mini Showcase(like screenshots):
![Uploading image.png…]()

forck and create a demo: https://bizcharts.net/gist/2mhtdhnkAyg

**Comment by Leannechn** [comment]
不等于1是因为你自己把数据formatter去掉了小数尾。
打开console看看，加禾是1.

**Comment by cpboom** [comment]
显示的时候不会显示全部小数点是不？我现在做法是提前把数据处理成百分比  我是觉得既然有转换百分比的方法   是不是能再优化一下 （如加个精度）当然以上只是建议
