### ISSUE TITLE
Interval can't display

### ISSUE THREAD

**Issue by Y-lonelY** [alibaba/BizCharts#1218]
BizCharts Version:4.0.10

如果**不设置 Chart 的 width 属性**，希望其能够自适应展示， Interval 无法显示，审查元素如下：

```html
<div class="bizcharts" style="height: 500px; width: 100%;">
<div style="position:relative;">
<canvas width="2" height="1000" style="width: 1px; height: 500px; display: inline-block; vertical-align: middle;"></canvas></div>
</div>
```

**Comment by Leannechn** [comment]
那你就设置一下autofit 开启自适应就行了

**Comment by Y-lonelY** [comment]
> 那你就设置一下autoFit={true} 开启自适应就行了

是的，感谢，貌似[当前文档](https://bizcharts.net/product/BizCharts4/category/62/page/77)里面没发现，通过全局搜索发现了
