### ISSUE TITLE
双轴图，不设置scale, 生成的坐标轴尺度不全

### ISSUE THREAD

**Issue by zhiyan** [alibaba/BizCharts#1224]
BizCharts Version: 4.0.10
Platform: mac
Mini Showcase(like screenshots):
![QQ20200721-114342](https://user-images.githubusercontent.com/1467767/88010441-74becf80-cb47-11ea-84e1-8181ab1ac576.png)
左侧坐标轴刻度没能覆盖最高的柱状图

forck and create a demo: 
https://bizcharts.net/gist/2nkdagszGjJ

**Comment by zhiyan** [comment]
知道了，需要设置nice才行

**Comment by zhiyan** [comment]
文档上写的scale里默认nice为true, 为什么需要手动设置nice=true才能开启，文档错了还是实现有问题?

**Comment by Leannechn** [comment]
你是对的，这个默认值的确是文档失误。非常抱歉！，已修改，当类型是 linear 和 time的时候 默认nice为false，其他默认为true
