### ISSUE TITLE
bizcharts4怎么设置图表标题呢

### ISSUE THREAD

**Issue by pyuyu** [alibaba/BizCharts#1226]
BizCharts Version: 4.0.10
Platform: macOs 10.15.5
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/16910913/88263189-328abf00-ccfc-11ea-89b9-4247a8d66faa.png)

forck and create a demo: https://bizcharts.net/gist/2nwUP8DRvzh

**Comment by liuguangsen0409** [comment]
https://bizcharts.net/product/BizCharts/demo/261 看看这个 demo 呢

**Comment by pyuyu** [comment]
> https://bizcharts.net/product/BizCharts/demo/261 看看这个 demo 呢

在4里面这么写效果和3不一样。。 https://bizcharts.net/gist/2nwUP8DRvzh

**Comment by Leannechn** [comment]
<Chart > 子组件不支持html组件，请放在<Chart>组件外
```js
<h5>图表标题</h5>
<Chart>
  .....
</Chart>
```
