### ISSUE TITLE
坐标轴 label 的 textStyle 设置

### ISSUE THREAD

**Issue by xhuanlee** [alibaba/BizCharts#123]
我只想个性化设置某些特定值 label 的 textStyle，其他的保持默认值，官方 demo 如下，这时其他坐标的标签都不显示了。感觉是只要设置了 textStyle 属性，默认值就无效了。
```
<Axis name="month" label={{textStyle: val => { 
    if(val === 'Mar') { 
        return {fontSize: '16', fill: 'red'};
    }
}}} />
```
![axios](https://user-images.githubusercontent.com/22806759/35317548-3aea2ca2-0112-11e8-82c7-87e43deb4abb.jpg)

当然，我也可以同时设置其他值的 textStyle，但是官方文档好像也没给出其他的默认值， 比如说 **fill**
```
<Axis name="month" label={{textStyle: val => { 
    if(val === 'Mar') { 
        return {fontSize: '16', fill: 'red'};
    }
    return return {fontSize: '12', fill: '#8c8c8c'};
}}} />
```

**Comment by weepy3641** [comment]
默认样式可以查看相应 theme 配置中的默认 style。
https://github.com/alibaba/BizCharts/blob/master/doc/api/theme.md
![image](https://user-images.githubusercontent.com/3838676/35317700-fa715cda-0112-11e8-9ec3-f91fce8e2d9e.png)
