### ISSUE TITLE
分组柱状图，x轴对应有2条数据，如果第一条数据中的Berlin中 ‘Jan’ 为null 或者0，应该怎么让它不占位置呢

### ISSUE THREAD

**Issue by X-ZW** [alibaba/BizCharts#1237]
BizCharts Version: 3.4.3
Platform:
Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/49856755/89014113-a0139c80-d347-11ea-8ba2-f8c80c6995ab.png)

forck and create a demo:

**Comment by heiniuhaha** [comment]
https://bizcharts.alibaba-inc.com/product/BizCharts4/demo/492
![image](https://user-images.githubusercontent.com/668144/89258368-9b5a2b80-d65a-11ea-9fd5-7dbae99158e9.png)
