### ISSUE TITLE
紧凑树布局如何隐藏左边、下面的标尺？

### ISSUE THREAD

**Issue by kofwang** [alibaba/BizCharts#1240]
BizCharts Version: 
Platform:
Mini Showcase(like screenshots):
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306

紧凑树布局如何隐藏左边、下面的标尺？
按照demo照搬code，却出现左边、下面的标尺。

![image](https://user-images.githubusercontent.com/7496943/90388340-3838b200-e0ba-11ea-95ed-0262d229e75b.png)

**Comment by Leannechn** [comment]
https://bizcharts.alibaba-inc.com/product/BizCharts4/category/62/page/77

**Comment by kofwang** [comment]
Thanks, issue resolved.
