### ISSUE TITLE
facet分面图legend消失

### ISSUE THREAD

**Issue by xbu** [alibaba/BizCharts#125]
G2例子 https://antv.alipay.com/zh-cn/g2/3.x/demo/facet/rect.html
无需配置自动就有legend

BizCharts例子 https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/facet/rect
运行后没有legend

**Comment by weepy3641** [comment]
@xbu 
bizcharts 中 legend 是默认隐藏的，若要显示，需要用户自己将 `Legend` 组件加上。
facet demo 中加上  `Legend` 组件即可。
``` jsx
<Chart>
  <Legend /> //here
  <Facet />
</Chart>
```
