### ISSUE TITLE
slider初始化无效

### ISSUE THREAD

**Issue by xianshangdeyu** [alibaba/BizCharts#1252]
BizCharts Version:
Platform:
Mini Showcase(like screenshots):
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306
slider初始设置end后，滚动条上的进度是在设置的位置，但是图上依旧是显示整个全图，手动拖拽后图上才发生变化

**Comment by zjfjiayou** [comment]
+1

**Comment by TnWah** [comment]
+1
请问这个有解决么？

**Comment by nolure** [comment]
如果只有line组件的话 可以用plots组件替代 https://bizcharts.net/product/BizCharts4/category/77/page/116

**Comment by guosihui** [comment]
+1

**Comment by Leannechn** [comment]
#1269

**Comment by Leannechn** [comment]
#1269

**Comment by TnWah** [comment]
大佬，修复版本什么时候可以发布啊，等待ing！！
