### ISSUE TITLE
如何异步更新数据，文档里也没有写

### ISSUE THREAD

**Issue by Joker0824** [alibaba/BizCharts#1253]
BizCharts Version:
Platform:
Mini Showcase(like screenshots):
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306

**Comment by Y-lonelY** [comment]
我在项目中，也有这样的需求，我是通过[高阶组件](https://zh-hans.reactjs.org/docs/higher-order-components.html#gatsby-focus-wrapper) 来解决，在外层组件内获取数据，并且 store 在当前组件的 state 内，之后分发给 bizcharts 封装的组件，这样的好处是可以对源数据做处理和过滤等操作。

```tsx
//  一些关键代码
useEffect(() => {
      async function initChartData() {
        let currentSelection
        if (async) {
          const { selection, list } = await async()
          // self define rule to set source data
          createDv(list)
        } else {
          createDv(data)
        }
   }
}

return (
<ChartComponent
     data={state.rows}
     isHoc={true}
     {...chartProps}
 />
)
```

**Comment by Leannechn** [comment]
更新数据是react通用方案，可以看看react社区中react组件如何更新数据
