### ISSUE TITLE
Dark Theme make Axis looks like disappear!

### ISSUE THREAD

**Issue by Y-lonelY** [alibaba/BizCharts#1254]
BizCharts Version: ^4.0.14
Platform: MacOS 10.15.6
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/46279229/91787868-70ed9500-ec3d-11ea-9a1c-895f323cc307.png)
forck and create a demo: https://github.com/Y-lonelY/bizcharts-darkTheme-bug.git 

After I have upgraded the Bizcharts, the x,y Axis seems like disappear!
But when i disable the `theme` in `<Chart>`, it works!
It's there any way to solve the problem do not by registerTheme?

**Comment by Symboler** [comment]
dark主题的background配置有问题，理论上讲只能去自定义主题修改这个配置处理，dark主题的配置可以拿到，你拿到后将background配置修改为‘transparent’,然后做自定义主题处理即可，不会影响使用体验。

**Comment by Y-lonelY** [comment]
```ts
const darkTheme = getTheme('dark')
darkTheme.background = 'transparent'
```
solved~
