### ISSUE TITLE
如果中间数据点丢失，可以通过配置默认用虚线或者红色的线条连接吗？

### ISSUE THREAD

**Issue by luyuanx2** [alibaba/BizCharts#1255]
BizCharts Version:
Platform:
Mini Showcase(like screenshots):
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306

**Comment by heiniuhaha** [comment]
https://bizcharts.net/product/BizCharts4/demo/485 可以参考这个Demo，用多条线叠在一起，视觉上看起来是连接的
