### ISSUE TITLE
自定义Tooltip 偶尔会出现两个tooltip

### ISSUE THREAD

**Issue by yc0524** [alibaba/BizCharts#1267]
BizCharts Version: 4.0.14
Platform: win

![image](https://user-images.githubusercontent.com/33405012/93190120-90280e80-f775-11ea-8482-8f489075213a.png)
![image](https://user-images.githubusercontent.com/33405012/93190220-ac2bb000-f775-11ea-91eb-8a736522074a.png)

**Comment by fatalxiao** [comment]
+1，会出现一个G2的Tooltip（ .g2-tooltip ），还有一个是BizCharts的Tooltip（ .bizcharts.bizcharts-tooltip.g2-tooltip ）

**Comment by Leannechn** [comment]
bizcharts@4.0.15 已修复 #1302
