### ISSUE TITLE
可否自定义Tooltip的enterable=true or false

### ISSUE THREAD

**Issue by lishaoh** [alibaba/BizCharts#1268]
BizCharts Version: 3.5.5
Platform: Mac

如果Tooltip文字过多时支持enterable=true，文字较少时支持enterabled=false

eg:
<Tooltip
            crosshairs={{
              type: 'y',
            }}
            enterable={[key, item => item.length > 500]}
          />

**Comment by BuggMaker** [comment]
不支持回调哦 可以去G2那里提feature issue
