### ISSUE TITLE
Slider的start初始值, Line组件并没有同步

### ISSUE THREAD

**Issue by nolure** [alibaba/BizCharts#1269]
BizCharts Version: 4.0.14
Platform: chrome 85
forck and create a demo: https://bizcharts.net/gist/2sHhACaLHdH

比如slider设置了初始值start=0.5, 但是line还是展示的所有数据，能不能line默认和slider的范围同步呢

还有一个疑问：当有多个view时，如何用一个slider联动多个view里面的组件，类似股票图这种场景https://bizcharts.net/product/BizCharts4/demo/346 。我想要的是3.0的demo那种联动效果 https://bizcharts.net/product/bizcharts/demo/191

**Comment by zsxing99** [comment]
同问一个slider联动多个view

**Comment by Leannechn** [comment]
bizcharts@4.0.15 已处理。目前在bizcharts层多渲染一次以使其生效。彻底解决需待@antv/g2@4.1.0 发布。
 #1302
