### ISSUE TITLE
Use different data points inside charts

### ISSUE THREAD

**Issue by kbardi** [alibaba/BizCharts#127]
Hi there, I'm using this awesome library, and it works for most of my charts, but now I need to show a chart with forecast projection, so I would like to do something like this...
<img width="504" alt="screen shot 2018-01-25 at 4 04 19 pm" src="https://user-images.githubusercontent.com/4523375/35407064-6d2296e6-01e9-11e8-831c-293971fa1279.png">
So from a specific period change data point or color. Is it possible with BizCharts? Can you tell me how to do it? Thanks in advance and congratulations for this great project.

**Comment by karoliang** [comment]
你是想把后面两个月换成不一样的颜色吧？

**Comment by weepy3641** [comment]
@karoliang 
You can use custom shape to draw this chart which geometry have two style.
Actually you can draw any geometry shape group with custom shape.

demo:
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/custom-bar
api doc:
https://github.com/alibaba/BizCharts/blob/master/doc/api/shape.md
api doc_en:
https://github.com/alibaba/BizCharts/blob/develop/doc_en/api/shape.md
