### ISSUE TITLE
柱状图X轴无法完全显示label文本

### ISSUE THREAD

**Issue by XSnowHoly** [alibaba/BizCharts#1278]
BizCharts Version: 4.0.14
Platform:  window 谷歌浏览器
Mini Showcase(like screenshots):

![image](https://user-images.githubusercontent.com/25945988/95650372-d45cc380-0b15-11eb-9ad6-44a61edc4066.png)

`
<Chart
        height={520}
        autoFit
        data={departmentData}
        scale={{ deptName: {
                        type: 'cat',
                        tickCount: 29,
                      }, performanceAmount: { alias: '业绩金额' } }}
        onIntervalClick={departmentClick} >
        <Interval
           position="deptName*performanceAmount"
          />
</Chart>
`
发现X轴只显示奇数的label文本，请问如何显示所有的X轴label文本
tickCount 值设置一个很大的值也不能全部显示

**Comment by XSnowHoly** [comment]
相关问题:  [折线图x轴显示不完全](https://github.com/alibaba/BizCharts/issues/506)

**Comment by BuggMaker** [comment]
设置axis label的autoHide为false，禁止自动隐藏即可
