### ISSUE TITLE
Bar chart messes up y-axis

### ISSUE THREAD

**Issue by gajo357** [alibaba/BizCharts#1281]
BizCharts Version: "^4.0.13"
Platform: Windows
Mini Showcase(like screenshots):
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306

You can see that the first item (Coffee) is not even shown, yet it clearly is there.
The y-axis is messed up,  -15 appears above 35 (if I keep adding values, they just stack up).

![Bizchart Bar error](https://user-images.githubusercontent.com/19407603/95852693-74079500-0d54-11eb-9e55-4d48395f4fb0.png)

The code for my components is this (basically copied from your demos):

`<BarChart data={[{product: "Coffee", value: 35}, {product: "SRAM", value: -15}]} xTitle="Product" yTitle="Yeild %" xField="product" yField="value" />`

`const BarChart: React.FC<Props> = ({
  xTitle,
  yTitle,
  data,
  xField,
  yField,
  ...rest
}) => {
  const scale: { [id: string]: any } = {};
  scale[xField] = { alias: xTitle };
  scale[yField] = { alias: yTitle, min: 0 };
  return (
    <Chart data={data} autoFit height={300} width={400} scale={scale} {...rest}>
      <Interval
        position={`${xField}*${yField}`}
        color={xField}
      />
    </Chart>
  );
};`

**Comment by Leannechn** [comment]
You can forck from the demo, and modify online. Then save and copy demo to us. 
As that we can know what is you problem

**Comment by gajo357** [comment]
I found a bug in my logic, the form didn't return numbers, but string instead.
So it all makes sense now!
Thank you for your time!
