### ISSUE TITLE
demo里使用YYYY-MM-DD格式作为横坐标时图表异常

### ISSUE THREAD

**Issue by DemosBin** [alibaba/BizCharts#1294]
BizCharts Version: 4.x
Platform: chrome
Mini Showcase(like screenshots): 向左突出到了y轴以外，当格式换为MM-DD或者YY-MM-DD时正常了
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306

![image](https://user-images.githubusercontent.com/18628034/97669162-7725b380-1abe-11eb-916b-3307d161c81c.png)

**Comment by swanf** [comment]
在 demo 里试了一下，怀疑是 JS 隐式转换导致的，在前加空格（即写成" 2020-01-03 "）使其转型为字符串可以解决这个问题。

**Comment by DemosBin** [comment]
done
