### ISSUE TITLE
Barchart Bar Length Problem

### ISSUE THREAD

**Issue by emin-karadag** [alibaba/BizCharts#1300]
**BizCharts Version:** v4.0.5
**Platform:** ReactJs

Hello,
The bar chart made up of a single column looks very ugly. I share the screenshot below.
Likewise, when there are 2 bars, it looks very big and rough.
BarChart is drawn dynamically. Sometimes a single column can be made up of n columns. In addition, the graphic outer frame can be dynamically resized. For this reason, I cannot give a fixed width to the column of the bar chart.

Can we do this automatically?

Thanks now.

![Ekran Alıntısı](https://user-images.githubusercontent.com/7556164/98954052-72292100-250e-11eb-9d2f-9a6d4cd8a381.PNG)

**Comment by Leannechn** [comment]
See this demo https://bizcharts.alibaba-inc.com/product/BizCharts4/demo/562
