### ISSUE TITLE
When set padding of Chart to 'auto', Some data's number not show.

### ISSUE THREAD

**Issue by iam-frankqiu** [alibaba/BizCharts#1309]
BizCharts Version: 3.5.9
Platform: Mac
Mini Showcase(like screenshots): 
fork and create a demo: https://bizcharts.net/product/BizCharts4/demo/407

Seted the padding to 'auto', you can see the number of china not show

**Comment by Leannechn** [comment]
See this demo https://bizcharts.net/gist/2AqMMsY9eDs
Need to be used in conjunction with appendPadding, padding will only calculate graphics and axes, not the size of the label
