### ISSUE TITLE
bizcharts-plugin-slider dosnt work for bizcharts v4

### ISSUE THREAD

**Issue by justebin** [alibaba/BizCharts#1312]
I have installed the bellow packages by using npm
    "bizcharts": "^4.0.15"
    "bizcharts-plugin-slider": "^3.0.1"

But i get errors

TypeError: Cannot read property 'Util' of undefined
.../node_modules/bizcharts-plugin-slider/umd/bizcharts-plugin-slider.min.js:1

Please help me.
Thank you

**Comment by Leannechn** [comment]
import { Slider } from 'bizcharts'
