### ISSUE TITLE
双Y轴的时候，如果不定义min和max不能对齐。

### ISSUE THREAD

**Issue by yuanye4017** [alibaba/BizCharts#1316]
BizCharts Version: ^4.0.14
Platform: macOS10.15.7
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/43987769/101305601-fc4e7600-387d-11eb-9d67-2d1a7285a65a.png)

forck and create a demo: https://bizcharts.net/gist/2AqOPKgmDer

moreInfo: 现实情况下min和max很难确定，官网demo的数据过于理想化。

**Comment by GCpigsic** [comment]
请问这个问题解决了吗

**Comment by Youmyin** [comment]
同问，我从后台获取的数据数据量很大并且是实时变化的，无法确定min和max

**Comment by Leannechn** [comment]
4.1.0 版本新增一个scale line-strict。 可严格按照tickCount计算刻度个数，这样双轴就能对齐。
```
<Chart
   scale={{
      y: {
       type: 'line-strict',
       tickCount: 5
     }
  }}
...
</Chart>

**Comment by Leannechn** [comment]
#1334
