### ISSUE TITLE
切换到其他页面再切换回的时候，图表会超出原来宽度，必须resize浏览器窗口才可恢复

### ISSUE THREAD

**Issue by kltsao** [alibaba/BizCharts#132]
切换到其他页面再切换回的时候，图表会超出原来宽度，必须resize浏览器窗口才可恢复，也见于在初始data为空后补数据时也会超过宽度（不指定宽度forceFit的情况下）。

**Comment by a67586646** [comment]
同样出现宽度溢出的问题，使用forceFit，初始data为空后补数据超出宽度

**Comment by havywu** [comment]
切换到其他页面，切换回来，canvas的宽度为0，但父元素宽度是存在的。

**Comment by j3r0lin** [comment]
遇到同样的问题，目前自己用的比较搓的解决办法：
``` javascript
render() {
    if (this.chart) {
      this.chart.forceFit();
    }
    return (<Chart
      {...opts}
      onGetG2Instance={(chart) => {
        this.chart = chart;
      }}
    />);
  }
```

**Comment by weepy3641** [comment]
跟 G2 那边的人讨论过了，推荐初始化时设置容器 size。
同时切换页面后有自适应问题，可以强制 forcetFit 。

``` jsx
// 例如， 这样做是对的。
render() {
    if (this.chart) {
      this.chart.forceFit();
    }
    return (<Chart
      {...opts}
      onGetG2Instance={(chart) => {
        this.chart = chart;
      }}
    />);
  }
```

**Comment by weepy3641** [comment]
还有一种方式，在组件 didmount 时，主动触发 resize 时间。
window.dispatchEvent(new Event('resize'));

**Comment by newyoung21** [comment]
window.dispatchEvent(new Event('resize'))

**Comment by tanzhihang** [comment]
> 还有一种方式，在组件 didmount 时，主动触发 resize 时间。
> window.dispatchEvent(new Event('resize'));

这个方法火狐上不生效

**Comment by gaius-qi** [comment]
可以在图表渲染前添加 loading，防止 data 为空时对图表进行渲染。

```js
if (data.length === 0) {
  return <div>spin</div>;
}
```
