### ISSUE TITLE
折线图无法连空吗？

### ISSUE THREAD

**Issue by Petter-li** [alibaba/BizCharts#1321]
BizCharts Version:4.0.14
Platform:react  chorme
Mini Showcase(like screenshots): https://bizcharts.net/product/BizCharts4/demo/352
在line中加上connectNulls={true} 无效。
根据介绍是基于g2来开发的，查看g2官方文档及实例，g2可以支持该属性。
请问是我的用法不对吗

**Comment by Leannechn** [comment]
1. 你是用的原子组件，还是plots. connectNulls 应该是Plots上的属性
2. 在原子组件上直接过滤掉这个null的数据，连线就不会断
