### ISSUE TITLE
按需加载后坐标消失

### ISSUE THREAD

**Issue by matianhe3** [alibaba/BizCharts#1331]
BizCharts Version: 4.x

![image](https://user-images.githubusercontent.com/24929062/102680923-f64e8280-41f7-11eb-8c55-0e33d9e37d65.png)
![image](https://user-images.githubusercontent.com/24929062/102680930-06fef880-41f8-11eb-86b5-5a98fe4f907e.png)
```
// import { Chart, Interval, Tooltip } from 'bizcharts';
import Chart from 'bizcharts/lib/components/Chart';
import Interval from 'bizcharts/lib/geometry/Interval';
import Tooltip from 'bizcharts/lib/components/Tooltip';
```

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/102733551-8ca9b200-4378-11eb-9b6b-f8632c86e03b.png)
饼图折线图等所有图形的Label也消失了.

**Comment by Leannechn** [comment]
按需加载相当于 pure模式，Axis什么的组件需求单独引入。
