### ISSUE TITLE
双Y轴scale仅设置min和tickCount两轴数据无法对应

### ISSUE THREAD

**Issue by Youmyin** [alibaba/BizCharts#1334]
BizCharts Version:4.0.16
Platform:Windows10

对于官网的示例https://bizcharts.net/product/BizCharts4/demo/474

该示例显示，双Y轴中的scale似乎需要同时设定min和max，但是实际情况是，如果后台返回的数据量很大并且是实时变化的，很难确定数据的范围，如果在scale中仅设置min和tickCount，两Y轴刻度无法对应，而且tickCount失效。

比如我将scale改为
`
const scale = {
        // tickCount控制双轴的对齐
        people: {
          alias: "处理中客户（个）",
          min: 0,
          tickCount: 5,
        },
        waiting: {
          alias: "等待中客户（个）",
          min: 0,
          tickCount: 5,
        },
        time: {
          alias: "时间（秒）",
          // type: 'timeCat',
          // mask: 'YYYY-MM-DD HH:mm:ss'
        },
      };
`

效果如下图所示，左边Y轴的tickCount并不是5，并且两端Y轴也无法对应起来
![image](https://user-images.githubusercontent.com/54265150/102863128-1c308d00-446d-11eb-9560-5b74a5c4df60.png)

**Comment by Leannechn** [comment]
4.1.0 以上版本 新增一个scale type 值为‘linear-strict’， 能够严格按照设置的tickCount绘制tick。
