### ISSUE TITLE
官网https证书过期了 

### ISSUE THREAD

**Issue by hetengji** [alibaba/BizCharts#1336]
https://bizcharts.net/
![cfbc4f763d5711b0c1d1ecf38d4e0cc](https://user-images.githubusercontent.com/30951653/102962352-a63a2d80-4521-11eb-89de-44b863f340ce.png)

**Comment by Suixinlei** [comment]
已修复，感谢提醒
如果刷新后显示证书仍然不正常，可以关闭浏览器后重新打开以清除缓存
