### ISSUE TITLE
构建代码报错4.1.0

### ISSUE THREAD

**Issue by fengxinming** [alibaba/BizCharts#1349]
BizCharts Version: 4.1.0
Platform: Mac

webpack构建代码报错，目前切回4.0.17就正常打包

```
app.js from UglifyJs
Unexpected token: operator (>) [app.js:41506,24]
```

**Comment by Leannechn** [comment]
forceFit  已废弃，请看文档。一直都是autoFit。forceFit 是3.x的旧版用法，已提示在4.1后废弃。

> +1， 4.1.0 forceFit属性找不到导致构建报错

**Comment by Leannechn** [comment]
> BizCharts Version: 4.1.0
> Platform: Mac
> 
> webpack构建代码报错，目前切回4.0.17就正常打包
> 
> ```
> app.js from UglifyJs
> Unexpected token: operator (>) [app.js:41506,24]
> ```

有具体的webpack配置吗？无法复现

**Comment by pyuyu** [comment]
> forceFit 已废弃，请看文档。一直都是autoFit。forceFit 是3.x的旧版用法，已提示在4.1后废弃。
> 
> > +1， 4.1.0 forceFit属性找不到导致构建报错

文档里没看到废弃0 0. https://bizcharts.net/product/BizCharts4/category/77/page/131#forcefit

**Comment by Leannechn** [comment]
> > forceFit 已废弃，请看文档。一直都是autoFit。forceFit 是3.x的旧版用法，已提示在4.1后废弃。
> > > +1， 4.1.0 forceFit属性找不到导致构建报错
> 
> 文档里没看到废弃0 0. https://bizcharts.net/product/BizCharts4/category/77/page/131#forcefit
抱歉，以为你说的是Chart组件。Plots组件文档我们正在更新，升级为g2Plot@2.0 文档升级需要点时间。
forcefit 废弃是为了和Chart组件对齐以及和g2Plot对齐，所以统一改成autoFit。
正在紧锣密鼓的改文档。你可以// @ts-ignore掉，实际功能是兼容的。

**Comment by Leannechn** [comment]
文档升级指南已更新，外网服务器有缓存，有一定延时时间。

**Comment by fengxinming** [comment]
@Leannechn 4.1.1也还是构建不成功，跟之前发的报错一样，用的脚手架是`@ali/bone-cli`比较古老，依赖的webpack还是3.x

**Comment by Leannechn** [comment]
好的吧，本来想支持一下treeShaking。现在4.1.2 降级回去默认指向umd文件。

**Comment by fengxinming** [comment]
@Leannechn 你可以构建umd和esm版本，package.json的main属性配置umd，module属性配置esm版本

**Comment by Leannechn** [comment]
现在的版本在您的脚手架上是否可用了？

**Comment by fengxinming** [comment]
@Leannechn 最后这个4.1.3版本可以构建成功，有问题的版本建议还是deprecate，小版本更新最好还是不要搞太大的变动，上周发布版本前构建失败，差点就吓尿了，要不是这个库一直给我不稳定的感觉，不然就一点点错误信息根本不可能在5分钟内定位出那里出问题了

**Comment by Leannechn** [comment]
好的
