### ISSUE TITLE
求一个双轴图的案例

### ISSUE THREAD

**Issue by anlia260** [alibaba/BizCharts#135]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html

**Comment by weepy3641** [comment]
如下 demo 是 三个 geom 实现的，带自定义 legend 交互。

``` jsx
import React from "react";
import ReactDOM from "react-dom";
import { Chart, Geom, Axis, Tooltip, Coord, Label, Legend, View, Shape, Facet, G2 } from "bizcharts";
import DataSet from '@antv/data-set';

const data = [
  { time: '10:10', call: 4, waiting: 2, people: 2, people2: 4 },
  { time: '10:15', call: 2, waiting: 6, people: 3, people2: 6},
  { time: '10:20', call: 13, waiting: 2, people: 5, people2: 8 },
  { time: '10:25', call: 9, waiting: 9, people: 1, people2: 10 },
  { time: '10:30', call: 5, waiting: 2, people: 3, people2: 12 },
  { time: '10:35', call: 8, waiting: 2, people: 1, people2: 16 },
  { time: '10:40', call: 13, waiting: 1, people: 2, people2: 8 },
  
];

const ds = new DataSet();
      const dv = ds.createView().source(data);
      dv.transform({
        type: 'fold',
        fields: [ 'people', 'people2' ], // 展开字段集
        key: 'nums', // key字段
        value: 'peoples', // value字段
      });
      console.log(dv);

scale = {
  call: {
    min: 0
  },
  people: {
    min: 0,
    tickCount: 4,
    max:20
  },
  people: {
    min:0,
    tickCount: 4,
    max:20
  },
  time:{
    tickCount: 4
  },
  waiting: {
		min: 0,
    tickCount: 4  }
}

let chartIns = null;
ReactDOM.render((
  <Chart height={window.innerHeight} scale={scale}  padding={60} forceFit data={data} onGetG2Instance={(chart)=>{chartIns=chart;}}>
		<Legend
      custom={true}
      allowAllCanceled={true}
      position="top"
  items={[
    { value: 'waiting', marker: {symbol: 'square', fill: '#3182bd', radius: 5} }, 
    { value: 'people', marker: {symbol: 'hyphen', stroke: '#ff0000', radius: 5, lineWidth: 3} },
    { value: 'people2', marker: {symbol: 'hyphen', stroke: '#0000ff', radius: 5, lineWidth: 3} }

  ]}
  onClick={ ev => {
    const item = ev.item;
        
    const value = item.value;
    const checked = ev.checked;
    const geoms = chartIns.getAllGeoms();
    for (let i = 0; i < geoms.length; i++) {
      
      const geom = geoms[i];
      
      if (geom.getYScale().field === value ) {
        if (checked) {
          geom.show();
        } else {
          geom.hide();
        }
      }
    }
  }}
/>
    <Axis
      name="people"
      grid={null}
      label={{
      textStyle:{
        fill: '#fdae6b'
      }
    }}
      />
    <Axis name="people2" visible={false} />
    <Geom type="interval" position="time*waiting" color="#3182bd"/>
    <Geom type="line" position="time*people" color={"#ff0000"} shape="smooth" />
    <Geom type="line" position="time*people2" color={"#0000ff"} shape="circle" shape={'smooth'} />
  </Chart>
), document.getElementById("mountNode"));
```

**Comment by PurpleDandelion** [comment]
@weepy3641 这个例子好像不行，不知道我哪儿错了，用你的和官网上的，都提示我Invalid source

**Comment by PurpleDandelion** [comment]
import React, { PureComponent } from 'react';
import { Chart, Geom, Axis, Tooltip, Coord, Label, Legend, View, Shape, Facet, G2 } from 'bizcharts';
// import { View } from '@antv/data-set';
import DataSet from '@antv/data-set';
export default class LineBar extends PureComponent {
  /*
  * height {integer} 图表高度
  * data {array} 数据源
  * axisXname {string} 横坐标名
  * axisYname {string} 纵坐标名
  * connectorName {string} 数据转换类型
  * 参考：https://github.com/alibaba/BizCharts/blob/master/doc/api/transform.md
  * transOtherOptions 其他参数o
  */

  render() {
    const data = [
      { time: '10:10', call: 4, waiting: 2, people: 2, people2: 4 },
      { time: '10:15', call: 2, waiting: 6, people: 3, people2: 6},
      { time: '10:20', call: 13, waiting: 2, people: 5, people2: 8 },
      { time: '10:25', call: 9, waiting: 9, people: 1, people2: 10 },
      { time: '10:30', call: 5, waiting: 2, people: 3, people2: 12 },
      { time: '10:35', call: 8, waiting: 2, people: 1, people2: 16 },
      { time: '10:40', call: 13, waiting: 1, people: 2, people2: 8 },
      
    ];

    const ds = new DataSet();
    const dv = ds.createView().source(data);
    dv.transform({
      type: 'fold',
      fields: [ 'people', 'people2' ], // 展开字段集
      key: 'nums', // key字段
      value: 'peoples', // value字段
    });
      console.log(dv);
    scale = {
      call: {
        min: 0
      },
      people: {
        min: 0,
        tickCount: 4,
        max:20
      },
      people2: {
        min:0,
        tickCount: 4,
        max:20
      },
      time:{
        tickCount: 4
      },
      waiting: {
        min: 0,
        tickCount: 4  }
    }

    let chartIns = null;
    return (
      <Chart height={295} scale={scale}  padding={60} forceFit data={dv} onGetG2Instance={(chart)=>{chartIns=chart;}}>
          <Legend
            custom={true}
            allowAllCanceled={true}
            position="top"
        items={[
          { value: 'waiting', marker: {symbol: 'square', fill: '#3182bd', radius: 5} }, 
          { value: 'people', marker: {symbol: 'hyphen', stroke: '#ff0000', radius: 5, lineWidth: 3} },
          { value: 'people2', marker: {symbol: 'hyphen', stroke: '#0000ff', radius: 5, lineWidth: 3} }

        ]}
        onClick={ ev => {
          const item = ev.item;
              
          const value = item.value;
          const checked = ev.checked;
          const geoms = chartIns.getAllGeoms();
          for (let i = 0; i < geoms.length; i++) {
            
            const geom = geoms[i];
            
            if (geom.getYScale().field === value ) {
              if (checked) {
                geom.show();
              } else {
                geom.hide();
              }
            }
          }
        }}
      />
          <Axis
            name="people"
            grid={null}
            label={{
            textStyle:{
              fill: '#fdae6b'
            }
          }}
            />
          <Axis name="people2" visible={false} />
          <Geom type="interval" position="time*waiting" color="#3182bd"/>
          <Geom type="line" position="time*people" color={"#ff0000"} shape="smooth" />
          <Geom type="line" position="time*people2" color={"#0000ff"} shape="circle" shape={'smooth'} />
        </Chart>
      );
  }
}

**Comment by heiniuhaha** [comment]
https://bizcharts.net/products/bizCharts/demo/detail?id=gallery-biaxial&selectedKey=%E6%A6%82%E8%A7%88
