### ISSUE TITLE
[bug]4.1.2 autofit = true的时候不起作用

### ISSUE THREAD

**Issue by alphabetabc** [alibaba/BizCharts#1351]
BizCharts Version: 4.1.2
Platform: win
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/29876424/105608035-8a55d000-5ddc-11eb-9399-3e9b67445ce3.png)
![image](https://user-images.githubusercontent.com/29876424/105608045-99d51900-5ddc-11eb-9c1b-76fa4b86bf51.png)

forck and create a demo: .. 

设置容器的高度为300，plot的autofit=true，渲染错误，初步确定是因为plot获取父元素的高度的时候出错了，如下图所示
![image](https://user-images.githubusercontent.com/29876424/105608110-fafcec80-5ddc-11eb-9ae4-2ca1dd1c54e6.png)

**Comment by alphabetabc** [comment]
@Leannechn 
我想升级bizcharts，但这块问题无法从外部传属性修复

**Comment by Leannechn** [comment]
已发布4.1.3修复此问题
