### ISSUE TITLE
折线图异常(4.0.15 ~ 4.1.2)

### ISSUE THREAD

**Issue by RK-WJW** [alibaba/BizCharts#1353]
BizCharts Version: 4.1.2
Platform: Chrome

x为时间类型，理解在4.0.15版本内x轴数据是会做排序的。而更新4.1.2之后，从异常效果看，应该是不处理排序了，这种调整是不是应该及时更新文档以及changelog告知一下

**Comment by alphabetabc** [comment]
感觉不能重度依赖plot，得使用createplot自己注册使用，然后根据业务进行调整

**Comment by Leannechn** [comment]
收到，已添加。谢谢提醒，此处g2层的changge没注意到，非常感谢提醒
