### ISSUE TITLE
externals方式引入js报错Cannot read property 'createContext' of undefined

### ISSUE THREAD

**Issue by yinjiefeng** [alibaba/BizCharts#1355]
![1611574038502](https://user-images.githubusercontent.com/6430116/105700123-64970b00-5f43-11eb-872c-f5f9d4be258c.jpg)

Ant Design Pro V5项目中通过webpack externals引入时报上述错误

webpack配置:
{
  externals: {
    bizcharts: 'BizCharts',
  },
  scripts: [
    'https://g.alicdn.com/code/lib/bizcharts/4.0.16/BizCharts.js',
  ]
}

react版本：17.0.0
node版本: v14.15.3

**Comment by Leannechn** [comment]
你在console中检查一下 React.version

**Comment by yinjiefeng** [comment]
> 你在console中检查一下 React.version

![image](https://user-images.githubusercontent.com/6430116/105793929-fb57dc00-5fc4-11eb-9822-829952b4a54b.png)

**Comment by Leannechn** [comment]
你extarnal后的react 要放在bizcharts之前。检查一下script标签的顺序
