### ISSUE TITLE
请双View x轴如何对齐？

### ISSUE THREAD

**Issue by mansters** [alibaba/BizCharts#1358]
# 问题描述

BizCharts 版本: 4.1.5

在双View的情况下，X轴出现错位的问题，同样的实现方式在3.5.6版本中是可以对齐的。由于度量值是动态配置的，所以无法通过硬编码的方式设置`appendPadding `。

# 截图示例
以下是相同数据下不同bizchart版本的对比
## 4.1.5版本
![image](https://user-images.githubusercontent.com/16091537/106230341-3eff4f80-622a-11eb-9dc6-202c86ebf863.png)

## 3.5.6版本
![image](https://user-images.githubusercontent.com/16091537/106229734-17f44e00-6229-11eb-926d-92b72093d165.png)

## 在线demo
https://bizcharts.net/gist/2FqTSKLaB4o

**Comment by Leannechn** [comment]
bizcharts @4.1.x版本后引入一个scale type类型为linear-strict，能够严格按照tickCount 分段。两边轴用一样段刻度个数tickCount即可。
demo地址 https://bizcharts.alibaba-inc.com/product/BizCharts4/demo/414
![image](https://user-images.githubusercontent.com/6812138/107135014-2a117300-6932-11eb-8522-a9b4c21951a0.png)
