### ISSUE TITLE
导入Slider时出现 Cannot read property 'Canvas' of undefined

### ISSUE THREAD

**Issue by Cuihongsen** [alibaba/BizCharts#136]
导入Slider时出现
import { Slider } from 'bizcharts-plugin-slider';
Unhandled Rejection (TypeError): Cannot read property 'Canvas' of undefined

**Comment by weepy3641** [comment]
@Cuihongsen 
有可能是 bizcharts-plugin-slider 比 bizcharts 先加载。
bizcharts-plugin-slider 依赖于 bizcharts，所以你先检查下 bizcharts 有没有加载及顺序

**Comment by chinaxiaoyy** [comment]
我也是同样的问题

**Comment by weepy3641** [comment]
@Cuihongsen 
你是不是用了 antd-pro ？ 
之前出现这个问题是因为 antd-pro 脚手架中的 bizcharts 、slider、g2 的版本没对上！ 你可以检查下你 package.json 以及 node-modules 中的版本号。
要求 bizcharts 3.x， g2 3.x， g2-slider 2.x， bizcharts-slider 2.x

**Comment by chinaxiaoyy** [comment]
this can help you
https://github.com/alibaba/BizCharts/blob/master/plugin/slider/demo/index.js
