### ISSUE TITLE
BizCharts is not defined

### ISSUE THREAD

**Issue by my9988** [alibaba/BizCharts#1360]
BizCharts Version:4.1.5
Platform:windows 
Mini Showcase(like screenshots):
基于antd pro v5 开发

我的问题如标题所示，我也反复看了 官方文档，按照文档配置如下：
![image](https://user-images.githubusercontent.com/17469220/106306107-97af0680-6283-11eb-9ba1-2a708588a3cf.png)
在开发环境下，运行完全OK，build后，就出问题了，在BizCharts is not defined之前是这个错误：
![image](https://user-images.githubusercontent.com/17469220/106306355-f2486280-6283-11eb-9e98-5560eb676b39.png)
如上图所示，react等3个js加载都正常，因为regeneratorRuntime is not defined 这个错误导致 BizCharts not defined.
我也查了这个错误的处理方法，都无效果，实在无奈，在此求助！！！

官方文档只是说出现not defined是因为没有加载成功，可是我的好像都加载OK 啊。

**Comment by Leannechn** [comment]
看一下这个配置，应该是V5 中默认配置少了，https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/106350057-f5883080-630d-11eb-8f0e-772a9959c820.png)
我用antd pro v5 初始化一个是可以正常使用的。你先自己试试配置，如果还不行，可以提供一下一个壳到github，分享给我

**Comment by my9988** [comment]
@Leannechn 

在开发环境下是可以的，我build后就不行了。比如最简单写个Html
![image](https://user-images.githubusercontent.com/17469220/106355967-b368ea00-6321-11eb-85a7-6c2e0699763b.png)
单独点击运行就会出错和我部署在apache的错误是一样的。

你提供的网址说的太复杂了，我也试过import regeneratorRuntime from "regenerator-runtime";没有效果

**Comment by my9988** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="keywords" content />
    <meta name="description" content />
    <meta name="description" content="ZK Licenese " />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <title>ZK License</title>
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="/static/umi.8aaaa5ee.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.3.7
    </script>
  </head>
  <body>
    <noscript></noscript>
    <div id="root">
      <style>
        html,
        body,
        #root {
          height: 100%;
          margin: 0;
          padding: 0;
        }
        #root {
          background-color: white;
          background-repeat: no-repeat;
          background-size: 100% auto;
        }
        .page-loading-warp {
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 98px;
        }
        .ant-spin {
          position: absolute;
          display: none;
          -webkit-box-sizing: border-box;
          box-sizing: border-box;
          margin: 0;
          padding: 0;
          color: rgba(73, 66, 66, 0.45);
          color: #18ff4a;
          font-size: 14px;
          font-variant: tabular-nums;
          line-height: 1.5;
          text-align: center;
          list-style: none;
          opacity: 0;
          -webkit-transition: -webkit-transform 0.3s
            cubic-bezier(0.78, 0.14, 0.15, 0.86);
          transition: -webkit-transform 0.3s
            cubic-bezier(0.78, 0.14, 0.15, 0.86);
          transition: transform 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86);
          transition: transform 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86),
            -webkit-transform 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86);
          -webkit-font-feature-settings: "tnum";
          font-feature-settings: "tnum";
        }

        .ant-spin-dot-item:nth-child(1) {
          top: 0;
          left: 0;
        }

        .ant-spin-dot-item:nth-child(2) {
          top: 0;
          right: 0;
          -webkit-animation-delay: 0.4s;
          animation-delay: 0.4s;
        }

        .ant-spin-dot-item:nth-child(3) {
          right: 0;
          bottom: 0;
          -webkit-animation-delay: 0.8s;
          animation-delay: 0.8s;
        }

        .ant-spin-dot-item:nth-child(4) {
          bottom: 0;
          left: 0;
          -webkit-animation-delay: 1.2s;
          animation-delay: 1.2s;
        }

        .ant-spin-dot-spin {
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg);
          -webkit-animation: antrotate 1.2s infinite linear;
          animation: antRotate 1.2s infinite linear;
        }

        .ant-spin-lg .ant-spin-dot {
          width: 32px;
          height: 32px;
          font-size: 32px;
        }

        .ant-spin-lg .ant-spin-dot i {
          width: 14px;
          height: 14px;
        }

        @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
          .ant-spin-blur {
            background: #fff;
            opacity: 0.5;
          }
        }

        @-webkit-keyframes antSpinMove {
          to {
            opacity: 1;
          }
        }

        @keyframes antSpinMove {
          to {
            opacity: 1;
          }
        }

        @-webkit-keyframes antRotate {
          to {
            -webkit-transform: rotate(405deg);
            transform: rotate(405deg);
          }
        }

        @keyframes antRotate {
          to {
            -webkit-transform: rotate(405deg);
            transform: rotate(405deg);
          }
        }
      </style>
      <div
        style="
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          height: 100%;
          min-height: 420px;
        "
      >
        <div class="page-loading-warp">
          <div class="ant-spin ant-spin-lg ant-spin-spinning">
            <span class="ant-spin-dot ant-spin-dot-spin"
              ><i class="ant-spin-dot-item"></i><i class="ant-spin-dot-item"></i
              ><i class="ant-spin-dot-item"></i><i class="ant-spin-dot-item"></i
            ></span>
          </div>
        </div>
        <div
          style="display: flex; align-items: center; justify-content: center"
        >
          ZK License
        </div>
      </div>
    </div>

  </body>
</html>
<script src="https://g.alicdn.com/code/lib/react/17.0.1/umd/react.production.min.js" type="text/javascript"></script>
<script src="https://g.alicdn.com/code/lib/react-dom/17.0.1/umd/react-dom.production.min.js" type="text/javascript"></script>
<script src="https://g.alicdn.com/code/lib/bizcharts/4.1.5/BizCharts.min.js" type="text/javascript"></script> -->

**Comment by my9988** [comment]
@Leannechn 
![image](https://user-images.githubusercontent.com/17469220/106358213-a7d0ef80-6330-11eb-87c0-2907225d1f71.png)
经过测试发现，如果用官网说的那个4.0.14就没问题，可以运行，这个4.1.5就有这个错误，需要配置什么吗？官网的文档写什么主入口文件，antd pro我都不知道哪个是主入口。比如在哪里加import 'regenerator-runtime/runtime';   我都怀疑人生，别人没问题？

**Comment by Leannechn** [comment]
4.0.14没问题 是因为4.1.5 依赖的g2Plot 依赖的d3-hierachy 包中的这个函数是generator。

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/106410863-d066ff80-647e-11eb-84da-6dd58f1b7ceb.png)
build后起http服务依然正常，
你是不是自己改了antd pro的配置呀，
![image](https://user-images.githubusercontent.com/6812138/106410925-f4c2dc00-647e-11eb-903e-8a500b1f0f76.png)

antd pro中有引入regenerator-runtime/runtime

**Comment by Leannechn** [comment]
你再检查一下antd pro 的脚手架版本是不是最新的。

**Comment by Leannechn** [comment]
我知道了，你是external的用法，稍等，我测一下

**Comment by Leannechn** [comment]
已补充runtime v4.1.6

**Comment by my9988** [comment]
> 已补充runtime v4.1.6

多谢，https://g.alicdn.com/code/lib/bizcharts/4.1.6/BizCharts.min.js  
请问这个地址什么时候可以下载，目前不行?是否还有别的CDN可推荐用？
