### ISSUE TITLE
plots 文档 维护是否有需要？

### ISSUE THREAD

**Issue by alphabetabc** [alibaba/BizCharts#1363]
BizCharts Version:latest
Platform: --
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/29876424/106720956-02bf5b00-663f-11eb-9c32-13343431d91c.png)

forck and create a demo: --
学习了createPlot的源码，实际上就是把g2plot的配置项透传过去的，感觉就没有必要我们在这里再维护一份文档，
1、及时性没法保证
2、有时候得两头看 

大佬有时间，不如搞点其他研究，开源给我们学习 (⓿_⓿)

**Comment by Leannechn** [comment]
确实 维护成本特别高。。。 所以，在搞一个工程快速同步。

**Comment by alphabetabc** [comment]
合适啊，必须合适，只需要在文档中说明干了啥，该咋干 就行了
