### ISSUE TITLE
antd proV5引入DonutChart后切换路由报错：Failed to execute 'unobserve' on 'ResizeObserver'

### ISSUE THREAD

**Issue by Elric-H** [alibaba/BizCharts#1365]
BizCharts Version:4.1.6
react Version:17.0.0
![image](https://user-images.githubusercontent.com/27395996/107014412-85c6e980-67d6-11eb-9295-8c529c2be80b.png)
是不是因为DonutChart组件内没有清理 resizeObserver？

**Comment by qiwang97** [comment]
@Elric-H 我也遇到了

**Comment by smddzcy** [comment]
I get the same error on all kinds of charts. I think this issue is introduced with the 3.1.6 version, I'm downgrading to 3.1.5 now to check.

**Comment by qiwang97** [comment]
@smddzcy i find one reason and i make a [pull request](https://github.com/alibaba/BizCharts/pull/1366) before your comment. i will check what happened after v3.1.5

**Comment by smddzcy** [comment]
@qiwang97 sorry, I actually meant "4.1.5". This whole block of code was added in 4.1.6, so that's what happened after 4.1.5 😄

![image](https://user-images.githubusercontent.com/13895224/107120668-baeb3e80-689f-11eb-8b50-b39e2accaa0f.png)

Your fix looks good to me, let's hope that it gets merged quickly.

**Comment by qiwang97** [comment]
> @smddzcy i find one reason and i make a [pull request](https://github.com/alibaba/BizCharts/pull/1366) before your comment. i will check what happened after v3.1.5

@smddzcy I make a [diff](https://github.com/alibaba/BizCharts/compare/v4.1.5...v4.1.6#diff-4eab05aa884dbe85089d1c57e419b649827934a7d006256b5352ef23d0f6bd8eR294) and you can see the changes.

**Comment by Elric-H** [comment]
> @Elric-H 我也遇到了 有解决方案么

目前还没解决方案，实在不行只有换回3.4.0了...

**Comment by Leannechn** [comment]
pr 已发布  4.1.7
