### ISSUE TITLE
x轴日期为2021-02-29的时候tooltip显示成了2021-03-01

### ISSUE THREAD

**Issue by D-KaiDi** [alibaba/BizCharts#1372]
BizCharts Version:3和4都存在
Platform:
Mini Showcase(like screenshots):
forck and create a demo: https://bizcharts.net/gist/2IxRrNMYhdJ

项目中有个需求 需要展示xxxx-02-29的数据 结果报错了导致图表展示不出来
报错如图
![image](https://user-images.githubusercontent.com/44960282/109750258-14345c80-7c17-11eb-827a-065f853b196e.png)
项目中的版本是3版本 我在官网试了3版本和四版本都不行

**Comment by BuggMaker** [comment]
2021年2月没有29号

**Comment by BuggMaker** [comment]
另外time的格式请看下官网文档Scale time

**Comment by D-KaiDi** [comment]
> 2021年2月没有29号
。。尴尬了  感谢解答
