### ISSUE TITLE
新版本外部用户无法安装

### ISSUE THREAD

**Issue by lyz810** [alibaba/BizCharts#1373]
BizCharts Version:4.1.8
Platform:
https://github.com/alibaba/BizCharts/blob/master/npm-shrinkwrap.json
这里将依赖的源设为了阿里内网源，外部用户没法访问到
@Leannechn

**Comment by hanks-yao** [comment]
+1

**Comment by nitzzzu** [comment]
seems that "registry.npm.alibaba-inc.com" is down

**Comment by Leannechn** [comment]
已更新 4.1.9, 多谢提醒。没注意到生成的shrinkwrap.json 非常抱歉。
