### ISSUE TITLE
叠加柱状图同一个柱子鼠标点击怎么区分不同的部分

### ISSUE THREAD

**Issue by TigerBill2016** [alibaba/BizCharts#140]
如题

**Comment by BambooSword** [comment]
绑在Chart的事件有回调函数，回调函数参数中有点击对应的不同堆叠数据 @TigerBill2016 
如图
![image](https://user-images.githubusercontent.com/18547539/35792668-41e83712-0a89-11e8-8417-441a3f5f5dc1.png)
