### ISSUE TITLE
是否有4.x下子弹图较为完整的demo

### ISSUE THREAD

**Issue by LuckyChou710** [alibaba/BizCharts#1400]
BizCharts Version: 4.x
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/448
是否有4.x下子弹图较完整的demo 上述的demo 我试图复制一条数据 但是页面就报错了

![image](https://user-images.githubusercontent.com/56244178/120261291-31d29a00-c2ca-11eb-9601-25cb7adbab53.png)

**Comment by Leannechn** [comment]
已修改
https://bizcharts.net/product/BizCharts4/category/77/page/142
