### ISSUE TITLE
请问可否调整x轴的偏移量 4.x下offsetX并未生效

### ISSUE THREAD

**Issue by LuckyChou710** [alibaba/BizCharts#1402]
BizCharts Version: 4.x
请问可否调整x轴的偏移量 我使用了label的offsetX并未生效 我试图将坐标轴右移一段距离
![image](https://user-images.githubusercontent.com/56244178/120620792-e538bb80-c48f-11eb-9a71-461e2a29b6c2.png)

**Comment by Leannechn** [comment]
不支持，一般认为横向便宜影响阅读。你可以通过Annotation来绘制这种非通用问题。

**Comment by Leannechn** [comment]
`<Effects>
{
     (chart) => {
       chart.render(); // 第一次渲染获取scale
       const xScale = chart.getScaleByField('x');
     //  xScale.ticks 就可以获取到所有label。Annotation支持数据坐标。
       return xScale.ticks.map(item => <Annotation.text position={{ x: item, y:0 }} content={item}/>)
       

    }
}
</Effects>
`

**Comment by LuckyChou710** [comment]
> ```
> <Effects>
> {
>      (chart) => {
>        chart.render(); // 第一次渲染获取scale
>        const xScale = chart.getScaleByField('x');
>      //  xScale.ticks 就可以获取到所有label。Annotation支持数据坐标。
>        return xScale.ticks.map(item => <Annotation.text position={{ x: item, y:0 }} content={item}/>)
>        
> 
>     }
> }
> </Effects>
> ```

ok 我尝试一下 这样的缘由是我用柱状图来绘制了直方图 通过调整它的size 但是最后发现坐标轴没对上 thank u
