### ISSUE TITLE
bulletChart 配置demo实现ok，在项目中崩溃

### ISSUE THREAD

**Issue by coco723** [alibaba/BizCharts#1406]
# 问题一： demo实现ok，在项目中页面崩溃
BizCharts Version: 4.1.10
Platform: MAC
Mini Showcase(like screenshots):
在官网上demo代码实现，可以，demo链接如下：https://bizcharts.net/gist/2SmCu2cZBOf
项目中代码如下（create-react-app新建的一个项目）：页面崩溃
![image](https://user-images.githubusercontent.com/24558814/122030447-5c5f3f80-ce00-11eb-82d6-adaeff5cc6e9.png)

问题仓库代码：https://github.com/coco723/bzicharts-dem

# 问题二：关于刻度显示
需求：![image](https://user-images.githubusercontent.com/24558814/122030749-a21c0800-ce00-11eb-9388-59aefd94075c.png)

问题描述：bulletChart中的配置data也是数组支持多个显示，那么如何配置显示：
在官网尝试实现配置
```js
yAxis={{
	tickCount: 11
}}
```
效果图如下，问题：如何调整为需求中的样式？

![image](https://user-images.githubusercontent.com/24558814/122031863-ad236800-ce01-11eb-916e-c3978d982bb1.png)

**Comment by Leannechn** [comment]
问题一：
升级兼容的时候漏考虑了多个条形图的情况。所以可以直接参考g2Plot的配置项。将数据中的 targets 改成 target。 就不会触发这个兼容bug。同时 我们会在这两天修复这个bug。

问题二：
直接添加
![image](https://user-images.githubusercontent.com/6812138/122034901-8d417380-ce04-11eb-81dc-d59ccbc93025.png)

demo地址 https://bizcharts.net/gist/2SmCu2cZBOf
