### ISSUE TITLE
[Question] Invert the visualization from axis 

### ISSUE THREAD

**Issue by viniciusrangelfp** [alibaba/BizCharts#1408]
BizCharts Version: 4.0.16
Platform:React

I'm trying to invert the Y axe.
![image](https://user-images.githubusercontent.com/29734167/122615996-e78a4080-d05f-11eb-843d-e2ba88432623.png)

In this example i want to start the counting from 0 to 16 or 1 to 16, this chart represents a ranking idea, where the Y it's the ranking it self, and the X are the week representing which ranking the user has in each week.

If i try to use the Coordenate component with reflect to do that, i`ve got a pretty weird behavior.
![image](https://user-images.githubusercontent.com/29734167/122616279-75662b80-d060-11eb-90f5-750935763232.png)

This is not bad, but when you put more charts into the same page it's very weird, since all other charts has the labels on the bottom.

Example code:
```
const data = [
        {
            "week": '17/2021',
            "year": 2021,
            "ranking": 14
        },
        {
            "week": '16/2021',
            "year": 2021,
            "ranking": 11
        },
        {
            "week": '15/2021',
            "year": 2021,
            "ranking": 1
        },
        {
            "week": '14/2021',
            "year": 2021,
            "ranking": 4
        },
        {
            "week": '13/2021',
            "year": 2021,
            "ranking": 7
        }
    ];

<Chart
            data={data}
            appendPadding={[8,12,30]}
            autoFit={true}     
        >
        <Line
                position={`ranking*week`}
                shape='smoth'
            />
</Chart>        

```

**Comment by BuggMaker** [comment]
Hi, you can solve this problem by setting x axis position to 'top'. Maybe it's a bit confusing, but it really works. See demo here: https://bizcharts.net/gist/2Vc9ji6YVK4
