### ISSUE TITLE
放弃resize-observer-polyfill，使用https://github.com/juggle/resize-observer

### ISSUE THREAD

**Issue by JaylanChen** [alibaba/BizCharts#1409]
BizCharts Version: 4.1.10
Typescript: >=4.2.3

现在在Typescript4.2.3及以上的版本都会报错 [que-etc/resize-observer-polyfill#80](https://github.com/que-etc/resize-observer-polyfill/issues/80)

使用 [https://github.com/juggle/resize-observer](https://github.com/juggle/resize-observer) 可以解决问题，因为resize-observer-polyfill作者已经3年不维护了，github活跃度为0，相反[https://github.com/juggle/resize-observer](https://github.com/juggle/resize-observer) 项目活跃度非常高。

**Comment by Leannechn** [comment]
靠谱，安排升级一下。
