### ISSUE TITLE
关于 Legend 的显示位置的一个 bug

### ISSUE THREAD

**Issue by radicalviva** [alibaba/BizCharts#141]
hi ！我最近在使用 `BizCharts` 的过程中，发现了如下 2 个问题

`BizCharts Version: 3.1.0`
浏览器： `chrome: 64.0.3282.140 `

代码在 [jsbin](http://jsbin.com/rafazinove/edit?html,js,output)

主要是如下问题：
1. 设置了 `useHtml` 属性后， `marker` 属性失效，只能是 `circle` 状态
2. 通过 `g2-legend` 设置图例的位置即便是 设置了 `right`，也会被默认设置的 `left` 给覆盖掉

**Comment by BambooSword** [comment]
1, 用了useHtml之后， marker 中内置的这些都不能用了，必须自己在html里自己定义
2， g2-legene 通过 left和top等定位，不建议用户再用left/top定位，如果非要用，在 Legend组件下设置autoPosition:{false}, 这样就能用了。建议用marginLeft等定位。 @radicalviva

**Comment by radicalviva** [comment]
@BambooSword 
感觉你解决了我上述 2 个问题，
还有一件事想请教
当我使用 `data` 数组渲染 一条折线的时候，
`Legend` 无法显示
代码在 [jsbin](http://jsbin.com/qobibumage/edit?html,js,output)

**Comment by radicalviva** [comment]
@BambooSword 
3Q
