### ISSUE TITLE
Stop doing strange requests to kcart.alipay.com

### ISSUE THREAD

**Issue by AmazingTurtle** [alibaba/BizCharts#143]
```
BIProfile:merge
d:[{"pg":"http://localhost:3000/#/app/dashboard","r":1517744165371,"g2":true,"version":"3.0.5-beta.1","page_type":"syslog"}]
```

You're doing strange requests... Stop that or make sure that everyone is aware of this.

**Comment by weepy3641** [comment]
In BizCharts's quick start tutorial, we showed that bizcharts's dependent library G2 G2 will send diagnostic info and the application URL back to AntV. As BizCharts is based on G2, this will happen as well and there is no explicitly blocking of this behavior. Request is currently being made to:

https://kcart.alipay.com/web/bi.do

Note that only the application URL and the G2 version is collected. All this information is used to help the development of G2. If you are concerned about this tracking behavior, you can turn it off by calling the following function
```
BizCharts.track(false);
```

https://github.com/alibaba/BizCharts/blob/master/doc_en/tutorial/start.md#telemetry
https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/start.md#%E4%BD%93%E9%AA%8C%E6%94%B9%E8%BF%9B%E8%AE%A1%E5%88%92%E8%AF%B4%E6%98%8E

**Comment by Stansbridge** [comment]
@weepy3641 Please note that for Chrome that certificate will be distrusted which may break this functionality on BizCharts
```
The SSL certificate used to load resources from https://kcart.alipay.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
```

Thank you for sharing how to turn tracking off :-)
