### ISSUE TITLE
component updated, legends status should reset.

### ISSUE THREAD

**Issue by ChenXiyu** [alibaba/BizCharts#144]
Hello, I like this library very much, it helps me to use G2 readily, thank you for your brilliant works.
but now, I'm facing a problem when i trying to  update the chart using a new set of data after clicked some legend,
the expected behave is reset the legends selection to all selected. but it just keep the selection status and cause some ui issues(like legends indicator's color becoming gray no matter legends selected or not). 
Is there any way to reset legends selection manually after component update or we can use some tricky way to rerender a new instance of component every time?

**Comment by weepy3641** [comment]
There are three ways to reset legend's selection state:
1、change chart's padding property, padding changing will cause bizcharts recreate the chart instance.
2、before change the data, get the g2Instance and call `` chart.filter('name', null); ``
3、get the g2Instance and call ``chart.filter('fieldName', null); ``  that's will clear chart's legend filters.

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/131

**Comment by ChenXiyu** [comment]
@weepy3641  that's works for me, thanks you!!

**Comment by 892744577** [comment]
i did it that changing chart's padding property when changing filter
