### ISSUE TITLE
柱状图-动态修改scale后图形位置偏移了

### ISSUE THREAD

**Issue by dontdrinkmylemontea** [alibaba/BizCharts#1441]
BizCharts Version: ^4.1.11
Platform: windows
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/25890927/132825734-a33c014f-72bd-4085-a18e-bc784b1d86b5.png)
![image](https://user-images.githubusercontent.com/25890927/132825842-08d503de-4a6a-4e7b-9862-060a391c85c5.png)
详情请看代码👇👇👇👇👇
forck and create a demo:  https://www.bizcharts.net/gist/30zP0c0SXD7

**Comment by programmer-yang** [comment]
https://www.bizcharts.net/product/BizCharts4/category/62/page/77#forceupdate

手动开启重绘就好了，默认scale的变化不会重绘的
