### ISSUE TITLE
文档错了： scale 度量 下面 time 的mask 

### ISSUE THREAD

**Issue by TiaossuP** [alibaba/BizCharts#145]
文档这里写错了/未同步，可以更新一下：
> 格式化日期时mask的占位符：
> 
> y: year
> m: month
> d: date
> H: hour
> M: minute
> s: second
https://github.com/alibaba/BizCharts/blob/master/doc/api/scale.md#time

g2 原文:
> 说明：mask 的占位符标准同 moment; （https://antv.alipay.com/zh-cn/g2/3.x/api/scale.html#_time）

**Comment by weepy3641** [comment]
已经修复 doc
