### ISSUE TITLE
[BUG] ios 15 任何浏览器, 使用 Geom 导致页面奔溃，无响应

### ISSUE THREAD

**Issue by 2673542667** [alibaba/BizCharts#1456]
BizCharts Version: 3.5.5
Platform: IOS15
Mini Showcase(like screenshots): 
forck and create a demo: https://bizcharts.net/product/BizCharts4/demo/306

在IOS15上，不管用Safari、还是Chrome，打开有Geom的页面都会奔溃

**Comment by fanguangpeng** [comment]
是的  antd-design-charts也有同样的问题

**Comment by yoyo837** [comment]
同样问题

**Comment by fliu2476** [comment]
g2那边已经修复了，bizcharts这边大佬们说今天发版本修复的，坐等了

**Comment by yoyo837** [comment]
包含3.x的吗

**Comment by qieshitianxia666** [comment]
IOS 15 上使用svg渲染模式就行了
![image](https://user-images.githubusercontent.com/31462855/134900546-6d308c47-db89-40c8-828d-334bddff50c6.png)

**Comment by 2673542667** [comment]
> 包含3.x的吗

包含

**Comment by 2673542667** [comment]
> IOS 15 上使用svg渲染模式就行了 ![image](https://user-images.githubusercontent.com/31462855/134900546-6d308c47-db89-40c8-828d-334bddff50c6.png)

非常感谢，改成SVG后一切就正常了，谢谢

**Comment by yoyo837** [comment]
为啥关闭呀，由于一下限制不能使用svg模式的咋办？

**Comment by yoyo837** [comment]
你们改成`svg`模式没有多出来一堆警告吗?

![image](https://user-images.githubusercontent.com/6134547/135382820-e2cc332f-684a-470d-bd63-4f09d81e08aa.png)

**Comment by yoyo837** [comment]
我还是等修复版本发布吧.
