### ISSUE TITLE
@antv/g2plot 的包名和代码中大小写不一致错误，导致打包失败

### ISSUE THREAD

**Issue by huey-LS** [alibaba/BizCharts#1458]
BizCharts Version: 4.1.12
Platform: Linux

https://github.com/alibaba/BizCharts/blob/aa3b3681a68fa461e6730d41578422badaa297cd/package.json#L50
```
    "@antv/g2plot": "2.3.35",
```

https://github.com/alibaba/BizCharts/blob/aa3b3681a68fa461e6730d41578422badaa297cd/src/core.ts#L7
```
export { setGlobal, GLOBAL } from '@antv/g2Plot/lib/core/global';
```

`@antv/g2plot` 和 `@antv/g2Plot` 大小写不一致... 导致打包错误。

可以提PR么？ 还是怎么修复呢？

**Comment by Leannechn** [comment]
bizchart@4.1.14
