### ISSUE TITLE
meaning of marginRatio

### ISSUE THREAD

**Issue by havywu** [alibaba/BizCharts#146]
![image](https://user-images.githubusercontent.com/29532857/35797448-b84160f8-0a9a-11e8-9e10-5b3af6f06a77.png)
What's meaning of this marginRatio?

**Comment by BambooSword** [comment]
It has a value from 0 to 1 and is used to adjust the spacing of individual columns in a group。

**Comment by havywu** [comment]
The ratio relative to whom.
0-1的比例是相当于单个柱子的宽度，还是group的宽度？

**Comment by havywu** [comment]
@BambooSword 
The ratio relative to whom.
0-1的比例是相当于单个柱子的宽度，还是group的宽度？

**Comment by BambooSword** [comment]
数值范围为 0 至 1，用于调整分组中各个柱子的间距

**Comment by havywu** [comment]
@BambooSword 
我的理解是这个用于调整下面的间距（如图红色的框）的，但是这个0-1应该是一个相对于x的比例吧，我不知道这个x是什么值，文档中也没有说明。
![image](https://user-images.githubusercontent.com/29532857/35843296-44e05f12-0b42-11e8-9264-a73375cdf55e.png)

**Comment by weepy3641** [comment]
marginRatio 是指分组的时候两个 shape 之间的空隙占 shape 本身宽度的比例
分母是柱子的宽度，分子是间距。

**Comment by havywu** [comment]
@BambooSword 
刚刚测试了一下，实现不了诶。
下面是代码
<html>
<head>
    <script src="https://unpkg.com/react@15.6.2/dist/react.min.js"></script>
    <script src="https://unpkg.com/react-dom@15.6.2/dist/react-dom.min.js"></script>
    <script src="https://cdn.bootcss.com/babel-core/5.8.38/browser.min.js"></script>
    <script type="text/javascript" src="//gw.alipayobjects.com/os/antv/assets/data-set/0.8.5/data-set.min.js"></script>
    <script src="https://unpkg.com/bizcharts@3.1.0/umd/BizCharts.min.js"> </script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    
  </head>
  <body>
      <div id="mountNode"><div data-reactroot=""><div><div style="position:relative;"><canvas id="canvas_1" width="631" height="400" style="width: 631px; height: 400px;"></canvas><div class="g2-tooltip" style="position: absolute; visibility: hidden; white-space: nowrap; z-index: 8; transition: visibility 0.2s cubic-bezier(0.23, 1, 0.32, 1), left 0.4s cubic-bezier(0.23, 1, 0.32, 1), top 0.4s cubic-bezier(0.23, 1, 0.32, 1); background-color: rgba(0, 0, 0, 0.65); border-radius: 4px; color: rgb(255, 255, 255); font-size: 12px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Helvetica, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, SimSun, sans-serif; line-height: 20px; padding: 10px 10px 6px;"><div class="g2-tooltip-title"></div><ul class="g2-tooltip-list"></ul></div></div></div></div></div>
      <script type="text/babel">
        const { Chart, Axis, Geom, Tooltip, Legend } = window.BizCharts;
        const data = [
          { name:'London', 'Jan.': 18.9, 'Feb.': 28.8, 'Mar.' :39.3, 'Apr.': 81.4, 'May': 47, 'Jun.': 20.3, 'Jul.': 24, 'Aug.': 35.6 },
          { name:'Berlin', 'Jan.': 12.4, 'Feb.': 23.2, 'Mar.' :34.5, 'Apr.': 99.7, 'May': 52.6, 'Jun.': 35.5, 'Jul.': 37.4, 'Aug.': 42.4}
        ];
        const ds = new DataSet();
        const dv = ds.createView().source(data);
        dv.transform({
          type: 'fold',
          fields: [ 'Jan.','Feb.','Mar.','Apr.','May','Jun.','Jul.','Aug.' ], // 展开字段集
          key: '月份', // key字段
          value: '月均降雨量', // value字段
        });
        ReactDOM.render((
          <Chart height={400} data={dv} forceFit>
            <Axis name="月份" />
            <Axis name="月均降雨量" />
            <Legend />
            <Tooltip crosshairs={{type : "y"}}/>
            <Geom type='interval' position="月份*月均降雨量" color={'name'} size={16} adjust={[{type: 'dodge',marginRatio: 10/16}]} />
          </Chart>
        ), document.getElementById("mountNode"));
    </script>
  

</body>
</html>

这边是效果
![image](https://user-images.githubusercontent.com/29532857/35852454-e4577b98-0b65-11e8-8eac-574e017a3b8a.png)

**Comment by weepy3641** [comment]
@havywu 
指定 size 的情况下，柱 的宽度就固定了，空隙 = （分组总宽度 - 所有柱子宽度和）/ 空隙个数 * marginRatio

**Comment by yaorao2770** [comment]
@havywu 最后实现了嘛？分组总宽度怎么获取呢？
