### ISSUE TITLE
BizCharts同步@Antv/g2 新版本 3.5.19

### ISSUE THREAD

**Issue by BraveHead** [alibaba/BizCharts#1460]
BizCharts Version: 3.x
Platform: safari 15
Mini Showcase(like screenshots): 请查看 https://github.com/antvis/G2/pull/3640

目前 BizCharts的3.x 版本最新为 3.5.9, 依赖的@Antv/g2版本为3.5.15，在safari 15下无法显示, 请发个最新的包解决，谢谢！

**Comment by yoyo837** [comment]
开源虽好, 活跃度低也无所谓, 但这种紧急问题还不快速响应, 真是...

**Comment by BraveHead** [comment]
https://www.npmjs.com/package/biz-test @yoyo837 我这边自己发了个包试下,把@antv/g2的版本升到3.5.19，自己这边的业务上图表可以在safari15.0版本上跑了。你可以下看能不能解决。我给他们提了PR也不理，已经不指望他们解决了，自己动手吧。

**Comment by BraveHead** [comment]
@yoyo837 我的可以

**Comment by yoyo837** [comment]
我知道为啥了, 我们直接用的npm包import进来, 它实际使用了umd的包,g2是打包到里面的, 所以我 https://github.com/alibaba/BizCharts/issues/1460#issuecomment-940628244 的`resolutions`才无用的.

**Comment by BraveHead** [comment]
@lovewenzi 等Owner发版

**Comment by lovewenzi** [comment]
好的 更新后我再替换。 感谢老铁！

**Comment by yoyo837** [comment]
@BraveHead 能把你的fork仓库共享出来吗?

**Comment by BraveHead** [comment]
@yoyo837 https://github.com/BraveHead/BizCharts

**Comment by yoyo837** [comment]
你用yarn 还是 npm 安装依赖打的包?

**Comment by yoyo837** [comment]
安装依赖时engine要求 >=4 <=9, 你如何绕过的?
