### ISSUE TITLE
ticks设置会丢失部分信息

### ISSUE THREAD

**Issue by rm1234rm1** [alibaba/BizCharts#147]
如设置ticks为[0,5,10,15,20,2u5,30,35,40]，如果图片在0-35之间即可展示完全，那么刻度40就会不显示，这样就造成了信息的丢失，但是highCharts就不会。有没有什么办法让 设置的刻度完整展示。

**Comment by weepy3641** [comment]
@rm1234rm1  
没有明白你的意思，我尝试过， ticks配置为 [0,5,10,15,20,2u5,30,35,40] ，tick 都可以显示，同时 40包括40以内的数据都能显示。
所以能否描述的清楚些，贴下具体的显示效果，预期效果，配置代码等。
