### ISSUE TITLE
色块图渲染问题：部分数据渲染错误，空白，数值重叠

### ISSUE THREAD

**Issue by amzfcy** [alibaba/BizCharts#1476]
BizCharts Version: 4.1.14
Platform:
Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/12525407/145148335-3cf9c911-a766-4300-a29f-05a95aa2c1ad.png)

forck and create a demo: https://bizcharts.net/gist/38XcumnVZGL

**Comment by mytrip** [comment]
您好，来信已收到，稍后查看邮箱将作回复，谢谢！！

**Comment by amzfcy** [comment]
大大已帮忙解决，解决方法：x，y轴数值转成字符串
