### ISSUE TITLE
柱状图的bar宽度自适应可支持宽度范围

### ISSUE THREAD

**Issue by emily-meng** [alibaba/BizCharts#148]
柱状图bar的宽度需要自适应，但并不是在数据量很小的时候变得很宽，要有一个最大值来限制bar的宽度，否则图表展示会非常丑。如果通过bar的个数来设置bar的宽度，就导致一个很大的问题，在屏幕的宽度变大和变小的时候无法确定bar的个数多少时要展示多宽。所以建议bar的设置中增加bar的size可设置一个大小范围自适应。

**Comment by BambooSword** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md
['field', [ min, max ]]，指定映射到 size 字段外，还提供了 size 的最大值和最小值范围；
这是不是你想要的功能？？？

**Comment by shirleyYing** [comment]
+1

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/632
同一个 issue，已经回复解决方案。
