### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by muxiaoyufei** [alibaba/BizCharts#15]
将鼠标悬停在图标上时Tooltip只显示一条信息，再次点击时Tooltip显示全部信息，这个需求该怎么实现

**Comment by mengchen007** [comment]
请教,项目是怎么启动的?

**Comment by muxiaoyufei** [comment]
npm 安装引入然后按使用教程启动的

**Comment by weepy3641** [comment]
@mengchen007 
按照教程就可以啦，
npm install
npm run demo
localhost 配置为 127.0.0.1
浏览器打开 localhost:3510

**Comment by weepy3641** [comment]
@muxiaoyufei 
再次点击**# 什么**时，tooltip 显示全部信息？ 你的具体需求我没太明白。

一般 tooltip 的自定义可以试试用 tooltip change 事件以及结合 tooltip html 自定义去实现。

**Comment by muxiaoyufei** [comment]
点击数值点

**Comment by weepy3641** [comment]
点击 Geom 上的数值点？ 还是点击 hover 后的 tooltip ？

**Comment by muxiaoyufei** [comment]
好的，谢谢！
