### ISSUE TITLE
import not found: registerShape

### ISSUE THREAD

**Issue by owendswang** [alibaba/BizCharts#1502]
BizCharts Version: 4.1.15
Platform: linux nodejs ice.js
Mini Showcase(like screenshots): `import not found: registerShape`
forck and create a demo: https://bizcharts.taobao.com/product/BizCharts4/demo/345

`import {
	Chart,
	Point,
	Annotation,
	Axis,
	Coordinate,
	registerShape,
} from 'bizcharts';`
简简单单就是报错`import not found: registerShape`。

**Comment by owendswang** [comment]
没事了，文档里找到了这一句：
`import { registerShape } from 'bizcharts/lib/core';`

**Comment by wusfe** [comment]
> 没事了，文档里找到了这一句： `import { registerShape } from 'bizcharts/lib/core';`

你是使用的Vite打包吗？

**Comment by wusfe** [comment]
> 您好，来信已收到，稍后查看邮箱将作回复，谢谢！！

Vite打包提示 `Uncaught SyntaxError: The requested module `

**Comment by owendswang** [comment]
> > 没事了，文档里找到了这一句： `import { registerShape } from 'bizcharts/lib/core';`
> 
> 你是使用的Vite打包吗？

嗯，我是vite，您看看bizchart官网文档吧，依赖包有没有搞全，是不是4.0以上版本。
