### ISSUE TITLE
how to add a plotLines 

### ISSUE THREAD

**Issue by cuiyonghua** [alibaba/BizCharts#153]
is there any method to add plotLines in the chart? 

like the image target date
![image](https://user-images.githubusercontent.com/550030/35956083-7402592a-0cce-11e8-98a6-a400279ea55c.png)

**Comment by weepy3641** [comment]
Use Guide Line components。

```jsx
<Guide>
  <Line  start={{x:'2019-07-01', y:0}} end={{x:'2019-07-01', y:2500}} 
   lineStyle= {{
      stroke: '#ff0000', 
      lineWidth: 1
    }} />
</Guide>
```
https://github.com/alibaba/BizCharts/blob/master/doc_en/api/guide.md#line
https://github.com/alibaba/BizCharts/blob/master/doc/api/guide.md#line

**Comment by cuiyonghua** [comment]
It's worked.  Thanks
