### ISSUE TITLE
Chart中onTooltipChange  不能修改title

### ISSUE THREAD

**Issue by xxxlihui** [alibaba/BizCharts#154]
在onTooltipChange回调中修改i每个tem的title后，toolti的title还是原来的title
是不是源码这里获取title的顺序有问题，应该放到emit后
      var title = first.title || first.name;
      // bugfix: when set the title in the tooltip:change event does not take effect.
      if (tooltip.isContentChange(title, items)) {
        chart.emit('tooltip:change', {
          tooltip: tooltip,
          x: x,
          y: y,
          items: items
        });
        tooltip.setContent(title, items);

**Comment by BambooSword** [comment]
你好，在onTooltipChange中修改title是可以生效的，只不过，items的title是根据第一个items的title而定，也就是说你只要改变items[0].title就可以改变tooltip的title了
