### ISSUE TITLE
雷达图每个轴不能设置不同的比例

### ISSUE THREAD

**Issue by Rimozhou** [alibaba/BizCharts#158]
雷达图的数据相差过大时（如一个轴的数据是300， 另一个轴的数据是0.04），生成的图不能完整的连接起来。是否有和echarts中indicator类似的属性？

**Comment by weepy3641** [comment]
@Rimozhou  
很遗憾，不可以哦。
在 g2 的雷达图中，只有一个半径轴，因此不能单位配置每个角度上半径轴的 min max，因为都是同一个轴。
