### ISSUE TITLE
火狐浏览器是否支持chart.downloadImage()方法？

### ISSUE THREAD

**Issue by Rimozhou** [alibaba/BizCharts#159]
如题，在火狐浏览器下载图片，调用chart.downloadImage()方法，并不能下载图片，也没有报错。

**Comment by weepy3641** [comment]
@Rimozhou  
浏览器什么版本？

**Comment by weepy3641** [comment]
@Rimozhou 
我这同样使用 firefox 58.0.2 (64 位) mac版，调用 downloadImage 接口，下载图片没问题哦，会弹出保存图片文件的提示框。
是否你自己的代码运行有问题？
