### ISSUE TITLE
demo地图报错，自行实现也有问题，求修正

### ISSUE THREAD

**Issue by iamhanson** [alibaba/BizCharts#16]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/map/china
这是官方的Demo，有问题，渲染不出来，可以解决么

**Comment by weepy3641** [comment]
将 demo 中
        <Geom type='polygon' position="x*y" style={{lineWidth: 1,stroke: '#fff'}} color={['count', [ 'rgb(200, 200, 255)', 'rgb(0, 0, 255)' ]]} />
这行去掉就可以了。 

站点的这个地图 demo 已经修复。

**Comment by iamhanson** [comment]
problem solved
