### ISSUE TITLE
npm package for @types/bizcharts

### ISSUE THREAD

**Issue by eswarasai** [alibaba/BizCharts#164]

**Comment by weepy3641** [comment]
fix at 3.1.3, 
src/index.d.ts

**Comment by eswarasai** [comment]
@weepy3641 -- Adding `index.d.ts` didn't fix the TypeScript errors. Can you please try following this [article](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) to publish the `types` for BizCharts? Let me know if you'd require any help from me. Thanks.

**Comment by rvanmarkus** [comment]
+1, Would be nice if the typings can be published!

**Comment by weepy3641** [comment]
@eswarasai  @rvanmarkus 
BizCharts@3.1.4-beta.4 fixed  “reference path="...." ” to  "import * as G2 from '@antv/g2/src';"
Now you can user "src/index.d.ts" directly.

**Comment by Cryrivers** [comment]
@rvanmarkus i'll create a PR. seems `types` field hasn't been added in `3.1.4-beta.4`.

**Comment by weepy3641** [comment]
@Cryrivers 
published in  3.1.4
