### ISSUE TITLE
怎么给数值增加一个单位？

### ISSUE THREAD

**Issue by chaotianwww** [alibaba/BizCharts#165]
怎么给数值增加一个单位？

**Comment by BambooSword** [comment]
你好，能更具体说明您想实现的功能吗？

**Comment by chaotianwww** [comment]
比如说在坐标轴上显示的时候，目前只能显示数值，1，2，3，4，5类似这种，但想在后面加上1（元），2（元）这种的，貌似就弄不了

**Comment by weepy3641** [comment]
可以在该轴对应的 scale 中，定义下 formatter 函数。

https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/stacked-percentage-column

https://github.com/alibaba/BizCharts/blob/master/doc/api/scale.md#%E5%BA%A6%E9%87%8F%E5%88%86%E7%B1%BB

**Comment by chaotianwww** [comment]
@weepy3641 666可以了

**Comment by chaotianwww** [comment]
![image](https://user-images.githubusercontent.com/11287694/36655421-8dab49f8-1afd-11e8-9168-2c869e2cb984.png)
还有个问题，就是加上单位rg后，为啥左测的会全变成0？？？？？

**Comment by weepy3641** [comment]
@chaotianwww 
应该是左侧的显示空间不够了，你给左侧的padding加大点。
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#7padding-objectnumberarray-

**Comment by chaotianwww** [comment]
@weepy3641 哈哈，哥，太感谢了。最近有点脑子不够用
