### ISSUE TITLE
tooltip 触发显示的内容不一致

### ISSUE THREAD

**Issue by mongris** [alibaba/BizCharts#166]
有如下实现:

```
<Chart
      data={[
        { time: 1519124400000, type: 'A', value: -100 },
        { time: 1519124400000, type: 'B', value: 2000 },
        { time: 1519124400000, type: 'C', value: -20.0022 },
        { time: 1519124400000, type: 'D', value: -5.9846 },
        { time: 1519124400000, type: 'E', value: -1980 },
        { time: 1519210800000, type: 'B', value: 0.8 },
        { time: 1519210800000, type: 'C', value: -0.008 },
        { time: 1519210800000, type: 'D', value: -0.0262 },
        { time: 1519210800000, type: 'E', value: -0.7128 },
      ]}>
      <Axis name="time" />
      <Tooltip />
      <Geom
        type="intervalStack"
        size={12}
        position="time*value"
        color="type" />
    </Chart>
```

对于同一个时间点上的数据，tooltip 的内容会随着鼠标移动而显示不同数据
![screen shot 2018-02-23 at 5 50 20 pm](https://user-images.githubusercontent.com/259816/36578439-1d393424-18c2-11e8-863c-30a969baf8f5.png)
![screen shot 2018-02-23 at 5 50 51 pm](https://user-images.githubusercontent.com/259816/36578443-1f2026e4-18c2-11e8-8717-8ec96108b0ec.png)

版本： 3.1.2
浏览器： chrome 64.0.3282.167 (Official Build) (64-bit)

**Comment by weepy3641** [comment]
@mongris 
1. 做 intervalStack 最好在分类字段上做，可以给 time 加一个 scale 定义： chart.scale('time', { type: 'timeCat' });  配置好 scale 后 tooltip 显示就没问题了，默认显示所有分类字段。

2. 想要 tooltip 在每个柱子上只显示当前分类的值，可以在 chart 的 onTooltipChange 事件中去自定义。
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#10ontooltipchange

**Comment by mongris** [comment]
@weepy3641 谢谢回复。
我用的多个图表对齐，这是一个副图表，主图表是 time scale 的 line chart。如果副图的 scale 改成 timeCat，那么坐标会对不齐。

期望的效果应该是在柱子上显示当前时间点的所有值， onTooltipChange 不能达到目的，我已经做过尝试。

**Comment by weepy3641** [comment]
@mongris 
```jsx
<Tooltip shared={false} />
// 可以让tooltip只显示柱子上当前时间点的所有值
```

**Comment by mongris** [comment]
@weepy3641 <Tooltip shared={false} /> 只能显示当前时间点的一个数据点数据，而不是所有数据。
这个问题并没有解决。
