### ISSUE TITLE
Chart在使用setState后会消除选中效果

### ISSUE THREAD

**Issue by edien8wing** [alibaba/BizCharts#167]
我在一个<Chart>中定义了选中效果  ，代码并运行正常。但是当我在页面中调用了setState后<Chart>中的所有已选中效果就会被重置掉，
`  <Geom type="interval" position={Object.keys(this.props.cols)[1]+'*'+Object.keys(this.props.cols)[0]}
         select={[true, {
         mode:  'multiple', // 选中模式，单选、多选
         style: {fill: '#ff9c00', }, // 选中后 shape 的样式
         cancelable: true , // 选中之后是否允许取消选中，默认允许取消选中
         animate: true  // 选中是否执行动画，默认执行动画
       }]} >
       <Label content={Object.keys(this.props.cols)[0]}  />
       </Geom>`

**Comment by weepy3641** [comment]
@edien8wing 
setState  中你改了什么东西？

**Comment by edien8wing** [comment]
@weepy3641  setstate一个table的data和select的值。测试过即使state的值没有render，setstate后选中效果也会失效。是否组件中 有一个设置已选中shape的方法。

**Comment by weepy3641** [comment]
@edien8wing 
setState 后图表会重新渲染，选中效果是临时状态，在 g2 中，重新渲染并不会保存选中效果。 因此 setstate 后选中效果会没有。g2 回复暂时不会修复此问题。
