### ISSUE TITLE
双线图右侧显示不全？？？？？

### ISSUE THREAD

**Issue by chaotianwww** [alibaba/BizCharts#168]
![image](https://user-images.githubusercontent.com/11287694/36627550-64fa2eea-197f-11e8-9029-8548b18f4b89.png)

**Comment by BambooSword** [comment]
你好，能描述具体点吗？

**Comment by weepy3641** [comment]
@chaotianwww 
可以通过调整 chart 的 padding 来调整显示效果。
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#7padding-objectnumberarray-

**Comment by chaotianwww** [comment]
可以了，thanks@weepy3631
