### ISSUE TITLE
设置纵坐标最小值为0，但是有时还是会出现负数

### ISSUE THREAD

**Issue by havywu** [alibaba/BizCharts#170]
![image](https://user-images.githubusercontent.com/29532857/36637141-4afdbcb4-1a10-11e8-825d-e0a46d5927ba.png)
![image](https://user-images.githubusercontent.com/29532857/36637144-5b3108de-1a10-11e8-8b37-0fb93f409d72.png)
![image](https://user-images.githubusercontent.com/29532857/36637154-8711e068-1a10-11e8-8ee6-f9eeda116669.png)

**Comment by weepy3641** [comment]
@havywu 
为了达到好的显示效果， scale 内部会有可能会计算一个更合理的值。可以将 yscale 的 nice 设置为 false 试试看。
```jsx
yscale:{
  nice: false,
  min: 0,
  type: 'linear'
}
```

**Comment by weepy3641** [comment]
@havywu 
能否将你的数据和配置都贴出来。

**Comment by havywu** [comment]
数据结构：
![image](https://user-images.githubusercontent.com/29532857/36714288-852a1622-1bcc-11e8-9358-b1cb5d16abb1.png)
配置
![image](https://user-images.githubusercontent.com/29532857/36714313-9ec2e78a-1bcc-11e8-8d38-29a57b89bbad.png)

**Comment by weepy3641** [comment]
@havywu 
知道问题了，应该是你的 scale 没有设置对地方。
你用 view 去画线图，view 基本上等同于一个独立的嵌套在 chart 内的图表，几乎拥有跟 chart 一样的配置、属性、能力。
因此你的 scale 应该设置在 view 上。

https://github.com/alibaba/BizCharts/blob/master/doc/api/view.md#6scale--object-

**Comment by havywu** [comment]
@weepy3641 刚刚在view上加了相同的配置，nice为false的时候，仍然有负数出现；若nice设置为false，会出现如下情况，最大值竟然没有纵坐标值。
![image](https://user-images.githubusercontent.com/29532857/36774792-6e7a7b5a-1c9a-11e8-8fbc-28d8b807cc03.png)

**Comment by SaundersDong** [comment]
@weepy3641 数值最小值min支持回调吗

**Comment by weepy3641** [comment]
@SaundersDong  scale 中不支持回调。
