### ISSUE TITLE
beta 版本发布到 npm 的 latest tag 上不符合预期?

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/BizCharts#171]
![image](https://user-images.githubusercontent.com/3922719/36656267-81901036-1b02-11e8-916d-33e395a3a908.png)

若发布的时候版本号为  3.1.1-beta.9   执行  `npm publish` 会默认发布到 latest  tag 上, 这个时候执行 `npm install bizcharts` 就会安装上这个版本, 应该是不符合预期的

![image](https://user-images.githubusercontent.com/3922719/36656310-bf5513da-1b02-11e8-9867-3b158a5efd3d.png)

我们通常的做法是在发布 beta 版本的时候使用  `npm publish --tag=beta`   这样不会影响到 latest

**Comment by wssgcg1213** [comment]
可以参考 react 的tag  
![image](https://user-images.githubusercontent.com/3922719/36656372-08f61fca-1b03-11e8-866a-f1d3b51b3d4f.png)

**Comment by weepy3641** [comment]
@wssgcg1213 
好的，之后的 beta 版本会这样发布。
