### ISSUE TITLE
如何使用透明度颜色？比如rgba格式

### ISSUE THREAD

**Issue by Aaronphy** [alibaba/BizCharts#172]
求解答

**Comment by weepy3641** [comment]
@Aaronphy 
看具体在什么地方想要配置透明度。
大部分地方可以通过 fillOpacity 和 strokeOpacity 配置。

**Comment by Aaronphy** [comment]
@weepy3641 Geom组件 color属性

**Comment by weepy3641** [comment]
直接使用 geom 的 opacity 属性即可，可以是固定的数值也可以是字段。
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#7opacity-----string--array--number-
```jsx
<Geom type="line" position="year*value" opacity={0.5}  />
```

**Comment by Aaronphy** [comment]
@weepy3641  你花名是啥？我直接内网联系你。还有些问题需要请教你

**Comment by weepy3641** [comment]
@Aaronphy 
花名芈乐～～
