### ISSUE TITLE
设置数据标签时，可以仿造highCharts关闭一部分，展示一部分吗？

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#173]
"data": [{
"y": 0.33,
"name": "视频",
"sliced": false,
"color": "transparent",
"dataLabels": {
"enabled": false
}
}, {
"y": 0.144,
"name": "休闲益智",
"sliced": false,
"color": "#995655"
}, {
"y": 0.0736,
"name": "冒险射击",
"sliced": false,
"color": "#81965B"
}, {
"y": 0.0448,
"name": "动作策略",
"sliced": false,
"color": "#74648C"
}, {
"y": 0.0576,
"name": "其他游戏",
"sliced": false,
"color": "#538A9B"
}, {
"y": 0.11,
"name": "阅读",
"sliced": false,
"color": "transparent",
"dataLabels": {
"enabled": false
}
}, {
"y": 0.04,
"name": "音乐",
"sliced": false,
"color": "transparent",
"dataLabels": {
"enabled": false
}
}, {
"y": 0.2,
"name": "其他",
"sliced": false,
"color": "transparent",
"dataLabels": {
"enabled": false
}
}]

**Comment by weepy3641** [comment]
@rmabcft 
是 geom 上的 label ？ 如果是有两种方式做这件事。
1、通过 label 上的 content 属性，传入数据和对应的 callback 函数，在 callback 函数中控制显示的内容，不需要显示返回空。
2、通过 fomatter 函数是做。

https://github.com/alibaba/BizCharts/blob/master/doc/api/label.md#1content--string--arraystring-function-
https://github.com/alibaba/BizCharts/blob/master/doc/api/label.md#6formatter---function-

**Comment by rmabcft** [comment]
这个问题已经得到了解决。通formatter函数进行设置的。
