### ISSUE TITLE
下一次渲染时去处 Geom 的 color 属性造成崩溃

### ISSUE THREAD

**Issue by zhuscat** [alibaba/BizCharts#174]
## 复现：

[![Edit o906w3w8mq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o906w3w8mq)

https://codesandbox.io/s/o906w3w8mq

**复现步骤：**

点击 `toggle` 按钮即可发生错误，一开始 `color` 为 `genre`，之后删去该 `prop`

## 报错信息

![2018-02-27 09 13 38](https://user-images.githubusercontent.com/14963619/36705125-8a667816-1b9e-11e8-84d0-742951c07146.png)

**Comment by weepy3641** [comment]
fix at bizcharts 3.1.3
