### ISSUE TITLE
tooltip 触发显示的内容不一致

### ISSUE THREAD

**Issue by mongris** [alibaba/BizCharts#175]
Ref: #166 

并没有解决，而问题已经被关闭，我只好重新再开一个了。

有如下实现:

```
<Chart
      data={[
        { time: 1519124400000, type: 'A', value: -100 },
        { time: 1519124400000, type: 'B', value: 2000 },
        { time: 1519124400000, type: 'C', value: -20.0022 },
        { time: 1519124400000, type: 'D', value: -5.9846 },
        { time: 1519124400000, type: 'E', value: -1980 },
        { time: 1519210800000, type: 'B', value: 0.8 },
        { time: 1519210800000, type: 'C', value: -0.008 },
        { time: 1519210800000, type: 'D', value: -0.0262 },
        { time: 1519210800000, type: 'E', value: -0.7128 },
      ]}>
      <Axis name="time" />
      <Tooltip />
      <Geom
        type="intervalStack"
        size={12}
        position="time*value"
        color="type" />
    </Chart>
```

对于同一个时间点上的数据，tooltip 的内容会随着鼠标移动而显示不同数据
![screen shot 2018-02-23 at 5 50 20 pm](https://user-images.githubusercontent.com/259816/36578439-1d393424-18c2-11e8-863c-30a969baf8f5.png)
![screen shot 2018-02-23 at 5 50 51 pm](https://user-images.githubusercontent.com/259816/36578443-1f2026e4-18c2-11e8-8717-8ec96108b0ec.png)

版本： 3.1.2
浏览器： chrome 64.0.3282.167 (Official Build) (64-bit)

**Comment by BambooSword** [comment]
我看了你之前的问题，是不是在Chart中 加入 scale = {{
        time: { type: 'time' }
      }}，就是你想要的效果了？？？ @mongris

**Comment by mongris** [comment]
@BambooSword 我的实际代码里已经设置了 scale ={{ time: { type: 'time' } }}

我遇到的问题是在 scale.time = { type: 'time' } 下，用 intervalStack 来显示数据，tooltip 会不一致

原帖中，@weepy3641 建议我设置为 { type: 'timeCat' }，但这个 chart 其实是一个副图，x轴与主图对齐，x轴是 scale.time = { type: 'time' }  下的 line chart

尝试过 onTooltipChange，只能获取一个数据点，无法拿到 x 轴上某一个时间点上的全部数据点

**Comment by mongris** [comment]
多谢两位回复

不知道是否在 timeCat 设置下，可以设置 x 轴偏移？这样我能够实现与主图的 x 轴对齐，也可以作为一个 workaround

**Comment by weepy3641** [comment]
@mongris 
x 轴目前只有 label 可以偏移。 
```jsx
<Axis name='type' label={offset:10} />
```
另外跟 g2 聊过了，堆叠图表 x 轴必须是类目轴，即你这个地方的时间轴 scale 需要为 'timeCat' 否则不保证堆叠的正确性。

**Comment by mongris** [comment]
sigh。。我再想其他的解决方式吧
