### ISSUE TITLE
设置坐标系旋转时，Label组件不跟着旋转，只是文本旋转？希望坐标系旋转时，支持其他组件跟随旋转

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#176]
<Chart height={window.innerHeight} data={dv} scale={cols} padding={[ 80, 100, 80, 80 ]} forceFit>
          <Coord type={'theta'} radius={0.75} innerRadius={0.6} rotate={80}/>
          <Axis name="percent" />
          <Legend position='right' offsetY={-window.innerHeight / 2 + 120} offsetX={-100} />
          <Tooltip 
            showTitle={false} 
            itemTpl='<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
            />
          <Guide >
            <Html position ={[ '50%', '50%' ]} html='<div style="color:#8c8c8c;font-size:1.16em;text-align: center;width: 10em;border:1px solid #f00；">主机<br><span style="color:#262626;font-size:2.5em">200</span>台</div>' alignX='middle' alignY='middle'/>
          </Guide>
          <Geom
            type="intervalStack"
            position="percent"
            color='item'
            tooltip={['item*percent',(item, percent) => {
              percent = percent * 100 + '%';
              return {
                name: item,
                value: percent
              };
            }]}
            style={{lineWidth: 1,stroke: '#fff'}}
            >
            <Label  content='percent' formatter={(val, item) => {
                return item.point.item + ': ' + val;}}/>
          </Geom>
        </Chart>

**Comment by weepy3641** [comment]
@rmabcft 
坐标系旋转，label 默认不旋转的，想要 label 旋转可以通过 label 自身的 rotate 属性做到。
```jsx
<Label
 content='sales'
 textStyle={{
   rotate: 30, // 这里，可以配置 label 的旋转
   fill: '#404040', // 文本的颜色
   fontWeight: 'bold', // 文本粗细
 }}
/>
```

**Comment by rmabcft** [comment]
这里的rotate只是文本的旋转，而不是label组件旋转。对于饼图而言是不可取的方式。

**Comment by weepy3641** [comment]
@rmabcft 
如果是饼图，设置 coord 的 startAngle 和 endAngle 可以解决问题。

```
<Coord 
              type='theta' 
              radius={0.75} 
              startAngle={0.5}
              endAngle={6.8}
              
            />
```

同 g2 issue
https://github.com/antvis/g2/issues/500

**Comment by rmabcft** [comment]
如果考虑分离度呢，分离度只是g2没有考虑到，但是在实际情况下分离度也是比较常用的，这个时候，用startAngle和endAngle是有一些问题的。不过目前我采用的也是这个方案。希望g2和biz能提供对分离度的支持。

**Comment by weepy3641** [comment]
@rmabcft 
同学，分离度跟 g2 对过了，暂时没有支持，如果需要，你可以先去 g2 体个issue。
