### ISSUE TITLE
不同视图下的图例不能都显示嘛？

### ISSUE THREAD

**Issue by wxmdsh** [alibaba/BizCharts#177]
![image](https://user-images.githubusercontent.com/33385371/36832658-5ff890b2-1d67-11e8-8caa-3d637661fe38.png)
比如exposureRate是右轴的，其他的三个是左轴的，  但是设置图例的时候咋只有左轴的三个呀，右轴的设置没用，左右轴是两个view

**Comment by weepy3641** [comment]
view 相当于 独立的 chart，想要 view 中的 legend 也显示，需要在 view 组件中声明 legend 组件。

```
 <Chart>
  <View>
    <Legend/>
    <Geom color='type' />
  </View>
</Chart>
```

**Comment by weepy3641** [comment]
view 相当于 独立的 chart，想要 view 中的 legend 也显示，需要在 view 组件中声明 legend 组件。

```jsx
 <Chart>
  <View>
    <Legend/>
    <Geom color='type' />
  </View>
</Chart>
```

**Comment by wxmdsh** [comment]
对，他们是独立，，    刚刚那个我改好了， 但是只有一个view的图例能点击，另外一个图例是不是要自己加点击事件，才能有一些默认的带的效果，比如线条的隐藏出现什么的

**Comment by weepy3641** [comment]
你这的 legend 是由于 color='某分类' 才出现的，你是不是有的 view 中没有配置 color='某分类' ？
如果没有，则该 view 没有自己的 legend，需要自己去自定义。
