### ISSUE TITLE
Labels do not show complete

### ISSUE THREAD

**Issue by Hongbo-Miao** [alibaba/BizCharts#178]
Labels do not show complete when they are long.

<kbd>[Live demo](https://stackblitz.com/edit/react-tarys9?file=index.js)</kbd>

BTW, the package looks awesome!

![image](https://user-images.githubusercontent.com/3375461/36835453-212c8bda-1ceb-11e8-9a06-56aa0fcac44f.png)

**Comment by Hongbo-Miao** [comment]
Sorry, duplicate with https://github.com/alibaba/BizCharts/issues/168

**Comment by Hongbo-Miao** [comment]
我看到

> padding 中存在 'auto'，时会自动计算边框，目前仅考虑 axis 和 legend 占用的边框。

所以现在，当纵坐标的label长度预先不知道时，还没有办法自动计算padding，是吗？谢谢

**Comment by weepy3641** [comment]
@Hongbo-Miao 
目前已经支持自动计算了， ``padding='auto' | padding=['20', 'auto', '80', 'auto'];``

更多 padding 的格式请查看 chart 的api 文档。
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#7padding-objectnumberarray-

**Comment by Hongbo-Miao** [comment]
哦 我之前用成了
```
<Chart height={400} data={dv} forceFit padding={{ top: 20, right: 30, bottom: 20, left: 'auto' }}>
```
改成
```
<Chart height={400} data={dv} forceFit padding={[20, 30, 30, 'auto']}>
```
就好了！

非常感谢！
