### ISSUE TITLE
官网demo 中国地图省市下钻有问题，希望指导

### ISSUE THREAD

**Issue by iamhanson** [alibaba/BizCharts#18]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/map/drill-down

**Comment by weepy3641** [comment]
今天稍晚会更新个版本，同时升级下官网这个 demo。请稍后。。。

**Comment by weepy3641** [comment]
3.0.4 已经解决，github bizcharts 上的 drill-down  demo 已经是修复后的了，可以实现地图下钻和联动。
data-set 版本必须 > 0.6.2.

站点上的 demo 稍后会更新。

**Comment by zakilo** [comment]
这个demo右边的下级地图没出来

**Comment by weepy3641** [comment]
@zakilo 
bizcharts 代码仓库中，demo 里面的 drill down 地图下钻已经修复可以正常运行，你可以直接去仓库的 demo 中查看。
官网要明天更新。

**Comment by zakilo** [comment]
@weepy3641 好的
