### ISSUE TITLE
Warning: `name` propertry should not be changed in `<Axis />`

### ISSUE THREAD

**Issue by yuanxiaoyu** [alibaba/BizCharts#180]
如何动态更新 axis节点name   ?

**Comment by weepy3641** [comment]
axis 的 name 代表着你想要配置的那个轴。加入改变 name， 那么老的名字代表的轴怎么办？ 是删掉？ 目前 bizcharts 没有默认这一行为。
想要动态更新 axis name，可以通过动态增加 axis 组件和 删除旧的 axis 组件做到。 用户自己控制老的轴和新的轴的行为。

例如：
```jsx
const axisName = 'month';
<Chart>
  axisName == 'month' ? <Axis name='month' /> : null
  axisName == 'xxx' ? <Axis name='xxx' /> : null
</Chart>
```

**Comment by joriewong** [comment]
@yuanxiaoyu just warning
```
const axisName = 'month';
<Chart>
  <Axis name={axisName} />
</Chart>
```

**Comment by yuanxiaoyu** [comment]
@weepy3641    我本来是动态加入的   

 render(){
    const {width,height,padding} = this.chartProps();
    let axisProps = this.axisProps({
      label:{
        textStyle:{
          fill:this.props.x_fontColor,
          fontSize:this.props.x_fontSize,
          rotate:this.props.x_rotate
        }
      }
    },{
      label:{
        textStyle:{
          fill:this.props.y_fontColor,
          fontSize:this.props.y_fontSize,
          rotate:this.props.y_rotate
        }
      }
    });
     let geomProps = this.geomProps("interval");
      const x_bind = this.props.x_bind || "year";
      const y_bind = this.props.y_bind || ["sales"];
      const ds = new DataSet();
      const dv = ds.createView().source(this.state.data);
      dv.transform({
          type: 'fold',
          fields: y_bind, // 展开字段集
          key: 'type', // key字段
          value: 'value', // value字段
      });
    return <Chart {...{width,height,padding}} data={dv}>
        {axisProps}
        {geomProps}
      <Tooltip crosshairs={{type: "y"}}/>
    </Chart>
  }

axisProps = (xprops,yprops)=>{
    let axis = [];

    if(this.props.x_bind && this.props.y_bind && this.props.y_bind.length){
      if(this.props.x_bind){
        axis.push(<Axis key={axis.length} name={this.props.x_bind} {...xprops}/>);
      }
      if(this.props.y_bind && this.props.y_bind.length){
        axis.push(<Axis key={axis.length} name="value" {...yprops}/>)
      }
    }else{
      axis = [
        <Axis name="year" key={0} {...xprops}/>,
        <Axis name="sales" key={1} {...yprops}/>
      ];
    }
    return axis;
  }



就这样每次更新axisProps会报错

**Comment by Leannechn** [comment]
方便的话请写一个codepen，或者将报错信息写的详细些方便debug。

**Comment by kakera** [comment]
可以通过指定 key 确保新建一个 Axis 而不是复用旧的，这样就不会出现警告了
`
const axisName = 'foo'
<Axis key={axisName} name={axisName} />
`
