### ISSUE TITLE
bizCharts是用什么控制分离度的

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#182]
![_20180301201816](https://user-images.githubusercontent.com/36733235/36844412-9bb38758-1d8d-11e8-94b1-c1467d7415a1.png)
我目前使用的是onGetG2Instance={g2Chart => {
	let shape= g2Chart.getAllGeoms()[0].getShapes()[0]
        g2Chart.getAllGeoms()[0].setShapeSelected(shape)
  }}这种方法去做分离，虽然可以控制每一块的分离状态，可是在分离的块比较多时，会造成内存泄露，里面含有大量的计算。而且分离度不可控。还有一种方式是适用geom里面的style:{stroke:'#fff',lineWidth:10},分离度用lineWidth去控制，可是不能控制每一块的分离状态。有没有其他好的方式呢？

**Comment by weepy3641** [comment]
等同于 ： https://github.com/alibaba/BizCharts/issues/182
