### ISSUE TITLE
希望Biz可以支持条饼图 

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#185]
![_20180301203125](https://user-images.githubusercontent.com/36733235/36878621-cf2a9474-1dfa-11e8-814c-03b4684af55f.png)
如图，俩个图形是左右布局，这点可以用Facet去控制布局，但是右边图形的数据是从左边图形的数据衍生来的，所以俩个数据之间是有联系的。但是BizCharts会将第二个图形作为一个单独的个体去设置，俩个图形之间并没有建立联系。

**Comment by weepy3641** [comment]
1、bizcharts 暂时不会直接内置这种复合图表，但会在以后推出复杂图表的 demo。
2、你自己要做这个图表，用两个 view 去做，点击饼图的适合出发下右边堆叠柱状图的数据更新即可。

**Comment by rmabcft** [comment]
我用俩个view做了，但是存在一些问题。俩条线的显示我选择用geom里面的line去做，可是没有合适的方法获取到坐标点

**Comment by weepy3641** [comment]
@rmabcft 
你右边的 view 有独立的数据啊，你将左边饼图代表的数据传递到右边的数据中就可以了啊。
