### ISSUE TITLE
Labels rotate after adding title on y-axis

### ISSUE THREAD

**Issue by Hongbo-Miao** [alibaba/BizCharts#187]
在没加纵坐标title前，是这样的
![image](https://user-images.githubusercontent.com/3375461/36887381-cccc77a6-1da5-11e8-94d1-39cbf812b7de.png)

但当加了 `title={true}`以后，纵坐标的label会变得很斜

![image](https://user-images.githubusercontent.com/3375461/36887395-e7b1003c-1da5-11e8-9190-343947f3926f.png)

根据[label文档](https://github.com/alibaba/BizCharts/blob/master/doc/api/axis.md#7label-object)，我尝试加`rotate: 0`属性在label上，但依然不管用。

<kbd>[Live demo](https://stackblitz.com/edit/react-hcqdsw?file=index.js)</kbd>(看到Can't find module 错误的话，随便编辑一下code，比如增加个空格，就可以正常运行了）

```jsx
    const data = [
      { 'State': 'A1234567890', '小于5岁': 25635, '5至13岁': 1890, '14至17岁': 9314 },
      { 'State': 'B1234567890', '小于5岁': 30352, '5至13岁': 20439, '14至17岁': 10225 }
    ];
  
    const ds = new DataSet();
    const dv = ds.createView().source(data);
    dv.transform({
      type: 'fold',
      fields: [ '小于5岁', '5至13岁', '14至17岁' ],
      key: '年龄段',
      value: '人口数量',
      retains: [ 'State' ]
    });

    const scale = {
      'State':{
        alias:'省份'
      }
    };

    const label = {
      offset: 12,
      rotate: 0 // <- 我尝试加这个属性，但依然不管用
    };

    return (
        <Chart height={400} data={dv} scale={scale} padding="auto" forceFit>
          <Legend />

          <Coord transpose />
          <Axis name="State" label={label} title={true} />
          <Axis name="人口数量" />
          <Tooltip />
          <Geom type="intervalStack" position="State*人口数量" color={'年龄段'} />
        </Chart>
    );
```

**Comment by weepy3641** [comment]
```
    const label = {
      offset: 12,
      autoRotate: false // 关闭自动旋转。
    };
```

**Comment by Hongbo-Miao** [comment]
Thanks!

**Comment by MrMuhammadRizwan** [comment]
you can try this
<Axis name="genre" label={{ offset: 5,  textStyle: { rotate: 90, textAlign : ' left ' } }}/>
or
just add "label={{ offset: 5,  textStyle: { rotate: 90, textAlign : ' left ' } }}" in you Axis
