### ISSUE TITLE
饼图的 setSelected 怎么设置？

### ISSUE THREAD

**Issue by fengsx** [alibaba/BizCharts#188]
在 G2 v3.0.5 版本中可以设置在初始化时，默认选中某一块儿数据。文档在[这里](https://antv.alipay.com/zh-cn/g2/3.x/api/geom.html#_setSelected)。但是在
BizCharts 里没有找到选中的方法。
设置前的效果如图：
![image](https://user-images.githubusercontent.com/7709602/36943868-d3ed3d54-1fcb-11e8-99bf-c1bdd769d358.png)

setSelected 设为示例一后的效果如图：

![image](https://user-images.githubusercontent.com/7709602/36943881-253ef54e-1fcc-11e8-9cf4-1b3a6e7f5dab.png)

G2 v3 设置代码如图：
![image](https://user-images.githubusercontent.com/7709602/36943809-c85e4470-1fca-11e8-80c0-6de94ab46151.png)

**Comment by rmabcft** [comment]
setSelected这里可以使饼图分离，那如何控制分离度？每一块的分离度要如何控制呢？

**Comment by weepy3641** [comment]
@fengsx 
setSelected 是 chart 上的方式，在bizcharts中想要使用，需要那个 g2 的chart 实例。
```
<Chart onGetG2Instance={ (chart)=>{ chart.setSelected(...); } } />
```

**Comment by rmabcft** [comment]
onGetG2Instance是一个非常大的对象，当饼图是多层且分离的块比较多时，会造成内存泄露，可以提供一个方式去初始化每一块的分离状态吗。

**Comment by rmabcft** [comment]
let keys=[0,1,2]
onGetG2Instance={
		            g2Chart => {
		            	keys.map(function(k){
		            		let shape= g2Chart.getAllGeoms()[0].getShapes()[k]
		            		g2Chart.getAllGeoms()[0].setShapeSelected(shape,true)
		            	})	
	 				}
	            }

**Comment by fengsx** [comment]
@rmabcft  的方法是对的
```jsx
<Chart
    onGetG2Instance={(chart) => {
      const gemos = chart.getAllGeoms()[0];
      gemos.setShapeSelected(gemos.getShapes()[0], true);
   }}
>
</Chart>
```

**Comment by weepy3641** [comment]
@dongkang1993 
最后再调用下绘制函数。
```
chart.repaint();
```

**Comment by dongkang1993** [comment]
解决了，非常感谢！！！ @weepy3641

**Comment by a654688383** [comment]
能否给个选中的完整demo呢，万分感谢

**Comment by heiniuhaha** [comment]
https://bizcharts.net/products/bizCharts/demo/detail?id=pie-setselected&selectedKey=%E9%A5%BC%E5%9B%BE

![image](https://user-images.githubusercontent.com/668144/63350731-8c6a6280-c390-11e9-85de-2aef3639aa21.png)

**Comment by abellee** [comment]
2019年了 有人说一下最新用法吗？完全没有这些方法啊

**Comment by abellee** [comment]
如果有typescript因为遇到没有类型声明报错的，用字符串形式来调用就好了
`chart.getAllGeoms()[0]['setShapeSelected'](...)` 这样

**Comment by WebFishtoFly** [comment]
想问下大神 怎么通过鼠标移入而不是点击就实现突出的效果啊？
