### ISSUE TITLE
请问怎么设置多条曲线？

### ISSUE THREAD

**Issue by LeesinChen** [alibaba/BizCharts#189]
demo看了半天，还是没弄明白，不用数据转化不可以吗？

**Comment by weepy3641** [comment]
要看你自己具体是什么样的数据，才能决定要不要数据转化。 多条曲线图有多种做法.
1、 `` <Geom color='type' /> `` 用 color 去分组数据显示多条线。
2、`` <Geom  /> <Geom /> `` 用多个 geom 去做，但这样实际上是多轴多点图，要做成什么样要看具体需求。

**Comment by LeesinChen** [comment]
万分感谢！终于弄明白了！
