### ISSUE TITLE
Theme在不同component render中切换失败

### ISSUE THREAD

**Issue by shuson** [alibaba/BizCharts#191]
Component1 render function里设置setTheme("dark")

Component2 render function里设置setTheme("default")

然后挂到app element
```html
<div id="app">
  <Component1 />
  <Component2 />
</div>
```

结果是Component1 和Component2 都是dark theme了

**Comment by weepy3641** [comment]
@shuson 
g2 中 setTheme 是全局切换主题的函数，会影响到所有图表的显示效果。
因此 bizcharts 中也是这样的特性，不能为单个组件配置主题。
如果有此需求，可以去 g2 中体个 issue， bizcharts 组件主题的支持需要 g2 支持。

**Comment by shuson** [comment]
看到G2 的文档有写调整局部主题
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/theme.html

但是没有找到bizcharts里的方法

**Comment by shuson** [comment]
也就是说只要setTheme("dark") 就没办法通过setTheme("default")回去了吧

**Comment by weepy3641** [comment]
@shuson 
g2 文档你理解有误差了，主题只能设置全部的。
想要一个组件一个主题，只能够是在每一个图表窗前见都 setTheme 一次，但这样的做法一旦页面刷新、状态变换很可能会有问题。

最直接的解决方式式，让 g2 支持没单个的 chart 配置主题。 例如 chart.setTheme() ,这样的方式，主题作为 chart 配置的一部分，就可以完全解决你的问题了。

**Comment by shuson** [comment]
我去G2开new feature request。lol
