### ISSUE TITLE
数据容错能力

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#193]
<script type="text/babel">
        // var BizCharts = window.BizCharts;
        // const Chart = BizCharts.Chart;
        // const Axis = BizCharts.Axis;
        // const Geom = BizCharts.Geom;
        // const Tooltip = BizCharts.Tooltip;
        const { Chart, Axis, Geom, Tooltip } = window.BizCharts;
        const data = [
          { year: '', sales: 38 },
          { year: '', sales: 52 },
          { year: '1956 年', sales: 61 },
          { year: '1957 年', sales: 145 },
          { year: '1958 年', sales: 48 },
          { year: '1959 年', sales: 38 },
          { year: '1960 年', sales: 38 },
          { year: '1962 年', sales: 38 },
        ];
        const cols = {
          'sales': {tickInterval: 20},
        };
        ReactDOM.render((
          <Chart height={400} data={data} scale={cols} forceFit>
            <Axis name="year" />
            <Axis name="sales" />
            <Tooltip crosshairs={{type : "y"}}/>
            <Geom type="interval" position="year*sales" />
          </Chart>
        ), document.getElementById("mountNode"));
    </script>
  图1:
![_20180306144108](https://user-images.githubusercontent.com/36733235/37017643-500eb5d0-214c-11e8-8b72-a8059f626464.png)
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: '各洲不同时间的人口条形图'
        },
        subtitle: {
            text: '数据来源: Wikipedia.org'
        },
        xAxis: {
            categories: ['非洲', '美洲', '亚洲', '', ''],
            title: {
                text: null
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: '人口总量 (百万)',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        },
        tooltip: {
            valueSuffix: ' 百万'
        },
        plotOptions: {
            bar: {
                dataLabels: {
                    enabled: true,
                    allowOverlap: true
                }
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -40,
            y: 100,
            floating: true,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true
        },
        credits: {
            enabled: false
        },
        series: [{
            name: '1800 年',
            data: [107, 31, 635, 203, 2]
        }, {
            name: '1900 年',
            data: [133, 156, 947, 408, 6]
        }, {
            name: '2008 年',
            data: [973, 914, 4054, 732, 34]
        }]
    });
});
图2:
![image](https://user-images.githubusercontent.com/36733235/37017778-dc88e170-214c-11e8-8765-70ac187be9b2.png)
当x轴数据为''时，bizCharts的容错能力没有highCharts好。

**Comment by weepy3641** [comment]
首先两个图表完全是不同类型，接收的数据格式也完全不同，不能同一而论。
bizcharts 那个图表第一个‘’刻度下有两条数据，因此显示成一个位置，这并不是错误，两个数据一样即使是空字符串当前会显示在同一个地方。

想要 highcharts 的效果，可以用同一做分组并列柱状图，应该是没有问题的。
