### ISSUE TITLE
BizCharts是否支持嵌套柱形图？要如何设置？

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#195]
![6bb7baf00fd29518da49f4897d656f9](https://user-images.githubusercontent.com/36733235/37019328-df52997c-2152-11e8-9169-2796f59dfe9d.png)

**Comment by weepy3641** [comment]
实际上根据你的设计稿，可以认为是重叠的柱状图，并且还是双轴的。
可以用两个 geom 去做，size 和 position 的 y 设置成不一样即可。
