### ISSUE TITLE
请问怎么设置饼图的默认打开

### ISSUE THREAD

**Issue by kingrui** [alibaba/BizCharts#197]
请问怎么设置饼图的默认打开，即用代码控制饼图的默认选中状态，如下图：
![image](https://user-images.githubusercontent.com/6029005/37024811-dde2573c-2164-11e8-9965-a16d5f8e3585.png)
我希望蓝色部分默认是选中状态的，请问如何设置，对应的文档地址是什么，谢谢！

**Comment by weepy3641** [comment]
相关解决问题的issue：https://github.com/alibaba/BizCharts/issues/188
