### ISSUE TITLE
饼图百分比堆叠时，获取不到y轴的值

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#198]
<script type="text/babel">
        const { Chart, Axis, Geom, Tooltip, Coord, Legend, Label } = window.BizCharts;
        const { DataView } = DataSet;
        const data = [
          { item: '事例一', y: 40 },
          { item: '事例二', y: 21 },
          { item: '事例三', y: 17 },
          { item: '事例四', y: 13 },
          { item: '事例五', y: 9 }
        ];
        const dv = new DataView();
        dv.source(data).transform({
          type: 'percent',
          field: 'y',
          dimension: 'item',
          as: 'percent'
        });
        const cols = {
          percent: {
            formatter: val => {
              val = (val * 100) + '%';
              return val;
            }
          }
        }   
        ReactDOM.render((
          <Chart height={window.innerHeight} data={dv} scale={cols} padding={[ 80, 100, 80, 80 ]} forceFit>
            <Coord type='theta' radius={0.75} />
            <Axis name="percent" />
            <Legend position='right' offsetY={-window.innerHeight / 2 + 120} offsetX={-100} />
            <Tooltip 
              showTitle={false} 
              itemTpl='<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
              />
            <Geom
              type="intervalStack"
              position="percent"
              color='item'
              tooltip={['item*percent',(item, percent) => {
                percent = percent * 100 + '%';
                return {
                  name: item,
                  value: percent
                };
              }]}
              style={{lineWidth: 1,stroke: '#fff'}}
              >
              <Label content='percent' formatter={(val, item) => {
                  console.log(item)
                  return item.point.item + ': ' + val;}} />
            </Geom>
          </Chart>
        ), document.getElementById("mountNode"));
    </script>
![image](https://user-images.githubusercontent.com/36733235/37031335-56bc1e5e-2179-11e8-9311-878110fe658d.png)

打印item是获取不到data中的y的值的。但是当key值变为其他的字符串，是可以获取到的，是bizCharts做处理了吗

**Comment by BambooSword** [comment]
你好，你说的是什么意思？ 方便说清楚一点吗？或者加我的钉钉15356664751，咱们私聊 @rmabcft

**Comment by rmabcft** [comment]
我想在Label里面调用formatter函数，通过item.point.y获取数值，但是发现如果data里面的数据是{y:3}，即当key值是‘y’字符串时，并且是堆叠的情况下，通过item.point.y是获取不到数值的，这个时候item.point.y指的应该是label组件的圆心坐标点。我是这样理解的。所以是不是bizCharts对这种情况做了处理

**Comment by RemyGong** [comment]
@rmabcft 在底层G2的实现中，y在数据结构中默认表示为y坐标位置，你的数据中如果有key值为y的情况，会被y坐标值覆盖导致item.point.y获取的不对，建议对原有的数据key值做一下rename处理。
