### ISSUE TITLE
调节俩个view的距离发现padding会影响view的大小？

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#199]
![image](https://user-images.githubusercontent.com/36733235/37145607-3cbdd978-22fc-11e8-90f2-2c564e28b8ef.png)

**Comment by weepy3641** [comment]
padding 不会影响 view 的大小。影响的是绘图区的大小。
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#%E5%9B%BE%E8%A1%A8%E5%B8%83%E5%B1%80
