### ISSUE TITLE
『关于slider部分的功能正在火速开发中』这块进度如何

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#20]
https://pro.ant.design/index-cn

的图表打算升级成 BizCharts，其中使用到了这个 `slider`。

**Comment by weepy3641** [comment]
这周会发布。

**Comment by weepy3641** [comment]
slider demo：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/rain-and-flow
slider doc：
https://github.com/alibaba/BizCharts/blob/slider/plugin/slider/README.md
