### ISSUE TITLE
负时间戳处理有问题

### ISSUE THREAD

**Issue by tianlaixhh** [alibaba/BizCharts#201]
当X轴数据为时间类型且为负值时，在formatter的回调中取得的text与原值有差异，
formatter(text){
// 此时拿到的text失真，如-2209104000000变成了-1861948800000
}
（-2209104000000这个时间戳在js中试过是没问题的，作为数字也没有越界。）
测试数据如 
```
data = [{
"y":5.1132164,
"x":-2209104000000
},
{
"y":5.219866,
"x":-2209100400000
},
{
"y":5.8201857,
"x":-2209096800000
},
{
"y":5.6507177,
"x":-2209093200000
}]
```

(x 为x轴，y为y轴)
为排除mask的问题，已经将mask设置为 'YYYY-MM-DD hh:mm:ss'（设置前后无差异）
我的需求就是希望通过formatter进行格式转换，希望得到最原始的时间戳。

**Comment by tianlaixhh** [comment]
问题在G2也提了，反馈很慢，希望bizcharts可以适当督促。

**Comment by weepy3641** [comment]
https://github.com/antvis/g2/issues/503

**Comment by weepy3641** [comment]
@tianlaixhh 
g2 已经回复了哦，可以看 g2 那个 issue 的回复。
