### ISSUE TITLE
体积问题

### ISSUE THREAD

**Issue by Hongbo-Miao** [alibaba/BizCharts#204]
现在只用到其中一个chart，也会加载整个包（超过500KB），是否有什么办法可以像lodash用哪个，import哪个吗？
```js
import debounce from 'lodash.debounce';
```
谢谢！

**Comment by weepy3641** [comment]
@Hongbo-Miao 
暂时不可以哦。
bizcharts依赖于 g2，大部分的 size 都是被 g2 占据，g2 目前并不提供按需加载的功能。因此目前 bizcharts 是整个包都打包的。

**Comment by Hongbo-Miao** [comment]
@weepy3641 谢谢，我在g2那边也新建了个issue。
希望将来有办法优化体积。否则当变得功能更强大时，体积也会更大。

**Comment by Hongbo-Miao** [comment]
链接到 https://github.com/antvis/g2/issues/364

**Comment by Hongbo-Miao** [comment]
@weepy3641 g2 那边已经支持了！https://github.com/antvis/g2/issues/364
这边也请支持，谢谢！This gonna become awesome!

**Comment by trexguo** [comment]
请尽快适配，项目上在等着用。。。

**Comment by weepy3641** [comment]
@Hongbo-Miao @trexguo 
好的， bizcharts 这边会尽快适配。

**Comment by trexguo** [comment]
请问进展如何？使用最新版+require依然没有减小体积。该如何使用？

**Comment by weepy3641** [comment]
@trexguo 
预计这周会有 beta 版本出来。

**Comment by weepy3641** [comment]
@trexguo  @Hongbo-Miao 
fix bizcharts@3.1.8
具体见文档 https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/needload.md

**Comment by Sukura7** [comment]
> @trexguo @Hongbo-Miao
> fix bizcharts@3.1.8
> 具体见文档 https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/needload.md
如果想单独引入intervalStack类型的Geom该怎么使用呢，在typedGeom目录下并没有找到intervalStack文件

**Comment by trampboy** [comment]
@weepy3641 
你好，我使用按需加载后，bizcharts 是少下去了（压缩后9.09KB），但 @antv 仍然有 1.25MB(压缩后145.8KB)，是否有进一步的提升空间？

使用版本:
bizcharts@3.5.10

使用方式:
```js
Chart = (await import("bizcharts/lib/components/Chart")).default;
Axis = (await import("bizcharts/lib/components/Axis")).default;
Tooltip = (await import("bizcharts/lib/components/Tooltip")).default;
Line = (await import("bizcharts/lib/components/TypedGeom/Line")).default;
Point = (await import("bizcharts/lib/components/TypedGeom/Point")).default;
```

谢谢。

**Comment by 1029800858** [comment]
> @trexguo @Hongbo-Miao fix bizcharts@3.1.8 具体见文档 https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/needload.md

按需加载文档打不开了，按照官网的按需加载，包的体积没有变化。参照官网的链接(https://bizcharts.taobao.com/product/bizcharts/category/12/page/23)
