### ISSUE TITLE
react-router 跳转后组件销毁错误

### ISSUE THREAD

**Issue by gaoli** [alibaba/BizCharts#21]
如题，options 获取为 undefined，导致 axes 属性获取报错，其它的几个组件都会有相同的问题：） 

<img width="1258" alt="error" src="https://user-images.githubusercontent.com/780578/33534169-be26902e-d8e0-11e7-9b33-7c62a76701e8.png">

**Comment by weepy3641** [comment]
react 什么版本？

**Comment by gaoli** [comment]
@weepy3641 本来使用的是 react 16 版本，发现这个问题后也曾降级至 react 15 版本，但是问题依旧，是不是还跟 react-router-dom 版本有关系？我的 react-router-dom 版本是 4.2.2

**Comment by weepy3641** [comment]
react-router-dom 不确定，我没有使用过，你也可以降个版本试试。 
目前我们这只发现 react16 中 ummout 有问题，因为 react16 unmount 函数调整了元素的 unmount 顺序。

所以如果你确定已经是 react 15了，可以尝试调整 react-router-dom 的版本。

**Comment by gaoli** [comment]
@weepy3641 `react-router-dom` 是 `react-router` v4 版本的用法，具体可以[参见这里](https://github.com/ReactTraining/react-router/issues/4648)。

按照你的意见，我又尝试将 `react-router` 降级到 v3 与 v2 版本，还是会出现相同的问题 Orz ...

**Comment by weepy3641** [comment]
@gaoli  我一直使用的 react 版本是 15.4.1，你可以试试看。
近期在兼容 react 16，应该可以一次性解决这些兼容问题，计划下周末发布。

**Comment by gaoli** [comment]
@weepy3641 切换 `react` 版本至 15.4.1，终于不会报错了：）

**Comment by weepy3641** [comment]
@gaoli 
bizcharts 兼容 react16 的 beta 版已经发布。 欢迎使用。
3.1.0-beta.1

facet 使用有一丢丢改变，参见： https://github.com/alibaba/BizCharts/blob/master/doc/api/facet.md
中的子组件说明。

**Comment by weepy3641** [comment]
以上 bug 都已经修复。
兼容 react16 正式版 3.1.0 已经发布。
