### ISSUE TITLE
区间面积图图例不能正确显示

### ISSUE THREAD

**Issue by thiswhy** [alibaba/BizCharts#211]
用的是官网的例子，然后自己加的legend，完全不管用呀。。。你能不能写一个关于区间面积图的图例让我参考一下呀亲，包邮吧

**Comment by weepy3641** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/area/stacked
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/area/with-negative


这两个区域图 demo 都有图例啊。。。

**Comment by thiswhy** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/area/range
老铁，我需要这个图的图例，再来个包邮吧，亲~

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/legend.md#%E4%BB%80%E4%B9%88%E6%98%AF%E5%9B%BE%E4%BE%8B
你看看图例的说明。你发的那个demo g2 不会生产默认的图例，需要自定义。
自定义请参考：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/double-axes

**Comment by thiswhy** [comment]
谢谢大神，我试试，这个图表工具真的很赞！
