### ISSUE TITLE
Style: strong line at y = 0

### ISSUE THREAD

**Issue by illumen** [alibaba/BizCharts#214]
Is it possible to make the line at y = 0, more bold, dark and stronger? 
Right now, it's hard to see when it becomes a negative value...

![0 line](https://user-images.githubusercontent.com/210810/37459244-c5ebe960-2847-11e8-9f13-30b35d439aa3.png)

**Comment by weepy3641** [comment]
@illumen 
You can add a guide line at y=0, and set it's style bold..
https://github.com/alibaba/BizCharts/blob/master/doc_en/api/guide.md#line
https://github.com/alibaba/BizCharts/blob/master/doc/api/guide.md#line

**Comment by illumen** [comment]
@weepy3641 
Hi, thank you for your reply.
The problem with this approach is:
1a) guide line is rendered UNDER the grid lines which leads to the dashed grids being over the guideline.
1b) if you set <Line top={true}...> the guideline also renders above the geometry lines/traces.
2) this approach doesn't work well with "interval" geometry,

**Comment by weepy3641** [comment]
You can use Guide Line 's top property to control the guide's rendering order.
https://github.com/alibaba/BizCharts/blob/master/doc/api/guide.md#1top-boolean
https://github.com/alibaba/BizCharts/blob/master/doc_en/api/guide.md#1top-boolean

**Comment by aprilandjan** [comment]
@weepy3641 用 `Guide.Lines` 虽然能绘制辅助线，但是如 @illumen 所说的

> this approach doesn't work well with "interval" geometry

柱状图类型的图案，该辅助线起始结束位置只在首位柱中间点，似乎没办法延伸到整个横坐标轴长度。有办法绕过这一点吗？
