### ISSUE TITLE
Default hidden traces/lines?

### ISSUE THREAD

**Issue by illumen** [alibaba/BizCharts#215]
Hi,

Is it possible to set some traces/lines to default disabled/hidden?

**Comment by weepy3641** [comment]
You can use Chart or View's filter property.
https://github.com/alibaba/BizCharts/blob/master/doc_en/api/chart.md#12filter---array
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#12filter---array

**Comment by illumen** [comment]
Thanks! Exactly what I was looking for!
