### ISSUE TITLE
G2 brush in BizCharts?

### ISSUE THREAD

**Issue by illumen** [alibaba/BizCharts#216]
Hi, 

I'm looking for a box selection solution.
Can I use G2 Brush directly in BizCharts, and if so how?

Thanks :)

**Comment by weepy3641** [comment]
Of course you can use G2 Brush directly.
According to g2 brush's api （https://github.com/antvis/g2-brush）,  g2 brush need g2 chart instance. so you can use chart's ongetg2instance
property to get the g2 chart instance, then create brush directly.


https://github.com/alibaba/BizCharts/blob/master/doc_en/api/chart.md#1ongetg2instance
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#1ongetg2instance

**Comment by illumen** [comment]
Thank you, that works great!
