### ISSUE TITLE
Chart 组件如何设置title

### ISSUE THREAD

**Issue by codeXian** [alibaba/BizCharts#219]
不好意思，我没有在文档中找到有关于设置图标的title API示例，
![image](https://user-images.githubusercontent.com/25171865/37637018-7dd88e24-2c40-11e8-9513-a9ff99b7bd1b.png)
如图所示我需要实现标题的写法

**Comment by weepy3641** [comment]
@codeXian 
bizcharts 并没设置图表标题的功能，如果要添加，可以自己利用 dom 去做。

**Comment by codeXian** [comment]
@weepy3641  gei it
