### ISSUE TITLE
Not to support React 16

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#22]
https://codepen.io/anon/pen/qVvWZZ

if you change react to `15.x`, it's ok.

![image](https://user-images.githubusercontent.com/1179603/33534432-3adf920e-d8e2-11e7-94aa-118c58a75c75.png)

**Comment by nikogu** [comment]
https://github.com/alibaba/BizCharts/blob/770ff0bf18d29e9af3ab138fffd503a410a4e458/src/components/Chart/purechart.jsx#L291

**Comment by weepy3641** [comment]
目前 react16 正在兼容中，最迟下周可以兼容好。

**Comment by viztor** [comment]
Any update on this @weepy3641 ?

**Comment by weepy3641** [comment]
@viztor 
The work of Compatible with react16 are being developed, is expected to release next week。

**Comment by wxj19880511** [comment]
Great, today I tried to use Bizchart in Ant design project and failed. Ant design depends on React 16.x while Bizchart relies on 15.x causing the faliture

**Comment by nikogu** [comment]
@weepy3641 How did this go ?

**Comment by ladjzero** [comment]
Any update?

**Comment by weepy3641** [comment]
@nikogu  @ladjzero @wxj19880511 
兼容 react16 改动稍大，已经在测试了。
这周会发 beta 版本出来。

**Comment by Pimaweichai** [comment]
@weepy3641  any update about the beta version?

**Comment by weepy3641** [comment]
@Pimaweichai  
在做最后的测试收尾工作，今天会发布。
稍等一丢丢。。。

**Comment by weepy3641** [comment]
@nikogu @Pimaweichai  @ladjzero  @wxj19880511  @viztor 
bizcharts 兼容 react16 的 beta 版已经发布。 欢迎使用。
3.1.0-beta.1

facet 使用有一丢丢改变，参见： https://github.com/alibaba/BizCharts/blob/master/doc/api/facet.md
中的字组件说明。

**Comment by nikogu** [comment]
3.1.0-beta1 貌似有问题：

https://codepen.io/anon/pen/ppNKdR?editors=1010

就是把：http://bizcharts.alibaba-inc.com/3_0/demo/guage/text  这个 demo 的 react 和 bizcharts 版本升级就挂了

**Comment by hihl** [comment]
@nikogu 应该还是因为版本问题吧，他们这个beta版依赖的是16.0.0，你这用的是16.2.0

**Comment by weepy3641** [comment]
@nikogu 
是 G2 3.0.3-beta.1 的问题。 
https://github.com/antvis/g2/issues/327


bizcharts 这个 demo 中需要将  name='1'  的轴隐藏掉， 即加上
<Axis name='1' visible='false' />
这样就可以避开这个 bug，并且不印象 demo 。

**Comment by nikogu** [comment]
@weepy3641 好像加了也没什么用，我已经更新 codepen

**Comment by weepy3641** [comment]
@nikogu 
`<Axis name='1' visible='false' />`
不好意思，检查了下 beta 版本确实没生效，我修复下。

**Comment by weepy3641** [comment]
fixed at  3.1.0-beta.2

**Comment by nikogu** [comment]
@weepy3641 `3.1.0-beta.2` 这个版本有个不是问题的问题：

Charts 貌似会对它的 children 进行处理，但是应该缺少判断，导致：

```jsx
<Chart>
    <Axis />
    <Tooltip />
    <Geom
        type="area"
        position="x*y"
    />
    { line && <Geom type="line" position="x*y" />
</Chart>
```

这样会挂掉，如果 `line` 为 `false`

**Comment by weepy3641** [comment]
@nikogu  我这这样使用没问题啊，能否把 error 贴一下或者最后的调用栈。

**Comment by weepy3641** [comment]
以上 bug 都已经修复。
兼容 react16 正式版 3.1.0 已经发布。
