### ISSUE TITLE
在分面中设置coord

### ISSUE THREAD

**Issue by rmabcft** [alibaba/BizCharts#222]
1.在分面中设置rotate时，不起作用
view.coord('theta', {
              innerRadius: 0.35,
              rotate:30*Math.PI
            });
2.在分面中设置startAngle,endAngle时，发现会使图像变大
 view.coord('theta', {
              innerRadius: 0.35,
              startAngle:0-90*Math.PI,
              endAngle:2*Math.PI-90*Math.PI
            });

![image](https://user-images.githubusercontent.com/36733235/37701091-ba1bb31e-2d28-11e8-9703-a14c9f5dd5f9.png)

**Comment by weepy3641** [comment]
1、 theta 坐标系下， rotate 是没有作用的。
2、 theta 坐标系下，rotate 实际上可以用  startAngle和 endAngle 实现
3、 配置 startAngle和 endAngle 放大，是有点问题，需要等 g2 修复。

**Comment by weepy3641** [comment]
修复
