### ISSUE TITLE
y轴不显示

### ISSUE THREAD

**Issue by PerkinJ** [alibaba/BizCharts#224]
折线图y轴设置了visible={true}，y轴依然不显示，请问这是g2的统一风格吗？

**Comment by weepy3641** [comment]
@PerkinJ 
不是的，visible={true} 轴就会显示了，你的没显示不确定原因，有可能是 padding 不够。
能够给个完整的你的图表的配置？

**Comment by PerkinJ** [comment]
```

let cols = {
    x: {
         nice:true,
         type:'log',
         base:10,
         range: [0,1]
    },
   value:{
        min:0,
        max:1,
   }
 }
<Chart width={800} height={600} key={index} data={dv} scale={cols} >
        <Guide>{value.label}</Guide>
        <Axis name="x" />
        <Axis visible={true} name="value"/>
        <Legend position='bottom' />
        <Tooltip crosshairs={{ type: "y" }} />
        <Geom type="line" position={`x*value`} size={2} color={'user'} />
</Chart>
```
如上所示，name="x"表示x轴，name="value"表示y轴，但这里只会显示x轴，y轴不显示。padding的问题应该不会，因为width设置多少，都没有y轴。

**Comment by weepy3641** [comment]
@PerkinJ 
你试试将 chart 的 padding 配置为 auto，看看有没有 y 轴显示。
 ```jsx
<Chart padding='auto' />
```

**Comment by PerkinJ** [comment]
@weepy3641
试过了，并没有变化。 从官网里似乎也没有找到有y轴的示例代码，基本上都是没有y轴的，按道理不是默认visible为true吗，所以我才怀疑是不是g2默认风格没有y轴。

**Comment by weepy3641** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/line/basic
官网上的大部分笛卡尔坐标系的图表都有 y 轴啊，你怎么会看不到。。。

如果还有问题，你写个 codepen demo 给我们瞅一眼把。

**Comment by weepy3641** [comment]
你是不是指没有 y 轴的轴线和刻度线啊？
如果是的画，自己配置一下线的样式就可以了, 默认都是不显示的。
https://github.com/alibaba/BizCharts/blob/master/doc/api/axis.md#5line-object--null
```
  <Axis name='value' line={{stroke: "#ff0000"}}  tickLine={{stroke: "#ff0000", length: 5, lineWidth:1}}/>
```

**Comment by PerkinJ** [comment]
不好意思，可能是我之前描述得不太清楚，我指的就是y轴的轴线。之前说的官方统一的样式就是指y轴的轴线是默认没有的。现在轴线加上了，怪我自己没有仔细看文档。谢谢啦。
