### ISSUE TITLE
region和line的范围在坐标轴之外显示会较严重溢出

### ISSUE THREAD

**Issue by joriewong** [alibaba/BizCharts#226]
![tim 20180323173257](https://user-images.githubusercontent.com/11408040/37822015-454cb940-2ec0-11e8-9d9c-756b1eabc48e.png)

**Comment by weepy3641** [comment]
@joriewong 
能够给个完整的截图、图表配置、及问题说明。
没明白你的意思。

**Comment by joriewong** [comment]
@weepy3641 
1. 在chart不设置高度的时候，region和line范围如果在坐标轴之外显示会溢出；
![tim 20180326143501](https://user-images.githubusercontent.com/11408040/37890347-e69be084-3102-11e8-9b1e-971a15d9e7e8.png)
2. 在chart设置了高度之后，溢出会更明显。
![tim 20180326143400](https://user-images.githubusercontent.com/11408040/37890354-ecc54f4a-3102-11e8-90a4-1b1aae7f7620.png)

**Comment by joriewong** [comment]
版本 3.1.4-beta.3 (可能与版本无关，可能是region、line的设计理念和我现有业务场景的使用方式有差异)。

**Comment by weepy3641** [comment]
嗯, region 和 line 就是这样设计的。

**Comment by zhxfei** [comment]
> 嗯, region 和 line 就是这样设计的。
> 想要不溢出，控制下guide 的坐标即可。



> 嗯, region 和 line 就是这样设计的。
> 想要不溢出，控制下guide 的坐标即可。

请教下   如何控制guide的坐标？
