### ISSUE TITLE
React环境下，页面存在多个Chart，数据会相互影响。

### ISSUE THREAD

**Issue by zoii** [alibaba/BizCharts#228]
场景：
页面有多个tab，每个tab下都会存在一个Chart。
问题：
每个tab都有个Select，选择Select的值，会改变当前tab的Chart的图表数据。
现在问题是，比如我在tab1改变了Select1的值，Chart1图表改变了，但是我点到tab2，Chart2的图表数据也改变了。
请问这种情况，可能是什么问题引起的？

**Comment by weepy3641** [comment]
@zoii  你的描述：每个tab都有个Select，选择Select的值，会改变当前tab的Chart的图表数据。

会不会你的操作触发了 tab2  select 的值，导致 chart2 数据变了？

**Comment by zoii** [comment]
刚刚验证了一下，不是这个问题，每个tab都是一个Component，他们的state应该不会影响。
感觉我不管在哪个tab操作Select，改变的都是同一个图表，就是感觉每个其实页面上只有一个图表，只是显示在不同的地方，所以在不同tab下操作Select都会影响。

**Comment by zoii** [comment]
@Leannechn 问题找到了，确实是因为我使用了同一个dataset导致的，我在Component之外new DataView()了一个对象，所以导致三个Chart都是指向了同一个，已经解决，非常感谢。🙏🙏
也很感谢@weepy3641 的即时回复，谢谢。

**Comment by wyssrzyj** [comment]
我看了你的文章 刚刚解决了 感谢
