### ISSUE TITLE
一个Chart 下面只能有一个Guide 辅助线嘛？ 就如bizCharts的漏斗图的第一个图，上面的写法，按意思是想每一层都显示百分比然而确只有最后一层显示了

### ISSUE THREAD

**Issue by wxmdsh** [alibaba/BizCharts#230]
就如那个图表示例中的 漏斗图中的第一个图的代码

**Comment by weepy3641** [comment]
不是的，一个图可以有 一个 Guide ，但是 Guide 中可以嵌套多个 Text Region Line 等等。
漏斗图第一个图中有些错误，写了过的 guide， 改下就好了，站点之后会修复的。

改为如下：
``
<Guide >
          {data.map((obj) => {
              return  (
            <Text 
              top={true} 
              position={{
              action: obj.action,
              percent: 'median'}}
              content={parseInt(obj.percent * 100) + '%'}
              style={{
              fill: '#fff',
              fontSize: '12',
              textAlign: 'center',
              shadowBlur: 2,
              shadowColor: 'rgba(0, 0, 0, .45)'}}
            />
            )
          })}
           </Guide>
``

**Comment by wxmdsh** [comment]
噢噢， 可以了，  谢谢哈
