### ISSUE TITLE
BizCharts.track(false);

### ISSUE THREAD

**Issue by HelenGuohx** [alibaba/BizCharts#233]
hey ,The tool is amazing . But I just wonder how to use this statement in react -BizCharts.track(false);

**Comment by weepy3641** [comment]
track is a function in BizCharts global namespace, so you can use like that:
```
import * as BizCharts from "bizcharts";
BizCharts. track(false);

//or
import { track } from "bizcharts";
track(false);

```

**Comment by wangcansunking** [comment]
```
import { G2 } from 'bizcharts';

G2.track(false);
```
Now we need to import `G1` to set track.
