### ISSUE TITLE
有双Y轴的实现案例或者方式吗？

### ISSUE THREAD

**Issue by gejialun8888** [alibaba/BizCharts#234]
比如X轴显示时间，左边Y轴是数量，右边Y轴是百分比，显示多条折线的方式展示

**Comment by weepy3641** [comment]
@gejialun8888 
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/double-axes

**Comment by gejialun8888** [comment]
![image](https://user-images.githubusercontent.com/6283875/38121400-748dfdc2-3401-11e8-9d2f-ea9d917d92d9.png)
要是现实这样的方式呢！感谢

**Comment by BambooSword** [comment]
你的数据结构是怎样的，上面同学不是已经给你例子了吗？ 不过我从你目前的代码分析：statis_date 是 时间对应 x 轴，temperature是温度，对应 Y轴左边，你没有数据对应Y轴右边，所以Y轴右边没有数据很正常（如果数据结构没猜错的话）
