### ISSUE TITLE
地图背景怎么设置自定义图片

### ISSUE THREAD

**Issue by Mapperka** [alibaba/BizCharts#235]
地图每个区域用自定义的图片当背景，替代颜色

**Comment by weepy3641** [comment]
@Mapperka 
每个区域时独立的图片背景，还是整个地图用一个图片背景？

**Comment by Mapperka** [comment]
@weepy3641 每个区域独立的背景

**Comment by weepy3641** [comment]
@Mapperka 
可以的，Geom 的 style 属性传入数据纬度和函数就行，可以在函数中控制不同的区域用什么作为填充图片。

https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#8style-----object--array-

```                  
<Geom 
  type='polygon' 
           style={['name', {
                      fill: function(sex) {
                          return 'p(a)https://gw.alipayobjects.com/zos/rmsportal/ziMWHpHSTlTzURSzCarw.jpeg';
                      }
                    }]}
                </Geom>
```

**Comment by Mapperka** [comment]
@weepy3641 图片是相对路径怎么设置

**Comment by weepy3641** [comment]
那是在你自己的项目中的相对路径吧，直接设计就行。

**Comment by Mapperka** [comment]
@weepy3641 不行

**Comment by weepy3641** [comment]
@Mapperka 
1、你可以自己 debug 看下 url 的请求，是不是 url 有问题，如果有问题，麻烦详细说下。 
2、你可以自己将图片路径计算为绝对路径。
