### ISSUE TITLE
能否提供一个曲线+柱状图一起的例子

### ISSUE THREAD

**Issue by jdongdong** [alibaba/BizCharts#236]
类似下图所示：
![image](https://user-images.githubusercontent.com/11850305/38133496-1b78f804-3442-11e8-85a3-112d8300ef24.png)

**Comment by BambooSword** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/double-axes

**Comment by jdongdong** [comment]
谢谢了
