### ISSUE TITLE
onTooltipChange

### ISSUE THREAD

**Issue by OPY-bbt** [alibaba/BizCharts#24]
### 事件写在Chart 和 Tooltip 组件上都没有触发回调，是什么原因。

**Comment by OPY-bbt** [comment]
目前是通过取chart实例
调用 chart.on('tooltip:change', (ev) => {};
注册事件

**Comment by weepy3641** [comment]
本来稍晚会发版本。

**Comment by weepy3641** [comment]
最新版 3.0.4 已经修复了。
