### ISSUE TITLE
legend排序功能

### ISSUE THREAD

**Issue by hihl** [alibaba/BizCharts#240]
看了下当前的legend是按照数据出现的顺序排序的，除了自定义图例没有其他办法设置图例顺序？(使用自定义顺序还需要自己实现时间，设置颜色等，而我仅仅只想改变顺序)，legend顺序不想与数据顺序一样

**Comment by weepy3641** [comment]
legend 对应 scale 中的 ticks 可以指定 legend 的顺序。

例如：
```jsx
const scale = {
  name: {
    ticks: ['aaa', '343', 'xxx']
  }
}
<Chart  scale={scale}/>
  <Geom color='name' />
</Chart>
  ```
