### ISSUE TITLE
怎样才算是空数据呢？

### ISSUE THREAD

**Issue by qazzhoubin** [alibaba/BizCharts#244]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/line/basic

我把data设为空数组，不显示暂无数据的文案，设置placeholder也不起作用。

**Comment by weepy3641** [comment]
1、data=null 默认显示为轴线，如下显示将 placeholder 配置为 true 会显示暂无数据。 
```
<Chart height={400} data={null} scale={cols} forceFit placeholder>
```
2、placeholder='userHtml' 是有点问题，用户配置没有作用，下个版本会修复。。。

**Comment by weepy3641** [comment]
@qazzhoubin 
fix at 3.1.5

**Comment by ChiaJune** [comment]
@weepy3641 最新版的使用`placeholder`，空数据的情况下不会显示 **暂无数据** 的提示，我使用`ant-design-pro`来测试，也没有效果。

**Comment by weepy3641** [comment]
@ChiaJune  
可能是你的版本过低导致的，新版本中没问题的。 

demo：
https://codepen.io/anon/pen/bxYbqM

**Comment by ChiaJune** [comment]
@weepy3641 谢谢你的回复。我发现问题了，我这里的空数据在传给`Chart`组件前，是经过`@antv/data-set`处理过的，处理过后的数据就是一个被包装过的对象，然后就不符合空数组或null的条件了：

https://github.com/alibaba/BizCharts/blob/423da94bbae01c80ed41e434a1ae7ea88c5297c8/src/components/Chart/index.jsx#L15
