### ISSUE TITLE
BizCharts可以显示多个Y轴吗？

### ISSUE THREAD

**Issue by Benjiman1986** [alibaba/BizCharts#246]
highcharts是可以的，但是BizCharts貌似不行，对否？

**Comment by weepy3641** [comment]
可以显示多个 y 轴，多个 geom 使用不同的 y 即可。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/double-axes

**Comment by Benjiman1986** [comment]
Thank you so much!
