### ISSUE TITLE
柱状图Y轴的字段过多如何像折线图自适应 [help wanted]

### ISSUE THREAD

**Issue by Hu-liang** [alibaba/BizCharts#248]
柱状图 : 
![image](https://user-images.githubusercontent.com/12908332/38475331-0222028e-3bda-11e8-8b98-66690a718c44.png)

折线图 : 
![image](https://user-images.githubusercontent.com/12908332/38475434-d7fa4e16-3bda-11e8-8ff1-5c543033d7cd.png)

柱状图的数据是按照日期分组排的 , 在Chart中设置了scale中并没有起效 , 官方有相应的例子么?

**Comment by weepy3641** [comment]
@Hu-liang 
事件坐标轴一般可以通过 scale 中的 tickCount 或者 tickInterval 去调整刻度个数。
如果没有效果，麻烦将你图表的完整数据及配置贴过来看看。

**Comment by Hu-liang** [comment]
@weepy3641  
谢谢 ~ 成功解决了 
之前的scale设置在DataSet transform之后的origin上 , 后设置到rows中就成功了

**Comment by Hu-liang** [comment]
@weepy3641 
![image](https://user-images.githubusercontent.com/12908332/38535313-78b43b16-3cb5-11e8-896e-43e2bfa40ec3.png)

还有个问题 , 设置了tickInterval之后x轴的柱子超出了范围 , padding都是为auto的状态中 .

![image](https://user-images.githubusercontent.com/12908332/38535350-a9e36a18-3cb5-11e8-87d4-f7a0c5f97987.png)

**Comment by weepy3641** [comment]
@Hu-liang ， x 轴 scale 的 range 范围配下。
例如： scale = {'time': {range: [0.1, 1.1]}} 
可以自己调整范围看看效果。

**Comment by Hu-liang** [comment]
@weepy3641 thanks

**Comment by Hu-liang** [comment]
![image](https://user-images.githubusercontent.com/12908332/38606887-da3208d8-3da9-11e8-8ac6-4c4d71359595.png)

@weepy3641  
如何实现这种十字型热词排序 , 在Shape.registerShape中drawShape设置x,y不理想

**Comment by weepy3641** [comment]
@Hu-liang 
可以使用 image mask 去做词云图。
参考 demo ：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/word-cloud-mask

这个 demo 中用了 https://img.alicdn.com/tfs/TB1VAglldfJ8KJjy0FeXXXKEXXa-2333-1200.png 这个图片作为 mask，你可以替换为一个十字架的图片 mask 。
