### ISSUE TITLE
Chart padding property can not trigger render

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#25]
props change can not re render.

demo: https://codepen.io/anon/pen/gXEpNB?editors=1010

**Comment by weepy3641** [comment]
bizcharts don't support change this property. 
Because when this property is be changed, bizcharts must destory the existing chart and create a new one.
Currently bizcharts did't do that.

Do you really need to change this property ？ If yes，We'll consider it in the future version。

**Comment by nikogu** [comment]
Yes, i think it is necessary. Usually in the auto response condition, padding's change is important and also in some config scene.

g2 can repaint it.

**Comment by weepy3641** [comment]
G2 provides no interface to change the chart's padding property.
BizCharts must destroy the old chart and create a new one.

OK.
This issue will be supported in the version which is compatible with React16.

**Comment by weepy3641** [comment]
fix at v3.1.0-beta-1
