### ISSUE TITLE
怎么实现如下图所示双y轴柱状图

### ISSUE THREAD

**Issue by Mapperka** [alibaba/BizCharts#252]
![qq 20180410142610](https://user-images.githubusercontent.com/37919239/38539544-33fbf796-3ccb-11e8-8a40-24b6e8c7a45b.png)

**Comment by Mapperka** [comment]
@weepy3641 好的 谢谢

**Comment by Cleam** [comment]
@weepy3641 
我看了下echarts支持的这种业务场景：https://www.echartsjs.com/examples/editor.html?c=mix-line-bar&theme=light
我觉得这个业务还算比较正常，请问在BizCharts里面是不是也要自定义shape？

**Comment by Cleam** [comment]
@Mapperka 
找到一个例子：https://bizcharts.net/products/bizCharts/demo/detail?id=double-axes-legend&selectedKey=%E6%A6%82%E8%A7%88
