### ISSUE TITLE
grouped-column 比较历史数据和昨日数据数据量大的时候画图错误，如何修复

### ISSUE THREAD

**Issue by codeXian** [alibaba/BizCharts#259]

**Comment by weepy3641** [comment]
@codeXian 
不太明白你的问题，麻烦详细描述下你的问题哦～～

**Comment by codeXian** [comment]
@weepy3641 你好，问题是这样子的：
bizcharts: 3.1.4-beta.3
浏览器: chrome64
图表: interval

我是基于react16.2.0开发的，当我做默认数据时，我画了一张图表
格式:
const data = [{name: '今日数据', '短信': 0, '微信': 0, '语音': 0}, {name: '总数据量', '短信': 0, '短信': 0, '语音': 0}]
const cols = {scales: {tickInterval: 20}}

当我调用查询接口的时候
格式:
const data = [{name: '今日数据', '短信': 0, '微信': 20, '语音': 0}, {name: '总数据量', '短信': 100000, '短信': 20000000, '语音': 30000000}]
const cols = {scales: {tickInterval: 345066}}
问题点：
我使用bizcharts开发的时候， 发现cols的值该变量很大的时候渲染图标很慢，基本上要30S或者1min

**Comment by weepy3641** [comment]
@codeXian  
你是说  cols 中的 tickInterval 变的很大的时候，图表渲染很慢？
你的数据量大不？ 大概多少？
能否给分完整的 数据 和 图表配置，给我这看下。

**Comment by weepy3641** [comment]
@codeXian 
你的数据量大不？ 大概多少？
能否给分完整的 数据 和 图表配置，给我这看下。

**Comment by codeXian** [comment]
我明天写给您，大佬，今天我在高强度开发

**Comment by codeXian** [comment]
@weepy3641

**Comment by weepy3641** [comment]
@codeXian 
你的数据和配置呢？
