### ISSUE TITLE
setTheme throw an error

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#26]
https://codepen.io/anon/pen/gXEaMq?editors=1010

![image](https://user-images.githubusercontent.com/1179603/33541833-9a7f822c-d90b-11e7-84f2-b69d792c8c81.png)

**Comment by weepy3641** [comment]
that's g2's bug, when g2 fix it, we will update.

**Comment by nikogu** [comment]
@weepy3641 更新了说一声哈

**Comment by weepy3641** [comment]
fixed at v3.1.0-beta.1
