### ISSUE TITLE
demo 报错

### ISSUE THREAD

**Issue by sanheng** [alibaba/BizCharts#260]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/bar-change-pie

![tim 20180413161717](https://user-images.githubusercontent.com/13793256/38724246-338f6190-3f36-11e8-9528-6ecb372387c5.png)

**Comment by sanheng** [comment]
这个链接是从 https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/dataset.md 最下面的 ”详情信息请点击这里“ 点过来的，应该是文档没有更新，我关闭了 @joriewong

**Comment by joriewong** [comment]
已提交pr优化 #261

**Comment by greatwhole** [comment]
https://alibaba.github.io/BizCharts/public/data/population-by-age.csv 还是报 404， .json 是有的。 @joriewong

**Comment by joriewong** [comment]
@greatwhole 是.json不是.csv

**Comment by greatwhole** [comment]
@joriewong  嗯嗯，文档最后有问题  https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/dataset.md

**Comment by joriewong** [comment]
@greatwhole thx，已pr
