### ISSUE TITLE
FIlter prop. How filter active legend when component mount? 

### ISSUE THREAD

**Issue by Rudnev90** [alibaba/BizCharts#263]
Hello! I want when mounting the component there are active N number of lines. (1 in the example) But filtering on the index chart is empty. And the lines will appear only after I click on legend.

What am I doing wrong? 

Sorry for my English.

Example: https://codesandbox.io/s/18ml3pv43j

**Comment by Rudnev90** [comment]
@weepy3641 thuthank you) I understood everything.
But I do, as you wrote` filter = {[["city", (city, index) => index <1]]}`. You can see the link https://codesandbox.io/s/18ml3pv43j

**Comment by Rudnev90** [comment]
Because if all the legends are active, data analysis becomes impossible.
<img width="1152" alt="2018-04-17 8 38 15" src="https://user-images.githubusercontent.com/15821454/38850576-bccbdccc-421a-11e8-9276-eae3bae16ed0.png">


I would like this.

**Comment by Rudnev90** [comment]
Perhaps I will close the issue for lack of a solution.

**Comment by weepy3641** [comment]
@Rudnev90 
You can count all the values of filter fieldName first, and then filter data by some name you counted.
That's the solution.

**Comment by Rudnev90** [comment]
@weepy3641 Yes, I do so. Thought I could do it somehow out of the box! Thank you!
