### ISSUE TITLE
能否支持甘特图呀？

### ISSUE THREAD

**Issue by mintsweet** [alibaba/BizCharts#264]
我本意是想用区间条形图和分段条形图组成甘特图，但是发现两个图都需要处理数据，而且方式不同，不知可否有办法到达效果？

**Comment by BambooSword** [comment]
你好能详细描述你想要实现的效果吗？ 
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/waterfall 这个图是否能给你一些启发呢？

**Comment by mintsweet** [comment]
横坐标为一段日期(例如：3月1日至3月31日)，
纵坐标为各个项目(例如其一为：北京地铁一号线XXX工程，他的工程在 3月2日至 3月20日之间画横轴条形图)，
今天假如是 3月11日
想实现以3月11日为分段点3月2日至3月11日为一个颜色，3月11日至3月20日为一个颜色。

不知道有没有说清楚，麻烦啦。

**Comment by BambooSword** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#4color-----string--array- 
如果你只是是想配置颜色可以参考上面的文档

**Comment by mintsweet** [comment]
误会了哈，不是改颜色文档还是会看的。
能否将区间柱状图和分段柱状图结合使用？

**Comment by BambooSword** [comment]
同一数据源用 不同的Geom, 不同数据源用View， 带上标签子没显示出来。。。
