### ISSUE TITLE
曲线图上，怎样加横线

### ISSUE THREAD

**Issue by ahuihui6688723** [alibaba/BizCharts#267]
曲线图中有办法动态加多条横线吗？

**Comment by BambooSword** [comment]
可以通过guide组件定制横线，能否满足你的需求，或者你可以把问题描述的更准确一点～

**Comment by ahuihui6688723** [comment]
比如，一个X-Y轴构成的图上有一条曲线，曲线上有多个点，每个点都有数值，我想在Y轴的某几个刻度上画几条横线，这几条横线是与X轴平行着哩，这几条横线表示着，比如一级报警、二级报警、三级报警，每条横线的颜色不一样，当曲线穿过第一条横线时，表示着值达到了一级报警。

**Comment by BambooSword** [comment]
可以，通过Guide组件设定～
