### ISSUE TITLE
typeings bizcharts时出现index.d.ts缺少类型定义？

### ISSUE THREAD

**Issue by galileo303** [alibaba/BizCharts#269]
/node_modules/bizcharts/typings/index.d.ts中
(285,5): '_refCallback', which lacks return-type annotation, implicitly has an 'any' return type.

出现引用时缺少类型定义

**Comment by weepy3641** [comment]
@galileo303 
缺少什么类型定义，麻烦说清楚哦。

**Comment by galileo303** [comment]
报错信息已经显示了285行缺少any，手动修改可以解决。

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/280
