### ISSUE TITLE
官方词云图demo的人口数据json可否分享一下

### ISSUE THREAD

**Issue by ZhangMingZhao1** [alibaba/BizCharts#270]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/word-cloud 请问一下这个网址的词云demo中，这个人口数据json文件可以分享一下吗
![image](https://user-images.githubusercontent.com/29058747/38977492-1ef40442-43e7-11e8-8ba6-c111ef4180a1.png)

**Comment by BambooSword** [comment]
亲，控制台下面network下面直接复制就行了，互联网下无机密

**Comment by x1nGoo** [comment]
@ZhangMingZhao1  请问词云的toolTip怎么不显示？ 您有弄吗？
