### ISSUE TITLE
bar xAixs 分组为时间时，识别有些问题，图形渲染超出y轴

### ISSUE THREAD

**Issue by shirleyYing** [alibaba/BizCharts#272]
如题，使用柱状堆叠图时，横坐标是如‘‘2018-3-11’’这样的时间。渲染出现柱子超出坐标轴，如果换成‘‘3/11’’就没有问题。

例子：[https://codepen.io/shirleyying/pen/yjyJKE](https://codepen.io/shirleyying/pen/yjyJKE)

**Comment by weepy3641** [comment]
可以配置下 x 轴的 scale 的 range。

如下：
``
 const defaultScale = {
      '月均降雨量': {
        type: 'linear',
        tickCount: 4,
      },
      '月份': {
        range:[0.2, 1]
      }
    };
``
