### ISSUE TITLE
chart自行封装一个component复用问题

### ISSUE THREAD

**Issue by wendylw** [alibaba/BizCharts#273]
复用了自己基于bizchart定义的chart的组件以后，设置chart的一个属性会用在所有canvas当中，请问有什么解决方法吗？是在设置padding的时候出现的

**Comment by weepy3641** [comment]
那得看你得自定义 chart 得实现啊，是不是配置了默认padding 到 chart 上， 或者别的原因导致得。
可以将你得封装代码拿来看下，不然也不好确认问题。
