### ISSUE TITLE
toolTip不好使用

### ISSUE THREAD

**Issue by 1126341821** [alibaba/BizCharts#276]
数据的值是string，然后为了让y轴的值顺序由大到小，所以scale里面用过了type linear，导致toolTip不好使用

**Comment by BambooSword** [comment]
我们正在修改这个问题

**Comment by Leannechn** [comment]
数据的值是string 不就是应该按照string的格式来排序。如果你要使用的话，请用transform处理一下。或者简单的使用map，建议是按照规范来排序和比较。string排序和number排序都会有场景的。
