### ISSUE TITLE
correct module field

### ISSUE THREAD

**Issue by kagawagao** [alibaba/BizCharts#277]
https://github.com/alibaba/BizCharts/blob/5a65fa78b802749e42a465ad175e966d38fb0c62/package.json#L5-L8

maybe `browser` is not needed, it has the highest priority when build web application with `webpack`, even though we can set `resolve.mainFields` to change the default behavior, but recommend drop it

https://webpack.js.org/configuration/resolve/#resolve-mainfields

![image](https://user-images.githubusercontent.com/6930280/39032151-d983bb24-449e-11e8-865d-c570e78797d1.png)

 as follow:
```json
{
"main": "lib/BizCharts.js", 
 "module": "es6/index.js", 
 "jsnext:main": "es6/index.js",
}
```

**Comment by weepy3641** [comment]
@kagawagao 
That's will be fixed in next version.

**Comment by kagawagao** [comment]
@weepy3641  accept PR?

**Comment by weepy3641** [comment]
@kagawagao 
Welcome PR.
