### ISSUE TITLE
使用forceFit之后，初次加载页面没有显示完全

### ISSUE THREAD

**Issue by leejay1992** [alibaba/BizCharts#279]
<img width="379" alt="bug" src="https://user-images.githubusercontent.com/15710933/39044068-aaae976a-44c1-11e8-8c7a-6559b6b21c01.png">
<img width="387" alt="code" src="https://user-images.githubusercontent.com/15710933/39044130-db8ce850-44c1-11e8-8749-1479a0f2724f.png">

**Comment by wxxcarl** [comment]
同问

**Comment by RemyGong** [comment]
@leejay1992 @wxxcarl 尝试了下无法复现。方便贴一下外层dom结构及样式代码么？或者给一个fiddle案例

**Comment by leejay1992** [comment]
最外层就是一个div来包裹着chart 布局用的是 ant的 row col

**Comment by x1nGoo** [comment]
问题解决了吗？ 我也是这样，需要手动缩小浏览器 才会正常

**Comment by x1nGoo** [comment]
@leejay1992 你好，请问你的问题解决了吗？ 我也是这样，需要手动缩小浏览器 才会正常

**Comment by leejay1992** [comment]
@x1nGoo 没有呢，我的也是需要调整浏览器 或者 调整可是区域的大小。

**Comment by x1nGoo** [comment]
@leejay1992  初始化后 调用forceFit() 方法 好像也是无效

**Comment by whyuan1976** [comment]
是不是都是用了antd pro才出现的问题。我也出现过这样的问题。
我猜是pro的实现有问题。pro上提过issue，上面说是bizcharts的问题，没理我。
只能自己改。
在GlobalHeader组件中，

```
export default class GlobalHeader extends PureComponent {
  componentDidMount() {
    this.triggerResizeEvent();
  }
```
这样就好了。

**Comment by weepy3641** [comment]
forceFit 实际上是在第一次加载图表以及每次window resize 事件的时候，拿 container 的 computedStyle 中的 width 作为图表的宽度的。
出现第一次 forceFit 没适应好基本上是因为 container 的 computedStyle 中的宽度和实际宽度不符，有可能是外层容器在布局完成后又调整布局了，但又没有触发 resize 事件，这种情况下 bizcharts 这边也没有太好的办法解决。

只能在用户层在图表加载完成后用户主动的调用 chart. forceFit()  或者像 @whyuan1976  回复的那样，组件加载后主动触发一个 resize，能让图表重新自适应一次。

**Comment by TheTimBecker** [comment]
I had to manually trigger a resize event every time my component updated, on mount was not enough.

```
componentDidUpdate() {
  window.dispatchEvent(new Event('resize'));
}
```

**Comment by botasky11** [comment]
这个问题解决了吗？我的也是需要调整浏览器 或者 调整图表区域的大小才会显示，同页面的react-table就没有这个问题，都是自适应。

**Comment by tanzhihang** [comment]
经过调试发现， window.dispatchEvent(new Event('resize'));在firefox下不能生效，因为布局采用display:flex;改为inline-block或者float布局就行了

**Comment by gaius-qi** [comment]
可以在图表渲染前添加 loading，防止 data 为空时对图表进行渲染。
```js
if (data.length === 0) {
  return <div>spin</div>;
}
```

**Comment by soeyi** [comment]
我在设置了 `triggerResizeEvent()`  之后。如果在相同的页面 重复刷新。
也要几率在后续的刷新之后 页面显示空白。

**Comment by soeyi** [comment]
```javascript
setTimeout(()=>{
  this. triggerResizeEvent()
}, 300)
```
之后每次刷新都能成功显示。
