### ISSUE TITLE
在typescript中使用scale类型是否定义错误？？？？？？

### ISSUE THREAD

**Issue by Bigpawn** [alibaba/BizCharts#280]
目前定义类型为
`scale?: {
      fieldName: string;
      scaleConnfig: any;
    };`

**Comment by Leannechn** [comment]
It`s wrong type, 已修改，正确是：{'fieldName': { } } 待发布ing

**Comment by Bigpawn** [comment]
fieldName应该为变量吧

**Comment by Leannechn** [comment]
fieldName 字段名。我临时先修改为any了，没有详细去配置，欢迎PR 。[fieldName: string ]: Object  这么佩的话没测过是否覆盖所有情况，所以先any了。

**Comment by Bigpawn** [comment]
突然发现padding类型定义的也有点问题，目前只支持`padding:{number}`,其它写法好像不支持

**Comment by YunS-Stacy** [comment]
现在只能设置一个axis的scale么？怎么设置多个？？

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/269

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/466
