### ISSUE TITLE
在Chart的onTooltipChange中调用setState图表本身出错

### ISSUE THREAD

**Issue by DDEle** [alibaba/BizCharts#281]
![image](https://user-images.githubusercontent.com/28386673/39081790-2169d2f8-457a-11e8-8c26-ff52dec1d33b.png)

**Comment by wunayou** [comment]
这么久的bug为什么还没有解决呢？

**Comment by weepy3641** [comment]
@DDEle  @wunayou 
我们这查了下，这个 bug 是因为在一个图表的交互事件执行流的过程中，去修改图表的状态，tooltip 重绘触发的 bug。
这个时候修改状态会同步触发图表及 tooltip的更新、重绘操作，这样做 g2 不支持。

我们这也解决不了这个问题，但可以避开。
可以在  onTooltipChange  中，用一个 timer 回调去改变图表的状态，这样就不会有问题了。

```jsx
      onTooltipChange={() => {
        const self = this;
        setTimeout(()=>{
          console.log('aaaaa');
          self.setState({
            height: 600
          }), 2000
        })
      }}
```

**Comment by windinging** [comment]
@weepy3641 这样还是有问题啊 不呢个实时更新 如果时间设置比较短的话 tooltip又不会显示

**Comment by windinging** [comment]
@weepy3641 这样还是有问题啊 如果每次onTooltopChange随着item值去setstate 这样tooltip一直一闪一闪的

**Comment by weepy3641** [comment]
@windinging 
是会一直闪的，这是因为 setstate 后图表刷新操作会中断 tooltip 的流程。
所以你在 onTooltopChange 中  setState 主要想做什么？

**Comment by weepy3641** [comment]
https://github.com/antvis/g2/issues/652

**Comment by malusama** [comment]
现在想要在鼠标滑动时取到鼠标指向的值应该怎么做啊..用onTooltopChange Tooltip会显示不了没有辅助线了
