### ISSUE TITLE
使用requestAnimationFrame 做简单的优化

### ISSUE THREAD

**Issue by chenshuai2144** [alibaba/BizCharts#285]
一个页面有许多图表的时候。会同时 render .
requestAnimationFrame 加上之后性能会提升很多

**Comment by weepy3641** [comment]
@chenshuai2144 
一个页面上图表太多， 首次加载确实会比较耗性能。所以想问下 requestAnimationFrame 是怎样使用的，requestAnimationFrame 的时候做了啥， 是将图表的加载放到了页面初步渲染后然后图表也是分批次加载？
你是怎么评估计算提升的性能的？

**Comment by zzswang** [comment]
@chenshuai2144 

能否 share 一下 相关code
