### ISSUE TITLE
数组个数不确定，柱状图设置padding后柱子会宽度自适应，但需求要求柱子宽度一致

### ISSUE THREAD

**Issue by shirleyYing** [alibaba/BizCharts#288]
需求：
1. y轴label为数据库字段，长度不定，
2. 数据lengh不定，但是要求柱子宽度一定
问题：
因为#1 ，需要设置padding才能使其全部显示
因为#2，我手动补齐数据，增加{name:'',val:0}这种空数据，以保证柱子宽度一致
但是设置padding后，label可以全部显示，但是柱子宽度自适应了。请问如何解决

![image](https://user-images.githubusercontent.com/12593649/39239069-7646aa86-48b2-11e8-8668-e694d1058225.png)

例子
https://codepen.io/shirleyying/pen/rvLWZg

**Comment by weepy3641** [comment]
@shirleyYing 
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#6size-----string--array--number-

配置下 geom 的 size 属性即可，配置为固定数值。
