### ISSUE TITLE
How to hide a View/Geom and Legend by default

### ISSUE THREAD

**Issue by chillyistkult** [alibaba/BizCharts#289]
I have complex chart with multiple Views and Axis. I would like to hide some of the Views and corresponding legend by default. If I set `<View [...] visible={false}>` the Geoms are hidden but the Legend is still in the checked state. As this is a very basic feature of any chart library, I am sure I could just not find the right option?

**Comment by weepy3641** [comment]
You add the `<Legend  name='viewLegendFieldName' visible='false'>` component in `<Chart/>`.
That's will hide the view's legend.

Like the example: 
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/pie/sunburst
And add the following code, view's name legend will be hided.

```   jsx
<Chart>      
      <Legend />
      <Legend name='name' visible={false} />
      <View>
        <Geom color='name' />
      </View>
</Chart>
```
