### ISSUE TITLE
Window resize throw an error sometimes

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#29]
![image](https://user-images.githubusercontent.com/1179603/33592998-62c96c0e-d9c8-11e7-939f-b0d08bbab9cf.png)

![image](https://user-images.githubusercontent.com/1179603/33593026-7ad54b38-d9c8-11e7-8929-2c18a10bc89c.png)

偶现，图表渲染正常，不过会抛出错误，窗口变化导致的图表自适应重绘会找不到 dom？感觉这个地方需要做一个 `dom` 的空判断。

**Comment by weepy3641** [comment]
这地方是 g2 的逻辑，上层是调用 g2 的 resize 接口，我给  g2 提个 issue 吧。

**Comment by weepy3641** [comment]
fixed at v3.1.0-beta.1
