### ISSUE TITLE
我发现Geom的color属性并不支持回调函数。

### ISSUE THREAD

**Issue by qazzhoubin** [alibaba/BizCharts#290]
我发现Geom的color属性并不支持回调函数。虽然文档中有说支持回调函数，但是实际情况并没有达到逾期的效果。

`<Geom type="line" position="time*value" size={2} 
                      color={['value',(value)=>{
                               if(value > MAX_VALUE){
                                   return '#f04864'
                               }else{
                                   return '#2fc25b'
                               }}]}/>
                <Guide>`

永远返回#2fc25b

**Comment by weepy3641** [comment]
@qazzhoubin 
geom 组件的 color 属性自定义可以做到，需要自己写个函数，在函数中根据数据去返回颜色。

https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/double-axes

**Comment by qazzhoubin** [comment]
不行啊

**Comment by Leannechn** [comment]
你的需求可以通过如下方式实现，将“某个值”在y轴中的位置替换下面的 .5,比如：MAX_VALUE / Y-range = 0.4
```
color="l (270) 0:rgba(255, 146, 255, 1) .5:rgba(255, 146, 255, 1) .5:rgba(215, 0, 0, 1) 1:rgba(215, 0, 0, 1)"
```
color 配置字段并非您想象的，color配置字段即数据按照该字段进行分组，然后对分组的图形上色。

**Comment by weepy3641** [comment]
@qazzhoubin 
参考demo:
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/gradient-color-line

**Comment by yaorao2770** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/double-axes   这种地址都是404呀，
