### ISSUE TITLE
demo里面的这个图 提示信息显示不正常

### ISSUE THREAD

**Issue by MinHongwei** [alibaba/BizCharts#291]
![br jl8s e3 1c1 xkm ryj](https://user-images.githubusercontent.com/34823990/39343175-0b2b64f0-4a0e-11e8-9b6e-76ffed837e98.png)
![ygp4fm r 1wq osu e p0](https://user-images.githubusercontent.com/34823990/39343186-11cb95c8-4a0e-11e8-9db9-0618ad6c83bf.png)

**Comment by MinHongwei** [comment]
我鼠标放的位置 分别是营运 和test 请问  这么解决这个问题。。。

**Comment by weepy3641** [comment]
@MinHongwei  没有你的数据和配置无法判断哦， 参考如下 demo， 是没有问题的。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/pie/sunburst

**Comment by weepy3641** [comment]
@MinHongwei  
sorry,  demo 中tooltip 有个属性写错了。修一下就好。

第一个 geom 的 tooltip 属性应该改为：
```
tooltip={['type*percent',(item, percent) => {
              percent = (percent * 100).toFixed(2) + '%';
              return {
                name: item,
                value: percent
              };
            }]}
```

站点demo稍后会更新。
