### ISSUE TITLE
Chart导出 svg

### ISSUE THREAD

**Issue by joriewong** [alibaba/BizCharts#294]
BizCharts支持像G2这样保存为图片？后续还会支持其他导出方式吗？
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/faq.html#_%E5%A6%82%E4%BD%95%E5%AF%BC%E5%87%BA%E5%9B%BE%E7%89%87

**Comment by weepy3641** [comment]
@joriewong 
保存为图片是支持的，直接拿到 g2 chart 的 instance 调接口就行。
跟 g2 讨论过，后续会支持导出为 svg，正在排期。

**Comment by joriewong** [comment]
png、svg足矣，已列入plan就好

**Comment by weepy3641** [comment]
@joriewong 
已经支持 svg 渲染及导出，导出接口跟铺平一致。 
http://bizcharts.net/products/bizCharts/api/chart#renderer

**Comment by joriewong** [comment]
@weepy3641 @liunian thx
