### ISSUE TITLE
How to add title in Axis by "alias"??

### ISSUE THREAD

**Issue by chuyinweilai** [alibaba/BizCharts#3]
I follow this deemo: [https://github.com/alibaba/BizCharts/blob/master/demo/component/area/basic.js](url) and add “alias” in cols:
![image](https://user-images.githubusercontent.com/21523040/33166158-3bc7d184-d074-11e7-9454-c133cdce1d41.png)
this is all of my code:
```

import React,  { Component } from 'react';
import { Chart, Geom, Axis, Tooltip, Coord, Label, Legend, Shape } from 'bizcharts';
import DataSet from '@antv/data-set';

const ds = new DataSet();
export default class Series extends Component {
	constructor(){
		super();
		this.state={
			data: [],
			cols: {},
		}
	}
	componentWillMount(){
		this.setState({
			data: [
				{ month: 'Jan', Tokyo: 7.0, London: 3.9 },
				{ month: 'Feb', Tokyo: 6.9, London: 4.2 },
				{ month: 'Mar', Tokyo: 9.5, London: 5.7 },
				{ month: 'Apr', Tokyo: 14.5, London: 8.5 },
				{ month: 'May', Tokyo: 18.4, London: 11.9 },
				{ month: 'Jun', Tokyo: 21.5, London: 15.2 },
				{ month: 'Jul', Tokyo: 25.2, London: 17.0 },
				{ month: 'Aug', Tokyo: 26.5, London: 16.6 },
				{ month: 'Sep', Tokyo: 23.3, London: 14.2 },
				{ month: 'Oct', Tokyo: 18.3, London: 10.3 },
				{ month: 'Nov', Tokyo: 13.9, London: 6.6 },
				{ month: 'Dec', Tokyo: 9.6, London: 4.8 }
			],
			cols: {
				temperature:{ alias: '销售量' },
				month: {
					alias: '横坐标',
					range:[0,1]
				}
			},
		})
	}

        render() {
		const dv = ds.createView().source(this.state.data);
		dv.transform({
			type: 'fold',
			fields: [ 'Tokyo', 'London', 'baseLine' ], // 展开字段集
			key: 'city', // key字段
			value: 'temperature', // value字段
			alias: '纵坐标',
		});
		// forceFit设置图表的宽度是否自适应
                return (
				<Chart height={400} data={dv} scale={this.state.cols} forceFit>
					<Axis name="month"/>
					<Axis name="temperature" label={{formatter: val => `${val}°C`}}/>
					<Tooltip crosshairs={{type : "y"}}/>
					<Legend/>
					<Geom type="line" position="month*temperature" size={2} color={'city'} />
				</Chart>
    );
  }
```
But, it's no use:
![image](https://user-images.githubusercontent.com/21523040/33166320-d2cff250-d074-11e7-84dc-69ee63276806.png)

**Comment by chuyinweilai** [comment]
There is another problem about <Axis/>
The Y-axis can't show the border like this:
![image](https://user-images.githubusercontent.com/21523040/33167875-f01bbd08-d079-11e7-9845-c97a1a250869.png)
This is the same code.

**Comment by weepy3641** [comment]
Axis' title is hidden default ，alias is just give a field data an alias name ，do not mean axis title show。

you should add title property in Axis component. title={{}} 

like this: <Axis name="month" title={{}} />   
that means the month Axis 's title should be showed.

thanks for your issue;  
we will adjust axis title property's value and doc in the next bizcharts@3.0.3 version.
like this:
<Axis name="month" title />    or  <Axis name="month" title={true} />

**Comment by chuyinweilai** [comment]
@weepy3641  I can't see your example……
![image](https://user-images.githubusercontent.com/21523040/33196817-9f720472-d11c-11e7-9f09-647a2a490c9c.png)
But I see what you means and understand the API of Axis.title:
```
<Axis name="temperature" label={{formatter: val => `${val}°C`}} 
	 title={{
		 autoRotate: true, // 是否需要自动旋转，默认为 true
		 offset: 40, // 设置标题 title 距离坐标轴线的距离
		 textStyle: {
			 fontSize: '12',
			 textAlign: 'center',
			 fill: '#999',
			 fontWeight: 'bold',
		 },
		 position: 'center', // 标题的位置，**新增**
	 }} 
 />
```
![image](https://user-images.githubusercontent.com/21523040/33197288-6ea302e4-d11f-11e7-81bc-16bb83f4a5fa.png)

Thanks for your help!
