### ISSUE TITLE
动态设置图表样式后原本隐藏的轴线会重新显示出来

### ISSUE THREAD

**Issue by huozw** [alibaba/BizCharts#300]
场景：从用户输入获取x轴标签字体大小，y轴设置visible=false；x轴字体标签大小改变，重新渲染图表时设置了visible=false的y轴会重新显示出来。
配置项除了更改的字体大小以外均无变化。
怀疑是我自己代码问题，在dome页新增按钮重新渲染图表也会出现同样问题。
求解决方法

**Comment by kreja** [comment]
https://jsfiddle.net/krejaone/qmurrygq/2/ 是这样吗？但是这里看起来是对的，y 轴没有显示出来。
要不你写个 jsfiddle 吧

**Comment by huozw** [comment]
@kreja 
尝试了下，在y轴添加label标签会出现重新显示的问题
![image](https://user-images.githubusercontent.com/20555156/39625129-b0908ad6-4fce-11e8-9d3a-6a8fe6b78772.png)
像这样添加一个label属性，初始化时不会显示，点击change按钮修改x轴字体大小的话y轴会重新显示出来

**Comment by ssfxz** [comment]
https://jsfiddle.net/krejaone/qmurrygq/2/ 试了一下并没有出现问题，楼上确认一下没有问题的话这个issues就close了
