### ISSUE TITLE
Legend 单类型数据的时候不会显示 

### ISSUE THREAD

**Issue by Hu-liang** [alibaba/BizCharts#301]
![image](https://user-images.githubusercontent.com/12908332/39562599-1b75abc4-4edf-11e8-895f-adce9727fec5.png)

实际上来说单类型一般都会有表条来解释这是什么类型的数据  , 没有必要再显示了 , 如果就是要该怎么做

**Comment by kreja** [comment]
可以自定义 Legend，参考 https://jsfiddle.net/qs4j1s9j/

**Comment by Hu-liang** [comment]
thanks
