### ISSUE TITLE
用slider插件后，图表数据展示不全

### ISSUE THREAD

**Issue by havywu** [alibaba/BizCharts#302]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/line-rain-and-flow（官方例子）

slider上的数据截止到9号，但上方图表数据紧展示到6号
![image](https://user-images.githubusercontent.com/29532857/39570790-14ed8d86-4efc-11e8-9e5e-81e0529f4847.png)

**Comment by kreja** [comment]
![image](https://user-images.githubusercontent.com/7478555/39612204-eb84454a-4f8f-11e8-869a-36f03c553840.png)

鼠标移上去看是展示到 9-9 的，只是下面的 label 按日期等分增加，所以最后一个显示是 9/6
9/6并不对应最后一天
