### ISSUE TITLE
label使用自定义颜色，部分label颜色显示错误

### ISSUE THREAD

**Issue by Ykeng** [alibaba/BizCharts#305]
https://jsfiddle.net/lindoGZ/qgxrdsL2/

![image](https://user-images.githubusercontent.com/13504029/39697447-8d3f5c22-5223-11e8-9b51-97c3caef12c8.png)

**Comment by Ykeng** [comment]
上面demo这种geom和label使用的是同一组自定义颜色
`const colors = ['#ff2a50', '#0f9efe', '#1de003', '#ffb64d'];`

**Comment by RemyGong** [comment]
@Ykeng Label的着色顺序和geom的着色顺序不一致的情况可以在textStyle的回调函数里面如下所示的解决
			   const size = colors.length;
                            return { fill: colors[(size - index) % size] };

**Comment by 892744577** [comment]
在回调函数中使用item.point.color
