### ISSUE TITLE
折线图当y轴value全是0时，min:0 失效，最低刻度为-1

### ISSUE THREAD

**Issue by shirleyYing** [alibaba/BizCharts#306]
如题
重现如下 [https://codepen.io/shirleyying/pen/VxymzY](https://codepen.io/shirleyying/pen/VxymzY``)

**Comment by RemyGong** [comment]
@shirleyYing 取消tickCount的设置就会使得min设置生效

**Comment by x1nGoo** [comment]
@RemyGong 那 tickCount 和 min  不能同时存在吗？

**Comment by JJoan0116** [comment]
@shirleyYing 可以用minLimit这个属性
