### ISSUE TITLE
多条折线图 支持 多个y轴吗？

### ISSUE THREAD

**Issue by x1nGoo** [alibaba/BizCharts#307]
多条折线在一个图里 支持 多个y轴吗？ 
		const shopDatas = [
			{ moment: '00:00', total: 20000, orderTotal: 10000, orderNum: 323 },
			{ moment: '02:00', total: 15000, orderTotal: 7500, orderNum: 221 },
			{ moment: '04:00', total: 8000, orderTotal: 4000, orderNum: 122 },
			{ moment: '06:00', total: 4000, orderTotal: 2000, orderNum: 52 },
			{ moment: '08:00', total: 5000, orderTotal: 2500, orderNum: 62 },
			{ moment: '10:00', total: 10000, orderTotal: 5000, orderNum: 142 },
			{ moment: '12:00', total: 20000, orderTotal: 10000, orderNum: 232 },
			{ moment: '14:00', total: 40000, orderTotal: 20000, orderNum: 442 },
			{ moment: '16:00', total: 60000, orderTotal: 30000, orderNum: 662 },
			{ moment: '18:00', total: 120000, orderTotal: 60000, orderNum: 1432 },
			{ moment: '20:00', total: 65000, orderTotal: 32500, orderNum: 645 },
			{ moment: '22:00', total: 80888, orderTotal: 40444, orderNum: 882 }
		]
      const cols = {
        moment: {
          range: [ 0, 1 ],
        },
	total: { alias: '总收入' },
        orderTotal: {alias: '订单总额'}
      }
`
为属性定义别名 无效啊

**Comment by RemyGong** [comment]
@x1nGoo 
多条折线在一个图里 支持 多个y轴吗？
-----支持的，具体可参考https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/double-axes

为属性定义别名 无效啊？
--------方便贴一下全部的代码么？

**Comment by x1nGoo** [comment]
@RemyGong 你好，
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/line/curved
例如这个例子，我想把属性的别名都改成中文。

**Comment by Leslie2014** [comment]
@x1nGoo 可以的，如果你想把 x 周的月份改为中文，可以在对应的 **Axis** 应用 label 的 `formatter` 方法，具体做法可以参考 y 轴温度的实现；如果你想把 **legend** 分类格式化中文，可以调用 legend 的 `itemFormatter` 方法，具体做法如下：
```jsx
<Legend itemFormatter={v => {
  switch (v) {
    case 'Tokyo':
      return '东京';
    case 'London':
      return '伦敦';
  }
}}/>
```

**Comment by TomIsion** [comment]
> @x1nGoo
> 多条折线在一个图里 支持 多个y轴吗？
> -----支持的，具体可参考https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/double-axes
> 
> 为属性定义别名 无效啊？
> --------方便贴一下全部的代码么？

多个 Y轴 的示例失效了 可否再提供个参考下？
