### ISSUE TITLE
关于地图下钻的例子出现的问题反馈

### ISSUE THREAD

**Issue by chlin7** [alibaba/BizCharts#309]
关于图标示例中，地图的第三个例子，地图下钻，出现报错异常“Uncaught Error: malformed path data”；
操作如下：
1、点击选择一个省份A；
2、点击选择另一个省份B；
3、重新点击选择省份A，无法切换回来，出现报错异常。不过当前情况下，选择一个从未点击过的省份还是可以切换的

**Comment by chlin7** [comment]
经过排查是这段代码报错了，
const geoDataView = ds.createView().source(mapData, {
              type: 'GeoJSON',
              });

**Comment by chlin7** [comment]
麻烦看下 如果修改

**Comment by RemyGong** [comment]
@chlin7 感谢~已经定位到原因。会尽快修复该问题~

**Comment by weepy3641** [comment]
@chlin7 
demo 已经修复。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/map/drill-down
