### ISSUE TITLE
Slider Support

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#31]
![image](https://user-images.githubusercontent.com/1179603/33602830-7d2d6be0-d9eb-11e7-81fa-368dfa84fcaa.png)

https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/candlestick/basic

record.

**Comment by weepy3641** [comment]
slider demo：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/rain-and-flow
slider doc：
https://github.com/alibaba/BizCharts/blob/slider/plugin/slider/README.md

**Comment by nikogu** [comment]
@weepy3641 这个名字：https://www.npmjs.com/package/bizcharts-plugin-slier ....貌似拼错了

**Comment by weepy3641** [comment]
... 发现了。  我下个版本更正。。。。

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/31
