### ISSUE TITLE
onItemSelected not working

### ISSUE THREAD

**Issue by quanyaji** [alibaba/BizCharts#313]
i want to know which one is selected when i click a piece of pie chart.

`<Chart 
          height={window.innerHeight} data={dv} scale={cols} 
            onItemSelected={(e) => console.log(e)}
            padding={[ 80, 100, 80, 80 ]} forceFit
            >`

click on blue area,  logs nothing in console.
maybe i am not doing it in a wrong way, please  point me out.

https://jsfiddle.net/gaving/vLm1p7vs/

**Comment by Leslie2014** [comment]
You can use `onPlotDblClick ` method instead, and get origin data in this way:
```jsx
onPlotClick={ e =>  e.data. _origin }
```
