### ISSUE TITLE
tooltip显示的值与实际数据不符

### ISSUE THREAD

**Issue by Kopjie** [alibaba/BizCharts#315]
https://codepen.io/kopjie/pen/rvrZPE
demo中tooltip有些数据是显示正常的，有些显示为0，我想知道是什么原因造成的
万分感谢

**Comment by RemyGong** [comment]
@Kopjie 数据内同一个key值有重复数据导致的，例如“05-08”这个字段出现两次；x轴是一个分类轴，在05-08这个分类下出现两次数据，一个是可见的100，另一个是没有高度的0；在鼠标交互区域的绘制（肉眼不可见）的时候两个区域发生了重叠，导致tooltip只能展示数据为0的那个数据点；

解决方案：1. 数据去重，对于相同分类的数据进行合理的去重计算；2. 对柱状图进行分组或者叠加等处理；
