### ISSUE TITLE
一些文档问题。

### ISSUE THREAD

**Issue by eternalsky** [alibaba/BizCharts#317]
tutorial 下面的 [theme 文档](https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/theme.md) 是完全和 G2 一样的，里面的 demo 也是 G2 而非 BizCharts 的 demo。

Api others 下面的 [theme 文档](https://github.com/alibaba/BizCharts/blob/master/doc/api/theme.md) 404

**Comment by Leslie2014** [comment]
Hi，已改正。
