### ISSUE TITLE
时间维度坐标轴不支持到时分秒？

### ISSUE THREAD

**Issue by snake2016** [alibaba/BizCharts#325]
![image](https://user-images.githubusercontent.com/17959330/40215166-7c4635d2-5a91-11e8-967e-b9a2ed1ba618.png)
![image](https://user-images.githubusercontent.com/17959330/40215178-9c85125a-5a91-11e8-9dac-3608e18e9b78.png)

设置了tickCount 好像也不起作用

**Comment by snake2016** [comment]
已经解决！ 
解决办法：data中的time先别format，直接用原值。然后在axis组件的label的formatter中再自定义处理

**Comment by joenahm** [comment]
请问如何阻止time被format啊，在使用了[dataSet](http://bizcharts.net/products/bizCharts/api/dataset)后无法在axis组件的label的formatter中取到原始数据了

**Comment by weepy3641** [comment]
@joenahm 
要么先别 format ，在 axis label 中 format
或者增加一列原始时间数据列。

**Comment by jack-chao** [comment]
你好，请问具体如何解决的呢，bizcharts一开始就自动format处理过了，求解决
