### ISSUE TITLE
如何规定y轴不能有小数？

### ISSUE THREAD

**Issue by x1nGoo** [alibaba/BizCharts#326]
当数据小时，y轴刻度会出现0.8  1.2 1.6，设置什么属性会不出现小数？
用formatter 四舍五入的话会出现重复的刻度  0.8变成1， 1.2 也变成1 ， 用Math也是会有重复的刻度

**Comment by Leannechn** [comment]
那就需要你自己大致计算一个步长，`tickInterval: Math.ceil(maxValue - minValue)` 。
