### ISSUE TITLE
DOMException: Failed to execute 'addColorStop' on 'CanvasGradient'

### ISSUE THREAD

**Issue by Ykeng** [alibaba/BizCharts#329]
- bizcharts Version: 3.1.7
- g2 Version: 3.0.9
- Platform or react version:  16.3.2

![tim 20180523093707](https://user-images.githubusercontent.com/13504029/40398920-0c3b0a26-5e6d-11e8-8005-013c26a32afa.png)

**Comment by weepy3641** [comment]
@Ykeng 
能否给个详细 demo ？
看错误信息是因为你的渐变色颜色配置中出现了浮点数，渐变色中必须整数。

```
  var g = context.createLinearGradient(0,0,canvas.width,0);
  // right
  g.addColorStop(0, 'rgb(255, 0, 0)');
  // wrong
  g.addColorStop(1, 'rgb(233.34343, 0, 0)');
```

**Comment by Ykeng** [comment]
@weepy3641 

https://jsfiddle.net/lindoGZ/tkLpLs4j/2/   

这个demo中传递渐变色是有一个浮点数，图表无法显示。但是实际项目中是可以显示图图表的，有没有这么一种可能： **外部传递的渐变色是整数，图标内部生成渐变颜色却出现浮点数，然后报出这个信息 ？？？**

**Comment by mwb-27** [comment]
@Ykeng 我用渐变色的时候也遇到了这个问题，自己设置的都是整数，但是内部显示的都是浮点数。请问你知道是什么原因了吗

**Comment by Leannechn** [comment]
什么情况会出现浮点数的颜色。能给个具体复现的demo不
