### ISSUE TITLE
自定义legend

### ISSUE THREAD

**Issue by FHyacinth** [alibaba/BizCharts#33]
<img width="347" alt="2017-12-06 2 36 43" src="https://user-images.githubusercontent.com/34297250/33648034-eb2c9be6-da92-11e7-9469-b5a07f61f4f9.png">

自定义的legend是否可以让它左对齐，而不是居中显示；
生成的代码中的样式无法覆盖修改；
下面是自定义legend生成的最外层div的style
<img width="436" alt="2017-12-06 2 38 18" src="https://user-images.githubusercontent.com/34297250/33648086-25a4ddd8-da93-11e7-832e-159c87c07832.png">

**Comment by weepy3641** [comment]
可以左对齐的。 
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#_使用-html-渲染图例
参考下 g2 这个 demo 中 legend 的样式配置。 bizcharts 跟 g2 是能力和配置是等同的。

  'g2-legend': {
    marginLeft: '0px',  // 此处可以控制左对齐
  },

**Comment by FHyacinth** [comment]
bizcharts并没有这个api
![image](https://user-images.githubusercontent.com/34297250/33749604-994e9c48-dc09-11e7-86b1-ff0f6f97cc17.png)

**Comment by Power-Deng** [comment]
在使用‘g2-legend’等属性前，首先要确定是html渲染，用useHtml={ true } g2-legend={{marginLeft:"100px"}},试一试，是不是可以了呢？ @FHyacinth

**Comment by cench** [comment]
@FHyacinth 自定义的 100%  是怎么读取到的？ 还是写死的？

**Comment by weepy3641** [comment]
自定义legend css 配置
https://github.com/alibaba/BizCharts/blob/master/doc/api/legend.md

![image](https://user-images.githubusercontent.com/3838676/35084453-fd1b9e04-fc5e-11e7-832f-afe046838e76.png)
