### ISSUE TITLE
可以考虑出个f2版本的吗

### ISSUE THREAD

**Issue by suiyi8760** [alibaba/BizCharts#331]
用习惯了bizcharts不太习惯f2的其他社区封装

**Comment by weepy3641** [comment]
@suiyi8760 
f2 公司内其他兄弟部门已经封装了 react 版本，最快会在 7 月份 bizcharts 的站点透出。

**Comment by weepy3641** [comment]
@suiyi8760 
f2 react 版本已经出了，有需求可以直接使用。
http://bizcharts.net/products/bizGoblin

**Comment by weepy3641** [comment]
@suiyi8760 
不会吧，确定打不开？ 提示啥？

**Comment by suiyi8760** [comment]
@weepy3641 没问题了现在，昨天控制台有几个文件报NET ERROR
