### ISSUE TITLE
柱状图 如何在每条柱的顶部显示数值

### ISSUE THREAD

**Issue by x1nGoo** [alibaba/BizCharts#332]
柱状图 如何把每列的值显示在顶部？ 
例如 该例子
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/basic-column 
添加什么能把值显示在顶部

**Comment by Leannechn** [comment]
```
<Geom type="interval" position="year*sales" >
            	<Label content="sales"/>
            </Geom>
```
https://github.com/alibaba/BizCharts/blob/master/doc/api/label.md
