### ISSUE TITLE
仪表盘label文字方向错误

### ISSUE THREAD

**Issue by Ykeng** [alibaba/BizCharts#334]
- bizcharts Version:  3.1.7
- g2 Version: 3.0.9
- Platform or react version: 16.3.2
- Mini Showcase(like screenshots):

![image](https://user-images.githubusercontent.com/13504029/40486086-e5c6474e-5f92-11e8-9685-59bb3bf7a59e.png)

- CodePen Link: 
https://jsfiddle.net/lindoGZ/nLunx9vc/1/

**Comment by Leannechn** [comment]
此处设计自动适应方向了，`autoRotate ` 默认开启，为了符合人观察的方向，旋转角度<0度，或者>180,即第三第四象限的文字会自动倒转。你可以手动关闭`autoRotate ={false}`, 然后在textStyle中使用回调函数 使用你自己定义的的角度。
