### ISSUE TITLE
分组层叠柱状图tooltip显示问题

### ISSUE THREAD

**Issue by xhuanlee** [alibaba/BizCharts#336]
- bizcharts Version: 3.1.5
- Platform or react version:  **我本地的16.0.0**(不是特别清楚 jsfiddle 的默认 react 版本)
- Mini Showcase(like screenshots):
![1527228398 1](https://user-images.githubusercontent.com/22806759/40528865-ee09b804-6024-11e8-9326-0c6753f5d11e.jpg)
- CodePen Link: https://jsfiddle.net/xhuanlee/s9hf0L2p/

就如上图所示，分组层叠的柱状图，Tooltip 只能显示其中一组数据，其他数据都显示不出来，我不知道代码哪里出了问题，还是我的数据格式不对。  
恳请大家提供帮助，非常感谢...

**Comment by Leannechn** [comment]
color如下修改
```jsx
      <Geom
        type="interval"
        position="day*value"
        color="stack*dodge"
        adjust={adjust}
      />
```

**Comment by xhuanlee** [comment]
@Leannechn 嗯，好像确实是这样，非常感谢。
