### ISSUE TITLE
Charts组件数据和redux动态绑定， 在fetch后图形没法重新渲染 

### ISSUE THREAD

**Issue by AndyZhangChuan** [alibaba/BizCharts#338]
- bizcharts Version: 3.1.3-beta.1
- Platform or react version: 16.3.0
- Mini Showcase(like screenshots):  
```
<WaterWave title={'未处理'} height={140}  percent={unDealAfterSalePercent} color={'#f5222d'}/>
``` 
- CodePen Link: 
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by AndyZhangChuan** [comment]
unDealAfterSalePercent 来自于异步请求

**Comment by AndyZhangChuan** [comment]
如果把percent={40} 写死显示是正常的

**Comment by ssfxz** [comment]
你将unDealAfterSalePercent获取的值更新到state里就会触发图表重绘了

**Comment by AndyZhangChuan** [comment]
我使用reduceer 和  state两种方法都试过，  还是没法重新绘制图表

**Comment by AndyZhangChuan** [comment]
state里面的数据改变后，  百分比数值显示会自动刷新， 但是图表重新绘制
比如说这个WaterWave,  由最开始的30 变成 50，水槽并不会重新绘制

**Comment by AndyZhangChuan** [comment]
示例代码如下， 发现在fetchData后  重新设置数值， 图表并不会重新绘制
```
state = {
    testPercent: 30
}

componentWillUnmount() {
      fetchData().then(() => {
            this.setState({testPercent: 80})
      });
}

<WaterWave title={'test'} height={140}  percent={this.state.testPercent} color={'#f5222d'}/>
```

**Comment by AndyZhangChuan** [comment]
我看了WaterWave这个组件的源代码，并进行的了调试，如下
```
componentDidMount() {
    this.renderChart();
    this.resize();
    window.addEventListener('resize', this.resize);
  }
```
结果发现： 使用Canvas绘制Chart是在componentDidMount这个节点执行， 实际上这个节点在首次render执行后会调用一次， 但是后续有prop更新， render方法会重新执行， 但是componentDidMount则不会在重新执行
