### ISSUE TITLE
Demo compare-donut overlaps the legend with figure

### ISSUE THREAD

**Issue by zhujinxuan** [alibaba/BizCharts#339]
See example at https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/compare-donut

The legend (亚太地区, etc.) is on the data figure
<img width="678" alt="screen shot 2018-05-29 at 1 47 41 pm" src="https://user-images.githubusercontent.com/746159/40675849-e0c5ac82-6346-11e8-9b56-07854b2befc0.png">

**Comment by mytrip** [comment]
set  <Legend offsetY={150} />  it will be ok ~~ thank for your adjustment
