### ISSUE TITLE
数据为0时，饼图不显示

### ISSUE THREAD

**Issue by ayiaq1** [alibaba/BizCharts#344]
官网地址：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/pie/donut
设置data只有一条数据，并且值为0时，饼图没有显示，没有查看到有相关API
const data = [
     { item: '事例一', count: 0 }
];

**Comment by ssfxz** [comment]
这个情况是正确的

**Comment by wqjiao** [comment]
怎么做到count为0时，显示饼图呢
