### ISSUE TITLE
为什么我们在画条形图组的时候，要引一个 “”dataSet“”库呢？在线等，速回。。。。

### ISSUE THREAD

**Issue by martinwithyou** [alibaba/BizCharts#345]
<script src="//g.alicdn.com/bizcharts/io-asserts/3.1.5/BizCharts.min.js"> </script>
就是引入这个库，
它的作用是为了清洗数据，
所以我们在实际的开发环境必须要这个库，
不然的话文件会找不到“”“dataset”这个对象？
你们可以在“你们的官网里面详细说明吗？谢谢。。。。。。。

- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@martinwithyou 
bizcharts 和 data-set 是两个独立的包，data-set 主要封装了大量的数据 transform 操作。有些图表需要用 data-set 配合使用。

所以你的意思是什么？ 没明白。

**Comment by martinwithyou** [comment]
我因为项目，需要画两个条形图，一个就是普通的条形图，直接就可以画，我画另外一个条形图组的时候，我看官网的实例就要引入一个库，然后
 const data = [
          { name:'London', 'Jan.': 18.9, 'Feb.': 28.8, 'Mar.' :39.3, 'Apr.': 81.4, 'May': 47, 'Jun.': 20.3, 'Jul.': 24, 'Aug.': 35.6 },
          { name:'Berlin', 'Jan.': 12.4, 'Feb.': 23.2, 'Mar.' :34.5, 'Apr.': 99.7, 'May': 52.6, 'Jun.': 35.5, 'Jul.': 37.4, 'Aug.': 42.4}
        ]；
         const ds = new DataSet();
        const dv = ds.createView().source(data);
        dv.transform({
          type: 'fold',
          fields: [ 'Jan.','Feb.','Mar.','Apr.','May','Jun.','Jul.','Aug.' ], // 展开字段集
          key: '月份', // key字段
          value: '月均降雨量', // value字段
        });
这样操作。。。。。。。。

**Comment by martinwithyou** [comment]
引得库就是    <script type="text/javascript" src="//gw.alipayobjects.com/os/antv/assets/data-set/0.8.6/data-set.min.js"></script>

**Comment by Leannechn** [comment]
你可以console log 一下数据转化后的数据格式。它将数据格式是二维的格式转化为三维。你说的条形图组，也就是三个数据维度，所以，data-set 将你的数据转为三个维度的数据格式。你可以自己用原生js函数或者原始数据就是表达这种数据的数据格式。那么就不需要data-set来做这件事了。data-set 的功能远不止数据格式转化，它还是一个数据流管理。做图表联动的时候，你会喜欢它的
