### ISSUE TITLE
刚刚是我误操作，把问题给关里，你们的项目还有很大的进步空间，我就画个简单的条形组图，还要像拖油瓶一样引入另一个库，我也是无语。。。。。。。代码已贴，。。。。。。。希望你们进步，不要被历史抛弃。。。。。

### ISSUE THREAD

**Issue by martinwithyou** [alibaba/BizCharts#346]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by martinwithyou** [comment]
我之前用过，chart.js ,   echarts,    ploty.js,   twave , 货比三家，你们。。。。。呵呵

**Comment by RemyGong** [comment]
@martinwithyou 感谢你的建议...我们会评估实现成本和优化方式

**Comment by Leannechn** [comment]
画个简单的条形组图，不需要用dataset呀，您可以仔细阅读文档。和详细了解一下data-set的功能
