### ISSUE TITLE
关于树状图（type: 'hierarchy.compact-box'）

### ISSUE THREAD

**Issue by Ktig** [alibaba/BizCharts#348]
- bizcharts Version:3.1.5

![image](https://user-images.githubusercontent.com/22739126/40782725-d62805fe-6512-11e8-909b-7c55629c0caa.png)

请问大神getHGap、getVGap、getWidth、getHeight都代表的什么意思。。。。能详细的说明一下嘛

**Comment by ssfxz** [comment]
这段源码似乎并不是BizCharts工程里的源码，你可以提供一下这段源码的来源。
不过从字面意思上理解，树状图是由多个矩形组成的，因此getHGap、getVGap指的是获取矩形间的水平间隔和垂直间隔，类似padding，getWidth、getHeight是获取矩形宽高。
