### ISSUE TITLE
有多余的空白处

### ISSUE THREAD

**Issue by shoukailiang** [alibaba/BizCharts#349]
- bizcharts Version:最新版
- Platform or react version:16.4
- Mini Showcase(like screenshots):
- CodePen Link: https://codesandbox.io/s/40233znm04
 链接如上，第二个card组件中，我的chart左边多一块空白下方多一块空白 
![image](https://user-images.githubusercontent.com/24668909/40839338-a9c9aedc-65d4-11e8-9efb-9dfcf64c2e2a.png)

**Comment by mytrip** [comment]
chart默认有padding：padding={[ 20, 30, 20, 30]}，可以设置为padding="auto";  详情可见chart的api介绍
