### ISSUE TITLE
如何优化打包大小

### ISSUE THREAD

**Issue by OPY-bbt** [alibaba/BizCharts#35]
打包完会有700+kb 如果又使用了data-set 将会超过1M，有什么办法优化吗？

**Comment by weepy3641** [comment]
bizcharts 本身的代码量实际不大。
你可以对比下 G2 + dataset 和 bizcharts + dataset 包的大小差异，多出来的就是 bizcharts 的大小。
如果 bizcharts 本身占的比较多，你可以考虑打包时去掉一些没有用到的组件，以及消减掉一些 bizcharts 的依赖包 比如 invariant、warning 等这些，会比较麻烦些。

如果 bizcharts 本身包不大，那我也没有特别好的办法，要问问 antv 的人 G2 + dataset 可不可以拆包。

**Comment by weepy3641** [comment]
你说的包大小是压缩后的吧？

**Comment by OPY-bbt** [comment]
使用webpack--analyze 看的大小

**Comment by OPY-bbt** [comment]
我把data-set 去掉了，现在大小可以接收了。谢谢

**Comment by weepy3641** [comment]
@OPY-bbt  
关于 bizcharts 包特别大的问题，我这发现在之前的版本中将 react-dom 打包进去了，webpack.config.js 文件中没有写external react-dom。
不好意思啊， 3.1.0-beta.6 已经将 react-dom 排除了，包大小会小很多。
你也可以等下周 3.1.0 的正式版。
