### ISSUE TITLE
module "./factoryWithThrowingShims" not found

### ISSUE THREAD

**Issue by wangpuyue07** [alibaba/BizCharts#350]
- bizcharts Version:最新版
/umd/BizCharts
19644引用行是不是得注释掉，我gulp-browserify编译不过去
if (true) {
  var REACT_ELEMENT_TYPE = (typeof Symbol === 'function' &&
    Symbol.for &&
    Symbol.for('react.element')) ||
    0xeac7;

  var isValidElement = function(object) {
    return typeof object === 'object' &&
      object !== null &&
      object.$$typeof === REACT_ELEMENT_TYPE;
  };

  // By explicitly using `prop-types` you are opting into new development behavior.
  // http://fb.me/prop-types-in-prod
  var throwOnDirectAccess = true;
  module.exports = __webpack_require__(444)(isValidElement, throwOnDirectAccess);
} else {
  // By explicitly using `prop-types` you are opting into new production behavior.
  // http://fb.me/prop-types-in-prod
  module.exports = require('./factoryWithThrowingShims')(); //这个
}

**Comment by weepy3641** [comment]
应该是你缺少了 prop-types 的包把，加上试试。

**Comment by weepy3641** [comment]
@wangpuyue07 
这行代码并不是 bizcharts 直接些的，而是依赖方的代码。因此我们这也没办法直接注释掉，出现变异不过的原因应该是你某些库没有加载进去。

**Comment by wangpuyue07** [comment]
哈哈，原来是这样！谢谢解答哦 ：）
