### ISSUE TITLE
柱状图 各条柱状数据之间的间距 怎么修改？

### ISSUE THREAD

**Issue by x1nGoo** [alibaba/BizCharts#351]
柱状图 各条柱状数据之间的间距  怎么修改？

**Comment by mytrip** [comment]
<Coord scale={[0.7, 1.2]} />  尝试使用这个标签是否能修复

**Comment by x1nGoo** [comment]
@mytrip 你好，怎么好像没效。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/basic 
 这个例子 我设置country 好像间距不会变

**Comment by x1nGoo** [comment]
@mytrip 你好，我想要设置的是 柱状图 两条柱状图形之间的距离，不是 标点数值的间距差值。

**Comment by mytrip** [comment]
你可以把Geom上添加一个size，将柱子的宽度变小，如果要求柱子的宽度不变，则可以设置柱子的宽度，将canvas的宽度加大
