### ISSUE TITLE
View组件的坐标轴范围怎么和Chart保持一致

### ISSUE THREAD

**Issue by TigerBill2016** [alibaba/BizCharts#353]
- bizcharts Version: 3.1.2
- Platform or react version: 16.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by mytrip** [comment]
你的意思是用view的方式画一个和demo一样的图？
