### ISSUE TITLE
如何绘制中国地图

### ISSUE THREAD

**Issue by forMine** [alibaba/BizCharts#356]
怎么绘制中国地图，文档太晦涩。请教

**Comment by minlx** [comment]
同求

**Comment by liunian** [comment]
基本思路是，拿到地理位置信息，然后用 `DataSet` 的 [geo.region](https://github.com/alibaba/BizCharts/blob/master/doc/api/transform.md#georegion-%E7%94%B1%E5%9C%B0%E5%90%8D%E8%8E%B7%E5%8F%96%E5%9C%B0%E7%90%86%E4%BD%8D%E7%BD%AE%E5%8C%BA%E5%9F%9F) 来进行 transform，提供经纬度（`longitude` 和 `lantitude`），最后用 `<Geom type='polygon' position="longitude*lantitude" />` 来绘制。

BizCharts 提供了地图绘制的能力，但没有专业的地图数据，所以建议大家使用专业的地图服务，如[高德地图](http://lbs.amap.com/getting-started/map/)。
