### ISSUE TITLE
How to ignore the missing points in the line graph?

### ISSUE THREAD

**Issue by Artoriayume** [alibaba/BizCharts#36]
See there's a sample data like this:
======
const data = [
  { time: '2017-11-08', sold: 275, income: 2300 },
  { time: '2017-11-09', sold: 115, income: 667 },
  { time: '2017-11-10 13:00', sold: 120},
  { time: '2017-11-10 15:00', income: 982 },
  { time: '2017-11-11', sold: 350, income: 5271 },
  { time: '2017-11-12', sold: 150, income: 3710 }
];
================
I got a result like this:
![plotting](https://user-images.githubusercontent.com/23534026/33703244-4995eabe-db62-11e7-9cef-0efb3c6cfaa6.png)

===================
I tried to do some transformations on the Dataset like **impute**. But the methods given are inserting unsatisfying values.

All I want is to **skip the missing point, and connect a straight line between two existing points**.

================================
I know there is a way to fix this is to fill in the missing using the average value.
But I don't think it is a good practice as the data is actually missing. I don't want these points to be shown on the tooltips when hovered.

Do you have any suggestions?

=================
the plotting code is like below: 
=============
SalesHistogram extends React.Component {
  constructor(props) {
    super(props);
    const dv = new View();
    dv.source(props.data);

    dv.transform({
      type: 'fold',
      fields: ['sold', 'income'],
      key: 'category',
      value: 'value'
    });
    console.log(dv);
    this.data = dv;
    this.cols = {
      time : {}
    };
  }

  render() {
    return (
	<Chart width={800} height={600} padding={100}data={this.data} scale={this.cols}>
	<Axis name = 'sold' />
	<Axis name = 'time'/>
	<Legend position="bottom"/>
	<Tooltip />
        <Geom type="path" position="time*value" color = 'category'
	shape='dot'/>
      </Chart>
    );
  }

**Comment by Artoriayume** [comment]
Sorry, there seems to be some formatting problems with the plotting code. But I think the issue is clearly pointed out.

**Comment by weepy3641** [comment]
two suggestions：
1、user guide line to connect a straight line between two existing points.
2、use custom shape to do this thing。 Custom shape allow you draw anything with the datas.

https://github.com/alibaba/BizCharts/blob/master/doc/api/shape.md
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/rounded-stacked-column-chart

**Comment by Artoriayume** [comment]
Hi weepy,
First off, thank you very much for your quick reply. I really appreciated it.

Excuse me but I am still a little bit confused. What do you mean by "user guide line", do you mean user guide, something like api documentation, or the user guides the line to connect between points?

To simplify, is there an existing method or api I can use to connect points igonoring missing points or do I need to implement by myself?

**Comment by weepy3641** [comment]
Guide.Line component api:
https://github.com/alibaba/BizCharts/blob/master/doc/api/guide.md#line

Guide.Line component can connect a straight line between two existing points.

here the Guide.Region example, Guide.Line can use the same like Guide.Region。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/bullet-graph

**Comment by Artoriayume** [comment]
Thanks again for your patient answer.
I read the introduction about guide lines.

Though seemingly it does not supposed to be used here, I will give it a try.
Also I will try to play with the customized shapes.

Thank you for your help!
谢谢！用英语是为了方便外国朋友方便查看，老铁辛苦了！
