### ISSUE TITLE
多组同类型数据怎么展示在一个实例里面

### ISSUE THREAD

**Issue by limeng90** [alibaba/BizCharts#360]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

比如说下面这组数据怎么根据cate，在同一个图标里面展示3条线图，其中每个cate的creatime 是不同的，dataset怎么transform， 感谢大佬，bizchart第一次用，dataset还不熟练， 万分感谢

let data = [
 [
  {createtime: 1526213605000, value: 10, cate: 1 },
  {createtime: 1526313706000, value: 20 ,cate: 1},
  {createtime: 1526413800000, value: 30,cate: 1 },
  {createtime: 1526313900000, value: 40,cate: 1 }
 ],
[
  {createtime: 1526313600000, value: 11,cate: 2 },
  {createtime: 1528313806000, value: 22,cate: 2 },
  {createtime: 1526313900000, value: 33 ,cate: 2},
  {createtime: 1526514900000, value: 44 ,cate: 2}
 ],
[
  {createtime: 1527313600000, value: 15 ,cate: 3},
  {createtime: 1528313800000, value: 25 ,cate: 3 },
  {createtime: 1526413900000, value: 36 ,cate: 3 },
  {createtime: 1526316900000, value: 46 ,cate: 3 }
 ],
]

**Comment by liunian** [comment]
想根据 cate 来分组

1. 首先先把数据转换为一维数组，同时把 `cate` 转成字符串，因为是数字时底层的默认处理是从 0 开始的索引，但代码里并不是从 0 开始，这样会导致渲染效果不对（如颜色可能无法区分）
2. 把 `(createtime, value)` 这样的数据作为点对应到直角坐标（为了方便阅读，把 `createtime` 的类型设为 `timecat`）
3. 以 `cate` 作为分组

详细见  https://codepen.io/liunian/pen/QxvMWR ，下面是部分代码

![image](https://user-images.githubusercontent.com/646129/41291129-6bb8da04-6e81-11e8-9c72-8ce9816db494.png)


```jsx
const data =  [
  [
    {createtime: 1526213605000, value: 10, cate: 1 },
    {createtime: 1526313706000, value: 20, cate: 1 },
    {createtime: 1526413800000, value: 30, cate: 1 },
    {createtime: 1526313900000, value: 40, cate: 1 }
  ],
  [
    {createtime: 1526213605000, value: 11, cate: 2 },
    {createtime: 1528313806000, value: 22, cate: 2 },
    {createtime: 1526313900000, value: 33, cate: 2},
    {createtime: 1526514900000, value: 44, cate: 2}
  ],
  [
    {createtime: 1526213605000, value: 15, cate: 3 },
    {createtime: 1528313800000, value: 25, cate: 3 },
    {createtime: 1526413900000, value: 36, cate: 3 },
    {createtime: 1526316900000, value: 46, cate: 3 }
  ],
]

// cate 是数字，用作分组时，G2 当做从 0 开始的索引，所以转成字符串会更好处理，否则分组颜色会展示不对
const data2 = data.reduce((res, cur) => {
  const list = cur.map(i => {
    return {
      ...i,
      cate: `${i.cate}`
    };
  });

  return res.concat(list);
}, []);

const scale = {
  createtime: {
    alias: '时间',
    type: 'timeCat'
  },
  cate: {
    type: 'cat'
  }
};

ReactDOM.render((
  <Chart height={400} data={data2} scale={scale} forceFit>      
    <Legend />
    <Tooltip />
    <Axis name="createtime" />
    <Axis name="value" />
    <Geom type="line" position="createtime*value" color={'cate'} />
    <Geom type="point" position="createtime*value" color={'cate'} />
  </Chart>
), document.getElementById("mountNode"));
```
