### ISSUE TITLE
柱形图点击对应的区域 执行 onPlotDblClick方法 无data参数

### ISSUE THREAD

**Issue by jolinlizhihua** [alibaba/BizCharts#364]
柱形图点击对应的区域 执行 onPlotDblClick方法 ，打印e，结果没有data数据这一项

**Comment by liunian** [comment]
只有事件触发源有实际数据时才会返回 `data`，否则是空。所以仅当点击柱形图有内容的那部分才有回 data。参见 G2 的说明  antvis/g2#614 

如果在没直接击中数据时也需要获取对应的数据，可以使用 [chart#getSnapRecords(point)](https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#getSnapRecords) 方法来获取。

如果没用到 `<View>` 组件来定义图表，可以通过事件对象中的 `views` 来操作，如：

```js
const dataList = evt.views[0].getSnapRecords({x: evt.x, y: evt.y})
```

如果有多个 view，目前需要通过 `onGetG2Instance` 来记录下对应的 `g2` 实例，再调用 `getSnapRecords`。

```jsx
let g2Inst;
function getG2Instance(i) {
  g2Inst = i;
}

function dblclick(e) {
  console.log(g2Inst.getSnapRecords({x: e.x, y: e.y }));
}

<Chart width={600} height={400} onGetG2Instance={getG2Instance} onPlotDblClick={dblclick} data={data} cols={cols}>
    <Axis name="sold" />
    <Axis name="genre" />
    <Geom type="interval" position="genre*sold" color="genre" />
</Chart>
```

@weepy3641 后续再优化获取 g2 chart 实例的方式。

**Comment by stillsilly** [comment]
getSnapRecords 这个api是不是在4.x 5.x里已经被移除了   
有类似功能的替代api吗
