### ISSUE TITLE
使用slider时报错

### ISSUE THREAD

**Issue by Z-X-L** [alibaba/BizCharts#368]
我在做官方例子时遇到这个问题（https://github.com/alibaba/BizCharts/blob/slider/plugin/slider/demo/slider-guide.js），
![image](https://user-images.githubusercontent.com/38447944/41274063-95bc1470-6e4e-11e8-975e-7ca8719e2c65.png)
拖动滑块时数据可以正常变化，但控制台一直提示这个错误

**Comment by liunian** [comment]
能否提供更详细一些的代码？比如基于[此 codepen 模板](https://codepen.io/leslie2014/pen/xjJGER)贴一下重现代码

**Comment by Z-X-L** [comment]
你好，这里是详细代码，
[chartsTest.txt](https://github.com/alibaba/BizCharts/files/2093999/chartsTest.txt)

**Comment by liunian** [comment]
@Z-X-L 能否提供下你的 data （注意业务数据脱敏）

**Comment by Z-X-L** [comment]
不好意思，我可能没说清楚，我用的都是demo里的例子，以下是链接：
https://github.com/alibaba/BizCharts/blob/master/plugin/slider/demo/data/candle-sticks.json
https://github.com/alibaba/BizCharts/blob/slider/plugin/slider/demo/slider-guide.js

**Comment by liunian** [comment]
@Z-X-L 我这边在最新的 master 分支下，通过下面的步骤来运行，在 Chrome 浏览器中访问，没有报错

1. `$ cd plugin/slider`
2. `$ npm i`
3. `$ npm run demo`
4. 浏览器访问 `http://localhost:3510`

看截图，你好像不是直接运行 demo ，而是用 cdn 的方式来引入 slider 的 plugin，是吗？
看看插件版本是不是比较旧的版本？尝试使用最新的版本看看 https://unpkg.com/bizcharts-plugin-slider@2.0.3/umd/bizcharts-plugin-slider.min.js

如果还是有问题，希望能帮忙提供下完整些的项目代码。如果是特定浏览器或特定操作下导致的，希望也提供下这方面的信息。

**Comment by Z-X-L** [comment]
我是用npm下载后引入的，而且版本也是2.0.3，在Chrome浏览器中访问，以下是完整项目，
[slider.zip](https://github.com/alibaba/BizCharts/files/2097170/slider.zip)

**Comment by liunian** [comment]
@Z-X-L `onChang` 中 `this.setState` 导致的，你可以先注释掉看看。https://codepen.io/liunian/pen/QxMqzG 这里注释掉后就不报错了。

@weepy3641 和 #281 是同一个原因吗？

**Comment by liunian** [comment]
duplicate of #281

**Comment by Z-X-L** [comment]
嗯，确实是这个问题，非常感谢
