### ISSUE TITLE
onTooltipChange和ToolTip里的crosshairs属性是否有冲突？

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#369]
我想用crosshairs 设置十字光标 但是 同时调用onTooltipChange这个API十字光标就不会展示出来

**Comment by liunian** [comment]
在 `<Chart />` 上设置 `onTooltipChange`，设置 tooltip `<Tooltip crosshairs={{ type: "cross" }} />`。
这个 demo 供参考 https://codepen.io/liunian/pen/xzrbxE

![image](https://user-images.githubusercontent.com/646129/41329438-507bb03e-6f00-11e8-815a-2dcda822cf90.png)

**Comment by preservance717** [comment]
在调用onTooltipChange， 用crosshairs 设置矩形框，矩形框不会展示出来

**Comment by preservance717** [comment]
在调用onTooltipChange， 用crosshairs 设置矩形框，矩形框不会展示出来
