### ISSUE TITLE
build之后，页面警告

### ISSUE THREAD

**Issue by OPY-bbt** [alibaba/BizCharts#37]
Warning: `It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.`

删除BizCharts库后就没有了。

**Comment by OPY-bbt** [comment]
使用 umd/BizCharts.js 作为入口文件导致生产环境出错

**Comment by OPY-bbt** [comment]
改为 min 是可以的， 我又试了下面几种方法都是可以的：
- 入口文件改为 "main": "lib/index"`
- 删掉main 和 browser，使用module 或 jsnext:main。
- 利用 webpack resolve 的 alias 属性，使 bizchart 强制使用 min 版本。

我现在的解决方案是在.roadhogrc 中添加 alias
```json
{
 "env": {
   "production": {
      "extraBabelPlugins": [
          ["module-resolver", {
             "alias": {
                "bizcharts": "./node_modules/bizcharts/umd/BizCharts.min.js",
             },
         }]
      ]
    }
 }
}
```

如果配置改为  NODE_ENV=production，不太清楚在开发模式下有没有问题。这个没时间测。

**Comment by weepy3641** [comment]
如果配置改为 NODE_ENV=production，相当于入口是打包压缩文件，不利于调试，其他问题应该没有。

**Comment by OPY-bbt** [comment]
有没有能兼顾开发与生产模式的入口？

**Comment by weepy3641** [comment]
@OPY-bbt 
查了下，没有兼顾的方案哦。
需要在 bizcharts 的使用方的 webpack 文件中自己去切换模式，根据模式使用不同的文件 min 或者 非 min。

**Comment by Molin123** [comment]
我使用下面的引入方式解决了这个问题
`import { Chart, Geom, Axis, Tooltip, Coord, Label, Legend, View, Guide, Shape } from 'bizcharts/umd/BizCharts.min.js';
`

**Comment by huanlirui** [comment]
> 我使用下面的引入方式解决了这个问题
> `import { Chart, Geom, Axis, Tooltip, Coord, Label, Legend, View, Guide, Shape } from 'bizcharts/umd/BizCharts.min.js'; `

good 官方示例中的imprt导致了很多问题，编译不了。这样引入解决了！
