### ISSUE TITLE
使用层叠图标 只显示最后一条数据 

### ISSUE THREAD

**Issue by nanfs** [alibaba/BizCharts#371]
- bizcharts Version:3.17
- Platform or react version:16.2.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by liangqi1** [comment]
@nanfs 不明白层叠图标的意思，是类似于堆叠柱状图那种吗？
![_20180627115453](https://user-images.githubusercontent.com/26572016/41952137-f3de77c4-7a00-11e8-90ee-be53ab582d8c.png)

**Comment by liangqi1** [comment]
最后需要做成效果是下面这种？
![image](https://user-images.githubusercontent.com/26572016/41952249-9fd7f10e-7a01-11e8-91a0-d1e9a6fa2200.png)

**Comment by weepy3641** [comment]
@liangqi1 
什么叫只显示最后一条数据？ 不明白。
如果想要只显示最后一条数据，你把其他数据删除不就可以。

**Comment by liangqi1** [comment]
@weepy3641 
并不是我提的问题，我也不是特别明白楼主@nanfs的意思

**Comment by weepy3641** [comment]
楼主不回就关了。。。

**Comment by zpfblockchains** [comment]
@liangqi1 你发的那个图片所示效果是怎么实现的

**Comment by liangqi1** [comment]
@zpfblockchains 
```
 <Geom type={type} position="xData*yData" color={'name'} >
<Label offset={12} content="xData*yData"
                     htmlTemplate={(text, item, index) => {
              /** 这里进行计算求和，返回结果就行了，注意只返回一个柱状图的 **/
/** Calculate and sum here, return the result ** /
                     }}
</Geom>
```
API文档：
[](https://github.com/alibaba/BizCharts/blob/master/doc/api/label.md)

**Comment by zpfblockchains** [comment]
@liangqi1 不太会写，有具体代码参考一下吗

**Comment by liangqi1** [comment]
@zpfblockchains 上面的代码片段就是写的内容，<Label />里面就是加文字的，你用htmlTemplate自定义下，写进去就完事儿了，可以看下文档

**Comment by zpfblockchains** [comment]
@liangqi1 type设置为堆叠柱状图，会每个都显示。怎么控制只在最上层显示？

**Comment by liangqi1** [comment]
@zpfblockchains 你可以判断一下，最上层的不就是所有值中最大的，你就只让他显示最大的不就完事儿了

**Comment by Wangyage1** [comment]
> @zpfblockchains 你可以判断一下，最上层的不就是所有值中最大的，你就只让他显示最大的不就完事儿了
htmlTemplate  也是循环遍历，两个都会显示 。你自己去写一下就知道了，不行的

**Comment by Wangyage1** [comment]
> @liangqi1 type设置为堆叠柱状图，会每个都显示。怎么控制只在最上层显示？
这个问题有解决 方案了吗？

**Comment by onlyforyoumylove** [comment]
假设只想在total后面显示的话，可以
const data=[
name: 'like',
age: 52,
total:100
]
<Label  
                content="total"
                offset ={3}
               htmlTemplate={(text, item, index)=>{
                  if(item.point.type=='total')
                    return "####"
                  return '';
              }
            }
               
            />
