### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by sl798970799** [alibaba/BizCharts#373]
- bizcharts Version:
- Platform or react version:图表的辅助元素legend 自定义图例的配置 { value: 'waiting', fill: '#3182bd', marker: 'hyphen' }, marker设置为hyphen不显示，且有多个 shape值不显示现象 ， 且类型比较少
- Mini Showcase(like screenshots):
- CodePen Link: https://github.com/alibaba/BizCharts/blob/master/doc/api/legend.md
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by sl798970799** [comment]
图表的辅助元素legend 自定义图例的配置 { value: 'waiting', fill: '#3182bd', marker: 'hyphen' }, marker设置为hyphen不显示，且有多个 shape值不显示现象 ，   且类型比较少

**Comment by liunian** [comment]
`<Legend marker="hyphen" />`

https://codepen.io/liunian/pen/RJZpWg
