### ISSUE TITLE
Legend自定义图例的配置 

### ISSUE THREAD

**Issue by sl798970799** [alibaba/BizCharts#374]
<Legend
  custom={true},
  items={[
    { value: 'waiting', fill: '#3182bd', marker: 'shape' },
    { value: 'call', fill: '#99d8c9', marker: 'shape' },
    { value: 'people', fill: '#fdae6b', marker: 'shape' },
  ]}
  onHover={ev => {}} // 自定义 hover 事件
  onClick={ev => {}} // 自定义 click 事件
/>

我指的是 这一段代码中   marker 设置为 marker: 'hyphen'  不显示  有好几个属性都不显示

**Comment by sl798970799** [comment]
<Legend
  custom={true},
  items={[
    { value: 'waiting', fill: '#3182bd', marker: 'shape' },
    { value: 'call', fill: '#99d8c9', marker: 'shape' },
    { value: 'people', fill: '#fdae6b', marker: 'shape' },
  ]}
  onHover={ev => {}} // 自定义 hover 事件
  onClick={ev => {}} // 自定义 click 事件
/>

我指的是 这一段代码中   marker 设置为 marker: 'hyphen'  不显示  有好几个属性都不显示

**Comment by liunian** [comment]
还请附上详细些的代码说明及截图

**Comment by kreja** [comment]
相关 issue https://github.com/antvis/g2/issues/330
解释：用户自定义 legend 时传入 marker 的配置项而不是名称。

自定义 legend 时传名称无法生效，以下写法是可以的：

```
items={[
  { value: 'value', marker: {symbol: 'diamond', fill: '#3182bd', radius: 5} }
]}
```

具体参考 https://jsfiddle.net/krejaone/k7dz09r5/2/

@weepy3641  我们的文档需要更新一下

**Comment by HelloxMrR** [comment]
symbol:'name',所有name为线型的都不显示啊....这个怎么解决呢

**Comment by weepy3641** [comment]
@HelloxMrR 
没明白你的意思。

**Comment by HelloxMrR** [comment]
参考G2API文档: https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_legend

{ value: 'waiting', marker: {symbol: 'square', fill: '#3182bd', radius: 5} },
{ value: 'call', marker: {symbol: 'hyphen', stroke: '#99d8c9', radius: 5, lineWidth: 3} },
{ value: 'people', marker: {symbol: 'hyphen', stroke: '#fdae6b', radius: 5, lineWidth: 3}
谢谢,问题已经解决了,是颜色填充的问题,fill/stroke
