### ISSUE TITLE
坐标轴不够，是否可以加横向滚动

### ISSUE THREAD

**Issue by TML4140** [alibaba/BizCharts#376]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by RemyGong** [comment]
slider-plugin may be helpful for you, see this example: https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/rain-and-flow
