### ISSUE TITLE
后台给的数据是string怎么处理

### ISSUE THREAD

**Issue by xchengguang** [alibaba/BizCharts#377]
一个饼图需要的是
   const data = [
          { item: '事例一', count: 40 },
          { item: '事例二', count: 21 },
          { item: '事例三', count: 17 },
          { item: '事例四', count: 13 },
          { item: '事例五', count: 9 }
        ];
后台现在返我的是
           const data = [
          { item: '事例一', count: ‘40’ },
          { item: '事例二', count: ’21‘ },
          { item: '事例三', count: ‘17’ },
          { item: '事例四', count: ’13‘ },
          { item: '事例五', count: ‘9’ }
        ];
数据量很大，在哪里能够更改组件吗

**Comment by liunian** [comment]
有两种思路

1. 把数据源转换成你想要的格式，比如你上面的例子可以使用 `const newData = data.map(i => ({ item: i.item, count: i.count - 0}));` 来把字符串转为数字
2. 通过配置度量 `scale` 来让 BizCharts 识别为数字（[文档](https://github.com/alibaba/BizCharts/blob/master/doc/api/scale.md#%E5%BA%A6%E9%87%8F%E5%88%86%E7%B1%BB)），例子 https://codepen.io/liunian/full/GGQQXy ，关键代码如下：

```jsx
const scales = {
  count: {
    type: 'linear'
  }
};

<Chart height={400} data={data} scale={scales} forceFit>
   ...
</Chart>
```
