### ISSUE TITLE
Padding auto sometimes doesn't work when having Label formatter on Axis

### ISSUE THREAD

**Issue by mk-nickyang** [alibaba/BizCharts#378]
- bizcharts Version: 3.1.0

- Platform or react version: 16.2.0

- Mini Showcase(like screenshots):
[![Screenshot from Gyazo](https://gyazo.com/90543ce957cf8b160846d98f5c3f93fa/raw)](https://gyazo.com/90543ce957cf8b160846d98f5c3f93fa)

- CodePen Link: https://codepen.io/lucissa/pen/QxmvmB

请问padding auto目前是只会计算没有format过的label的边框吗？

**Comment by RemyGong** [comment]
@mk-nickyang 确实存在这个问题。暂时可以先手动设置padding的下边距来解决这个问题，我们也会跟进看看如何解决

**Comment by weepy3641** [comment]
需要 G2 修复，暂时关闭。
