### ISSUE TITLE
使用bizcharts画仪表盘时，当比例为100%时，画的仪表盘会歪掉，包括官网的例子也是一样的情况

### ISSUE THREAD

**Issue by amelonsamy** [alibaba/BizCharts#379]
![image](https://user-images.githubusercontent.com/29348038/41703050-a7c057c2-7564-11e8-9337-64888b8dab6d.png)

**Comment by RemyGong** [comment]
@amelonsamy 因为下面的cols中设置value的最大值为9，因此当前值设置为10的时候仪表盘会歪；建议在不确定最大值为多少的情况下，注释掉cols中的max和ticks两项

**Comment by smileDm** [comment]
如果注释掉cols中的max和ticks两项，仪表盘显示在满格位置，怎么改变data的值都是在满格位置

**Comment by smileDm** [comment]
![image](https://user-images.githubusercontent.com/28996448/54675517-b4337100-4b39-11e9-9d37-9a2b5330d238.png)
![image](https://user-images.githubusercontent.com/28996448/54675611-d9c07a80-4b39-11e9-9c43-492ddda09071.png)
把cols的max改为10，Arc的end第一个区间改为10
