### ISSUE TITLE
设置渐变色,会导致tooltip里的颜色都变成黑的

### ISSUE THREAD

**Issue by shadiniao** [alibaba/BizCharts#380]
- codesandbox Link:
- https://codesandbox.io/s/421p0xvn9w

不论是crosshairs上的颜色,还是tooltip里提示信息的颜色都是黑的
![image](https://user-images.githubusercontent.com/14309730/41704848-ea280790-7569-11e8-8478-8e265e1e1929.png)

**Comment by weepy3641** [comment]
https://github.com/antvis/g2/issues/597

**Comment by weepy3641** [comment]
@shadiniao 
新版本已经修复 bizcharts@3.2.4
