### ISSUE TITLE
在一个View中多条折线公用一个y轴 y轴刻度出现重叠

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#382]
![image](https://user-images.githubusercontent.com/23026361/41753127-1c2122ce-75fe-11e8-85f6-e7f1fa83ea69.png)

**Comment by weepy3641** [comment]
多跟轴的问题，可以配置 axis 中的 label offset 属性避免重叠。

https://github.com/alibaba/BizCharts/blob/master/doc/api/axis.md#7label-object--null


不过不建议使用多根 y 轴哦，因为分不清线对应的刻度。
