### ISSUE TITLE
bizcharts-plugin-slider: 拖动滑块过程中鼠标超出了slider范围，此时松开鼠标左键，再移动到slider上，滑块依然会跟着滑动

### ISSUE THREAD

**Issue by isegon** [alibaba/BizCharts#386]
- bizcharts Version:3.1.5
- bizcharts-plugin-slider:2.0.1
- Platform or react version:16.2.0

**Comment by weepy3641** [comment]
fix at bizcharts-plugin-slider 2.0.4
