### ISSUE TITLE
var items = chart.getTooltipItems(point);

### ISSUE THREAD

**Issue by liuliuLiu161** [alibaba/BizCharts#387]
```
<chart
  onPlotEnter={ev => {
	var point = {
	  x: ev.x,
	  y: ev.y
	};
	var items = chart.getTooltipItems(point);
	console.log(items);
  }}
/>
```

请问var items = chart.getTooltipItems(point);这个方法中的chart是什么？

**Comment by weepy3641** [comment]
@liuliuLiu161 
是 g2 图表实例， 可以通过 chart 的 onGetG2Instance 获取。
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#1ongetg2instance
