### ISSUE TITLE
tooltip 在图表相邻时的bug 

### ISSUE THREAD

**Issue by rannuo** [alibaba/BizCharts#388]
- bizcharts Version:3.1.8
- Platform or react version:16.3.16
- Mini Showcase(like screenshots):

![image](https://user-images.githubusercontent.com/21377874/41842876-96ae492a-789e-11e8-9dc3-8971bad796a9.png)

- CodePen Link: https://codepen.io/balaman/pen/YvjQwy
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

当两个图表紧挨着时，鼠标从一个图表移向相邻的图表，移出的图表的tooltip 不会消失

**Comment by weepy3641** [comment]
https://github.com/antvis/g2/issues/554
