### ISSUE TITLE
[Feature] Tooltiop 的itemTpl属性返回一个函数？

### ISSUE THREAD

**Issue by edmundluk3** [alibaba/BizCharts#389]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
自定义模版，有时候需要把英文映射成中文，itemTpl如果是纯字符串替换的话，貌似做不到？

**Comment by edmundluk3** [comment]
(name, color)  => `<li><span style="background-color:${color};" class="g2-tooltip-marker"></span>${name}: ${value}</li>`

**Comment by weepy3641** [comment]
需要用 geom 上的 tooltip 属性对 tooltip 内容格式化。

```js
<Geom type='line' position='month*tem' tooltip={["month*tem", (month, tem) => {
                return  {
                    name:month,
                    value: tem + "xxx" , // 在这里格式化。
                  }
              }]}/>
```

https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#9tooltip-----boolean--string--array-
