### ISSUE TITLE
度量的类型为timeCat时，数据为空数组，报invalid date in fecha.format

### ISSUE THREAD

**Issue by TigerBill2016** [alibaba/BizCharts#390]
- bizcharts Version:3.1.10
- Platform or react version:16.3.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

如题

**Comment by liunian** [comment]
Duplicate of #343

**Comment by heiniuhaha** [comment]
已修复，查看以下Demo
bizcharts@3.x https://bizcharts.net/product/bizcharts/demo/525
bizcharts@4.x https://bizcharts.net/product/BizCharts4/demo/524
