### ISSUE TITLE
Not sure is how to hide a line

### ISSUE THREAD

**Issue by henrych4** [alibaba/BizCharts#391]
Thanks for the great library.

Currently there is a Chart component on my project and I would like to display the curve based on input. However I cannot find property in <Geom /> to hide/unhide a line.

Now I hide the line by setting the size of line to 0 and use a flag in order not to show tooltip. However I think that's too ugly and this can be done in a better way. Can anyone give some suggestions? Thank you.

jsfiddle link:
[https://jsfiddle.net/sb284x5h/](https://jsfiddle.net/sb284x5h/)
Hide line by setting value of `fields` on line 30
```
const fields = [];  //hide all lines
const fields = ['Tokyo'];  //hide 'London' line
const fields = ['London'];  //hide 'Tokyo' line
const fields = ['Tokyo', 'London']  //hide nothing
```

**Comment by weepy3641** [comment]
@henrych4 
When there is only one line in the chart,  Bizcharts do not support hide this one line chart default. 
You should define an custom legend and hide the line by your self.

See demo's legend click event:
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/double-axes
