### ISSUE TITLE
仪表盘的调试问题

### ISSUE THREAD

**Issue by amelonsamy** [alibaba/BizCharts#392]
![image](https://user-images.githubusercontent.com/29348038/41949232-1cf39aa8-79f3-11e8-80eb-f612d954deac.png)
startAngle和endAngle是一什么为基准的么，调处来的角度老是会变歪  不知道什么原因

**Comment by weepy3641** [comment]
startAngle 和 endAngle 都是以弧度值为单位，方向是顺时针的。
startAngle 为 0 ，起始方向为 x 轴延伸方向，弧度为 0.

```
chart.coord('theta', {
  radius: 0.75,
  startAngle: 0,
  endAngle: 3.14
});
```
效果如下：

![image](https://user-images.githubusercontent.com/3838676/41963998-82d94cea-7a2b-11e8-87c2-fb71ea85d323.png)
