### ISSUE TITLE
图表内容不居中

### ISSUE THREAD

**Issue by yucccc** [alibaba/BizCharts#393]
- bizcharts Version: 3.1.8
- Platform or react version: 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/24189407/41964930-e0ef0a16-7a2d-11e8-8db0-01082689d366.png)

不知设置了什么 图表总是从最左边开始 可能是因为我是多个图表切换吗？ 但是我的图表都是不同的配置
![堆积柱状图](https://user-images.githubusercontent.com/24189407/41965101-5ba8ac08-7a2e-11e8-8529-747279de08d5.png)

**Comment by yucccc** [comment]
找到具体原因了 因为如何 fields的值时日期格式时 比如'2018-06-26' 就会出现问题

**Comment by weepy3641** [comment]
@yucccc  没明白你的意思，能否在 codepen 上写个demo 以及描述的具体些。

**Comment by weepy3641** [comment]
@yucccc 
这是因为图内内部将 ‘2016-02-01’ 解析为连续时间格式了，实际上你需要的是离散时间格式，配置下 scale 类型就可以了。

事例代码如下：
```
const scale={
          月份: {
            type: 'timeCat'
        }
}

<Chart scale={scale} />
```

**Comment by zsdostar** [comment]
> @yucccc
> 这是因为图内内部将'2016-02-01'解析为连续时间格式了，实际上你需要的是离散时间格式，配置下尺度类型就可以了。
> 
> 事例代码如下：
> 
> ```
> const scale={
>           月份: {
>             type: 'timeCat'
>         }
> }
> 
> <Chart scale={scale} />
> ```

非常感谢   同样的问题
![image](https://user-images.githubusercontent.com/17907135/60063805-b6a4f880-9730-11e9-9c7b-1264c884b881.png)
