### ISSUE TITLE
安装bizCharts是否需要另外安装G2

### ISSUE THREAD

**Issue by allan2coder** [alibaba/BizCharts#394]
bizCharts是基于G2开发的，那么我们在使用bizCharts的时候是否需要安装G2？
我的理解是bizCharts是一个单独的库，应该不需要另外在我们本地安装G2把？

谢谢

**Comment by weepy3641** [comment]
@allan2coder 
目前 bizcharts 已经将 g2 打包进去了，因此无需额外安装 g2.
