### ISSUE TITLE
图例放在图表下方时没法完全显示

### ISSUE THREAD

**Issue by rallet** [alibaba/BizCharts#395]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
应该是 chart padding不够，将 padding 改为 auto 即可。
```
<Chart padding='auto' />
```
