### ISSUE TITLE
为什么有些数据需要处理有些不要

### ISSUE THREAD

**Issue by xchengguang** [alibaba/BizCharts#396]
有些data需要
const ds = new DataSet();
const dv = ds.createView().source(data);
有些直接data就用了，为什么。。。文档里也没理解

**Comment by weepy3641** [comment]
@xchengguang  看图表需求，有些图表需要数据转换下才能实现，有些图表不需要。
具体什么样的图表需要转换数据，可以参考站点的 demo 以及熟悉 dataview 文档。

https://alibaba.github.io/BizCharts/demo.html
https://github.com/alibaba/BizCharts/blob/master/doc/api/transform.md

**Comment by xchengguang** [comment]
请问demo中有哪个是可以仿照着实现双轴柱状图的吗，还没有自定义shape的能力。。。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/grouped-column 
上面这个demo我画不出右边的轴
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/area-large
上面这个demo我画不出柱状图。。。
