### ISSUE TITLE
Legend中传递class名来修改模板样式

### ISSUE THREAD

**Issue by hcxw11** [alibaba/BizCharts#397]
修改图例的位置(比如右下角),使用以下的方式
`
          <Legend 
            useHtml={true}
            g2-legend = {{
              right: 0,
              left: 'unset'
            }}
          />
`
产生的结果和预想的不太一样
![](http://wx-picture.oss-cn-hangzhou.aliyuncs.com/18-6-29/10164878.jpg)
![](http://wx-picture.oss-cn-hangzhou.aliyuncs.com/18-6-29/99150381.jpg)

这里的模板样式是否可以修改为以传入的值为准？

- bizcharts Version: 3.1.5
- Platform or react version: react16.0.0
- CodePen Link: https://codepen.io/hcxw11/pen/Nzeqpe?editors=1000

**Comment by weepy3641** [comment]
@hcxw11 
可以的，直接在 css 样式中写即可，由于要覆盖掉默认样式，需要加上 important 才会生效。

![image](https://user-images.githubusercontent.com/3838676/42143294-fc8b37ce-7de6-11e8-80d2-882dede3e981.png)

![image](https://user-images.githubusercontent.com/3838676/42143300-028725b6-7de7-11e8-8b5b-28b14465bb6a.png)

**Comment by hcxw11** [comment]
@weepy3641 这个必须通过css吗？因为我看到文档里面是可以通过`g2-legend = {{ right: 0, left: 'unset' }}`这种方式直接修改属性的，只是left这个会在后面重新计算，导致我设置的值没有生效。另外如果left设置的值为一个确定的值，重新生成的值也很奇怪，大概的效果如下：
![image](https://user-images.githubusercontent.com/16369309/42158495-2a431902-7e23-11e8-8630-b6c27de345ab.png)

**Comment by weepy3641** [comment]
文档中写通过g2-legend = {{ right: 0, left: 'unset' }}这种方式直接修改属性的，g2 有点bug，不生效。

想要 css 生效，需要 加上 important。
