### ISSUE TITLE
双轴柱状图如何构建

### ISSUE THREAD

**Issue by xchengguang** [alibaba/BizCharts#398]
请问demo中有哪个是可以仿照着实现双轴柱状图的吗，还没有自定义shape的能力。。。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/grouped-column
上面这个demo我画不出右边的轴
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/area-large
上面这个demo我画不出柱状图。。。

**Comment by kreja** [comment]
https://jsfiddle.net/krejaone/joLezydb/60/ 参考下这个 demo
