### ISSUE TITLE
在Chart里设置forceFit以后，宽度总是超出页面

### ISSUE THREAD

**Issue by yuyu19880526** [alibaba/BizCharts#399]
在Chart里设置forceFit以后，宽度总是超出页面
如下图，我是这样写的代码
![image](https://user-images.githubusercontent.com/7857167/42144697-1c9f6848-7def-11e8-8d99-981d41e483c0.png)
如下图，页面里是这样显示的，超出了页面范围
![image](https://user-images.githubusercontent.com/7857167/42144732-4dc83d0a-7def-11e8-941a-19dc3c23856f.png)
如下图，但是缩放一下页面，或者f12一下就恢复正常了
![image](https://user-images.githubusercontent.com/7857167/42144749-6d8737d6-7def-11e8-88cc-22f57696dc8e.png)

请教各位这个bug怎么解决

**Comment by kreja** [comment]
参考下这个 issue https://github.com/alibaba/BizCharts/issues/132

**Comment by childdd** [comment]
<Chart forceFit onGetG2Instance={chart => {
           setTimeout(()=>{
             chart.forceFit();
           },0);
        }}>

为什么我必须要变成异步才管用，并且首次打开还有个回归正常的动画

**Comment by kreja** [comment]
异步的问题可以提供个 demo 吗？
动画可以关掉 https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md#8animate-boolean-

**Comment by weepy3641** [comment]
可以在 didMount 时触发一次 resize 事件，会自适应宽度。

window.dispatchevent(new event('resize'))
