### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by bopengleon** [alibaba/BizCharts#400]
![2018-07-02 1 51 52](https://user-images.githubusercontent.com/18209795/42147736-bf999c00-7e01-11e8-8706-efde8c3fc5ad.png)
![2018-07-02 1 52 04](https://user-images.githubusercontent.com/18209795/42147738-bfe9a33a-7e01-11e8-85e2-2e8c13552a87.png)
渲染不了全部数据。 改变视窗大小后可以load 全部数据

**Comment by kreja** [comment]
来个 demo 看看？
