### ISSUE TITLE
修改热点图坐标系方向

### ISSUE THREAD

**Issue by zerofront** [alibaba/BizCharts#404]
- bizcharts Version:   "3.1.8",
- Platform or react version:  16.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER 

![image](https://user-images.githubusercontent.com/19327366/42255310-b78111b0-7f7d-11e8-9607-bca9ceaa3c47.png)

热点图绘制默认是这样的。
![image](https://user-images.githubusercontent.com/19327366/42255353-e22e1462-7f7d-11e8-95a3-b2ed93b0ef38.png)

如何修改坐标系？
![image](https://user-images.githubusercontent.com/19327366/42255367-ef416730-7f7d-11e8-84f7-6f08feaa50e7.png)

**Comment by weepy3641** [comment]
坐标系转一下。
<Coord reflect />  

https://github.com/alibaba/BizCharts/blob/master/doc/api/coord.md#4reflect----x--y--array
