### ISSUE TITLE
如何渲染2组多条折线图，而不混乱起来

### ISSUE THREAD

**Issue by childdd** [alibaba/BizCharts#407]
const data = [
          { date: '一月',   '项目1': 7,  '项目2': 3 ,'项目3': 11,'项目4': 13,project:'a'},
          { date: '二月',   '项目1': 6,  '项目2': 4 ,'项目3': 13,'项目4': 14,project:'a'},
          { date: '三月',   '项目1': 9,  '项目2': 5 ,'项目3': 16,'项目4': 15,project:'a'},
          { date: '四月',   '项目1': 14, '项目2': 8 ,'项目3': 19,'项目4': 21,project:'a'},
          { date: '五月',   '项目1': 18, '项目2': 11,'项目3': 21,'项目4': 31,project:'a'},
          { date: '六月',   '项目1': 21, '项目2': 15,'项目3': 22,'项目4': 34,project:'a'},
          { date: '一月',   '项目1': 25, '项目2': 17,'项目3': 25,'项目4': 35,project:'b'},
          { date: '二月',   '项目1': 26, '项目2': 16,'项目3': 24,'项目4': 34,project:'b'},
          { date: '三月',   '项目1': 23, '项目2': 14,'项目3': 23,'项目4': 32,project:'b'},
          { date: '四月',   '项目1': 18, '项目2': 10,'项目3': 19,'项目4': 20,project:'b'},
          { date: '五月',   '项目1': 13, '项目2': 6 ,'项目3': 14,'项目4': 18,project:'b'},
          { date: '六月',   '项目1': 9,  '项目2': 4 ,'项目3': 11,'项目4': 15,project:'b'}
        ];
![qq 20180704174358](https://user-images.githubusercontent.com/26546435/42272737-b2f46cfa-7fb9-11e8-8890-51de305b571c.png)

**Comment by kreja** [comment]
建议画两个图， 分别绘制 project a、project b
