### ISSUE TITLE
折叠条形图显示label时数值为0的时候与前一个数值重叠

### ISSUE THREAD

**Issue by mantianrefeng** [alibaba/BizCharts#408]
![image](https://user-images.githubusercontent.com/25834502/42299376-6ea76dc0-803d-11e8-8d1c-b38b64e82834.png)

如图所示，如果数值为0的情况

**Comment by kreja** [comment]
建议 val 为 0 时返回空字符串，因为没有柱状了也就不用绘制0了吧，tooltip 还可以看到 0 就可以了
