### ISSUE TITLE
Geom 组件的 type 是否支持，根据数据设置不同类型的线 。

### ISSUE THREAD

**Issue by Pillar-Zhang** [alibaba/BizCharts#410]
比如 ：我想要给不同的分组的数据 设置 实线 虚线  粗线 细线 。

类似颜色 可以这样设置： color={["score", ["#EE5050", "#DBDBDB", "#E9E9E9", "#F3F3F3"]]} 

我发现 type 属性只能设置一种值 不支持 数组

**Comment by kreja** [comment]
可以在 geom 上设置 shape
案例 https://jsfiddle.net/krejaone/pw8ktex0/4/
文档 https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md#5shape-----string--array
