### ISSUE TITLE
数据更新时，Geom中animate属性不生效

### ISSUE THREAD

**Issue by hcxw11** [alibaba/BizCharts#412]
- bizcharts Version: 16.0.0
- Platform or react version: 3.1.5
- Mini Showcase(like screenshots):
![](http://wx-picture.oss-cn-hangzhou.aliyuncs.com/18-7-6/7955354.jpg)
- CodePen Link: https://codepen.io/hcxw11/pen/wXLyWa
### 问题描述：

数据更新时，图表中的数据直接变成了新的值，参考[animate教程](https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/animate.md)没有效果，配置如下：
```
// 在Chart标签中设置animate={true}
<Geom
  type="interval"
  position="x*y"
  color={color}
  tooltip={tooltip}
  animate={{
    update: {
      animation: 'fadeIn', // 动画名称
      easing: 'easeInQuart', // 动画缓动效果
      delay: 100, // 动画延迟执行时间
      duration: 600, // 动画执行时间
    },
  }}
/>
```

后面看了g2的教程，使用`chart.changeData(nextProps.data)`和`chart.source(data); chart.repaint();` 图表也没有进行渲染。

不知道是哪里出了问题，可以说是非常绝望了。。

手动召唤大佬
@weepy3641

### 期望：
当数据发生变化时，图表能有一个动效，比如折线图从左向右绘制这样。

**Comment by weepy3641** [comment]
@hcxw11 
查了下，g2 本身就有这个问题，需要等它修复。

**Comment by hcxw11** [comment]
@weepy3641 
我试了下，appear里面的动画是可以用的，但是update和enter里的动画没有效果，就像我上面CodePen的[例子](https://codepen.io/hcxw11/pen/wXLyWa)那样，主要是想要在数据变化的时候有一个动画效果，或者是不是更新数据的时候不能直接修改\<Chart\>中的data，而是调用其他的什么函数？

另外[animate教程-动画配置参数](https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/animate.md#%E5%8A%A8%E7%94%BB%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0)中动画缓动效果的例子最好修改一下。

**Comment by weepy3641** [comment]
给 g2 提交 issue 了。  
临时解决方案是暂时不用bizcharts 的 state 更新触发动画，直接拿到 chartInstance 调用 changeData 接口。 （不要调用 repaint。）
https://github.com/antvis/g2/issues/783

**Comment by wangcongyi** [comment]
@hcxw11 与 官网上的 demo 只是时间上的差别 ?

**Comment by hcxw11** [comment]
@wangcongyi 是的，我的问题是修改数据后，update和enter里面的动画都不起效果，用上面的临时方案调用changeData可以用

**Comment by lx70770** [comment]
@hcxw11 您好，请问您的问题解决了吗 ？我现在遇到了和你一样的问题，更新state图表没有动画，但是使用 chartInstance 调用 changeData 接口就可以解决，可是我的另一个组件里使用的DataSet，使用同样的方法更新数据也没有动画

**Comment by hcxw11** [comment]
> @hcxw11 您好，请问您的问题解决了吗 ？我现在遇到了和你一样的问题，更新state图表没有动画，但是使用 chartInstance 调用 changeData 接口就可以解决，可是我的另一个组件里使用的DataSet，使用同样的方法更新数据也没有动画

我这也只是用changeData接口改了下，[修改的例子](https://codepen.io/hcxw11/pen/ejVXXP)，不知道是不是你要的，如果不是的话，最好发一个例子看下。另外这个bug后面应该会修复，可以关注下。

**Comment by nuintun** [comment]
使用 `setState` 没动画 +1

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/597
关联 issue

已经检查出是因为 bizcharts 中调用了 changeData 后再次调用的 repaint，将 changeData 的状态清楚了，因此没有动画。

需要记录下 changeData 状态，有的情况下不再调用 repaint。

**Comment by CharlesMoone** [comment]
我用onGetG2Instance里把g2Chart暴露之后，调用了g2Chart.changeData方法可以触发动画效果。
可以作为一个临时方案把

**Comment by neekey** [comment]
同样没有动画+1

我仔细看了一下官方给的demo https://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-realtime&selectedKey=%E6%A6%82%E8%A7%88，里面有两个非常tricky的地方：

- 添加了 `onGetG2Instance()` 但是完全没有使用回调里面的`g2Chart`。我试了下注释掉这个回调，动画就没有了
- demo里面的数据渲染，用的不是state里面的data，而是一个实例变量，且更新的过程中要保证这个data变量的引用不变。我试了下，只要引用一改变( `data = [...data]`）动画效果就会消失。

所以这个也是非常坑了，请问是否有更好的解决方案呢？

**Comment by ggleo08** [comment]
同问题！
bug opened at 2018/07/06 ?

**Comment by hangaoke1** [comment]
2020年了 这bug还没修复？

**Comment by Leannechn** [comment]
该问题由于整个渲染架构问题，改动比较大，已在最新 4.0.5版本中修复
