### ISSUE TITLE
横轴数据较多  展示不下怎么办

### ISSUE THREAD

**Issue by RayToby** [alibaba/BizCharts#415]
横轴数据较多  展示不下怎么办     想展示一个月每天的数据  或者更多这种的

**Comment by RayToby** [comment]
是自适应的

**Comment by sunxinyang** [comment]
https://www.bizcharts.net/products/bizCharts/demo/detail?id=g2-bar-diverge&selectedKey=%E6%A6%82%E8%A7%88    尝试X轴转换成Y轴，设置： <Coord  transpose/>

**Comment by sunxinyang** [comment]
https://www.bizcharts.net/products/bizCharts/demo/detail?id=g2-bar-diverge&selectedKey=%E6%A6%82%E8%A7%88 尝试X轴转换成Y轴，设置：  <Coord  transpose/>

**Comment by sunxinyang** [comment]
尝试将X轴转换成Y轴，设置： <Coord  transpose/>
参考demo：https://www.bizcharts.net/products/bizCharts/demo/detail?id=g2-bar-diverge&selectedKey=%E6%A6%82%E8%A7%88

**Comment by sunxinyang** [comment]
尝试将X轴转换成Y轴，设置：<Coord  transpose /> 
参考demo：https://www.bizcharts.net/products/bizCharts/demo/detail?id=g2-bar-diverge&selectedKey=%E6%A6%82%E8%A7%88

**Comment by sunxinyang** [comment]
尝试将X轴转换成Y轴，设置：---<Coord  transpose/>---
参考demo：https://www.bizcharts.net/products/bizCharts/demo/detail?id=g2-bar-diverge&selectedKey=%E6%A6%82%E8%A7%88

**Comment by shufangu** [comment]
同问 tickCount需要动态设置吗
