### ISSUE TITLE
Axis name字段数据和图标不一致 

### ISSUE THREAD

**Issue by qyjandroid** [alibaba/BizCharts#416]
![image](https://user-images.githubusercontent.com/6645414/42434096-64b55e90-8384-11e8-9563-1fa01a4d6115.png)
![image](https://user-images.githubusercontent.com/6645414/42434117-7056a506-8384-11e8-8555-239e6ad2e658.png)

我的   <Axis name={config.get("time")} />   
为什么生成的时间被转换了

**Comment by Leslie2014** [comment]
我用你上面的数据测试并非发生上图的情况，测试地址：https://codepen.io/leslie2014/pen/vaYBRz。

你可以对这个 CodePen Demo 进行修改，以便我们更好的发现问题。

**Comment by liunian** [comment]
@qyjandroid 你 demo data 数组里的 `time` 是时间格式，默认是当做**连续时间**来处理，开始时间和结束时间位于两端。如果是希望该表示分类的意思，可设置 [scale](https://github.com/alibaba/BizCharts/blob/master/doc/api/scale.md) 为 `timeCat`，即你 demo 中的 `cols` 改为以下设置

```js
const cols = {
  time: { type: 'timeCat' }
};
```
