### ISSUE TITLE
混合图的实现

### ISSUE THREAD

**Issue by tudou330121** [alibaba/BizCharts#417]
![image](https://user-images.githubusercontent.com/30098601/42619227-0395448c-85ea-11e8-87f6-941624bbb31b.png)

**Comment by Leannechn** [comment]
请详细描述你的问题
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
