### ISSUE TITLE
如何隐藏图的Y轴

### ISSUE THREAD

**Issue by shadiniao** [alibaba/BizCharts#419]
我制作了多根Y轴,想点击时隐藏线和对应的Y轴,直接调用this.chart.axis(key, false),但隐藏不了,需呀配合chart的repaint,但调用repaint后,点击其他线也隐藏不了
效果如图
![image](https://user-images.githubusercontent.com/14309730/42721607-3cebe72c-8770-11e8-9876-fecb057ffc9f.png)

demo地址:
https://codesandbox.io/s/xormx3jp1q

**Comment by Leannechn** [comment]
自定义的legend可以使用react state去管理重绘。代码如下
https://codesandbox.io/s/4wo0qolmw0
