### ISSUE TITLE
世界地图渲染名称问题

### ISSUE THREAD

**Issue by exinren** [alibaba/BizCharts#422]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
如何将地图中的英文替换成中文，不是直接修改json的方法

**Comment by Leannechn** [comment]
可以对label渲染自定义函数，将你的名称映射成想要的文本。
<Lable content={['fieldName', (name)=> {return newName;}]}
