### ISSUE TITLE
自定义Legend

### ISSUE THREAD

**Issue by HelloxMrR** [alibaba/BizCharts#423]
- bizcharts Version:3.1.7
- Platform or react version:16.2.0

{ value: 'oilLine',  marker: {symbol: 'hyphen', fill: '#FF0000'} },
所有symbol为线型的都不显示

**Comment by HelloMrR** [comment]
参考G2API文档: https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_legend


{ value: 'waiting', marker: {symbol: 'square', fill: '#3182bd', radius: 5} }, 
    { value: 'call', marker: {symbol: 'hyphen', stroke: '#99d8c9', radius: 5, lineWidth: 3} }, 
    { value: 'people', marker: {symbol: 'hyphen', stroke: '#fdae6b', radius: 5, lineWidth: 3} }
