### ISSUE TITLE
bug: 气泡图Legend组件里去除滑动块时，会多处一个弧线

### ISSUE THREAD

**Issue by startdt-yiye** [alibaba/BizCharts#424]
- bizcharts Version: ^3.1.10
- Platform or react version:   ^16.4.1
- Mini Showcase(like screenshots):  去掉滑动块，会出现和一个浮动线
- CodePen Link: https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/point/bubble
![image](https://user-images.githubusercontent.com/37532875/42754502-48cf7f96-8927-11e8-90d5-25c5ab28f579.png)

**Comment by Leannechn** [comment]
sorry，我这边没办法复现。能提供更多的信息吗？比如系统，浏览器版本号什么的

**Comment by Leannechn** [comment]
😂，查了很久！这个需要指定Geom对应的字段即可。参考如下代码
 <Legend name="LifeExpectancy" reversed width={100} height={20} slidable={false} />

**Comment by liyunying** [comment]
@Leannechn  可是为什么我加了Geom对应的字段之后，连slidable={false}都不生效了……滑动块又出来了

**Comment by liyunying** [comment]
直接去掉图例不好吗？ visible={false}

**Comment by weepy3641** [comment]
圆弧线是图例，直接隐藏即可。
