### ISSUE TITLE
能否实现多个图表使用同一提示框?

### ISSUE THREAD

**Issue by hihl** [alibaba/BizCharts#425]
如题，如Hightcharts的官方示例  https://www.hcharts.cn/demo/highcharts/synchronized-charts

**Comment by Leannechn** [comment]
内置的tooltip并没有这个功能，需要通过自定义tooltip来实现。
方法1. 绑定onTooltipChange事件自己查询当前需要展示到数据进行修改；
方法2.配置对应到tooltip模版，在Geom的tooltip属性中对数据赋值进行自定义。
方法2中如果使旧版本有隐藏bug,自定义函数返回值必须包含name，value属性，升级新版可解决这个问题。

**Comment by xfause** [comment]
> 内置的tooltip并没有这个功能，需要通过自定义tooltip来实现。
> 方法1. 绑定onTooltipChange事件自己查询当前需要展示到数据进行修改；
> 方法2.配置对应到tooltip模版，在Geom的tooltip属性中对数据赋值进行自定义。
> 方法2中如果使旧版本有隐藏bug,自定义函数返回值必须包含name，value属性，升级新版可解决这个问题。

能否提供一个范例，或者说现在是否已经支持这个功能？
