### ISSUE TITLE
关于仪表盘的起始弧度定义

### ISSUE THREAD

**Issue by amelonsamy** [alibaba/BizCharts#426]
在使用仪表盘当中虽然说是通过startAngle和endAngle来定义起始弧度，但是起始弧度的值不是自己随机定义的，应该是根据值的变化范围，但是他们之间到底是什么关系呢，我觉得文档当中没有阐述清楚，在我自己的开发过程中以某个固定百分比来调试仪表盘将仪表盘调正时，一旦变为其他值就歪掉了，从文档当中无法获得答案，望解答。

**Comment by weepy3641** [comment]
fix doc

**Comment by weepy3641** [comment]
startAngle 和 endAngle 代表了整个极坐标系的开始和结束的弧度值。

也就是饼图布局的总体弧度范围。

```
<Coord type='theta' radius={0.75}  startAngle={0} endAngle={3.14}/>
```

demo地址：
https://codepen.io/anon/pen/VBdZrW

效果
![image](https://user-images.githubusercontent.com/3838676/43630826-0515b336-9734-11e8-80b3-cb2d030980a4.png)
