### ISSUE TITLE
GeoJSON 报错 malformed path data

### ISSUE THREAD

**Issue by qyjandroid** [alibaba/BizCharts#427]
![image](https://user-images.githubusercontent.com/6645414/42880209-1e2a886c-8ac6-11e8-9e48-83bc83b60ec6.png)
![image](https://user-images.githubusercontent.com/6645414/42880217-2490f2ea-8ac6-11e8-8883-e199c535e9d7.png)
![image](https://user-images.githubusercontent.com/6645414/42880246-3fdfd458-8ac6-11e8-9283-660fd1f05b8b.png)

**Comment by dengkaidi** [comment]
你应该使用正确的gemoJson， 里面的"coordinates"是数值型的经纬度坐标。正确的json格式长这样：[https://i.loli.net/2018/07/19/5b50378c663b3.png](url)

**Comment by Leannechn** [comment]
使用GEOjson需要注意合法合规，bizchart暂无提供geoJson资质，可以期待一下我们与高德合作的BizMap产品，正在努力开发ing。欢迎加入一起搞事情！目前可以使用高德地图的可视化方案以解燃眉之急。😊
