### ISSUE TITLE
X轴居中设置（Y轴0刻度处）

### ISSUE THREAD

**Issue by dengkaidi** [alibaba/BizCharts#428]
- bizcharts Version: 3.1.5
- Platform or react version:  16.2
- Mini Showcase(like screenshots): https://i.loli.net/2018/07/19/5b5035d7abe4d.png
https://i.loli.net/2018/07/19/5b5035d7ae4cf.png
- CodePen Link: https://codepen.io/anon/pen/JBRaOb
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

我看了API发现坐标轴没有居中设置，不知有没有让x轴居中（处于Y轴的0刻度处）的实现方案吗？

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/43045303-d77a53ae-8de8-11e8-9ad2-de9846990837.png)
配合scale和View使用，使View为图表的上办部分0.5区域，scale为-1到1，就从下面到上面全部区域填充
![image](https://user-images.githubusercontent.com/6812138/43045326-406dd7d2-8de9-11e8-97b2-f035cb30c2cd.png)

**Comment by dengkaidi** [comment]
谢谢
