### ISSUE TITLE
中国地图-省市下钻怎么在antdPro这种项目实现

### ISSUE THREAD

**Issue by MinHongwei** [alibaba/BizCharts#429]
- bizcharts Version: ^3.1.3-beta.1
- Platform or react version: ^16.2.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
antdProURL：https://pro.ant.design/index-cn

**Comment by MinHongwei** [comment]
Map of China - how does this map work in projects like antdPro

**Comment by Leannechn** [comment]
中国地图我们推荐使用高德地图的可视化库，https://lbs.amap.com/api/loca-api/prod_intro
由于地图geoJson 是需要国家资质审核的，所以bizcharts暂时不提供geoJson，通过高德绘制中国地图可以避免相关法律问题。可以期待一下bizcharts未来的地图产品BizMap，我们正在努力开发中

**Comment by MinHongwei** [comment]
我是指  https://antv.alipay.com/zh-cn/g2/3.x/demo/map/drill-down.html 这个图用react怎么实现。

**Comment by weepy3641** [comment]
@MinHongwei 
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/map/drill-down
