### ISSUE TITLE
Legend的marker属性自定义

### ISSUE THREAD

**Issue by ChestnutMr** [alibaba/BizCharts#433]
看了一下API，Legend的marker属性只支持几个默认的图形，需要自定义图形如何处理？

**Comment by mytrip** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/legend.md  可以使用分类html自定义图例

**Comment by ChestnutMr** [comment]
找到解决方案了，参考G2的实现。给marker传一个自定义函数：
                      marker: {
                          symbol : (x, y, r, ctx)=>{
                            ctx.lineWidth = 2;
                            ctx.fillStyle = ctx.strokeStyle;
                            ctx.moveTo(x - r - 3, y);
                            ctx.lineTo(x + r + 3, y);
                            ctx.arc(x, y, r - 2, 0, Math.PI * 2, false);
                            ctx.fill();
                          },
                          stroke: '#fff',
                          radius: 8,
                          lineWidth: 2,
                      }
