### ISSUE TITLE
Bizchart中Legend在右边无法显示出来，设置在上面和下面可以显示的。

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#434]
- bizcharts Version: 3.2.0
- Platform or react version: 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

Bizchart中Legend在右边无法显示出来，设置在上面和下面可以显示的。

**Comment by mytrip** [comment]
设置下chart的padding，将右边的padding放大，按照默认的padding是会被挤压出可视区域的

**Comment by weepy3641** [comment]
@DonChengCheng 
设置 <Chart padding='auto' /> 也可以解决你的问题
