### ISSUE TITLE
BizCharts 能实现3D词云的效果吗

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#435]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@DonChengCheng 
bizcharts 是 2d 图表库，3d 词云图不直接支持。
你可以自己仿造 3d 数据用 2d 渲染。
