### ISSUE TITLE
能否根据x轴定义折线的形状或颜色

### ISSUE THREAD

**Issue by hubing01** [alibaba/BizCharts#436]
能否根据x轴的值定义形状或颜色
![image](https://user-images.githubusercontent.com/38777869/43243922-627385d0-90db-11e8-8507-fdee572e4778.png)
比如希望将2018-06左边线shape设为line，右侧设置为dash

**Comment by weepy3641** [comment]
@hubing01 
参考 demo ：https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/line-of-dashed
