### ISSUE TITLE
分组柱图中显示两个 x 轴的问题

### ISSUE THREAD

**Issue by zengkan0703** [alibaba/BizCharts#438]
- bizcharts Version: 3.1.10
- Platform or react version: 16.4.1
- Mini Showcase(like screenshots):
![bizcharts](https://user-images.githubusercontent.com/20679471/43364182-1018365e-9348-11e8-9122-6c2711e844ec.png)

- CodePen Link: https://codepen.io/zengkan0703/pen/ejeMjw

你好，我想实现的是在分组柱图中显示两个 x 轴，不过配置了之后还是只能显示一个 x 轴。请问我这个配置是哪里有问题吗？

另外，我想请教一下在这个分组柱图中，tooltip 可不可以以每一个柱子为单位触发，且只显示这一个柱子的数据，我在文档中没有看到相关的配置。

非常感谢您的帮助。
```javascript
 const data = [
    { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
    { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
    { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
    { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
    { name: 'London', 月份: 'May', 月均降雨量: 47 },
    { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
    { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
    { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
    { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
    { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
    { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
    { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
    { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
    { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
    { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
    { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
];
<Chart
    data={data}
    padding={{ top: 30, right: 10, bottom: 30, left: 30 }}
>
    <Axis name="月份" position="bottom" visible={true} />
    <Axis name="月均降雨量" />
    <Axis name="name" position="top" />
    <Tooltip />
    <Geom
        type="interval"
        position="name*月均降雨量"
        color={['月份', '#019a99']}
        adjust={[{ type: 'dodge' }]}
    />
</Chart>
```

**Comment by weepy3641** [comment]
@zengkan0703 
你的图表只有一个 name 的 x 轴，显示在 top 位置。
月份并非 x 轴，而是在某一个刻度下，多个柱子的布局方式，让你看上去有 x 轴一样。

1、可以换一种图表展现方式，并列柱状图。 demo： https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/grouped-column
2、按照你的需求，需要用 facet 实现。 demo：https://codepen.io/anon/pen/oMpvgy
code：
``
<html>
<head>
    <script src="//g.alicdn.com/bizcharts/io-asserts/3.1.2/react16.0.0.production.min.js"></script>
    <script src="//g.alicdn.com/bizcharts/io-asserts/3.1.2/react-dom16.0.0.production.min.js"></script>
    <script src="//cdn.bootcss.com/babel-core/5.8.38/browser.min.js"></script>
    <script type="text/javascript" src="//gw.alipayobjects.com/os/antv/assets/data-set/0.8.6/data-set.min.js"></script>
    <script src="//g.alicdn.com/bizcharts/io-asserts/3.1.5/BizCharts.min.js"> </script>
    
    
  </head>
  <body>
      <div id="mountNode"</div>
      <script type="text/babel">
        const { Chart, Axis, Geom, Tooltip, Legend, Facet, View } = window.BizCharts;
       const data = [
          { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
          { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
          { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
          { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
          { name: 'London', 月份: 'May', 月均降雨量: 47 },
          { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
          { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
          { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
          { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
          { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
          { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
          { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
          { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
          { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
          { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
          { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
        ];
        ReactDOM.render((
          <Chart
            data={data}
            padding={[30, 0, 50, 30]}
          >
            <Facet type='rect' fields={['name']} >
              <View>
                <Geom position='月份*月均降雨量' />
              </View>
            </Facet>
      	</Chart>
        ), document.getElementById("mountNode"));
    </script>
  

</body>
</html>
``

**Comment by zengkan0703** [comment]
好的，谢谢你的帮助
