### ISSUE TITLE
关于点击onPlotDblClick点击事件返回参数ev下面data概率性出现的问题

### ISSUE THREAD

**Issue by ht1131589588** [alibaba/BizCharts#439]
- bizcharts Version: 3.1.10
- Platform or react version: 16.4.1
onPlotDblClick事件在饼图中基本上都会返回data参数，在柱状图中点击事件不会返回data的概率超过90%

**Comment by liunian** [comment]
只有事件触发源有实际数据时才会返回 data，否则是空。所以仅当点击柱形图有内容的那部分才有回 data，详细请参考 #364 的说法以及解决方案

Duplicate of #364
