### ISSUE TITLE
今天下载更新代码发现 所有折线图 提示框的样式都变成白色的了 为什么

### ISSUE THREAD

**Issue by sl798970799** [alibaba/BizCharts#441]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by sl798970799** [comment]
今天下载更新代码发现 所有折线图 提示框的样式都变成白色的了 为什么

**Comment by weepy3641** [comment]
@sl798970799 
g2 默认样式将 tooltip 背景色配为白色了。这是经过设计精心配置出的，如果觉得不舒服，可以自行将样式改为之前的。

**Comment by sl798970799** [comment]
不行啊 搞得原来的项目都变了 麻烦真大了

**Comment by weepy3641** [comment]
@sl798970799  
你可以降一个 bizchars 的版本，固定为 3.1.10.
或者将使用下老版本中 g2 的default  theme 。
