### ISSUE TITLE
文档中可否做一个双轴图表的示例?

### ISSUE THREAD

**Issue by Shen-Shuyi** [alibaba/BizCharts#442]
Viser示例地址: https://viserjs.github.io/demo.html#/others/double-axes   
官网亦有相似例子: https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_legend (28. custom: boolean下面的例子)  

这种图表在实践中还是比较常见的, 希望出一个官方示例  
非常感谢

**Comment by weepy3641** [comment]
@Shen-Shuyi 
http://bizcharts.net/products/bizCharts/demo/detail?id=84&selectedKey=%E6%A6%82%E8%A7%88

**Comment by Shen-Shuyi** [comment]
艾玛, 好尴尬
