### ISSUE TITLE
已经import“Guide”了，但是Guid标签下的Text、Html等无法识别

### ISSUE THREAD

**Issue by RyujoKen** [alibaba/BizCharts#444]
- bizcharts Version:
3.0
- Platform or react version:
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/26379438/43761291-41c48a84-9a57-11e8-9880-e543b85ba998.png)

**Comment by RyujoKen** [comment]
![image](https://user-images.githubusercontent.com/26379438/43761494-d26e67c6-9a57-11e8-9777-77c1d5deaa71.png)
第二张图上传失败了，是这个

**Comment by weepy3641** [comment]
@RyujoKen 
Text 没定义啊。

const { Text } = Guide;

加上。。。。
