### ISSUE TITLE
Chart高无法自适应

### ISSUE THREAD

**Issue by cuichuanteng** [alibaba/BizCharts#446]
Chart中 可以设置宽度自适应但高度必须设置值，因此高度无法自适应。
是否可以根据外面容器高度来适应？因为 外层容器大小可变的所以 无法设置值。

**Comment by weepy3641** [comment]
@cuichuanteng 
暂时没有自适应高度的功能，如果需要可以你自己在外层监听下容器的高度。

**Comment by cuichuanteng** [comment]
百度一圈没找到加高度的方法，请问react下怎么获取外层容器高度？ 目前网上只找到事件触发后获取元素宽高的方法，但并不适用现在的需求。

**Comment by cuichuanteng** [comment]
@weepy3641

**Comment by liunian** [comment]
React  的 `findDOMNode` 方法获取元素（或者用 ref 甚至如 querySelector 等 DOM 相关的 api），然后使用 DOM 方法，如 `clientHeight`，`offsetHeight` 或 `getBoundingClientRect` 等属性或方法来获取

**Comment by andy1247008998** [comment]
@weepy3641 同样需要这个功能，请考虑添加，谢谢！
