### ISSUE TITLE
Interval geom renders out of chart bounds

### ISSUE THREAD

**Issue by ReigoHein** [alibaba/BizCharts#447]
- bizcharts Version: 3.1.2 & 3.2.0
- Platform or react version: 16.2.0
- Mini Showcase(like screenshots):

Without forceFit, width={1000}
![2018-08-09-091741_997x297_scrot](https://user-images.githubusercontent.com/3507236/43881640-7ff747ba-9bb5-11e8-8960-4ac2f84113ee.png)
With forceFit
![2018-08-09-091809_3347x284_scrot](https://user-images.githubusercontent.com/3507236/43881642-825d1b4c-9bb5-11e8-911c-a8551028617f.png)

- CodePen Link:
https://codepen.io/reigohein/pen/xJQzWQ

**Comment by weepy3641** [comment]
@ReigoHein 
Set date's scale type as timeCat.  The default data's scale type is time linear, that's will affect the axis and geometry layout.
```
const scale = {
          date: {
            type: 'timeCat',
            mask: 'DD MMM'
          },
          gbs: {
            formatter: (val) => {
              return `${val} GB`
            }
          }
        }
```

**Comment by ReigoHein** [comment]
Hey, that indeed fixed it. But why does it go out of bound with time?

**Comment by liunian** [comment]
@ReigoHein related to the default behavior between category and time  https://github.com/alibaba/BizCharts/blob/master/doc_en/api/axis.md#4blank-space-at-both-ends-of-axis
