### ISSUE TITLE
柱状图线形图混用问题

### ISSUE THREAD

**Issue by Clish** [alibaba/BizCharts#45]
如何设置四列数据中三列数据用柱状图显示, 另外一列用线形图显示

**Comment by weepy3641** [comment]
需要用两个 geom 去做。
三列数据先 fold ，然后用 geom 显示, 然后 color 等于 fold 的 key 字段。
fold参考：
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/line/series
另一列数据单独用一个 geom 显示。

两个 geom  y 不一样会出现双轴，如果不需要双轴，隐藏掉其中一根，并且将两根 y 轴的刻度范围对齐下。

**Comment by Clish** [comment]
@weepy3641 谢谢你的指点.
我用多View来解决的这个问题.
以后会深度使用BizCharts, 以后可以多交流

**Comment by weepy3641** [comment]
欢迎使用及提意见。

**Comment by chaselss** [comment]
另一列数据的柱状图和三列数据的柱状图重叠怎么解

**Comment by weepy3641** [comment]
@chaselss 
没明白你的意思，你是想要并列柱状图？
可以参考如下 demo
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/grouped-column
