### ISSUE TITLE
如何为折线图添加一根横线，

### ISSUE THREAD

**Issue by zhaodongxx** [alibaba/BizCharts#450]
- bizcharts Version: 
- Platform or react version: 
- Mini Showcase(like screenshots): 
- CodePen Link: 
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

![这里写图片描述](https://img-blog.csdn.net/20180809211941611?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2RvcmFfMzEw/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)
就像这个图一样 链接 ：https://img-blog.csdn.net/20180809211941611?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2RvcmFfMzEw/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70

**Comment by liunian** [comment]
使用 [Guide](https://github.com/alibaba/BizCharts/blob/master/doc/api/guide.md)，参考 https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/bubble-text
