### ISSUE TITLE
窗口大小没变，改变图表外层DOM宽度，图表不自适应宽度

### ISSUE THREAD

**Issue by fanguyun214** [alibaba/BizCharts#451]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
图表自适应是通过监听 window 的 resize 事件才触发的，所以你改外层容器的宽度，应该是没有触发 resize 事件吧。

方式1: 改了外层容器宽度后，自己触发一个 window 的 resize 事件。
方式2: 外层容器宽度改变后，修改下图表的宽度。
