### ISSUE TITLE
Bizcharts的通过DataSet加载数据。如果默认初始化显示值事没有问题的，如果通过异步加载获取的数据，怎么更新DataSet里的数据

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#453]
- bizcharts Version: 3.2.0
- Platform or react version: react version 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by liunian** [comment]
用 `source` 来加载数据就可以了

- demo：https://codepen.io/liunian/pen/GBzeqR
- 文档：http://bizcharts.net/products/bizCharts/api/dataset#dvsource
