### ISSUE TITLE
bizcharts 的x轴如何显示两个维度

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#454]
- bizcharts Version:  3.2.1-beta.2
- Platform or react version: react 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@DonChengCheng 
没明白你的意思，是指要两个 x 轴？
可以参考双 y 轴的 demo：
http://bizcharts.net/products/bizCharts/demo/detail?id=84&selectedKey=%E6%A6%82%E8%A7%88

**Comment by DonChengCheng** [comment]
<img width="898" alt="4bec9fe8-1060-44d5-92d8-cd2ba5b04aea" src="https://user-images.githubusercontent.com/17453366/44024124-05817f92-9f1f-11e8-9e45-bf60f7e39fab.png">这是x轴显示多维度的效果，看怎么实现

**Comment by weepy3641** [comment]
@DonChengCheng 
facet 可以了解一下
http://bizcharts.net/products/bizCharts/demo/detail?id=49&selectedKey=%E5%88%86%E9%9D%A2%E5%9B%BE

http://bizcharts.net/products/bizCharts/demo#%E5%88%86%E9%9D%A2%E5%9B%BE

本质上 facet 所实现的就是你要的效果，只是 x 轴放置的位置跟你的不一样，但可以调整。
或者你自己用 guide 实现也可以。

**Comment by DonChengCheng** [comment]
怎么调整facet上的x轴，达到我的效果呢？

**Comment by weepy3641** [comment]
http://www.bizcharts.net/products/bizCharts/api/facet#facet
facet 文档看下，axis colTitle rowTitle 位置、显示内容都可以调整。
