### ISSUE TITLE
Label textStyle callbacks not working

### ISSUE THREAD

**Issue by TheTimBecker** [alibaba/BizCharts#456]
- bizcharts Version: 3.1.8
- Platform or react version: 15.5.4
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/8620123/44118154-d4952034-9fda-11e8-8b8c-8796c0bb8248.png)
```
<Label content="value" textStyle={{
    fill: (value) => {
      if (value >= 5)
        return '#ff0000'; // red
      return '#00ff00'; // green
    }
  }}
/>
```
Labels should be red or green, not black.

- CodePen Link: https://codepen.io/TheTimBecker/pen/rrbXbb

- Documentation: https://github.com/alibaba/BizCharts/blob/master/doc/api/label.md#4textstyle----object-

**Comment by weepy3641** [comment]
@TheTimBecker 
Sorry, some mistakes in doc. the right code is:
```
      <Label 
        content="value"
        textStyle={val => {
          if(val >= 5)
            return {fill: '#ff0000'};
          return {fill: '#00ff00'};
        }}
        />
```
codepen: https://codepen.io/anon/pen/jpoWpz
