### ISSUE TITLE
how to hide all Legend

### ISSUE THREAD

**Issue by cuiyonghua** [alibaba/BizCharts#458]
- bizcharts Version: newest 

Hi , 
How to hide all data in Legend?  Is there any guide? Thanks.

**Comment by weepy3641** [comment]
@cuiyonghua 

set legend's selectedmode as  multiple.
http://bizcharts.net/products/bizCharts/api/legend#selectedmode

```
<Legend selectedmode="multiple" />
```

**Comment by cuiyonghua** [comment]
Thanks for your response, but maybe my question is not very clear. I want to know whether there is a solution to add a 'hide all' as the following picture, it's disabled default, when selected it all others two legend data will disappeared.  when any one legend data is selected, the 'hide all' will be set disabled.    
![image](https://user-images.githubusercontent.com/550030/44183687-88cd4b80-a13e-11e8-9a41-7a5932b8216e.png)

**Comment by weepy3641** [comment]
@cuiyonghua 
Use custom legend you can customize  the legend items and each item's operation。
see demo:
http://bizcharts.net/products/bizCharts/demo/detail?id=84&selectedKey=%E6%A6%82%E8%A7%88

**Comment by cuiyonghua** [comment]
Thanks for the guide, is there any consider added a default setting parameter in legend to support this feature?

**Comment by weepy3641** [comment]
No default setting to support it.
You must use custom legend.
