### ISSUE TITLE
热力图无数据的网格颜色问题

### ISSUE THREAD

**Issue by cuichuanteng** [alibaba/BizCharts#460]
- bizcharts Version:3.2.1-beta.2
- Platform or react version:16.4.2
- Mini Showcase(like screenshots):
1. 热力图中没有数据的颜色是是否可单独配置？
2. 热力图可以颜色可以使用回调函数设置但不能设置渐变色
3. 颜色配置的回调函数只给了一个数据的值作为参数，并不方便去指定某行某列的数据。
4. 我想实现的是有数据的按渐变映射颜色，没有数据的网格设置成灰白交替的风格，请问如何实现？

**Comment by weepy3641** [comment]
@cuichuanteng 
1、 热力图的数据的颜色可以单独配置， 直接使用 geom 的 color 属性即可。
http://bizcharts.net/products/bizCharts/api/geom#color
2、你说的设置渐变色是什么意思？没明白！
3、颜色 callback 指有数据作为参数。 
4、如果在没有数据的情况下，想要黑白交替，可以自己 mock 一组交替数据，然后根据数据值去配置颜色。

**Comment by cuichuanteng** [comment]
这里面不好发图，可以留个联系方式吗 发图沟通下，谢谢。

**Comment by cuichuanteng** [comment]
![image](https://user-images.githubusercontent.com/20423692/44248635-5dba2900-a21e-11e8-9521-85db63e3b2db.png)
![image](https://user-images.githubusercontent.com/20423692/44248642-67dc2780-a21e-11e8-98ca-e444ee0adfce.png)
1.如上图，第二张图没有数据部分是交替的颜色。
2. color: ['断刀数量', '#BAE7FF-#1890FF-#0050B3'] 这个是配置的颜色，没有值默认会显示第一个颜色值。 如果用回调函数来配置颜色需要对每个值进行计算对应的颜色值这个比较麻烦，是否可以让这个操作方便一些，比如回调函数return的值还是 '#BAE7FF-#1890FF-#0050B3'这种形式自动计算数值的颜色，如果return单色就设置单色，最好参数里面再给个当前是第几行几列，这样好指定某个单元格的色值。

**Comment by weepy3641** [comment]
暂时没有这样的支持计划。
