### ISSUE TITLE
label visible为false时依然能显示的BUG

### ISSUE THREAD

**Issue by cuichuanteng** [alibaba/BizCharts#461]
-bizcharts Version:3.2.1-beta.2
-Platform or react version:16.4.2
-Mini Showcase(like screenshots):
1. 做的实时波形图，X轴上不想显示label中的文字因此代码如下：
label: {
            visible:false,
            textStyle: {
                fontWeight: 'bold',
                fill: 'rgba(0,0,0,0)'
            }
        }
设置了visible为false但 刷新一段数据后就出现文字跳动，
只能设置颜色为透明才没能再显示出来

**Comment by weepy3641** [comment]
@cuichuanteng 
http://bizcharts.net/products/bizCharts/api/axis#label

axis label 如果不需要显示，请讲 label 的值配置为 false.
```
<Axis label={false} />
```
