### ISSUE TITLE
饼图Geom怎么设置默认选中某块饼图

### ISSUE THREAD

**Issue by mwb-27** [alibaba/BizCharts#464]
g2的Geom有个setSelected方法，bizCharts有类似的api吗？？？我希望在饼图刚画出来的时候就选中某块饼图。

**Comment by weepy3641** [comment]
相关问题解决 issue： https://github.com/alibaba/BizCharts/issues/188

**Comment by mwb-27** [comment]
@weepy3641 谢谢，搞定了
