### ISSUE TITLE
Legend 图例有很多，默认只想选中前3个图例

### ISSUE THREAD

**Issue by yucccc** [alibaba/BizCharts#465]
- bizcharts Version: 3.1.8
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

通过设置Chart 的filter 属性 回调会被执行很多次 因为数据通过dataset包装过， 如何拿到 index 进而默认只选中前3个？

**Comment by kreja** [comment]
先给个 demo

**Comment by yucccc** [comment]
没办法 最后通过filter 过滤 fields字段

**Comment by collinsyu** [comment]
求大神给个知道，我现在还不会，用filter会把全部数据都去掉，或者全都不去掉，不能去掉某一个legend

**Comment by z791483920** [comment]
这个如何在bizcharts如何实现 没找到·····echarts 倒是有这个api

**Comment by yucccc** [comment]
<Chart 
   filter={[['过滤的字段', (val) => 返回需要选中的legend  ]] }
>
如果你需要切换数据更新图表 那么你可能还需要每次在 componentDidUpdate 执行 this.chart.filter('city', (val) => 返回选中 )

确实很不人性....
我是这么解决的
filter 函数会被执行n次....
@z791483920

**Comment by z791483920** [comment]
我也找到了这个···一开始没仔细看文档
@yucccc 感谢
