### ISSUE TITLE
g2Chart.showTooltip doesn't  work

### ISSUE THREAD

**Issue by caolinjian** [alibaba/BizCharts#467]
- bizcharts Version: 3.2.0
- Platform or react version: 16.3.1

bizcharts Version 3.1.8 was work

**Comment by kreja** [comment]
3.1.8 是这样用吗？这里也不能出现 tooltip，可能这个属性已经去掉了，我跟开发确认下

![image](https://user-images.githubusercontent.com/7478555/44375612-2356d180-a527-11e8-9360-24454c962847.png)

**Comment by caolinjian** [comment]
不是这个，，chart上没有这个属性的，你用tooltip的直接创建<tooltip/>。
我说的是拿到chart的实例后去掉showTooltip(point)的方法。这个方法3.2.0仍然存在的，但是没效果出来，应该是bug了。

**Comment by kreja** [comment]
有的呢，跟传入 showTooltip 的 x y 有关，应该是内部计算过的，有些位置不会出现 tooltip

![image](https://user-images.githubusercontent.com/7478555/44376301-6fefdc00-a52a-11e8-92d3-ee6ccdd28727.png)
不会出现
![image](https://user-images.githubusercontent.com/7478555/44376355-b34a4a80-a52a-11e8-8e10-d04d0e20ca30.png)

**Comment by caolinjian** [comment]
我是先赋值出来，然后很多坐标都试过，出不来啊
`onGetG2Instance={(g2Chart) => {
           this.g2Chart = g2Chart;
          }}`
`this.g2Chart.showTooltip({ x, y });`
换成3.1.8就没毛病了，，，
话说我在3.1.8下又遇到了新问题。
我一个页面加载两个chart后
我hover在前面一个，结果后面的生效，，，
我看看能不能去codepen写下例子

**Comment by caolinjian** [comment]
https://codepen.io/caolinjian/pen/mGdYVg
没找到3.2.0的cdn地址，，这个是3.1.5下的代码，这里是没问题的。你换成3.2.0的试试

**Comment by kreja** [comment]
https://codepen.io/kreja/pen/mGyXvd

3.2.0 这个也有 tooltip 显示的哇
![image](https://user-images.githubusercontent.com/7478555/44438345-52d21080-a5f1-11e8-926a-a29867ed7c3a.png)
