### ISSUE TITLE
建议在Lable绘图属性中增加超出文本换行，显示省略号的属性

### ISSUE THREAD

**Issue by z784324922** [alibaba/BizCharts#468]
![default](https://user-images.githubusercontent.com/31068244/44325437-62cfe000-a48b-11e8-8527-052d081cc478.png)

**Comment by z784324922** [comment]
在treemap中超出文显示，会导致很多文字重叠， 看起来有点头晕

**Comment by preservance717** [comment]
那在矩形关系图中每个块的大小不一致，怎么设置一个合适的宽度呢
