### ISSUE TITLE
How do you invert the axis from increasing to decreasing on the y-axis

### ISSUE THREAD

**Issue by kankyu** [alibaba/BizCharts#471]
- bizcharts Version:
3.2.2
- Platform or react version:
16.4.2

Rather than having a increasing y-axis, I want it decreasing.

basic line plot:
```
  <Chart height={400} data={data} scale={cols} forceFit>
    <Axis name="year" />
    <Axis name="value" />
    <Tooltip crosshairs={{type : "y"}}/>
    <Geom type="line" position="year*value" size={2} />
    <Geom type='point' position="year*value" size={4} shape={'circle'} />
```

**Comment by kreja** [comment]
try reflect
https://bizcharts.alibaba-inc.com/products/bizCharts/api/coord#reflect
![image](https://user-images.githubusercontent.com/7478555/44398089-31334380-a575-11e8-9db0-325d78020675.png)

**Comment by kankyu** [comment]
This works great thanks :)
