### ISSUE TITLE
如何获取饼图的颜色值啊

### ISSUE THREAD

**Issue by dongkang1993** [alibaba/BizCharts#472]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
如何获取饼图的颜色值啊

**Comment by kreja** [comment]
什么情况下获取饼图的什么颜色，请描述完整

**Comment by dongkang1993** [comment]
默认主题色下，Piechart使用<Geom  @color='cut'/>完成行数据值到颜色值的映射；想在PieChart之外根据数值得到对应的颜色 @kreja

**Comment by kreja** [comment]
你可以自己设一套颜色，就不用根据数据去取颜色了
https://antv.alipay.com/zh-cn/g2/3.x/api/geom.html#_color

![image](https://user-images.githubusercontent.com/7478555/44461793-d23cff80-a644-11e8-93eb-aa0273823747.png)
