### ISSUE TITLE
按需加载 报错

### ISSUE THREAD

**Issue by pxzsl** [alibaba/BizCharts#473]
- bizcharts Version: 3.2.2
- Platform or react version: 16.4.2

使用和官网一样的代码（http://bizcharts.net/products/bizCharts/docs/needload#%E4%BD%BF%E7%94%A8-demo），但是报错

`
Warning: Failed prop type: The prop `height` is marked as required in `PureChart`, but its value is `undefined`.
`
如果把 `<Axis />` 删掉就不报错了

**Comment by weepy3641** [comment]
@pxzsl 
不好意思，官网代码 axis 处有一点书写错误，正确的如下：


```
//正确写法：
import Axis from 'bizcharts/lib/components/Axis';

//旧的错误写法：
import Axis from 'bizcharts/lib/components/Chart';
```

文档下个版本会更新。
