### ISSUE TITLE
请问如何实现鼠标移入一个指定的图形，其他的图形全部隐藏？

### ISSUE THREAD

**Issue by windSandEye** [alibaba/BizCharts#474]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by kreja** [comment]
鼠标移入一个指定的图形 用 Mouseenter 事件 http://bizcharts.net/products/bizCharts/api/chart#%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%E4%BA%8B%E4%BB%B6

隐藏图形，过滤掉对应的字段 http://bizcharts.net/products/bizCharts/api/chart#filter
