### ISSUE TITLE
图形元素事件未响应

### ISSUE THREAD

**Issue by windSandEye** [alibaba/BizCharts#476]
我使用和旋图组件做了一个例子，现在想要鼠标移入某一部分边时，只显示当前边和连接线，其他的透明，鼠标移入某条连接线时，只显示该连接线和对应的边。
有这个需求的原因是：目前bizcharts中的图像虽然做了高亮显示，但是相比于本身的图形并不明显，这导致我们想看到的数据不能突显出来，希望你们能够关注这一点，对于越复杂的图形来说，只是tooltip的提示是远远不够的，能够让用户更直观的看到想要看的的东西，才是可视化的目的。

看了官方文档，你们提出有图形事件，所以我尝试使用onEdageMousemove，但是毫无效果，该事件并未触发。代码如下：
`<Chart
                    data={data}
                    forceFit={true}
                    height={window.innerHeight}
                    scale={scale}
                    onGetG2Instance={this.initChart.bind(this)}
                    onEdageMousemove={this.protrudeItem.bind(this)}
                >`
请问：是我的写法有误，还是其他原因造成的。

**Comment by kreja** [comment]
应该是 onEdgeMousemove，文档拼写有误会改一下
