### ISSUE TITLE
bizcharts-plugin-slider 导航条不能正常缩放，只能左右移动，显示相同宽度的数据

### ISSUE THREAD

**Issue by zhaodongxx** [alibaba/BizCharts#477]
- bizcharts Version: 3.2.1-beta.2
- Platform or react version: 
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by zhaodongxx** [comment]
@kreja 你好

当我把
`bizcharts` 的版本从 `3.2.1-beta.2` 回退到 `3.1.5`,
`bizcharts-plugin-slider` 版本回退到 `2.0.0`后，问题得到了一定的解决：
      
    现在可以缩放一次Slider滚动条，但是缩放一次后，Slider左右两侧的拖动图标和左右两侧的数字就会消失，只能作平行移动。

因时间关系，我会尽量在今天晚上po出demo。

**Comment by XionGuo37** [comment]
我今天也动了版本，也出现这个问题，请问你解决了吗？

**Comment by Leslie2014** [comment]
已经确认了问题的存在，我们已经在修复中。

**Comment by Leslie2014** [comment]
^2.0.7

**Comment by zhaodongxx** [comment]
@Leslie2014 

修改到如下版本，问题依然存在
- "bizcharts": "^3.2.2"
- "bizcharts-plugin-slider":"^2.0.7"
