### ISSUE TITLE
onPolygonMouseleave事件并未触发

### ISSUE THREAD

**Issue by windSandEye** [alibaba/BizCharts#478]
我想使用onPolygonMousemove、onPolygonMouseleave这一对组合事件，当鼠标在Polygon上时执行一种效果，当鼠标离开Polygon时执行另一种效果，但是onPolygonMousemove始终触发，onPolygonMouseleave从未触发，什么原因导致的？

**Comment by kreja** [comment]
你好，这里可以正常触发事件 https://codepen.io/kreja/pen/xawYqd
![image](https://user-images.githubusercontent.com/7478555/44568009-73dc6200-a7a7-11e8-9839-d940d7f699e8.png)
