### ISSUE TITLE
堆叠柱状图type: linear 显示异常

### ISSUE THREAD

**Issue by yucccc** [alibaba/BizCharts#479]
- bizcharts Version: 3.1.8
- Platform or react version: 16.x
- Mini Showcase(like screenshots):
- CodePen Link: https://codepen.io/yucccc/pen/OoyvvN?editors=0010
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

如demo所示  当后端返回数据为string时 增加type= linear 图表不能正常显示

**Comment by kreja** [comment]
如果是数字的话需要先处理成数字类型

**Comment by yucccc** [comment]
如果最终显示需要保留两位小数 通过toFixed会变成string 那也会有问题的

**Comment by kreja** [comment]
可以先转成数字，最终显示在显示的时候再处理，通过:
http://bizcharts.net/products/bizCharts/api/scale#formatter
http://bizcharts.net/products/bizCharts/api/label#formatter
