### ISSUE TITLE
多VIew图表时 图例不会自动换行

### ISSUE THREAD

**Issue by Clish** [alibaba/BizCharts#48]
Chart内嵌套多个View时, legend自动换行功能失效

**Comment by weepy3641** [comment]
这是 G2 的问题，目前 G2 不支持 legend 自动换行。
你可以用 html 去自定义，然后改 css 配置让他自动换行。

**Comment by Clish** [comment]
试了很多方法都不太友好, 目前只能先自定义处理. 待我去 G2提个 Issue...
