### ISSUE TITLE
请问一下BizCharts支持折线柱状图吗

### ISSUE THREAD

**Issue by shenzekun** [alibaba/BizCharts#483]
- bizcharts Version: 3.2.2
- Platform or react version: 16.3.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@shenzekun 
支持的，柱状图 demo 看一下！
http://bizcharts.net/products/bizCharts/demo#%E6%9F%B1%E7%8A%B6%E5%9B%BE

**Comment by shenzekun** [comment]
@weepy3641 说错了是折线柱状图 像这样的 
![image](https://user-images.githubusercontent.com/21151080/44696405-03d12300-aaaa-11e8-866f-572a6f8b6692.png)

**Comment by shenzekun** [comment]
像Echarts 是有折线柱状图的 如下
![image](https://user-images.githubusercontent.com/21151080/44696671-15ff9100-aaab-11e8-85e5-9c94522206ac.png)

**Comment by weepy3641** [comment]
http://bizcharts.net/products/bizCharts/demo/detail?id=84&selectedKey=%E6%A6%82%E8%A7%88

**Comment by shenzekun** [comment]
@weepy3641  非常感谢：）
