### ISSUE TITLE
facet分面图 其中一个图更改x轴

### ISSUE THREAD

**Issue by dearpeach** [alibaba/BizCharts#487]
- bizcharts Version: 3.1.10
- Platform or react version: 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
使用分面图，x轴是时间，但是分面图中的一个图我想要使用另外一个变量作为x轴，类型也是时间，该怎样实现呢？

**Comment by weepy3641** [comment]
@dearpeach 
可以用 eachView 传入 callback 函数去定制，参考demo：
http://bizcharts.net/products/bizCharts/demo/detail?id=52&selectedKey=%E5%88%86%E9%9D%A2%E5%9B%BE
