### ISSUE TITLE
RegionFilter添加后上方Legend不显示的bug

### ISSUE THREAD

**Issue by zhenpengfei** [alibaba/BizCharts#488]
- bizcharts Version:^3.2.1-beta.2
- Platform or react version:16.3.16
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/27199755/44713043-d2297d80-aae4-11e8-8896-b77150bce158.png)
![image](https://user-images.githubusercontent.com/27199755/44713093-f2f1d300-aae4-11e8-950e-1fefc7eab38a.png)

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
当使用RegionFilter时 Tooltip 设置position=“top” 后Legend不显示 
设置position="bottom” Legend显示

**Comment by weepy3641** [comment]
https://github.com/antvis/g2/issues/842

**Comment by weepy3641** [comment]
新版本已经解决。
