### ISSUE TITLE
Geom tooltip怎么显示非图表的信息

### ISSUE THREAD

**Issue by shuaidiao** [alibaba/BizCharts#489]
- bizcharts Version:"3.1.0"
- Platform or react version:"16.4.1"
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/42376214/44721231-cf865280-aafb-11e8-9494-814def51500c.png)
![image](https://user-images.githubusercontent.com/42376214/44721396-5a674d00-aafc-11e8-8894-8861062db635.png)

现在只显示一条折线图，但是我还想要在tooltip里面显示其他的信息（跟多条折线显示的信息一样，或者其他自己想要显示的信息），怎么实现？

**Comment by weepy3641** [comment]
@shuaidiao 
相关 issue 
https://github.com/alibaba/BizCharts/issues/413
https://github.com/alibaba/BizCharts/issues/118
https://github.com/alibaba/BizCharts/issues/138
