### ISSUE TITLE
Slider 插件的包的 main 字段有大小写问题

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#49]
导致引用失败：`Module not found`

https://github.com/alibaba/BizCharts/blob/slider/plugin/slider/package.json#L5

![image](https://user-images.githubusercontent.com/1179603/34087743-1be921cc-e3e0-11e7-80ce-821d97161490.png)

**Comment by weepy3641** [comment]
好的，多谢提出。
下个版本会修复。

**Comment by weepy3641** [comment]
bizcharts-plugin-slider@2.0.0  版本修复了。

**Comment by nikogu** [comment]
@weepy3641 记得更新文档

**Comment by weepy3641** [comment]
@nikogu  已经更新～～
