### ISSUE TITLE
环形图怎么添加辅助线

### ISSUE THREAD

**Issue by Mapperka** [alibaba/BizCharts#490]
在环形上添加一条线

![qq 20180829114755](https://user-images.githubusercontent.com/37919239/44764274-77922f00-ab81-11e8-93f5-6e8250c93361.png)

在上面添加一条表示室温的线

**Comment by weepy3641** [comment]
@Mapperka 
可以使用 guide 组件
http://bizcharts.net/products/bizCharts/api/guide

**Comment by Mapperka** [comment]
@weepy3641  start 和 end 怎么取

**Comment by weepy3641** [comment]
@Mapperka 
看下位置值说明。可以是百分比、数据等。
http://bizcharts.net/products/bizCharts/api/guide#%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E

**Comment by Mapperka** [comment]
@weepy3641 我是看来文档弄不出来才来问的

**Comment by weepy3641** [comment]
@Mapperka  
我也艰难的加了跟线： https://codepen.io/anon/pen/WgRodj?editors=0010
你具体想要画什么样的线，能否详细说明。

**Comment by Mapperka** [comment]
@weepy3641 
![inkedqq 20180829114755_li](https://user-images.githubusercontent.com/37919239/44965755-f2848c80-af69-11e8-85d0-29769725a639.jpg)
像这样的 只在环形上有

**Comment by weepy3641** [comment]
@Mapperka 
https://codepen.io/anon/pen/YOxPvp
