### ISSUE TITLE
guide里的Text怎么动态添加content？？

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#491]
content只能接受字符串，而用react里的setState又会造成死循环，没有办法动态改变content吗？？

**Comment by weepy3641** [comment]
@houzip 
为什么会死循环，能否贴个 demo。

**Comment by houzip** [comment]
react 在render中调用setState就会死循环。。。

**Comment by houzip** [comment]
@weepy3641 react 在render中调用setState就会死循环。。。

**Comment by houzip** [comment]
@weepy3641 是这样的 我想要动态展示 烛型图最高点的数据 DataMarker的position接受function 我就想这个function中setState了 就会造成死循环

**Comment by weepy3641** [comment]
1、为什么会在 datamarker 的 position callback 中去设置 state 来改变 datamarker 的 content ，这种逻辑是否正常。
2、在 callback 中可以使用 timeout 避开死循环。

**Comment by houzip** [comment]
@weepy3641 我想动态改变content 只有在position的callback中才能获得当前数据值，content是不是也应该可以接收function 可以动态的展示当前的数据

**Comment by weepy3641** [comment]
@houzip 
datamarker content 不支持函数以及动态数据，如果需要，需要 g2 支持，可以去 g2 github 提个 issue。 
暂时可以考虑用geom 中 label 来满足你的需求：
http://bizcharts.net/products/bizCharts/api/label
