### ISSUE TITLE
parsePoints方法转值会把点转成相同的坐标值

### ISSUE THREAD

**Issue by z54749412** [alibaba/BizCharts#492]
在多色仪表盘中绘制多边形，使用parsePoints方法转坐标会把多个点转成相同的坐标，导致绘不出正常的多边形，`const points = this.parsePoints(cfg.points);` 
![default](https://user-images.githubusercontent.com/29242214/44770715-7b32af80-ab9b-11e8-9b14-2734f86f022f.png)

codepen Demo: https://codepen.io/anon/pen/rZMeYR?editors=0010

**Comment by weepy3641** [comment]
@z54749412 
demo 中什么地方绘制不正确？

**Comment by z54749412** [comment]
demo中绘制正确，但是如果是本地开发环境就会出问题

**Comment by z54749412** [comment]
@weepy3641 codepen 中的demo正常的效果，但是本地开发的话，就如那个截图一样，他会吧points[0] 和 points[2]的坐标转成一个，这样就绘不出任何图形了

**Comment by liunian** [comment]
@z54749412 如果能提供一下可重现的最小代码，我们看一下

**Comment by z54749412** [comment]
@liunian 好的，，我去找一下。我们的这个项目也很久没维护了

**Comment by z54749412** [comment]
@liunian 你把https://codepen.io/anon/pen/rZMeYR?editors=0010这里面的代码复制到项目就浮现了，，在web 看不出，开发环境那个方法会把返回的坐标都转成同一个，我在钉钉给他们演示过，他们让我过来提个issue。

**Comment by z54749412** [comment]
@liunian 这个问题就是如果用你们build好的 js 通过 cdn 引入的话就没有任何问题，，如果是本地开发用开发文件，那个方法会把坐标转错，导致没办法绘制出图形，你把上面codepen 中的代码复制到本地环境 再跑下 就可以复现问题的

**Comment by z54749412** [comment]
-。-看了这么久没回复，就是我现在的代码在codepen 和本地包上运行出来的展示结果 不一样，你可以把codepen 中的代码复制到本地开发环境试一下就懂了，
