### ISSUE TITLE
【使用帮助】Guide-Line：图表的辅助线条如何设置为实线

### ISSUE THREAD

**Issue by zhaodongxx** [alibaba/BizCharts#494]
- bizcharts Version: 3.2.2

> 【使用帮助】Guide-Line：图表的辅助线条如何设置为实线

**Comment by weepy3641** [comment]
```
<Line lineStyle={{lineDash: null}} />
```

**Comment by lahvey** [comment]
@weepy3641 为什么设置虚线辅助线的时候偶尔出现实线，例如：
https://codepen.io/anon/pen/QJjwXr?editors=0010
在08:00的位置出现了实线，把tickInterval改动一下就好了...
