### ISSUE TITLE
Legend 自定义点击事件

### ISSUE THREAD

**Issue by shuaidiao** [alibaba/BizCharts#495]
bizcharts Version:"3.1.0"
Platform or react version:"16.4.1"
- Mini Showcase(like screenshots):
- CodePen Link:

加了<Legend />之后，图表的图例会显示，并且点击某一个图例，图表中对应的折线会消失，如果加了onClick(ev=>{})事件之后，点击图例后图表对应的折线就不会消失了，我想让它消失，怎么处理

**Comment by weepy3641** [comment]
@shuaidiao 
demo 参考 
http://bizcharts.net/products/bizCharts/demo/detail?id=84&selectedKey=%E6%A6%82%E8%A7%88

**Comment by ht1131589588** [comment]
@weepy3641 如果柱状图是分组柱状图呢？怎么自定义点击？

**Comment by ht1131589588** [comment]
![oelm f 3 e4i xuuc7 ty](https://user-images.githubusercontent.com/24310479/47280428-0151fc00-d609-11e8-9d76-9a771f5b7ba2.png)

**Comment by weepy3641** [comment]
@ht1131589588 

demo 链接
https://codepen.io/anon/pen/MPRmqR
