### ISSUE TITLE
请问如何一次性画7000多个坐标点后，可以不卡。

### ISSUE THREAD

**Issue by sundayha** [alibaba/BizCharts#499]
- bizcharts Version: 3.2.2
- Platform or react version: 16.3.2
一次性画7000多个坐标点后很卡，请问有没有什么好的办法可以解决

**Comment by weepy3641** [comment]
@sundayha 
跟 g2 的人聊了下，散点图的极限大概在 5000 左右，暂时 g2 底层没有优化方案透出。
你的散点图是不是用默认的 圆形 画的？
建议将散点图 shape 改为 square， 性能会好很多。

**Comment by sundayha** [comment]
@weepy3641 多谢，我试试。😉
