### ISSUE TITLE
ticks 指定失效

### ISSUE THREAD

**Issue by wb-tyz279201** [alibaba/BizCharts#500]
- bizcharts Version:3.2.2
- Platform or react version:16.4.0
- Mini Showcase(like screenshots):
- CodePen Link:https://riddle.alibaba-inc.com/riddles/3a850a50
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
https://github.com/antvis/g2/issues/873
g2 bug

**Comment by ironicstone** [comment]
升级最新版本即可
