### ISSUE TITLE
我想详细了解箱型图的数据是如何计算得来的

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#502]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ssfxz** [comment]
箱线图的数据一般有5个统计量，分别是最小值、第一四分位数、中位数、第三四分位数、和最大值。
注意5个值对应的是同一条数据，其实这5条数据是通过更细一级维度的数据统计而来的。

以每年12个月的降雨量举例，原本应该有12条数据，
然而如果使用箱线图的话，则需要更细一级维度的数据，例如日降雨量，而每月的5条统计数据则由该月的降雨量统计得出。

这5个统计量分布中，四分位数的概念就是将数据**顺序排列**，出现在25%、50%、75%**位置**的数据即为四分位数，同时第二四分位数其实也就是中位数。
例如：有升序数列 [ 1，3，3，4，5，7，9 ]
其四分位数分别为：(3+3)/2=3，4，(5+7)/2=6

事实上对于一些日常事件，假设使用生态分布来描述其事件分布特征，则可以通过这5个统计量建立该分布的具体模型。

然而假如数列中存在过于异常的数据，则会影响分布数据的表达，因此通常使用一些异常点检测算法来将异常点从数列中剔除，异常点检测算法有很多种，统计学上通常使用95%的置信区间来判断是否采用该结论。结合业务场景采用合适的异常点检测方式有利于提高模型精度。

参考链接：https://zh.wikipedia.org/zh-hans/%E7%AE%B1%E5%BD%A2%E5%9C%96
