### ISSUE TITLE
我想进一步的了解canvas的transform和scale

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#503]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ssfxz** [comment]
canvas的scale()用于在x,y方向上对图形进行缩放
使用方法：
const ctx=c.getContext("2d");
ctx.scale(2,2);
参考：http://www.w3school.com.cn/tags/canvas_scale.asp

transform()方法可以对canvas进行矩阵变换，同样也可实现缩放
ctx.transform(2, 0, 0, 2, 0, 0);
参考：http://www.w3school.com.cn/tags/canvas_transform.asp
