### ISSUE TITLE
x轴坐标可否支持a.b.c这种格式的？

### ISSUE THREAD

**Issue by plainnany** [alibaba/BizCharts#504]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

比如我的一组数据是这样的
```
const data = [
        { ds: {date: '2018/8/1'}, Tokyo: 7.0, London: 3.9 },
        { ds: {date: '2018/8/2'}, Tokyo: 6.9, London: 4.2 },
        { ds: {date: '2018/8/3'}, Tokyo: 9.5, London: 5.7 },
        { ds: {date: '2018/8/4'}, Tokyo: 14.5, London: 8.5 },
        { ds: {date: '2018/8/5'}, Tokyo: 18.4, London: 11.9 }
      ];
 
```
现在绘制两条折线图，横坐标是以每一个item的ds.date 来显示的，有什么方法么？查了文档和issue都没找到解决方法，对bizchart还不太熟悉，有哪位大神可以说一下怎么解决么？

[codepen链接](https://codepen.io/plainnany/pen/qMmJJK)

**Comment by weepy3641** [comment]
@plainnany 
1、 自己对数据处理下，将 ds 中 date 数据提出来，跟 tokyo，london 平级。
2、如果自己不想处理，可以使用 transform 将数据 map 下。
http://bizcharts.net/products/bizCharts/api/transform#map-%E6%95%B0%E6%8D%AE%E5%8A%A0%E5%B7%A5

**Comment by plainnany** [comment]
好的，多谢
