### ISSUE TITLE
如何让双折线图一条折线一条虚线，并且能够定义其中一条的label显示

### ISSUE THREAD

**Issue by shenzekun** [alibaba/BizCharts#505]
- bizcharts Version: 3.1.10
- Platform or react version:16.4.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

示例图如下：
![image](https://user-images.githubusercontent.com/21151080/45008596-16ad9f80-b036-11e8-88a0-85eb4c91ebcb.png)

目前参照http://bizcharts.net/products/bizCharts/demo/detail?id=450&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE 写法，但是没办法定义一条折线一条虚线和定义其中一条的label显示，请问有其他方法实现如何双折线图一条折线一条虚线，并且能够定义其中一条的label显示吗？

**Comment by weepy3641** [comment]
@shenzekun 
1、配置下 geom 的 shape，可以解决实线、虚线问题。
http://bizcharts.net/products/bizCharts/api/geom#shape
http://bizcharts.net/products/bizCharts/docs/chartType#%E5%9B%BE%E8%A1%A8%E7%B1%BB%E5%9E%8B%E5%92%8C%E5%9B%BE%E5%BD%A2%E5%BD%A2%E7%8A%B6

2、label 的 format 可以传函数，判断下如果是虚线的数据，直接返回空字符串。
http://bizcharts.net/products/bizCharts/api/label#formatter

**Comment by bibiehy** [comment]
@weepy3641 折线图上，怎么设置一段用实线，一段用虚线呢，用于0~24小时制的实时数据
