### ISSUE TITLE
折线图x轴显示不完全

### ISSUE THREAD

**Issue by plainnany** [alibaba/BizCharts#506]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

数据为
```
const data = []
    for(var i=0; i< 10;i++){
      data.push({
        Tokyo: parseInt(Math.random()*100),
        London: parseInt(Math.random()*100),
        month: i
      })
    } 
```

发现横坐标只显示month是偶数的，没有全部显示，请问是什么问题呢？[链接](https://codepen.io/plainnany/pen/zJwyqg)

**Comment by weepy3641** [comment]
@plainnany 
自动布局算法会计算出比较适合的刻度个数。如果想要全部显示，配置下 scale 中的 tickCount。
```
      const cols = {
        month: {
          range: [ 0, 1 ],
          tickCount: 10
        }
      }
```

**Comment by bengle** [comment]
@weepy3641 图标数据不确定的情况怎么办呢？不能每次改这个tickCount吧？

**Comment by heyguo** [comment]
const scale = {
      date: {
        type: 'cat',
        alias:'日期',
      }
    };
把type设置成cat
