### ISSUE TITLE
2个以上的Y轴会重叠，如何设置偏移量？

### ISSUE THREAD

**Issue by ztz1234567** [alibaba/BizCharts#507]
2个以上的Y轴会重叠，如何设置偏移量？
![image](https://user-images.githubusercontent.com/32659023/45012069-34840000-b048-11e8-832f-d57a1bacb8ac.png)

**Comment by ztz1234567** [comment]
其中一个Axis:
<Axis
                                        line={{
                                            stroke: "#000"
                                        }}
                                        tickLine={{
                                            stroke: "#000",
                                            value: 6 // 刻度线长度
                                        }}
                                        name="people"
                                        position="right"
                                        label={{
                                            textStyle: {
                                                fill: "#ffae6b",
                                                textAlign: "start"
                                            }
                                        }}
                                    />

**Comment by weepy3641** [comment]
@ztz1234567 
轴上面 label 的 offset 配置下。
http://bizcharts.net/products/bizCharts/api/axis#label

**Comment by ztz1234567** [comment]
这个只是让Y轴的数值偏移，Y轴线并没有偏移

**Comment by ztz1234567** [comment]
![image](https://user-images.githubusercontent.com/32659023/45138225-44354d00-b1de-11e8-80a7-26beb6f3291a.png)
zis紫色和橙色叠加在一起了。

**Comment by ztz1234567** [comment]
![image](https://user-images.githubusercontent.com/32659023/45138321-91192380-b1de-11e8-82d7-8cbdbf359f71.png)
数值偏移了 但是Y轴线被紫色覆盖了

**Comment by weepy3641** [comment]
@ztz1234567 
g2 轴线并不提供偏移的配置项，你可以选择将紫色的线隐藏掉。
http://bizcharts.net/products/bizCharts/api/axis#line

**Comment by ztz1234567** [comment]
好的 谢谢了
