### ISSUE TITLE
怎么在nextjs项目中用bizcharts

### ISSUE THREAD

**Issue by liumlbzx** [alibaba/BizCharts#508]
import { Chart, Axis, Tooltip, Geom } from "bizcharts";
引用这个就报document is not defined 是不是只能用回G2了

**Comment by weepy3641** [comment]
参考下业界 nextjs 的使用。
https://github.com/zeit/next.js/issues/2528
https://github.com/zeit/next.js/issues/1639

**Comment by liumlbzx** [comment]
https://github.com/antvis/g2/issues/296
