### ISSUE TITLE
三个Y轴支持么？

### ISSUE THREAD

**Issue by ceasor** [alibaba/BizCharts#509]
我发现当我将轴都放在左边，轴都重叠在一起了，怎么布局这些轴？
![image](https://user-images.githubusercontent.com/23649217/45149796-f7ad3a00-b1fc-11e8-8b72-804f04bba5d2.png)

**Comment by weepy3641** [comment]
@ceasor 
1、可以通过 axis 中 label 的 offset 调整 y 轴的布局。
http://bizcharts.net/products/bizCharts/api/axis#label
2、 为何一个图表中有三根 y 轴，这样的图表实际很不易于查看，并不推荐使用。

**Comment by ceasor** [comment]
实际上工程中 观察多个物理量的变化是十分常见的需求。

**Comment by weepy3641** [comment]
@ceasor  
好的，你们能看懂就行。

**Comment by ceasor** [comment]
搞定了，截张图，表示感谢
![image](https://user-images.githubusercontent.com/23649217/45404061-0037c180-b690-11e8-9d16-7f2ae576d48e.png)

**Comment by panlw** [comment]
@ceasor 怎么实现的，能分享一下关键配置吗？

**Comment by guangming21** [comment]
@ceasor 这是3个曲线，如果是10个曲线呢，坐标轴就把屏幕占满了
