### ISSUE TITLE
如何让 Axis 支持超链接点击并且用react 写超链接？

### ISSUE THREAD

**Issue by shenzekun** [alibaba/BizCharts#511]
- bizcharts Version:3.1.10
- Platform or react version: 16.4.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

目前查看Axis 的文档有个htmlTemplate ，但是目前并不支持react写超链接，请问如何用react写超链接呢

**Comment by shenzekun** [comment]
@weepy3641 没法支持react写法的

**Comment by weepy3641** [comment]
@shenzekun 
htmlTemplate  暂时不支持 react 写法， 需要等到 3.3.x 的版本，还在排期。

**Comment by shenzekun** [comment]
@weepy3641 好的

**Comment by fay04** [comment]
@weepy3641 已经3.3.6版本了
