### ISSUE TITLE
使用'bizcharts-plugin-slider'后，数据集结束日期这样设置，chart上就看不到最后一天的数据了

### ISSUE THREAD

**Issue by bibiehy** [alibaba/BizCharts#512]
"bizcharts": "^3.2.2",
"bizcharts-plugin-slider": "^2.0.7",
"@antv/data-set": "^0.9.0",
"react": "^16.3.2",

我的数据源 dataSource 里面的日期格式： date: '2018-08-01'
假如最后一天是 date: '2018-08-12'，
在创建数据集 new DataSet() 开始日期: '2018-08-01'， 结束日期: '2018-08-12'
而我在Slider上想看到时分，设置 mask:'M/DD H:mm'
**运行，这时可以看到slider上开始和结束时间默认为 8/01 8:00 和 8/12 8:00
当我直接拖动slider中间，我就再也看不到 12 号的数据了**

**还一个问题，我在 5 号日期上加了一个特殊标注，当我在slider上选择 2-5号时间段，拖动时候，标注自动跑偏。**

代码如下，
import React from 'react';
import { Chart, Geom, Axis, Tooltip, Legend, Guide } from 'bizcharts';
import { DataSet } from '@antv/data-set';
import Slider from 'bizcharts-plugin-slider';

const { DataMarker, Line } = Guide;

const  ChartSpline = () => {
    //
    const dataSource = [
        { id: 1, uv: 4000, pv: 2400, amt: 1400, date: '2018-08-01' },
        { id: 2, uv: 3000, pv: 1398, amt: 210, date: '2018-08-02' },
        { id: 3, uv: 2000, pv: 9800, amt: 6290, date: '2018-08-03' },
        { id: 4, uv: 2780, pv: 3908, amt: 2000, date: '2018-08-04' },
        { id: 5, uv: 1890, pv: 4800, amt: 6181, date: '2018-08-05' },
        { id: 6, uv: 2390, pv: 3800, amt: 7500, date: '2018-08-06' },
        { id: 7, uv: 3490, pv: 4300, amt: 2900, date: '2018-08-07' },
        { id: 8, uv: 2000, pv: 9800, amt: 5290, date: '2018-08-08' },
        { id: 9, uv: 2780, pv: 3908, amt: 1000, date: '2018-08-09' },
        { id: 10, uv: 1890, pv: 4800, amt: 9181, date: '2018-08-10' },
        { id: 11, uv: 2390, pv: 3800, amt: 2500, date: '2018-08-11' },
        { id: 12, uv: 3490, pv: 4300, amt: 6100, date: '2018-08-12' },
    ];

    const startDate = '2018-08-01', endDate = '2018-08-12';

    const ds = new DataSet({ // 数据集
        state: {
            start: new Date(startDate).getTime(),
            end: new Date(endDate).getTime()
        }
    });

    // slider 数据集
    const sliderDv = ds.createView('slider').source(dataSource);
    sliderDv.transform({
        type: 'fold',
        fields: ['uv', 'pv'], // 展开字段集
        key: 'itemkey', // key字段 - 合集的属性
        value: 'itemval', // value字段 - 合集属性的值
    });

    // chart 数据集
    const chartDv = ds.createView('chart').source(dataSource);
    chartDv.transform({
        type: 'fold',
        fields: ['uv', 'pv'], // 展开字段集
        key: 'itemkey', // key字段 - 合集的属性
        value: 'itemval', // value字段 - 合集属性的值
    }).transform({
        type: 'filter',
        callback(obj) {
            const time = new Date(obj['date']).getTime(); // 转换为时间戳进行比较
            return time >= ds.state.start && time <= ds.state.end;
        }
    });

    const chartOptions = {
        padding: [100, 100],
        forceFit: true,
        height: 400,
        data: chartDv,
        scale: {
            date: {
                type: 'time',
            }
        }
    }

    const onChangeSlider = (obj) => {
        const { startValue, endValue } = obj;
        ds.setState('start', new Date(startValue).getTime());
        ds.setState('end', new Date(endValue).getTime());
    }

    return (
        <React.Fragment>
            <Chart {...chartOptions}>
                <Legend marker="circle" />
                <Axis name="date" />
                <Axis name="itemval" />
                <Tooltip crosshairs={{type: 'y'}} />
                <Geom
                    type="line"
                    position={'date*itemval'}
                    size={2}
                    color={'itemkey'}
                    shape={'smooth'}
                />
                <Guide>
                    <DataMarker
                        key="2018-08-05"
                        position={["2018-08-05", 0]}
                        display={{ point: true }}
                        style={{
                            point: { stroke: '#fff', shadowColor: '#a33131', shadowBlur: 3, opacity: 1, lineWidth: 1, fill: '#a33131' }
                        }}
                        lineLength={10}
                    />
                </Guide>
            </Chart>
            <Slider
                padding={[0, 100]}
                data={sliderDv}
                xAxis="date"
                yAxis="itemval"
                start={ds.state.start}
                end={ds.state.end}
                onChange={onChangeSlider}
                scales={{['date']: {type: 'time', mask:'M/DD H:mm' }}}
                fillerStyle={{ fill: '#BDCCED', fillOpacity: 0.6 }}
            />
        </React.Fragment>
    );
}

export default ChartSpline;

**Comment by weepy3641** [comment]
升级版本应该已经解决。
