### ISSUE TITLE
y轴坐标不支持溢出滚动

### ISSUE THREAD

**Issue by dearpeach** [alibaba/BizCharts#515]
- bizcharts Version: 3.2.2
- Platform or react version: 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link: https://codepen.io/dearpeach/pen/ZMJwwW
- you can fork CodePen template form this:

**Comment by weepy3641** [comment]
@dearpeach 
溢出滚动 是什么意思？

**Comment by dearpeach** [comment]
如果y坐标的坐标刻度值比较长，但是已经固定了chart的padding-left值，怎样让这个比较长的刻度值展示滚动效果，而不是直接溢出不展示呢？

例图如下：
![image](https://user-images.githubusercontent.com/8085417/45280261-406b3880-b506-11e8-8e88-b03ddd5c410e.png)

**Comment by weepy3641** [comment]
@dearpeach 
可以试试 padding = “auto” 。
http://bizcharts.net/products/bizCharts/api/chart#padding

**Comment by dearpeach** [comment]
可否固定padding-left，刻度值超出部分滚动展示呢

**Comment by weepy3641** [comment]
@dearpeach  不可以。
