### ISSUE TITLE
当在数据一定时，多条折线图Y轴出线bug。

### ISSUE THREAD

**Issue by wang5909912** [alibaba/BizCharts#516]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/26141772/45211478-fcd5bc00-b2c4-11e8-9afc-e0ec36569b01.png)
当X轴比较少或者更多时，Y轴没有bug，在一定范围内（大概两个月到四个月的长度）会出线Y轴显示bug问题。
![image](https://user-images.githubusercontent.com/26141772/45211574-42928480-b2c5-11e8-8e3d-9db5a6819f3c.png)
这是代码。
![image](https://user-images.githubusercontent.com/26141772/45211602-5211cd80-b2c5-11e8-9c60-2132395bae3a.png)
这是sscale配置

**Comment by wang5909912** [comment]
数据min=0， max=1818，

**Comment by weepy3641** [comment]
@wang5909912 
没明白你说的 y 轴 bug 是什么，能否详细描述并且写个 codepen 的 demo。

**Comment by wang5909912** [comment]
@weepy3641 
![image](https://user-images.githubusercontent.com/26141772/45464902-469b2800-b745-11e8-9fd0-2cfd382b2970.png)
图片圈红部分，我数据最大值是1818，已经发现问题原因了，是因为我设置了Y轴的scale的tickCount为10，删了就ok了
