### ISSUE TITLE
bizcharts-plugin-slider 可以用于不是时间段的滑动吗

### ISSUE THREAD

**Issue by EternityQi** [alibaba/BizCharts#518]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@EternityQi  可以的。

**Comment by zsio** [comment]
@weepy3641   拖动的时候     两边的拖动块会向右跑   然后就跑远了

**Comment by weepy3641** [comment]
@zsio 
将 slider 升级到 2.0.7 版本，拖动会正常。
