### ISSUE TITLE
折线图出现多条时，无法正常映射

### ISSUE THREAD

**Issue by z784324922** [alibaba/BizCharts#522]
![image](https://user-images.githubusercontent.com/31068244/45278124-42c99480-b4fe-11e8-87de-ddeb4d90d82d.png)

![image](https://user-images.githubusercontent.com/31068244/45278134-507f1a00-b4fe-11e8-9bc7-d90a4f573c2b.png)

**Comment by z784324922** [comment]
上面第一条线是实际数据，应该在蓝色区域内，后面就不显示了。下面第二条线，是预测的数据，要比第一条数据多几个点，所以会超出蓝色区域显示。但这样的数据结构，好像不能正常映射。

**Comment by z784324922** [comment]
有什么办法可以让第一条数据在蓝色后面区域就不显示，让第二条数据超出蓝色区域正常显示

**Comment by weepy3641** [comment]
需要你自己数据处理下，如果超出区域不想显示，将相应的数据删除即可。
参考demo：
http://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-of-dashed&selectedKey=%E6%A6%82%E8%A7%88

**Comment by z784324922** [comment]
这个数据就是处理过的了，第一条线应该到 09-10 01：29就结束了
