### ISSUE TITLE
support tooltip  show hide in mobile

### ISSUE THREAD

**Issue by isitrita** [alibaba/BizCharts#523]
Hi, I found that Tooltip can be triggered by 'mouseMove' or click event, but I need the same behaviour on mobile. 
I found that chart support `onTouchMove` and wonder how how I can properly change data in tooltip with `chart.showTooltip`
should I import chart from g2 or I can do it via BizCharts?

**Comment by weepy3641** [comment]
@isitrita 
We suggest you use  [bizGoblin](http://bizcharts.net/products/bizGoblin) or [F2](https://antv.alipay.com/zh-cn/f2/3.x/index.html) to suport mobile charts.
F2 is a  chart library  for the mobile， and bizGoblin is react chart library base F2.
