### ISSUE TITLE
bizcharts-plugin-slider 拖动过程中 往右面跑    稍微一动 就不见了

### ISSUE THREAD

**Issue by zsio** [alibaba/BizCharts#525]
- bizcharts Version: 3.2.2
- bizcharts-plugin-slider: 2.0.3
- Platform or react version: 16.4.1
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/16083606/45339949-188fd980-b5c7-11e8-9beb-ac302d9e08fa.png)
- CodePen Link: http://bizcharts.net/products/bizCharts/demo/detail?id=g2-area-large&selectedKey=%E6%A6%82%E8%A7%88

 两边的两个拖动块，只要一拖动，就会往右面跑   
大概拖动几十像素  就会不见了     
尝试mac和windows PC  都会出现这个问题   

可随时联系我远程尝试

**Comment by zsio** [comment]
链接是官方的demo示例    均会出现此bug

**Comment by zsio** [comment]
@weepy3641 召唤大佬

**Comment by weepy3641** [comment]
@zsio 
是 slider 版本问题，升级下就可以了。
站点 demo  slider 版本不是最新导致的。

**Comment by dengl11** [comment]
升级了在笔记本电脑上运行良好，在iMac Pro似乎还是存在这个问题呀~
