### ISSUE TITLE
Legend 修改position 没有作用，并且显示不全

### ISSUE THREAD

**Issue by qinyuhua** [alibaba/BizCharts#527]
<Chart height={height} padding={padding} data={dv} scale={cols} forceFit>
            <Legend name="y" position="bottom" />
            <Axis name="x" />
            <Tooltip />
            <Geom type="line" position="x*value" size={borderWidth} color="key" />
          </Chart>
![qq 20180911175825](https://user-images.githubusercontent.com/28893646/45352978-505d4800-b5ec-11e8-80ba-f06b77e5566c.png)

**Comment by weepy3641** [comment]
显示不全是 padding 不够造成的。
http://bizcharts.net/products/bizCharts/api/chart#padding

position 没有作用麻烦贴下代码，我们这不能复现。
如下 demo 所有位置都生效
http://bizcharts.net/products/bizCharts/demo/detail?id=other-legend-position&selectedKey=%E5%85%B6%E4%BB%96%E5%9B%BE%E8%A1%A8

**Comment by qinyuhua** [comment]
刚才试了下，加上属性 name就好像就不起作用了

**Comment by weepy3641** [comment]
@qinyuhua 
https://codepen.io/anon/pen/WgzapG
demo 中 legend 加上 name 依然生效。 所以如果你那还有问题，麻烦写个 codepen。
