### ISSUE TITLE
当一个大屏显示多个同类型的图表组件时，会只显示一个，另外一些图表会渲染不出来

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#528]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
没有出现过你说的这种问题，所以麻烦写个 codepen  demo 好进一步看是什么问题。
