### ISSUE TITLE
slider 可以支持三个y轴么？

### ISSUE THREAD

**Issue by ceasor** [alibaba/BizCharts#529]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
我有三条线（或者以上）要显示在slider里，不知道可以不可以。谢谢

**Comment by weepy3641** [comment]
可以的。

**Comment by ceasor** [comment]
这样写么：
![image](https://user-images.githubusercontent.com/23649217/45413828-ab567400-b6ac-11e8-8ac1-df9940075544.png)

**Comment by weepy3641** [comment]
@ceasor 
不好意思，我理解错了你的意思。
slider 不支持多个 y 轴。

**Comment by weepy3641** [comment]
@ceasor 
这个需要 g2 支持，你可以去 g2 提个issue。

**Comment by ceasor** [comment]
其实能显示多条线就好了，可以不要那么多轴，有办法么？

**Comment by weepy3641** [comment]
@ceasor 
暂时没有办法，需要 g2 支持，可以去 g2 提个 issue。
另外 slider 交互实际上可以考虑用框选，框选可以支持多根线，跟普通图表一样，例如demo：

http://bizcharts.net/products/bizCharts/demo/detail?id=g2-brush-ds-state&selectedKey=%E6%A6%82%E8%A7%88
