### ISSUE TITLE
可否添加波纹效果示例

### ISSUE THREAD

**Issue by wangxingkang** [alibaba/BizCharts#530]
demo如下:  http://antvis.github.io/g2/demo/19-creations/point-shape-animate.html

**Comment by wangxingkang** [comment]
demo采用的是g2 v2写的  v3无这样的示例

**Comment by mytrip** [comment]
我们没有地图资质，建议寻找合适的第三方资源，给亲推荐个
https://lbs.amap.com/api/loca-api/demos/loca_point/all_city

**Comment by mytrip** [comment]
水波纹效果实现可以通过bizcharts的shape自定义实现，api参考地址http://bizcharts.net/products/bizCharts/api/shape#shape

**Comment by wangxingkang** [comment]
好的
