### ISSUE TITLE
scale和slider中的mask属性不支持gggg-w（2015-34）年-周数的format形式（moment支持gggg-ww此种format形势）

### ISSUE THREAD

**Issue by neilwang543** [alibaba/BizCharts#531]
如标题所示 目前的mask属性只支持：
y: year
m: month
d: date
H: hour
M: minute
s: second
不支持w：week 周数的显示
期望支持此属性与moment同步

![menu saveimg savepath20180912165628](https://user-images.githubusercontent.com/29112920/45414275-8adae980-b6ad-11e8-9a76-aa05526fe40b.jpg)

![menu saveimg savepath20180912165809](https://user-images.githubusercontent.com/29112920/45414280-8c0c1680-b6ad-11e8-84c0-5a3072e003f0.jpg)

**Comment by mytrip** [comment]
http://bizcharts.net/products/bizCharts/api/scale#mask-1   当前mask已经支持了moment以及fecha的数据格式
