### ISSUE TITLE
词云图点击页面跳转

### ISSUE THREAD

**Issue by lukouxinan** [alibaba/BizCharts#532]
请问词云图能否实现点击图上的某一个词后跳转到到一个链接

**Comment by mytrip** [comment]
可以通过设置chart的onPlotClick事件，判断当前点击的是否为词云图上的某一个词，同时在返回的dom节点信息上进行跳转链接的设置，在事件处理函数中进行链接的跳转

**Comment by JeffreyCSL** [comment]
设置chart的onPlotClick事件 回调对象中的data._origin 可以获取到
