### ISSUE TITLE
SVG Charts remain in background if you change the data. 

### ISSUE THREAD

**Issue by J1marotta** [alibaba/BizCharts#533]
I'm want to do OnClick events based on SVG coordinates, but If I make the charts render in SVG, it does not clean up properly and leaves me with a faded chart, once you do this a few times, the chart becomes completely unreadable. 

This does not occur with Canvas, but I cannot accurately create onClick events with Canvas

Any help would be very appreciated. 

- bizcharts Version:     "bizcharts": "^3.2.2",
- Platform or react version:      "react": "16.2.0",
- Mini Showcase: 
<img width="641" alt="screen shot 2018-09-13 at 2 50 35 pm" src="https://user-images.githubusercontent.com/23306962/45467746-7a397a80-b764-11e8-9ae7-ff366cfae517.png">
<img width="1145" alt="screen shot 2018-09-13 at 12 19 59 pm" src="https://user-images.githubusercontent.com/23306962/45467747-7a397a80-b764-11e8-87bb-502213717476.png">
<img width="1143" alt="screen shot 2018-09-13 at 12 20 58 pm" src="https://user-images.githubusercontent.com/23306962/45467748-7ad21100-b764-11e8-9aa0-554d2eefed0b.png">
- CodePen Link: `https://codepen.io/j1m87/pen/dqeaPK?editors=0010`

**Comment by weepy3641** [comment]
@J1marotta 
It's bizcharts dependent library G2‘s bug。
when chart change data, after the chart fade out animation, the fade out svg elements will not be deleted.

Currently you have 3 ways to avoid this problem.

1、change chart padding，so chart will be created again.
https://codepen.io/anon/pen/jvxjbG?editors=0010

2: close chart animation .
``` 
<Chart animate={false} ... />

3、 render in canvas

**Comment by weepy3641** [comment]
bug related：
https://github.com/antvis/g2/issues/881

**Comment by J1marotta** [comment]
Thank you for the speedy Reply, I hope this gets fixed soon, I will use canvas until then.

**Comment by weepy3641** [comment]
@J1marotta 
 bizcharts@3.2.5-beta.3  fixed this bug.
