### ISSUE TITLE
label只会显示两条数据

### ISSUE THREAD

**Issue by nouh** [alibaba/BizCharts#535]
- bizcharts Version: 3.2.2
- Platform or react version: 16.4.1
- Mini Showcase(like screenshots):
<img width="997" alt="screen shot 2018-09-13 at 4 10 39 pm" src="https://user-images.githubusercontent.com/445029/45475929-4e23f680-b770-11e8-8dd2-4a6f9adf84f6.png">
<img width="1058" alt="screen shot 2018-09-13 at 4 18 03 pm" src="https://user-images.githubusercontent.com/445029/45476088-a955e900-b770-11e8-8557-527b95e3c3cd.png">

- CodePen Link: https://codepen.io/nouh/pen/qMKBNG

**Comment by weepy3641** [comment]
date type 配置为 cat
```
const scale = {
      count: {
        type: 'linear',
        tickInterval: 5,
        alias: '投票地址数',
      },
      date: {
        type: 'cat',
        range: [0.05, 0.9],
        alias: '投票日期',
      },
    };
```
