### ISSUE TITLE
Geom type=“line” 时，怎么实现一个趋势图上有实线有虚线

### ISSUE THREAD

**Issue by qinyuhua** [alibaba/BizCharts#536]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@qinyuhua 
demo参考：

https://codepen.io/anon/pen/vzrPBw

http://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-of-dashed&selectedKey=%E6%A6%82%E8%A7%88
