### ISSUE TITLE
调整滑块大小后，再更新Slider 就会崩溃。

### ISSUE THREAD

**Issue by ceasor** [alibaba/BizCharts#537]
调整滑块大小后，再更新Slider 就会崩溃。
问题发生在：

![6](https://user-images.githubusercontent.com/23649217/45539599-cd7efc00-b83c-11e8-9148-bfaba3b074cc.PNG)

因为minText 是根据mask得到的， 所以不一定可以用在_initRange()里.
![7](https://user-images.githubusercontent.com/23649217/45539753-3797a100-b83d-11e8-957c-abcc1fcb86ca.PNG)

在scale.translate(start), 可能转成NaN，于是后面会报异常。

试了一下
this.start = min;
this.end = max;
结果还好，不知道可以这样改不？

- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by mytrip** [comment]
https://codepen.io/leslie2014/pen/xjJGER  麻烦在codepen里写下亲的代码，便于复现我们进行排查哦

**Comment by ceasor** [comment]
不太会用codepen,。你们琢磨一下，当mask为"H:mm:ss"时，重新render slider， 是不是会有问题。 我们的数据是实时增长的，所以时不时在重新render。

**Comment by weepy3641** [comment]
没有反馈，暂时关闭。
