### ISSUE TITLE
如何设置滑块大小

### ISSUE THREAD

**Issue by ceasor** [alibaba/BizCharts#538]
我在render 的时候可以控制Slider 滑块的大小和位置么？

- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by mytrip** [comment]
官网的http://bizcharts.net/products/bizCharts/api/sliderPlugin   slider 处有设置起大小样式的接口，可以在render的时候动态设置

**Comment by ceasor** [comment]
我觉得你们没说清楚， start 是指下图A还是B对应的值？
![image](https://user-images.githubusercontent.com/23649217/45607253-c0048480-ba7d-11e8-80ca-9df2d68539a0.png)

**Comment by weepy3641** [comment]
@ceasor 
http://bizcharts.net/products/bizCharts/api/sliderPlugin#start
写的很清除，是A
