### ISSUE TITLE
环形 50% bug

### ISSUE THREAD

**Issue by weizheng1992** [alibaba/BizCharts#541]
- bizcharts Version:3.2.2
- Platform or react version:16.4.2

<img width="352" alt="0dcfd220-b088-47b7-a78b-24a6cb77542a" src="https://user-images.githubusercontent.com/10727313/45604371-2f6e7a00-ba66-11e8-9234-d2ef4432ca08.png">

**Comment by mytrip** [comment]
麻烦在https://codepen.io/leslie2014/pen/xjJGER 中提供亲的代码，并详细描述亲的问题，以便于我们更精准定位到问题

**Comment by weizheng1992** [comment]
<img width="900" alt="ab25aaaf-7e8a-491b-9cb6-1cbb45c9f684" src="https://user-images.githubusercontent.com/10727313/45605067-c5a59e80-ba6c-11e8-9f08-fbf4874f170e.png">
<img width="1993" alt="19b910ba-9278-492c-9621-480df94ae552" src="https://user-images.githubusercontent.com/10727313/45605072-ccccac80-ba6c-11e8-92e2-4239317b9ef1.png">

**Comment by weepy3641** [comment]
@weizheng1992 
fix at bizcharts@3.2.1-beta.2

**Comment by weizheng1992** [comment]
我替换版本了 还是没解决 @weepy3641

**Comment by weepy3641** [comment]
@weizheng1992 
3.2.3-beta.4 底层 g 已经修复了。

**Comment by weizheng1992** [comment]
thank you very much!!!!
