### ISSUE TITLE
设置了单个坐标轴-y轴不可见后，legend错位

### ISSUE THREAD

**Issue by yang0211a** [alibaba/BizCharts#542]
示例如下
http://riddle.alibaba-inc.com/riddles/65414173?amdType=undefined

**Comment by yang0211a** [comment]
当坐标轴没有设置隐藏的时候 是没有问题的。
设置y轴隐藏 就会出现legend错位问题。
同时隐藏x和Y轴，legend位置也没有问题

**Comment by liunian** [comment]
已反馈到 antvis/g2#889 ，待跟进

**Comment by weepy3641** [comment]
新版本已经修复。
