### ISSUE TITLE
[BUG] Axis' title can't support offsetY？

### ISSUE THREAD

**Issue by zhoumh1988** [alibaba/BizCharts#543]
- bizcharts Version: ^3.2.1-beta.4
- Platform or react version: antd@^3.9.2
- Mini Showcase(like screenshots):

![image](https://user-images.githubusercontent.com/7434920/45611313-8e95b400-ba91-11e8-9bff-a0a5d2695001.png)

```javascript
<Axis name="value" title={{offsetX: 0, offsetY: -10}} />
```
### How can I achieve the effect I want?

**Comment by liunian** [comment]
Not yet, we'll consider

**Comment by zhuzz11** [comment]
@zhoumh1988 这个你最后怎么实现的title？使用外部div么？

**Comment by larissa-n** [comment]
You can try:
  ```
title={{
     position: "end",
     autoRotate: false,
     rotate: 0,
     offset: 0,
}}
```
This will put the title right about where it's shown in the image. It may be overlapping with the axis though, so you might have to play with `nice: false` to create some space.
