### ISSUE TITLE
legend显示masker设置无效

### ISSUE THREAD

**Issue by luckhpy** [alibaba/BizCharts#544]
发现masker在对应的color字段对应的值为数字的时候，设置masker无效

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>多条折线图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;margin:0;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.2.8-beta.5/dist/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.8.9/dist/data-set.min.js"></script>
<script>

var data = [{
  "month": "Jan",
  "city": "Tokyo",
  "temperature": 7,
  a: 11
}, {
  "month": "Jan",
  "city": "London",
  "temperature": 3.9,
  a: 11
}, {
  "month": "Feb",
  "city": "Tokyo",
  "temperature": 6.9,
  a: 11
}, {
  "month": "Feb",
  "city": "London",
  "temperature": 4.2,
  a: 11
}, {
  "month": "Mar",
  "city": "Tokyo",
  "temperature": 9.5,
  a: 11
}, {
  "month": "Mar",
  "city": "London",
  "temperature": 5.7,
  a: 11
}, {
  "month": "Apr",
  "city": "Tokyo",
  "temperature": 14.5,
  a: 11
}, {
  "month": "Apr",
  "city": "London",
  "temperature": 8.5,
  a: 11
}, {
  "month": "May",
  "city": "Tokyo",
  "temperature": 18.4,
  a: 11
}, {
  "month": "May",
  "city": "London",
  "temperature": 11.9,
  a: 11
}, {
  "month": "Jun",
  "city": "Tokyo",
  "temperature": 21.5,
  a: 11
}, {
  "month": "Jun",
  "city": "London",
  "temperature": 15.2,
  a: 11
}, {
  "month": "Jul",
  "city": "Tokyo",
  "temperature": 25.2,
  a: 11
}, {
  "month": "Jul",
  "city": "London",
  "temperature": 17,
  a: 11
}, {
  "month": "Aug",
  "city": "Tokyo",
  "temperature": 26.5,
  a: 11
}, {
  "month": "Aug",
  "city": "London",
  "temperature": 16.6,
  a: 11
}, {
  "month": "Sep",
  "city": "Tokyo",
  "temperature": 23.3,
  a: 11
}, {
  "month": "Sep",
  "city": "London",
  "temperature": 14.2,
  a: 11
}, {
  "month": "Oct",
  "city": "Tokyo",
  "temperature": 18.3,
  a: 11
}, {
  "month": "Oct",
  "city": "London",
  "temperature": 10.3,
  a: 18
}, {
  "month": "Nov",
  "city": "Tokyo",
  "temperature": 13.9,
  a: 11
}, {
  "month": "Nov",
  "city": "London",
  "temperature": 6.6
}, {
  "month": "Dec",
  "city": "Tokyo",
  "temperature": 9.6,
  a: 11
}, {
  "month": "Dec",
  "city": "London",
  "temperature": 4.8,
  a: 11
}];

var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: window.innerHeight
});
chart.source(data, {
  month: {
    range: [0, 1]
  }
});
chart.tooltip({
  crosshairs: {
    type: 'line'
  }
});

chart.legend('a', {
  marker: 'square'
})
chart.axis('temperature', false);
chart.line().position('month*temperature').color('a')
// chart.line().position('month*a').color('a')
// .tooltip('month*temperature*city', (month, temperature, city) => {
// 	return {
//     	name: map[city],
//     	value: temperature
//   	}
// } )
chart.render();
</script>
</body>
</html>

不知道为什么这样子设计，一般如果我需要设置别名会通过formatter，这里的设置貌似color设置的是字段的别名。（把.color('a')修改成.color('city')，.legend('a', ... )修改成.legend('city', ... )就可以正常的显示方形masker）

**Comment by weepy3641** [comment]
@luckhpy 
color 对应的数据字段值为数值类型时，默认 是一个可以拖动 legend。
该 legend 没有 mask 属性。
