### ISSUE TITLE
bizChart.js报错

### ISSUE THREAD

**Issue by JediBai** [alibaba/BizCharts#545]
- bizcharts Version: 3.1.3
- Platform or react version: 
- Mini Showcase(like screenshots):
![biz](https://user-images.githubusercontent.com/31715147/45658700-27284480-bb23-11e8-968f-e02cac4364a2.png)
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
---------------------------------------------------------------------------------------------
在使用bizChart时使用了<Legend>,在切换不同的图例时出现了这个报错，请问这个有什么办法解决吗？

**Comment by JediBai** [comment]
功能上没有出现问题，主要出现这个报错后界面会卡主很久，体验不是很好，想问下有没有解决方案。

**Comment by liunian** [comment]
能否提供一个可重现的简单示例呢？

**Comment by JediBai** [comment]
@liunian 
`<Chart
                  height={400}
                  data={dv}
                  scale={scale}
                  forceFit
                  padding={{ top: 20, right: 50, bottom: 110, left: 50 }}
                >
                  <Axis name="periodDate" />
                  <Axis name="num" label={{ formatter: val => `${val}` }} />
                  <Tooltip crosshairs={{ type: 'y' }} />
                  <Geom type="line" position="periodDate*num" size={1} color="type" />
                  <Geom
                    type="point"
                    position="periodDate*num"
                    size={4}
                    shape="circle"
                    color="type"
                  />
                  <Legend />
                </Chart>`
使用<Legend>就会出现，我是在React-antd-pro的环境下使用的.

**Comment by JediBai** [comment]
![w7 pnozbd k1 _ sb16l9c](https://user-images.githubusercontent.com/31715147/45733410-3d153280-bc13-11e8-97d4-06f0e3e846e9.png)

bizChart的版本

**Comment by JediBai** [comment]
@liunian 在我把biz升级到3.2.2版本后解决了这个问题，可能是旧版本的遗留问题吧，请问biz有更新日志看吗？

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/blob/master/CHANGELOG.md
