### ISSUE TITLE
Slider滑动条的结束时间显示不完整，请问显示位置可以修改吗？

### ISSUE THREAD

**Issue by zhangyanf** [alibaba/BizCharts#546]
可以设置结束时间的位置在右侧滑块图标的左侧吗？
![image](https://user-images.githubusercontent.com/10766381/45663272-2ea61880-bb38-11e8-93c6-7860115776d9.png)

**Comment by weepy3641** [comment]
@zhangyanf 
可以将 slider 的 padding 加大一点。

**Comment by zhangyanf** [comment]
可以，不过通过修改padding的方式不太理想，如果slider显示的开始结束时间的格式变化了，就需要重新调整padding，并且slider与图表也不太容易对齐了

**Comment by weepy3641** [comment]
@zhangyanf 
暂时没有其他解决办法，可以向 g2 slider 提个 issue。
