### ISSUE TITLE
点图如何去掉上方多余的横线

### ISSUE THREAD

**Issue by meixiaohei** [alibaba/BizCharts#547]
![image](https://user-images.githubusercontent.com/33745879/45663706-73cb4a00-bb3a-11e8-9862-e47600432da7.png)

**Comment by liunian** [comment]
看上去是指网格线，但看上去不是左轴的，能否提供下重现例子？

**Comment by meixiaohei** [comment]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/bubble
你可以看看这个例子   上面多出的一行能否去掉

**Comment by weepy3641** [comment]
@meixiaohei 
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/g2/bubble

**Comment by meixiaohei** [comment]
这块用tickCount时  y轴如果是数字时   可控   但是  如果改为文字或者英文  完全不可控  
可能是因为没有可控的type属性

**Comment by meixiaohei** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/punch-card.html
删除49行可见

**Comment by tli4** [comment]
<Axis name="..." grid={{ hideLastLine: true }} />

这个属性不是能隐藏最上面的线吗

**Comment by aprilandjan** [comment]
@tli4 这个属性很关键啊，实测有效 😂
 敢问哪里看到有这个属性的？我看了 api 文档 <https://bizcharts.net/products/bizGoblin/api/axis#grid> 完全没提到啊。这里不得不吐槽下，bizchart 文档真的不够友好，层次和关联都不太清晰。

**Comment by tli4** [comment]
> @tli4 这个属性很关键啊，实测有效 😂
> 敢问哪里看到有这个属性的？我看了 api 文档 https://bizcharts.net/products/bizGoblin/api/axis#grid 完全没提到啊。这里不得不吐槽下，bizchart 文档真的不够友好，层次和关联都不太清晰。

是的，文档不清楚完全是摸着石头过河，当时因为项目用的typescript看了下g2的ts[类型定义](https://github.com/antvis/g2/blob/master/src/index.d.ts#L475)

**Comment by aprilandjan** [comment]
@tli4 学到了学到了，看声明文件知 api 😂

**Comment by liunian** [comment]
解决方案见 https://github.com/alibaba/BizCharts/issues/547#issuecomment-468143477

`<Axis name="..." grid={{ hideLastLine: true }} />`
