### ISSUE TITLE
bizchart 渐变 

### ISSUE THREAD

**Issue by lvhongxiang** [alibaba/BizCharts#548]
-怎么解决 Bar图 或者其他图形中的渐变的问题，

**Comment by liunian** [comment]
能否详细描述下你的问题，最好能提供可重现的例子

**Comment by lvhongxiang** [comment]
采用 Ant desgin Pro框架，开发我们的网站，其间使用控件 bizcharts中的Bar 控件，想柱状图的颜色做成渐变色
![image](https://user-images.githubusercontent.com/3476977/45730082-5b266700-bc02-11e8-8186-d88e2e976d87.png)

**Comment by lvhongxiang** [comment]
问题已经解决了，但是 有一点不太完美的地方，在鼠标挪上去之后的出现的提示。无法识别渐变颜色，原因应该是在mark.get（‘color’）这个函数上，获取的不了渐变色。
渐变色解决的办法是，设置   color = 'l(100) 0:#1DE3C5 1:#103649', 这样就可以了。语法不知道啥语法，如有朋友知道，请指点。

**Comment by weepy3641** [comment]
@lvhongxiang 
鼠标移上去，交互的点不是渐变色，这个bug需要 g2 修复。
ref issue： https://github.com/alibaba/BizCharts/issues/380
