### ISSUE TITLE
紧凑树布局中调用dv.getAllNodes()方法显示this.root.each() is not a function

### ISSUE THREAD

**Issue by xxz11** [alibaba/BizCharts#549]
在使用bizcharts中的紧凑树布局时，在第一个项目库中调用是好使的。但我在另一个项目库中调用就报this,root.each不是一个函数了。验证过了，bizcharts和dataset是版本是同版本号，不知道是什么原因，能帮忙回答一下么

**Comment by xxz11** [comment]
40533 | assign(View.prototype, {
  40534 |   getAllNodes: function getAllNodes() {
  40535 |     var nodes = [];
> 40536 |     this.root.each(function (node) {
  40537 |       nodes.push(node);
  40538 |     });
  40539 |     return nodes;

**Comment by JiangHaoCode** [comment]
需要什么依赖啊？
