### ISSUE TITLE
为什么仪表盘图表无法显示指针

### ISSUE THREAD

**Issue by zhouliuhao** [alibaba/BizCharts#55]
已经在项目中自定义了shape属性，其他显示正常，只有数值指针未渲染成功

**Comment by weepy3641** [comment]
@zhouliuhao  
可以参考demo:
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/guage/color

这边的demo指针是正常的哦。

**Comment by zhouliuhao** [comment]
已经对比出异常了，我的数据的key值与 position="value*1"的不匹配，导致指针不显示
