### ISSUE TITLE
scale ->  alias设置别名无效

### ISSUE THREAD

**Issue by lizibeite** [alibaba/BizCharts#550]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
多个柱状图是 设置别名还无效

**Comment by lishaoh** [comment]
我也遇到了，请问解决了吗

**Comment by vaynevayne** [comment]
+1 分组柱状图alias 无效
