### ISSUE TITLE
Render more than one <Label /> component for a single <Geom />

### ISSUE THREAD

**Issue by igor-pavlichenko** [alibaba/BizCharts#551]
Is there a way of rendering 2 Labels for the same Geom component? For example I would like to show quantity inside and percentage outside, or vice-versa.

- bizcharts Version: 3.2.2
- Platform or react version: 16.4.1
- Mini Showcase(like screenshots): 
![2labels](https://user-images.githubusercontent.com/7633886/45826246-07904800-bcec-11e8-90be-18a76b282d21.jpg)
- CodePen Link: https://codepen.io/anon/pen/EerEga
this doesn't work
```
<Geom>
  <Label content="percent" />
  <Label content="count" />
</Geom>
```
only the last Label is getting rendered

**Comment by weepy3641** [comment]
Bizcharts only support one <Label />  in <Geom />.
If you need more than one label text, you can use <Label htmltemplate="xxx" />. 

http://bizcharts.net/products/bizCharts/api/label#htmltemplate
