### ISSUE TITLE
Axis坐标设置label旋转角度rotate位置偏移

### ISSUE THREAD

**Issue by NaturalDragon** [alibaba/BizCharts#553]
- bizcharts Version:3.2.2
- Platform or react version:16.4.1
- Axis坐标设置label旋转角度rotate位置偏移

- CodePen Link:https://codepen.io/naturaldragon/pen/pOMeLx

**Comment by weepy3641** [comment]
@NaturalDragon  
这个 bug 是由于旋转更新动画引起了，你暂时可以关闭图表的动画规避这个bug，等解决后再开启动画。
```
<Chart animate={false} />
```

**Comment by NaturalDragon** [comment]
@weepy3641 谢谢，关闭动画就可以了
