### ISSUE TITLE
可以用angularJS使用bizcharts吗？

### ISSUE THREAD

**Issue by lixuan185** [alibaba/BizCharts#555]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@lixuan185 
可以使用兄弟团队的 viserjs， 也是基于 g2 封装的图表库，支持 angularJS 语法，支持功能跟 bizcharts 等同。
https://viserjs.github.io/demo.html
