### ISSUE TITLE
cannot assign to read only property 'constructor' of object

### ISSUE THREAD

**Issue by bWhirring** [alibaba/BizCharts#556]
- bizcharts Version: 3.2.4
- Platform or react version: 
   node 8.9.3
   npm 5.5.1
   react 16.3.2
- Mini Showcase(like screenshots):

![](https://static.dingtalk.com/media/lADPDgQ9qRob8sXNARnNAxg_792_281.jpg_620x10000q90g.jpg)

使用3.2.2版本就没问题

**Comment by bWhirring** [comment]
代码如下
`
import React from "react";
import ReactDOM from "react-dom";

import { Chart } from "bizcharts";

const App = () => <div>test</div>;

ReactDOM.render(<App />, document.getElementById("root"));
`

**Comment by bWhirring** [comment]
代码如下
```
import React from "react";
import ReactDOM from "react-dom";

import { Chart } from "bizcharts";

const App = () => <div>test</div>;

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by ssfxz** [comment]
当assign合并的目标对象的该属性是不可修改时会报这个错，建议你排查一下有没有写不合理的assign，另外polar.js中的内容也可以排查一下

**Comment by HaveF** [comment]
@bWhirring 发现同样问题, 感谢3.2.2解决方案
