### ISSUE TITLE
怎么实现饼图默认选中某一项，类似g2里面的setSelected方法

### ISSUE THREAD

**Issue by ht1131589588** [alibaba/BizCharts#557]
- bizcharts Version: 3.1.10
- Platform or react version: 16.4.1
期望实现效果如下：[g2饼图设置默认选中](https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/donut.html)

**Comment by heiniuhaha** [comment]
![image](https://user-images.githubusercontent.com/668144/63350666-6ba20d00-c390-11e9-9eb0-aeb3fbad38eb.png)

https://bizcharts.net/products/bizCharts/demo/detail?id=interval-onplotclick&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE

https://bizcharts.net/products/bizCharts/demo/detail?id=pie-setselected&selectedKey=%E9%A5%BC%E5%9B%BE
