### ISSUE TITLE
Custom timezone

### ISSUE THREAD

**Issue by FernandoGOT** [alibaba/BizCharts#558]
- bizcharts Version:
    bizcharts: 3.1.10,
    bizcharts-plugin-slider: 2.0.3,

- Platform or react version:
    react: 16

Is there a way to force the timezone used by the chart?

I'm receiving a timestamp with the timezone as UTC 0 from the server, so is there a way to set the timezone (UTC) based on the user settings and not the PC or browser?

**Comment by ssfxz** [comment]
You can use a third-party library to customize the time zone. [moment](https://momentjs.com/)

**Comment by weepy3641** [comment]
@FernandoGOT 
slider's scale mask property support [moment](https://momentjs.com/) and [fecha](https://github.com/taylorhakes/fecha) time format.
https://github.com/alibaba/BizCharts/tree/master/plugin/slider#9-scales-object
http://bizcharts.net/products/bizCharts/api/scale#time

**Comment by heiniuhaha** [comment]
已修复，查看以下Demo
bizcharts@3.x https://bizcharts.net/product/bizcharts/demo/525
bizcharts@4.x https://bizcharts.net/product/BizCharts4/demo/524
