### ISSUE TITLE
legend支持自定义

### ISSUE THREAD

**Issue by beno890522** [alibaba/BizCharts#559]
![image](https://user-images.githubusercontent.com/5343554/46642111-e8c4f900-cba7-11e8-9518-55b8c3ca8fbf.png)
如图newOpen，done，existed，expected等希望能支持自定义

**Comment by ssfxz** [comment]
在本例中，由于存在多组Geom，因此Legend默认显示label的是源数据的字段名，因此alias在这里是不生效的。这种情况下可以使用Legend的itemFormater来对label进行格式化[itemFormater](https://bizcharts.net/products/bizCharts/api/legend#itemformatter)。
