### ISSUE TITLE
Legend custom 问题

### ISSUE THREAD

**Issue by catXiaoXiao** [alibaba/BizCharts#560]
场景：多组柱状图 + 折线
transform数据之后，所有柱状图数据名统一改为“value‘’,
Legend自定义之后的click事件找不到对应的柱状图数据名从而隐藏显示失效。。。求救c⌒っﾟДﾟ)っ！！！
CodeOpen地址：
https://codepen.io/PandaKing/pen/aRpGJa

**Comment by ssfxz** [comment]
Geom的颜色划分可以通过Shape实现
[https://codepen.io/ssfxz/pen/MPpOMj?editors=1010](https://codepen.io/ssfxz/pen/MPpOMj?editors=1010)

**Comment by catXiaoXiao** [comment]
@ssfxz 阿里嘎多！！虽然我也想到了这种修改数据的办法，但是感觉好麻烦呢，不知道BizCharts作者能不能把这方面优化一下Thanks♪(･ω･)ﾉ
