### ISSUE TITLE
柱状图自定义鼠标样式问题

### ISSUE THREAD

**Issue by gnosis23** [alibaba/BizCharts#561]
在什么地方可以自定义鼠标移动到柱子上的样式？ 类似于css中 cursor:pointer 效果。

**Comment by ssfxz** [comment]
你好，目前canvas渲染的鼠标指针配置并没有开放接口，但是你可以使用svg渲染方式，然后通过CSS控制指针。
[https://bizcharts.alibaba-inc.com/products/bizCharts/api/chart#renderer](https://bizcharts.alibaba-inc.com/products/bizCharts/api/chart#renderer)
