### ISSUE TITLE
How to use self-defined variables in Legend, similar as Tooltip

### ISSUE THREAD

**Issue by benedict1986** [alibaba/BizCharts#563]
- bizcharts Version: 3.2.3-beta.2
- Platform or react version: 16.3.2
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

When I use itemTpl for Legend, how can I use self-defined variables? For Tooltip, I can add variables in tooltip attribute in Geom, but could not find a way to do so for Legend. Can anyone give some suggestions. Thanks.

**Comment by harry75369** [comment]
Since itemTpl is just a string, if you want to use self-defined variables in itemTpl, you can write like this
```
<Legend useHtml={true} itemTpl={`<div>{value} ${variable}</div>`}/>
```
where 'value' is built-in variable in itemTpl and `variable` is yours. Full code is here: https://codepen.io/harry75369/pen/jeaRPz

Does it solve your problem?

**Comment by weepy3641** [comment]
@benedict1986 
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-double-axes&selectedKey=%E6%A6%82%E8%A7%88


May be this demo can help you.

**Comment by benedict1986** [comment]
Thanks @harry75369 and @weepy3641, my issue has been solved.
