### ISSUE TITLE
官网因依赖 bootcdn 导致图表无法正常显示

### ISSUE THREAD

**Issue by zhangjie2012** [alibaba/BizCharts#565]
https://cdn.bootcss.com/babel-core/5.8.38/browser.min.js

**Comment by harry75369** [comment]
好的，我们会看看的，感谢

**Comment by yangxs9** [comment]
遇到了同样的情况，官网图表示例无法查看。

**Comment by harry75369** [comment]
正在修复中，预计明天更新后会解决。

**Comment by zhangjie2012** [comment]
@harry75369 是已经解决了吗？我这边可以访问了。要是解决了关 issue 了。

**Comment by harry75369** [comment]
是的，已经更新了。可以关闭 issue 了。
