### ISSUE TITLE
官网中的基础柱状图拷贝下来后，添加onPlotClick事件，回调函数的参数中有时不显示data属性

### ISSUE THREAD

**Issue by fuyongxia** [alibaba/BizCharts#572]
- bizcharts Version:3.1.1
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this:
问题补充：点击回调函数会显示data属性，必须点到某个点吗，在官网也没中尝试的点击柱状图的任意地方都是有效的，但是本地的点击柱状的任意地方，回调函数的参数都不显示data属性， 是版本问题吗，还是

**Comment by harry75369** [comment]
我这边无法复现你的问题。你可以制作一个能够复现问题的 codepen 给我么？

**Comment by harry75369** [comment]
已在钉钉答疑群中解决，可关闭 issue

**Comment by leitongda** [comment]
怎么解决的，

**Comment by harry75369** [comment]
> 怎么解决的，

用户自己逻辑代码的问题 @leitongda 

> 搞定了，是因为我addShape了俩次，但第二次没赋值给最后return的变量

**Comment by dmdoit** [comment]
> 已在钉钉答疑群中解决，可关闭 issue

钉钉答疑群是哪一个？
