### ISSUE TITLE
点击浏览器的刷新按钮，图表内容宽度会溢出

### ISSUE THREAD

**Issue by SongZhikuan** [alibaba/BizCharts#573]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@SongZhikuan 
相关 issue
https://github.com/alibaba/BizCharts/issues/399
