### ISSUE TITLE
chart width padding={0} but also have padding

### ISSUE THREAD

**Issue by lidianhao123** [alibaba/BizCharts#576]
- bizcharts Version:3.2.4
- Platform or react version:16.0.0
- Mini Showcase(like screenshots):
![map-issue](https://user-images.githubusercontent.com/7970645/47280631-e8961600-d609-11e8-80e7-1595ea23d2da.png)
- CodePen Link:https://codepen.io/dainli/pen/XxMLVd?editors=1010
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

Refer to  #445  I have add below code.
step1:

```jx
<Chart padding={0}>
```

step2:

```css
canvas {
  display: block;
}
```

**Comment by lidianhao123** [comment]
All style is show above，you can see the CodePen Link https://codepen.io/dainli/pen/XxMLVd

**Comment by weepy3641** [comment]
![image](https://user-images.githubusercontent.com/3838676/49056695-bd6d9a80-f237-11e8-8088-d01b448fc358.png)

codepen demo's canvas has no padding !
