### ISSUE TITLE
示例里的地图组件打不开

### ISSUE THREAD

**Issue by Jlber** [alibaba/BizCharts#58]
示例里的地图组件为什么打不开，浏览器里的console显示也报错  “ TypeError: Cannot read property 'Chart' of undefined”

**Comment by weepy3641** [comment]
@Jlber 打不开的地图在哪，能否给个地址？

站点上的地图 demo 都能打开哦。
https://alibaba.github.io/BizCharts/demo.html#地图

**Comment by zhouliuhao** [comment]
其他的demo都ok的，只有地图图表显示不出来，报错
![image](https://user-images.githubusercontent.com/22805182/34283970-93455cc8-e709-11e7-91c0-9499efe4bd10.png)

**Comment by weepy3641** [comment]
@zhouliuhao 
给个打不开的链接啊！

**Comment by Jlber** [comment]
@weepy3641   你打开还是列表 要进有代码的页面 
看这个吧  https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/map/choropleth-map

**Comment by weepy3641** [comment]
@Jlber 
我这每个都能独立打开，你是不是有什么资源文件加载失败了？ 
![image](https://user-images.githubusercontent.com/3838676/34330695-8b950f7a-e95a-11e7-971e-580480fbb22e.png)
