### ISSUE TITLE
曲线折现图，加载后宽度超出屏幕宽度，改变屏幕窗口大小后，又正常显示

### ISSUE THREAD

**Issue by tuihou123321** [alibaba/BizCharts#581]
![image](https://user-images.githubusercontent.com/7146036/47288413-9ca69980-d628-11e8-9b4e-76f20e01fbc3.png)
右边还有一个值没显示

**Comment by weepy3641** [comment]
相关问题解决 issue
 https://github.com/alibaba/BizCharts/issues/399
