### ISSUE TITLE
漏斗图数据源缺乏递进式百分比，现有基础漏斗图百分比为总额百分比，不适用实际漏斗图使用情况

### ISSUE THREAD

**Issue by lilianxie11** [alibaba/BizCharts#582]
- bizcharts Version:3.2.4
- Platform or react version:16.5.2

**Comment by weepy3641** [comment]
@lilianxie11 
没明白你的问题，最好能详细描述下并且给个 codepen 复现的 demo。

**Comment by lilianxie11** [comment]
@weepy3641 
实例中的漏斗图（比如基础漏斗图），展示中出现了百分比，但是这个百分比是求和百分比（比如实例中浏览网站的百分比是  50000/（50000+35000+25000+15000+8000）），实际情况中，即使是实例里的场景，漏斗图多展示一种递进的关系，比如浏览网站有50000人，放入购物车有35000人，这35000人是包含在50000人中的，所以应该要展示的百分比是类似：浏览网站 100%，放入购入车 35000/50000=70%。
以上这种计算百分比的方式没有在transform中找到

**Comment by weepy3641** [comment]
@lilianxie11 
你可有自己提前算好，然后按照普通的漏斗图做就可以了。
