### ISSUE TITLE
词云外面的容器设置宽度时，词云会出现错误

### ISSUE THREAD

**Issue by DonChengCheng** [alibaba/BizCharts#584]
- bizcharts Version: ^3.2.4
- Platform or react version:  react  ^16.3.2
- Mini Showcase(like screenshots):
<img width="1139" alt="b67af57d-daf4-4b14-939b-7dee4ee84354" src="https://user-images.githubusercontent.com/17453366/47410407-4d7f7680-d798-11e8-88e8-3920fec75bd2.png">

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@DonChengCheng 
最好能给一个复现的 codepen ，我们这才好定位问题。

**Comment by haossu** [comment]
遇到同样问题，请问大佬fix了吗
