### ISSUE TITLE
柱状图Legend样式问题

### ISSUE THREAD

**Issue by JediBai** [alibaba/BizCharts#585]
- bizcharts Version: 3.2.0+
- Platform or react version: antd-pro 1.2.0
- Mini Showcase(like screenshots):
- CodePen Link:
https://codepen.io/jedibai/pen/LgXMYY?editors=0010

- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/31715147/47473310-bae8e100-d844-11e8-9dda-b5c07cbd79be.png)
--------------------------
这个legend的提示图标被遮住了，如何调整样式让它正常显示~

**Comment by weepy3641** [comment]
这是由于顶部 图表的 padding 不够导致了，forcefit 时自动计算 padding  不够，你可以自己将  chart 的 padding 设置大些。
