### ISSUE TITLE
设置padding引发的怪异现象

### ISSUE THREAD

**Issue by yuanjie007** [alibaba/BizCharts#586]
- bizcharts Version:  3.2.7
- react version:  16.5.2
- Mini Showcase(like screenshots):

正常: 
![default](https://user-images.githubusercontent.com/18167335/47472821-9be94f80-d842-11e8-9ccf-8d8079fbbf4b.png)

**因为最后一个标签显示不全，所以我就想用padding来搞**

设置padding='auto' && forceFit=true 之后，正常显示了，但是我改变窗口大小: 
![treedemo](https://user-images.githubusercontent.com/18167335/47473425-27fc7680-d845-11e8-8628-ead4c8f6cde5.gif)

设置padding={right: 20} && forceFit=true 就好像被放大了:
![11111](https://user-images.githubusercontent.com/18167335/47473621-ecae7780-d845-11e8-885e-0214957dfa1d.png)

- CodePen Link: [柱状图](https://codepen.io/anon/pen/ReqqoX)

我用CodePen来设置padding，也会有放大的问题。

**Comment by weepy3641** [comment]
@yuanjie007 
这是由于动画的 bug 引起了，暂时你可以关闭图表的动画来避开这个 bug。
```
<Chart animate={false} >
```

也可以升级到 bizcharts@3.2.5-beta.3 版本来解决这个问题。

**Comment by yuanjie007** [comment]
@weepy3641  
设置 padding={{right: 20}} 还是会变大啊，用CodePen测试也会

**Comment by weepy3641** [comment]
@yuanjie007 
如果还有问题，麻烦给个 codepen。
