### ISSUE TITLE
bizcharts-plugin-slider 可以设置滑块文字左右影藏吗？

### ISSUE THREAD

**Issue by jiechud** [alibaba/BizCharts#587]
- bizcharts Version:   3.2.2
- bizcharts-plugin-slider version: 2.1.1-beta.1
- Mini Showcase(like screenshots): 
  标红的影藏
![image](https://user-images.githubusercontent.com/9709396/47475670-246ded00-d84f-11e8-934b-d4c2bd857d7b.png)

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@jiechud 
可以的，设置下 slider 的 text style 属性

```
<Slider textStyle={{
                         
                           fillOpacity: 0
                          }}/>
```
