### ISSUE TITLE
复杂图表dataview问题

### ISSUE THREAD

**Issue by syxxjgh** [alibaba/BizCharts#588]
- bizcharts Version: 3.2.4
- Platform or react version: 16.2.0

![image](https://user-images.githubusercontent.com/18287573/47540475-0617f800-d908-11e8-8004-50a854eb0563.png)

请问这种图形可以实现么 ,
如何用transfrom展开成这种图形的dv,
官网上只有单柱形图配单线图的组合图

**Comment by ssfxz** [comment]
- 可以
- 这中图表的数据使用transform不好处理，建议你自己处理数据
- 给你做了个简单了例子可以参考

**Comment by syxxjgh** [comment]
> * 可以
> * 这中图表的数据使用transform不好处理，建议你自己处理数据
> * 给你做了个简单了例子可以参考https://codepen.io/ssfxz/pen/OBrKPR?editors=1010

感谢
