### ISSUE TITLE
[feat request] initailize and resize to wrapper element.

### ISSUE THREAD

**Issue by aixfox** [alibaba/BizCharts#590]
- bizcharts Version: 3.2.4
- Platform or react version: 16.6.0

---

Fitting to wrappers size automatically is meaningful, developers would just concern about the styles(flex, percentage, vh, etc.) of wraps.

And it seems to be frequently issue, would you fit it like [echarts-for-react](https://github.com/hustcc/echarts-for-react)?

---

The ResizeObserver and resize event of object element will be helpful.

see ref:
https://github.com/hustcc/size-sensor/blob/master/src/sensors/object.js#L25
https://github.com/aixfox/hoc-bizcharts-chart-fit

**Comment by kreja** [comment]
Thanks for your advice. We'll take it into consideration.
@weepy3641 Have a look at this request.

**Comment by liunian** [comment]
@chenshuai2144 add this feature at #807, now at beta, will release in the future.

**Comment by weepy3641** [comment]
fix at bizcharts@3.5.3
