### ISSUE TITLE
面积图右侧多了滚动条

### ISSUE THREAD

**Issue by Luxiaoshi** [alibaba/BizCharts#592]
- bizcharts Version:3.2.5
- Platform or react version: umi
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

面积图右侧多了滚动条
![image](https://user-images.githubusercontent.com/8713879/47771669-2a684000-dd1f-11e8-950d-933a714375e3.png)
导致页面hui会无法拖动，只有当鼠标hover到chart后，拖动条才会消失。

**Comment by kreja** [comment]
应该跟你外部容器结构有关，请给个 demo，我这里无法复现
