### ISSUE TITLE
使用曲线图如何只用单纯的json数据渲染

### ISSUE THREAD

**Issue by zhdfly** [alibaba/BizCharts#593]
如题，json格式如下：
        { month: 'Jan', Tokyo: 7.0 },
        { month: 'Feb', Tokyo: 6.9 },
        { month: 'Mar', Tokyo: 9.5 },
        { month: 'Apr', Tokyo: 14.5 },
        { month: 'May', Tokyo: 18.4 },
        { month: 'Jun', Tokyo: 21.5 },
        { month: 'Jul', Tokyo: 25.2 },
        { month: 'Aug', Tokyo: 26.5 },
        { month: 'Sep', Tokyo: 23.3 },
        { month: 'Oct', Tokyo: 18.3 },
        { month: 'Nov', Tokyo: 13.9 },
        { month: 'Dec', Tokyo: 9.6 }
       { month: 'Jan',  London: 3.9 },
        { month: 'Feb',  London: 4.2 },
        { month: 'Mar',  London: 5.7 },
        { month: 'Apr',  London: 8.5 },
        { month: 'May', London: 11.9 },
        { month: 'Jun',  London: 15.2 },
        { month: 'Jul',  London: 17.0 },
        { month: 'Aug',  London: 16.6 },
        { month: 'Sep',  London: 14.2 },
        { month: 'Oct',  London: 10.3 },
        { month: 'Nov',  London: 6.6 },
        { month: 'Dec',  London: 4.8 }

**Comment by kreja** [comment]
https://bizcharts.net/products/bizCharts/demo/detail?id=line-curved&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE 参考这个案例做格式转换

**Comment by zhdfly** [comment]
> https://bizcharts.net/products/bizCharts/demo/detail?id=line-curved&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE 参考这个案例做格式转换

做数据转换没有问题，有没有什么方法不做数据转换的既可以渲染的
