### ISSUE TITLE
Legend 使用 containerTpl & itemTpl 创建图例，onClick无效

### ISSUE THREAD

**Issue by Arweil** [alibaba/BizCharts#594]
- bizcharts Version: 3.2.4
- Platform or react version: Chrome 69.0.3497.100  React 15.6.1
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/13160193/47901921-1a399780-debc-11e8-96a2-cd1746ab2867.png)
![image](https://user-images.githubusercontent.com/13160193/47901939-24f42c80-debc-11e8-9e98-64a1248a70e2.png)

Legend 使用 containerTpl & itemTpl 创建图例，onClick无效。
并且使用g2实例提供的chart.on('legend-item:onclick', ev => {})，onClick依旧无效。

是否在使用containerTpl & itemTpl的情况下需要addEventListener自定义事件。

**Comment by kreja** [comment]
请自定义事件

**Comment by Arweil** [comment]
好的，谢谢。我目前的解决方案是没有再使用Legend组件，自己另外写了组件完成Legend功能，通过g2Chart实例完成与chart的一些交互操作，这样事件方便一点。
附简单代码：
![image](https://user-images.githubusercontent.com/13160193/47972925-053b4f00-e0dc-11e8-92f1-1919ca813658.png)
