### ISSUE TITLE
百分比面积图问题

### ISSUE THREAD

**Issue by LoverMaker** [alibaba/BizCharts#595]
- bizcharts Version:4.6.0
- Platform or react version:15.5.4
- Mini Showcase(like screenshots):  
你们的示例  https://bizcharts.net/products/bizCharts/demo/detail?id=area-percentage&selectedKey=%E9%9D%A2%E7%A7%AF%E5%9B%BE  默认的legend的透明度降得很低，设置backgroud都无效
- CodePen Link:
https://codepen.io/anon/pen/bQbvqW?editors=1111 
比较两个图的legend

**Comment by kreja** [comment]
具体问题是？如果觉得颜色太淡了，可以自定义 legend

**Comment by LoverMaker** [comment]
默认的legend透明度有问题，不管怎么调都调不过来，最后加了 marker="square" 才显示正常。不是自定义的问题
