### ISSUE TITLE
guide设置position时，x轴坐标错位

### ISSUE THREAD

**Issue by lzuntalented** [alibaba/BizCharts#596]
- bizcharts Version: 3.2.4
- Platform or react version: 16.0.0
- CodePen Link: [实例地址](https://codepen.io/lzuntalented/pen/qQEKWa)

使用辅助 html时，放置的html位置不能正确定位，总是向左漂移一定距离
## 示例
有组数据：
    `const data = [
          { year: "1991", value: 3 },
          { year: "1992", value: 4 },
          { year: "1993", value: 3.5 },
          { year: "1994", value: 5 },
          { year: "1995", value: 4.9 },
          { year: "1996", value: 6 },
          { year: "1997", value: 7 },
          { year: "1998", value: 9 },
          { year: "1999", value: 13 }
        ]`
使用：
`
<Guide.Html position={{ year: '1998', value: 10 }} html="<div class='guide-item' style='color:red;' >我是测试文本</div>" />
              </Guide>
`
> 文本显示的x轴对应到 year：1994
预期对应1998

END 望能给出解答，谢谢！

**Comment by weepy3641** [comment]
@lzuntalented 
bizcharts@3.3.0-beta.3 已经修复。
