### ISSUE TITLE
使用DataSet，获取到Chart实例后调用changeData方法更新数据没有更新动画

### ISSUE THREAD

**Issue by lx70770** [alibaba/BizCharts#597]
- bizcharts Version: 3.1.0
- Platform or react version: umi 2.1.0

如果不使用DataSet渲染图表数据，使用<Chart/>的 onGetG2Instance 方法获取chart实例，调用chart.changeData(newData)，图表更新会有动画

如果使用DataSet，请问该如何更新数据才会有更新动画

**Comment by ssfxz** [comment]
changeData是强制替换数据源，因此都是没有动画的
可以修改dataview后使用repaint更新图表
`
const updateData = () => {
  dv.transform({
    type: 'map',
    callback: (row, index) => {
      if (index === 0)
        row.sold = 500;
      return row;
    }
  });
  chartIns.repaint();
}
`

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/issues/412
ref issue
