### ISSUE TITLE
烛型图使用Label，当被放大时，Label文字显示与图形重叠

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#598]
正常时：
![image](https://user-images.githubusercontent.com/23026361/48038445-97f6ef00-e1ab-11e8-8b5c-d5066c70c66d.png)
放大时：
![_20181106100845](https://user-images.githubusercontent.com/23026361/48038528-0045d080-e1ac-11e8-9e2a-ed027096914f.png)

**Comment by Leslie2014** [comment]
这个放大是浏览器放大吗？这个应该不属于默认表现问题的。如果你要适配放大版本，可以调整 Label offset 属性。

**Comment by houzip** [comment]
@Leslie2014 不是 是用Slider放大的效果
