### ISSUE TITLE
词云有个bug

### ISSUE THREAD

**Issue by chjiyun** [alibaba/BizCharts#599]
你们的demo 没有考虑词语出现次数全部相等的情况，导致max-min 也就是分母为0的错误，最后图也出不来，数学类错误

**Comment by ssfxz** [comment]
bug已确认，感谢您为开源事业做出的贡献，我们会尽快修复该问题。

**Comment by weepy3641** [comment]
这是用户代码，并非 bizcharts 库中的，用户自己保护一下就行了。

站点 demo 已经修复待发布。
