### ISSUE TITLE
双轴图标的两侧Y轴的标题如何设置？

### ISSUE THREAD

**Issue by xuchenchenBoy** [alibaba/BizCharts#600]
在Api里找不到对应的设置方法，参照图表示例：https://bizcharts.net/products/bizCharts/demo/detail?id=g2-double-axes&selectedKey=%E6%A6%82%E8%A7%88.

**Comment by ssfxz** [comment]
在需要显示标题的轴组件里配置title属性即可。
请参考：https://bizcharts.net/products/bizCharts/api/axis#title
