### ISSUE TITLE
烛型图和线图在同一个view里，crosshairs根据线图定位

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#601]
烛型图和线图在同一个view里，crosshairs根据线图定位，
能不能设置成根据烛型图定位，
而且烛型图的crosshairs没法定位 在图上是自由移动的
![image](https://user-images.githubusercontent.com/23026361/48048835-b672df80-e1d7-11e8-8bf8-541058c5f89e.png)

**Comment by Leslie2014** [comment]
调整下这两个图的代码书写顺序试试。另外方便的话提供个 codepen 的可复现链接吧，方便我们排查问题
