### ISSUE TITLE
堆叠柱形图Lable图形文本无法在图形中上下居中

### ISSUE THREAD

**Issue by wangdedi1990** [alibaba/BizCharts#602]
![image](https://user-images.githubusercontent.com/28214000/48058198-d06cec00-e1f0-11e8-9595-4c91c6e31621.png)

![image](https://user-images.githubusercontent.com/28214000/48058270-fb574000-e1f0-11e8-80ee-00b711e83b2e.png)
如同所示，图形文本上下无法居中在图形中，自定义文本的方法htmlTemplate这个function用法上好像也有问题，没有解析html元素；

**Comment by wangdedi1990** [comment]
https://codesandbox.io/s/4095jjpkvw

**Comment by Leslie2014** [comment]
已在钉钉群私聊解决~
