### ISSUE TITLE
在服务端渲染的时候直接使用了document对象，导致服务端渲染失败

### ISSUE THREAD

**Issue by xiaoTuiMao** [alibaba/BizCharts#603]
- bizcharts Version: 3.2.5-beta.4
- Platform or react version: 15
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/15075094/48174404-d1159780-e342-11e8-8360-032f4faf0779.png)

![image](https://user-images.githubusercontent.com/15075094/48174458-0de18e80-e343-11e8-9552-58b0613fc7ca.png)

**Comment by Leslie2014** [comment]
在 node 端 请使用 jsdom 或类似的框架 mock 浏览器环境

**Comment by kongyes** [comment]
是怎么解决的？

**Comment by SetsunaMango** [comment]
请问是怎么解决的,我也是这个问题

**Comment by SetsunaMango** [comment]
> 是怎么解决的？

哥们你解决这个问题了吗

**Comment by kongyes** [comment]
> > 是怎么解决的？
> 
> 哥们你解决这个问题了吗

解决了，不支持服务端渲染的组件都可以用这种方法：

//引入
let bizcharts;  

if (process.browser) {  
    bizcharts = require('bizcharts');
  }

//使用
 {process.browser &&
    <bizcharts.Chart height={270} width={280} data={dv} scale={cols} padding={[20, 30, 80, 50]}>
        <bizcharts.Legend />
        <bizcharts.Axis name="date" />
       <bizcharts.Axis name="value" />
       <bizcharts.Tooltip crosshairs={{ type: "y" }} />
       <bizcharts.Geom type="line" position="date*value" size={2} color={'key'} shape={'smooth'} />
       <bizcharts.Geom type='point' position="date*value" size={4} shape={'circle'} color={'key'} style={{ stroke: '#fff', lineWidth: 1 }} />
    </bizcharts.Chart>
}

**Comment by crane0** [comment]
如果你使用的是 next 进行服务端渲染，next 有做处理，可以单独将这个组件不使用 ssr 的方式引入。

https://nextjs.org/docs#basic-usage-also-does-ssr

我使用下面的例子解决了。
```
import dynamic from 'next/dynamic'

const DynamicComponent = dynamic(() =>
  import('../components/hello').then(mod => mod.Hello)
)

function Home() {
  return (
    <div>
      <Header />
      <DynamicComponent />
      <p>HOME PAGE is here!</p>
    </div>
  )
}

export default Home
```
