### ISSUE TITLE
How to implement showing values at cursor position

### ISSUE THREAD

**Issue by nodeworks** [alibaba/BizCharts#604]
- bizcharts Version: 3.2.4
- Platform or react version: React 16.2.0
- CodePen Link: https://codepen.io/team/amcharts/pen/wjVXmY

How would I go about displaying a chart where you can display the values wherever the cursor is. The codepen above is a good example of what I mean. Particularly the Y axis, whenever you move the cursor it displays on the left the value of where the cursor is, regardless of the values of the items within the chart.

I'm assuming this would need to be done with a tooltip? But every tooltip implementation i've seen only shows the values of the data items and not the position in the grid.

Any info would be great!

**Comment by Leslie2014** [comment]
Hi, Tooltip display default title is the X position, and the value within the chart is Y position。if you want  to show crosshair，you can use `showCrosshairs` attr on Tooltip， here is demo: https://codepen.io/leslie2014/pen/pQbGrW

**Comment by liunian** [comment]
@nodeworks It's possible, do not enable the default tooltip, use `onMousemove` event to get canvas coordinates, and then draw custom information with `Guide` or other solutions.

But, this is not our main requirement, and it might be difficult to locate the exact value of given dataset if any value will be visible.
