### ISSUE TITLE
使用柱形图的时候x轴label太长文字会堆叠在一块

### ISSUE THREAD

**Issue by youpeng929** [alibaba/BizCharts#605]
![image](https://user-images.githubusercontent.com/36942873/48237569-311f4300-e402-11e8-867b-511ae9b9c05e.png)

**Comment by youpeng929** [comment]
图表能不能设置滚动

**Comment by Leslie2014** [comment]
你可以使用  forceFit 来迫使图表的宽高与父容器保持一致，当然也可以在 Chart 上设置固定宽高。 滚动的话应该是在包裹图表的容器层做的事情。

关于 label 文字压缩这块，你可以使用 `autoRotate` 属性来自动旋转 label 文字，也可以使用 `textStyle` 来控制以达到你想要的效果。

可以参考文档：https://www.bizcharts.net/products/bizCharts/api/label#autorotate
