### ISSUE TITLE
使用了DataSet里的transform 中的fold 怎么自定义Legend？

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#606]
使用了DataSet里的transform 中的fold类型
自定义图例的时候？怎么写onClick事件，控制同一个Geom中不同的线显隐？

**Comment by Leslie2014** [comment]
请参考文档：https://www.bizcharts.net/products/bizCharts/api/legend#onclick

**Comment by 1053061407** [comment]
> 使用了DataSet里的transform 中的fold类型
> 自定义图例的时候？怎么写onClick事件，控制同一个Geom中不同的线显隐？

同学你这个问题解决了么？他解决方案提供的链接就是个这个
![image](https://user-images.githubusercontent.com/22407482/52911197-9cb75d00-32db-11e9-9181-045e072ab177.png)
什么信息也获取不到啊

**Comment by 1053061407** [comment]
在另外一个issue里面找到了解决方案，https://github.com/alibaba/BizCharts/issues/560

主要原理就是在legend的onClick事件中,不能再使用[官方demo](https://bizcharts.net/products/bizCharts/demo/detail?id=g2-double-axes&selectedKey=%E6%A6%82%E8%A7%88)中的
```
if (geom.getYScale().field === value) {
   if (checked) {
      geom.show()
  } else {
          geom.hide()
  }
}
```
来控制geom的显示隐藏了。因为geom.getYScale().field的值是使用type: fold的transform中的value字段的值，不等于所点击的legend的值。要想获取legend对应的具体的线或者柱，得通过geom.getShapes()，获取geom的所有shapes，然后一个个遍历直到找到legend对应的shape，然后设置它的
```
shape._cfg.visible = !shape._cfg.visible
```
重绘canvas，就可以实现控制同一个Geom中不同的线显隐。

以上这些geom.getYScale()，geom.getShapes(),都是g2的api，感觉bizcharts的文档还是不详细，官方demo也太少，遇到问题在网上搜到解决方案很费劲。要想实现复杂的图表纯靠自己摸着石头过河。
