### ISSUE TITLE
饼图 跟 矩形树图 怎么设置图表标题

### ISSUE THREAD

**Issue by li305263** [alibaba/BizCharts#608]
- bizcharts Version: 3.2.5-beta.4
- Platform or react version: 15.6.1, 

const scale = {
            percent: {
              alias:'标题',
              formatter: val => {
                val = (val * 100).toFixed(2) + "%";
                return val;
              },
            },
          };
<Axis name="percent" title/>
这样设置的话 标题无效, 
矩形树图好像没设置标题的地方?

**Comment by Leslie2014** [comment]
标题建议在图表元素前面加个div，然后调整css处理
