### ISSUE TITLE
左侧存在导航栏 当导航栏收起时 bizchart 容器宽度变大 但是图大小并不改变 不能够自适应

### ISSUE THREAD

**Issue by kanxuehe** [alibaba/BizCharts#610]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ssfxz** [comment]
建议可以从以下几个方面排查：

- Chart组件是否配置了forceFit属性
- forceFit监听的是图表容器dom的大小，因此请检查容器大小是否发生了变化
- 如果容器大小没有发生变化，请从布局方面debug该现象的原因

**Comment by ZhiGang-Fang** [comment]
我也遇到这样的问题，所使用的环境如下：

react ：v16.5.0；
BizCharts：最新版本；
操作系统：mac pro 13寸
browser：Chrome 版本 70.0.3538.110（正式版本） （64 位）

容器大小没有发生变化

问题描述：
1.BizCharts 的 forceFit 属性已经设置
2.导航收起展开时，放置Chart 的容器大小会变化，其他的图表是能正常自适应，只有柱形图会存在问题
3. 当左侧导航收起时，能正常自适应
4..当左侧导航收起展开时，自适应失效

排查主要的原因是 padding='auto' 时，是不生效的。可以参照具体的图片：

<img width="642" alt="wx20181207-004800 2x" src="https://user-images.githubusercontent.com/24228407/49598625-0224ce80-f9ba-11e8-9ba2-002913a3db5f.png">
<img width="368" alt="wx20181207-004820 2x" src="https://user-images.githubusercontent.com/24228407/49598634-04872880-f9ba-11e8-91aa-9b9fa4463a89.png">

CodePen模板 ： https://codepen.io/pen/?editors=1010 （通过调整浏览器的大小验证）

**Comment by JJoan0116** [comment]
我也遇到了这种问题，父容器的width明明变大了，但是并没有自适应。后来我去源码中找了一下，如果没有找错的话，自适应监听的是resize函数，也就是说只有当窗口大小发生变化，我的canvas画布的宽度才会变大
`  
_proto._initEvents = function _initEvents() {
    if (this.get('forceFit')) {
      window.addEventListener('resize', Util.wrapBehavior(this, '_initForceFitEvent'));
    }
  };
` @liunian
