### ISSUE TITLE
怎么做Tooltip图表联动

### ISSUE THREAD

**Issue by 15531400827** [alibaba/BizCharts#615]
- bizcharts Version:  3.3.0
- Platform or react version: 16.5.0
- CodePen Link: https://codepen.io/15531400827/pen/pQWVyy?editors=1010
- 以做到legend联动，点击图例两个图表同步， 如何做到ToolTip也联动呢， 就是滑到任意一个图表上Tooltip同时出现（版本使用最新版就行）
- 还感觉有一个问题就是 鼠标滑到另一个图表上 Tooltip不消失 这个体验在图表离得近的情况下感觉不好，有没有办法解决（可以看例子上下滑动试试）

**Comment by weepy3641** [comment]
@15531400827 
需要调用 g2 的接口做。 showTooltip 和 hideTooltip。 监听一个图表的 tooltip 事件，将另一个图表的 tooltip 唤起。
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html

**Comment by 15531400827** [comment]
@weepy3641 感谢回答，去G2的issues里面看了一下，这样是可以解决的，但是感觉有必要分装成一个组件来使用，就像下面这个说的这样：https://github.com/antvis/g2/issues/485
阿里团队没有分装联动组件的想法吗。。

**Comment by weepy3641** [comment]
@15531400827  暂时没有哦。

**Comment by maplor** [comment]
@15531400827  其实我在内部封装了一个包，但是还没有开源出来，不好意思哈。只能先自己实现了。

**Comment by ZindexYG** [comment]
@15531400827 
bizcharts Version: 3.5.5
Platform or react version: 16.8.6

[![Edit old-river-f6y48](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/old-river-f6y48?fontsize=14)

根据 G2 文档 和 Bizcharts 已经做出来了

**Comment by beadth** [comment]
> @15531400827
> bizcharts Version: 3.5.5
> Platform or react version: 16.8.6
> 
> [![Edit old-river-f6y48](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/old-river-f6y48?fontsize=14)
> 
> 根据 G2 文档 和 Bizcharts 已经做出来了

404了老哥
