### ISSUE TITLE
bizchart 绘图区域背景，不能实现渐变色吗？

### ISSUE THREAD

**Issue by wax1026** [alibaba/BizCharts#617]
![image](https://user-images.githubusercontent.com/18465169/48814374-7c781080-ed75-11e8-9d08-21c4d53faf1e.png)
如何实现图中渐变色，谢谢！

**Comment by weepy3641** [comment]
@wax1026  
可以的，fill 配置为内置格式的渐变色即可。
```
 <Chart
            background={{
              fill: "l (270) 0:rgba(255, 146, 255, 1) .5:rgba(100, 268, 255, 1) 1:rgba(215, 0, 255, 1)"
            
            }}
            height={400} data={data} scale={cols} forceFit
          >
```

参考demo
https://codepen.io/anon/pen/oQpygP?editors=1010

api:
https://antv.alipay.com/zh-cn/f2/3.x/api/canvas.html#_%E6%B8%90%E5%8F%98%E8%89%B2

**Comment by wax1026** [comment]
3q
