### ISSUE TITLE
如何实现legend分页显示

### ISSUE THREAD

**Issue by 15531400827** [alibaba/BizCharts#618]
- bizcharts Version: 3.3.0
- CodePen Link:  https://codepen.io/15531400827/pen/pQWVyy
- 如演示中第一个图，实际使用中 不想让图例换行， 支持图例翻页现实吗？

**Comment by weepy3641** [comment]
@15531400827 
bizcharts@3.4.0 图例翻页已经支持。
参考 demo：
https://codepen.io/anon/pen/bQaMjP?editors=1010

**Comment by 15531400827** [comment]
@weepy3641 你发的链接可以正常打开？ 为什么我点开之后在不停的闪，一直在加载。。。。

**Comment by weepy3641** [comment]
@15531400827 
我这没问题，很正常。
