### ISSUE TITLE
在版本 3.4.0 中使用Axis组件时，设置了rotate 时，x轴只有第一个生效其他不会改变

### ISSUE THREAD

**Issue by ZhiGang-Fang** [alibaba/BizCharts#625]
- bizcharts Version: 3.4.0 
- Platform or react version: 16.5.0
- Mini Showcase(like screenshots):
- CodePen Link: https://codepen.io/zhigang-fang/pen/bQKoQJ?editors=1010
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by liunian** [comment]
g2 的 bug，已反馈到 g2，等待其修复 https://github.com/antvis/g2/issues/1069

**Comment by liunian** [comment]
根据 antvis/g2#1069 ，目前 axis label 的 rotate 的设置方式是把 `rotate` 属性提到外层，和 `textStyle` 同级，形如：

```jsx
<Axis
  name="time"
  grid={null}
  label={{
  rotate: 30,
  textStyle:{
    fill: '#000'
  }
}}
```

**Comment by ZhiGang-Fang** [comment]
@liunian 记得同步 更新https://bizcharts.net/products/bizCharts/api/axis#label 的API 文档谢谢
