### ISSUE TITLE
要求只有鼠标在柱状图内才显示Tooltip内容，鼠标所在位置不在区域内了还是在显示Tooltip

### ISSUE THREAD

**Issue by markyun** [alibaba/BizCharts#628]
- bizcharts Version:"^3.1.10",
- Platform or react version: "^16.4.1",
- Mini Showcase(like screenshots): https://riddle.alibaba-inc.com/riddles/e5e9926c
- CodePen Link: https://riddle.alibaba-inc.com/riddles/e5e9926c 
要求只有鼠标在柱状图内才显示Tooltip内容，鼠标所在位置明显已经不在区域内了还是在显示；这样数据会误导用户，需要修改

![image](https://user-images.githubusercontent.com/2833137/49009789-64a4f000-f1ac-11e8-8581-0ed883cf81ff.png)

**Comment by liunian** [comment]
tooltip 默认是全画布响应的，如果需要仅指定图形上才展示，那么需要通过[图形元素事件](https://bizcharts.net/products/bizCharts/api/chart#%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%E4%BA%8B%E4%BB%B6)以及[Guide](https://bizcharts.net/products/bizCharts/api/guide) 来自行实现。

**Comment by markyun** [comment]
@afc163 @xiaran030 @liunian  能帮忙看看这个issues吗？

要求：只有鼠标在柱状图内才显示Tooltip内容，现在的Tooltip显示的时候，鼠标所在位置明明已经不在区域内了还是在显示，数据会误导用户，需要修改。

**Comment by weepy3641** [comment]
@markyun 
跟 g2 的人讨论了下，暂时没办法做到 hover 的时候精确选中柱子，出现 tooltip。
我向 g2 提个 issue，要等他们那边排期做。
https://github.com/antvis/g2/issues/1088
