### ISSUE TITLE
BizCharts区域图和g2-bush结合使用的时候没有框选放大效果 

### ISSUE THREAD

**Issue by ZhaiZH** [alibaba/BizCharts#631]
当我使用g2-bush想做某个区域的放大效果时。可以在图表上框选 但是图表并没有作出放大效果，时代码问题问 还是存在冲突？
-------------------------
代码：
<Chart
          height={window.innerHeight}
          data={dv}
          padding={"auto"}
          scale={scale}
          forceFit
          onGetG2Instance={g2Chart => {
            new Brush({
              canvas: g2Chart.get('canvas'), // must be set
              g2Chart, // if you want to filter data by default, please set the chart
              type: 'X', // set the brush type, default value is 'XY'
            });
          }}
        >
          <Tooltip crosshairs />
          <Axis />
          <Legend />
          <Geom type="area" position="year*value" color="type" shape="smooth" />
          <Geom
            type="line"
            position="year*value"
            color="type"
            shape="smooth"
            size={2}
          />
        </Chart>

**Comment by weepy3641** [comment]
@ZhaiZH 
不确定问题了，你可以写个 codepen 看下。

如下是区域图 brush demo。
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-brush-ds-state&selectedKey=%E6%A6%82%E8%A7%88
