### ISSUE TITLE
Bizcharts中柱状图的宽度不好修改

### ISSUE THREAD

**Issue by yuwangjie123** [alibaba/BizCharts#632]
分组柱状图的柱子的宽度当有一个数据的话就会变得非常大，用了size，两个柱子之间的间距也会变大，怎么办，非常急，这是不是bug
![default](https://user-images.githubusercontent.com/45473703/49263489-c18ef780-f485-11e8-9d29-c6100fd5fa2e.PNG)

**Comment by yuwangjie123** [comment]
不是这一张图
![default](https://user-images.githubusercontent.com/45473703/49263472-a6bc8300-f485-11e8-9903-2bbf66a6ad7b.PNG)

**Comment by weepy3641** [comment]
https://codepen.io/anon/pen/GwPpQM?editors=1010

**Comment by hugo1o1** [comment]
设置了size之后，marginRatio 也不再生效
