### ISSUE TITLE
bizcharts-plugin-slider 默认选择局部范围问题

### ISSUE THREAD

**Issue by TivonJJ** [alibaba/BizCharts#633]
[https://codepen.io/tivonjj/pen/oQJWrv](https://codepen.io/tivonjj/pen/oQJWrv)

上面代码示列，在数据量过大的时候我默认选中最后10条数据范围，但是这样整个slider的范围就变成最后10条了，无法拉动到之前的。 正常应该是以dv的起始值为准，只是滑块范围默认在最后10条数据。
我尝试把start初始0，数据出来后延迟setState('start','xxx')来改变值，图表数据范围变化了，但是slider的滑块位置并没有变化。

**Comment by weepy3641** [comment]
https://codepen.io/anon/pen/vQPmdv
需要配的是 slider 的 start end 属性
https://github.com/alibaba/BizCharts/tree/master/plugin/slider#7-start-number--string
