### ISSUE TITLE
chart filter state 变后，不会触发图表更新

### ISSUE THREAD

**Issue by ntscshen** [alibaba/BizCharts#634]
- bizcharts Version:^3.4.1
- Platform or react version:^16.4.1
- CodePen Link: https://codepen.io/ntscshen/pen/vQvZEG?editors=0010

**Comment by weepy3641** [comment]
@ntscshen 
你的 filter  配的有问题。
https://codepen.io/anon/pen/XyGEaP?editors=0010

**Comment by ntscshen** [comment]
@weepy3641 
如果是初始化的过滤问题，确实是filter配置的问题。
在初始化的时候点击显示隐藏按钮没有问题，但是当点击下面的图例（Tokyo、London、money、money1、money2）任一一个之后，再次点击左上角的显示隐藏按钮，此时filter就不会生效。

**Comment by weepy3641** [comment]
新版本已经修复。

**Comment by chinaxiaoyy** [comment]
@weepy3641  3.5.1版本貌似还是没有修复，setState后，render下能拿到最新的state，但是filter下拿到的state还是旧值

**Comment by weepy3641** [comment]
@chinaxiaoyy 
我这再看下。

**Comment by Thomstrong** [comment]
我这里也是遇到了一个类似的问题。但是我的目的是通过`chart`实例（以下简称chart）获取geom的数据。
我这里使用的过程是通过chart的`chart.filter()`方法配置的filter，然后通过chart调用到`geom.get('dataArray')`获取数据。同样不会重新应用我>=2次的filter。
但是我发现，如果我每次重新配置filter之前，使用`this.chart.filter('x', null);`这样的方法重置filter之后，下一次就能再正常调用到`geom.get('dataArray')`获取数据。

**Comment by LinkChenzy** [comment]
bizcharts@3.5.4版本仍遇到同样的问题，chart的filter在setState之后仍然之前的值。
解决的方法是在传入chart的data时对数据进行filter,拿到想要的数据

**Comment by panfangqi** [comment]
针对[https://codepen.io/anon/pen/XyGEaP?editors=0010](https://codepen.io/anon/pen/XyGEaP?editors=0010)这个例子的解决方法：
1.通过onGetG2Instance获取chart的实例
2.在componentDidMount重新赋值chart.filter
3.使用chart.repaint()刷新

### 代码：

import React, { Component } from 'react';
import { Chart, Geom, Axis, Tooltip, Legend } from 'bizcharts';
import DataSet from '@antv/data-set';

class About extends Component {
    constructor(props) {
        super(props);
        this.state = {
            filterName: 'Tokyo',
            data: [
                { month: "Jan", Tokyo: 70.0, London: 3.9, money: 10, money1: 10, money2: 10 },
                { month: "Feb", Tokyo: 6.9, London: 4.2, money: 11, money1: 20, money2: 20 },
                { month: "Mar", Tokyo: 9.5, London: 50.7, money: 12, money1: 30, money2: 30 },
                { month: "Apr", Tokyo: 44.5, London: 8.5, money: 15, money1: 40, money2: 20 },
                { month: "May", Tokyo: 18.4, London: 11.9, money: 20, money1: 50, money2: 10 },
                { month: "Jun", Tokyo: 21.5, London: 15.2, money: 30, money1: 60, money2: 20 },
                { month: "Jul", Tokyo: 25.2, London: 17.0, money: 10, money1: 70, money2: 30 },
                { month: "Aug", Tokyo: 26.5, London: 16.6, money: 50, money1: 80, money2: 10 },
                { month: "Sep", Tokyo: 23.3, London: 24.2, money: 60, money1: 90, money2: 20 },
                { month: "Oct", Tokyo: 18.3, London: 10.3, money: 30, money1: 80, money2: 30 },
                { month: "Nov", Tokyo: 43.9, London: 6.6, money: 80, money1: 70, money2: 10 },
                { month: "Dec", Tokyo: 9.6, London: 4.8, money: 50, money1: 60, money2: 20 }
            ]
        };
    }
    componentDidUpdate() {
        const { filterName } = this.state;
        if (this.chart) {
            this.chart.filter('city', val => val === filterName);
            this.chart.repaint(); // 这句很重要
        }
    }
    onGetG2Instance(chart) {
        this.chart = chart;
    }
    handleSelectNone() {
        this.setState({ filterName: 'xxx' });
    }
    handleSelectFirst() {
        this.setState({ filterName: 'Tokyo' });
    }
    render() {
        const { data, filterName } = this.state;
        const ds = new DataSet();
        const dv = ds.createView().source(data);
        dv.transform({
            type: 'fold',
            fields: ['Tokyo', 'London', 'money', 'money1', 'money2'], // 展开字段集
            key: 'city', // key字段
            value: 'temperature' // value字段
        });
        const cols = {
            month: {
                range: [0, 1]
            }
        };
        return (
            <div>
                <button onClick={this.handleSelectNone.bind(this)}>隐藏图表</button>
                <button onClick={this.handleSelectFirst.bind(this)}>显示图表</button>
                <Chart height={400} data={dv} scale={cols} forceFit
                    onGetG2Instance={this.onGetG2Instance.bind(this)}
                    filter={[['city', (val) => {
                        return filterName == "" ? val : val == filterName;
                    }
                    ]]}
                >
                    <Legend
                        allowAllCanceled={true}
                    />
                    <Axis name="month" />
                    <Axis name="temperature" label={{ formatter: val => `${val}°C` }} />
                    <Tooltip crosshairs={{ type: "y" }} />
                    <Geom type="line" position="month*temperature" size={2} color={'city'} shape={'smooth'} />
                    <Geom type='point' position="month*temperature" size={4} shape={'circle'} color={'city'} />
                </Chart>
            </div>
        );
    }
}

export default About;

**Comment by LyndonXiao** [comment]
都2020年末了，3.5.9版本还有这个bug，参考的@LinkChenzy 的方法，算是能用了

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/98625431-8de3ca00-234a-11eb-9597-651fe570c8e8.png)

```js
setTimeout(() => { 
if (chart) {
  chart.filter('字段', () => {}); 
  chart. repaint()
}
 }, 0)
```
setTimeout 用来异步刷新，先让图表完成自己的绘制。然后再执行，filter，最后要repaint一下。
