### ISSUE TITLE
自定义动画引用问题

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#635]
![image](https://user-images.githubusercontent.com/23026361/49349293-ee8d1580-f6e4-11e8-92fb-1f1b824b61b0.png)
自定义动画时里面这个BizCharts 是从哪引用的？

**Comment by weepy3641** [comment]
@houzip 
BizCharts 这个变量指的是 bizcharts 库的全局作用域。
如果是 umd 文件直接引入，那么指 window.BizCharts

如果是 npm 包引入，需要自己顶一下。
```
import * as BizCharts form "bizcharts";
```
animate 可以这样引入：
```
import  { Animate } form "bizcharts";
```
