### ISSUE TITLE
我x轴有三个指标，我想前两个指标用柱状图，最后一个指标用折线图，能实现吗

### ISSUE THREAD

**Issue by leai-jiang** [alibaba/BizCharts#637]
- bizcharts Version: 3.4.1
- Platform or react version: 16.2.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@leai-jiang 
可以，弄三个 geom 就可以了。

**Comment by leai-jiang** [comment]
@weepy3641 谢谢及时反馈，用三个geom，但是读取的是一个 data 啊，就会显示三个树状，三个折线
![image](https://user-images.githubusercontent.com/30949881/49368765-8b25d680-f72a-11e8-94bd-f0b9761b8ca7.png)

**Comment by leai-jiang** [comment]
![image](https://user-images.githubusercontent.com/30949881/49368876-e6f05f80-f72a-11e8-842a-14ddaf9cdc1a.png)
这是我想实现的结果

**Comment by weepy3641** [comment]
数据处理下就可以了。
可以用分组柱状图和一条折线图做。
https://bizcharts.net/products/bizCharts/demo/detail?id=bar-grouped-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE
https://bizcharts.net/products/bizCharts/demo/detail?id=line-basic&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE

或者：
https://codepen.io/anon/pen/MPRmqR
