### ISSUE TITLE
饼图 写的是整数，显示有小数点，怎么解决呢？

### ISSUE THREAD

**Issue by Angelababy0928** [alibaba/BizCharts#640]
![image](https://user-images.githubusercontent.com/26860828/49416470-0633cf00-f7b5-11e8-9735-b0375c3ac51a.png)

![image](https://user-images.githubusercontent.com/26860828/49416485-0e8c0a00-f7b5-11e8-83f4-1bcb873b9551.png)

**Comment by liunian** [comment]
这是 JavaScript 浮点数精度运算的常见问题，`28` 对应的占比是 `0.28`，`* 100` 得到的是 `28.000000000000004`。

考虑到两位小数适用于大多数的场景，所以你代码里的 `val = val * 100 + '%'` 可以替换为 `val = (val * 100).toFixed(2) - 0 + '%'`
