### ISSUE TITLE
Questions about package.json field module.

### ISSUE THREAD

**Issue by aixfox** [alibaba/BizCharts#642]
- bizcharts Version: 3.4.1
- Platform or react version: 16.6.0

以下说明有可能有理解错误之处，或者有些地方 bizcharts 也有自己的考虑，希望可以跟进或说明一下。

---

1、能否去除  package.json field browser？

webpackConfig.resolve.mainFields 在 target: 'web'  的时候为 ['browser', 'module', 'main']。
现在 `"browser": "umd/BizCharts.js",` 这个值会导致 webpack 打包的时候使用的是 umd，这样按需加载  bizcharts/es6 或者 bizcharts/lib 就失效了。

webpack-bundle-analyzer 图如下：

![default](https://user-images.githubusercontent.com/28643426/49421470-05a63300-f7cb-11e8-9ed9-ca836a41fde2.png)

实际上按需加载是要这样：

![default](https://user-images.githubusercontent.com/28643426/49421490-1bb3f380-f7cb-11e8-8d39-44d2edfaee78.png)

关于 #327 中要求增加 field browser，可能是因为当时 es6 下的代码没有编译？现在 3.4.1 中 es6 的代码是可以被 uglifyjs-webpack-plugin 成功处理的。

希望可以去除 browser，像 antd 那样只声明 module 和 main 就可以了，这样会使用 bizcharts/es6 或者 bizcharts/lib，避免整个 bizcharts。

---

2、es6 的编译结果好像有错？

babel 编译至 es6 的时候，不应该把 import/export 编译成 commonJS 的 require/module.exports，webpack 处理 field module 'es6/index.js' 的意义在于，利用 es module 规范（静态的），给模块加上注释，让 uglify 处理达到 tree shaking 的效果，但是现在 es6 和 lib 的编译结果好像一模一样，居然欺骗可怜的 webpack。

**Comment by aixfox** [comment]
@weepy3641 
这里的第一个问题，是我这边弄错了，webpack 打包了一个 umd 的版本在 vendor chunk，es6 的被打包在一个 async chunk 的小角落里，一时没有发现。Bizcharts 这个字段没有问题，希望没带来太多的困扰…

第二个问题的解决方法是使用 @babel/preset-env，可以参照
https://github.com/ant-design/antd-tools/blob/master/lib/getBabelCommonConfig.js#L33

另外还需要注意一下 targets。如果不希望升级 babel 7 的话，babel 6 也有这个 preset。

**Comment by Thyiad** [comment]
@aixfox 居然欺骗可怜的 webpack

这句话看了真是忍俊不禁，的确啊，es6的输出是commonjs的，我尝试了一下vite，里面一直报错，就是这个原因。。现在还不知道咋整。。。
