### ISSUE TITLE
chart销毁

### ISSUE THREAD

**Issue by xiayu1986** [alibaba/BizCharts#643]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
想在componentWillUnmount中将图表chart销毁该如何做？
![default](https://user-images.githubusercontent.com/13351108/49501207-4bd3c300-f8ad-11e8-8b63-6c789f494dc5.png)

**Comment by weepy3641** [comment]
@xiayu1986 

bizcharts 图表在 <Chart /> 节点 unmount 的时候，内部会自动销毁 chart 实例，因此用户无需外部销毁chart。

如果你直接操作 chartInstance 销毁，但是 <Char /> 虚拟节点还在，页面后续的图表相关更新、操作会有问题的。
