### ISSUE TITLE
分组柱状图可以用两个Geom吗

### ISSUE THREAD

**Issue by xxxlf** [alibaba/BizCharts#644]
因为数据格式有所不同，可以用两个Geom来实现分组柱状图吗？  还是说必须要用demo上的数据格式？
如果用demo上的格式Geom的yan颜色怎么分别指定。谢谢~
<img width="590" alt="20181205195232" src="https://user-images.githubusercontent.com/39181844/49513016-9dd71180-f8ca-11e8-9178-e7afbb85de6b.png">

**Comment by weepy3641** [comment]
@xxxlf 
默认是不支持分组柱状图用两个 geom 的，因为这样相当于双 y 轴分组柱状图。
比较难看出图表的意图。

如果一定要做，可以用 shape 定制实现。
https://bizcharts.net/products/bizCharts/api/shape
