### ISSUE TITLE
环图在某些数据下显示会有问题

### ISSUE THREAD

**Issue by dbfu** [alibaba/BizCharts#650]
- bizcharts Version: 3.4.1
- Platform or react version: 16.4.1
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/32224358/49773280-697cae80-fd2b-11e8-8100-67028d72020e.png)
- CodePen Link: https://codepen.io/anon/pen/oJgqJY?&editable=true
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
3.4.1 版本无法复现。
https://codepen.io/anon/pen/LMGvGP?editors=1010
