### ISSUE TITLE
数据源是csv，数字类型变成了字符串，柱状图第一条内容显示不完整

### ISSUE THREAD

**Issue by lijiangwei** [alibaba/BizCharts#651]
- bizcharts Version: 3.4.1
- Platform or react version: react-16.4.1
- Mini Showcase(like screenshots): 
   http://wap.xiaosl.cn/demo/
- CodePen Link: 
https://github.com/lijiangwei/bizcharts-bar-demo/blob/master/components/Bar/BasicBar.js
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

csv数据源：
genre,sold,income
Strategy,115,667
Action,120,982
Shooter,350,5271
Other,150,3710
Sports,275,2300

代码放到了github上，相同的数据使用json数组格式显示没问题，使用csv的时候，里面的数字被转换成了字符串，放到柱状图显示的时候，数字显示的不正确，第一条数字不会显示，使用transform把字符串转成Number显示正常，这个csv格式的数据怎么不转换格式。

**Comment by Leannechn** [comment]
这是csv解析问题。
1. 你用的什么工具解析csv，你的解析工具是否有这个功能，要么换个解析工具，要么自己转格式。
2. 如果没有，transform 已经为你提供工具了。
3. 如果觉得Dateset包很大，你可以用任意函数自己处理一下。

**Comment by lijiangwei** [comment]
@Laniman 使用的就是DataSet里面Connector方法，
`const ds = new DataSet();
ds.createView().source(data, {
      type: 'csv'
})`

**Comment by weepy3641** [comment]
@lijiangwei 
参考用法及文档：
https://www.yuque.com/antv/g2-docs/api-data-set#gccalr
