### ISSUE TITLE
tooltip可不可以只显示crosshair，不展示tooltip框

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#652]
![image](https://user-images.githubusercontent.com/23026361/49841184-8c719600-fdf1-11e8-8b27-cbbc4e5cc36e.png)
我想要只显示crosshair 不展示tooltip框，请问怎么设置可以达到？

**Comment by houzip** [comment]
@weepy3641 
![image](https://user-images.githubusercontent.com/23026361/49913370-5bb06000-fec8-11e8-827b-2c1454b2146a.png)
我在render中这样写 并不生效

**Comment by weepy3641** [comment]
直接在 css 中写就可以。

```
.g2-tooltip {
  visibility: hidden !important;
}
```
