### ISSUE TITLE
流图点击legend，x轴乱序

### ISSUE THREAD

**Issue by z784324922** [alibaba/BizCharts#654]
https://riddle.alibaba-inc.com/riddles/95ca3964

![image](https://user-images.githubusercontent.com/31068244/49980621-2cb0f180-ff8f-11e8-98af-eb1274cdc5dc.png)

**Comment by z784324922** [comment]
官网的demo：https://bizcharts.net/products/bizCharts/demo/detail?id=other-streamgraph&selectedKey=%E5%85%B6%E4%BB%96%E5%9B%BE%E8%A1%A8

**Comment by z784324922** [comment]
不是数据问题，点击 DATA_RECV这个图例，x轴会乱序

**Comment by weepy3641** [comment]
@z784324922 
x 轴的 scale type 指定下，需要指定为 time。 不指定的情况下，由于是字符串类型，会乱序。

https://riddle.alibaba-inc.com/riddles/bd3a48e2
