### ISSUE TITLE
3.4.1 版本使用 Guide 报错

### ISSUE THREAD

**Issue by OnedayLiu** [alibaba/BizCharts#655]
```js
const {
  DataMarker,
  DataRegion
} = Guide;
```
![image](https://user-images.githubusercontent.com/7758413/49999906-f5fcca80-ffd2-11e8-9685-baf2ff8bccbd.png)

看了下 v3.4.1 源码已经把 DataMarker DataRegion 删除了，文档上找不到相关的变更，请问应该怎么处理？

![image](https://user-images.githubusercontent.com/7758413/50000071-64418d00-ffd3-11e8-8ebd-1e1f712bcc69.png)

**Comment by OnedayLiu** [comment]
使用的时候报错了
```js
[ts] Type 'typeof Guide' has no property 'RegionDataMarker' and no string index signature. [2459]
```

**Comment by weepy3641** [comment]
是 ts 文件没有跟上库的更新速度。
