### ISSUE TITLE
BizCharts能支持画流程图吗？

### ISSUE THREAD

**Issue by shiningbeer** [alibaba/BizCharts#657]
您好，我想实现使用nodejs动态生成由矩形、菱形、箭头组成的流程图，BizCharts能帮助我完成这一点吗？我大概浏览了文档，还是不能确定。

**Comment by weepy3641** [comment]
@shiningbeer 
bizcharts 适合画普通统计图表，推荐使用 G6：  https://antv.alipay.com/zh-cn/g6/2.x/demo/index.html
