### ISSUE TITLE
请问我们的矩形树图、能否支持下钻功能

### ISSUE THREAD

**Issue by ZhiGang-Fang** [alibaba/BizCharts#658]
在开中遇到一个关系数据展示，需要用到矩形树图，请问我们的矩形树图、能否支持下钻功能？

[类似这样的功能](https://jshare.com.cn/demos/hhhhij)

**Comment by weepy3641** [comment]
默认不支持下钻，你可以自己做。
在点击矩形的适合，切换这个矩形块代表的数据，就可以实现下钻功能了。

点击时间：
https://bizcharts.net/products/bizCharts/api/chart#%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%E4%BA%8B%E4%BB%B6
