### ISSUE TITLE
在Tooltip组件下，htmlContent方法缺失

### ISSUE THREAD

**Issue by wawow** [alibaba/BizCharts#660]
- bizcharts Version:3.4.1

`<Tooltip
              crosshairs={{
                type: "y"
              }}
              useHtml
              htmlContent ={() => {
                console.log(222);
              }}
/>`
代码中缺少对useHtml、htmlContent的定义，导致无法自定义tooltip的全局格式和样式，希望尽快修复

**Comment by Leannechn** [comment]
多谢反馈，我们会尽快check和更新类型声明文件。

**Comment by pot-code** [comment]
在 type 目录下，补上类型代码：

```typescript
declare namespace bizcharts {
  interface TooltipProps {
    htmlContent: (title: string, items: any) => string
  }
}
```

利用 interface 的叠加性
