### ISSUE TITLE
3.41 版本热力图示例无法显示Label

### ISSUE THREAD

**Issue by yangxs9** [alibaba/BizCharts#662]
- bizcharts Version: 3.4.1
- CodePen Link: https://codepen.io/xinsong/pen/pqRyKK

示例链接: https://bizcharts.net/products/bizCharts/demo/detail?id=heatmap-basic&selectedKey=%E7%83%AD%E5%8A%9B%E5%9B%BE

把示例代码版本换成3.4.1后无法显示label

**Comment by harry75369** [comment]
谢谢。确认了下，从 3.3 版本开始就有这个 bug。 @weepy3641

**Comment by ps756405678** [comment]
这个问题预计什么时候解决呢？

**Comment by weepy3641** [comment]
还在等 g2 修复。

**Comment by weepy3641** [comment]
@harry75369 
3.4.5 版本已经修复了。

**Comment by zf1517** [comment]
我更新到3.4.5了，为什么还是没显示Label @weepy3641

**Comment by weepy3641** [comment]
@zf1517  不好意思，是没修复，那你要再等等，目前 g2 已经再 beta 版本中修复，正式版本还没发。

**Comment by weepy3641** [comment]
bizcharts@3.5.1 已经修复。详建官网demo
https://bizcharts.net/products/bizCharts/demo#%E7%83%AD%E5%8A%9B%E5%9B%BE
