### ISSUE TITLE
数据种类不连续时bargap（marginRatio）属性会失效

### ISSUE THREAD

**Issue by gzjfly2017** [alibaba/BizCharts#663]
- bizcharts Version:
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/28820501/50409516-390a3980-082e-11e9-9a79-432455a1d3df.png)
![image](https://user-images.githubusercontent.com/28820501/50409545-635bf700-082e-11e9-8fde-a4e72aaa5f98.png)
![image](https://user-images.githubusercontent.com/28820501/50409550-68b94180-082e-11e9-8997-cc70c95a50ae.png)
![image](https://user-images.githubusercontent.com/28820501/50409557-71117c80-082e-11e9-9960-55610e1926c7.png)

- you can fork CodePen template form this: https://codepen.io/pen/?editors=0010#0
- Demo Link:https://bizcharts.net/products/bizCharts/demo/detail?id=bar-grouped-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE

**Comment by liunian** [comment]
并不是失效，而是，3行数据，因为 name 不同，实际分成了 3 组，即每个月份实际有 3 个柱形图。但一月份只有 `b`，另外的 `London` 和 `a` 没数据，所以柱形图没有高度而不展示出来。二月份出于同样的原因， `b` 的柱形高度为 0
