### ISSUE TITLE
tooltip是否能动态设置位置

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#664]
我这有个需求想要点击图上某条数据，让crosshair定位在该点，让后通过键盘方向键控制crosshair的左右移动选中数据，请问大神有没有什么思路可以提供一下！

**Comment by weepy3641** [comment]
可以用 guide 去实现 crosshair，然后用键盘事件控制 guide 坐标。

**Comment by houzip** [comment]
@weepy3641 可是使用guide的话 通过onPlotMove事件更新guide位置 每次都会重新渲染，性能上会有影响吧

**Comment by weepy3641** [comment]
@houzip 
默认的 crosshair 也是要重新渲染的。
如果不想图表重新渲染，可以用 html guide。

**Comment by houzip** [comment]
@weepy3641 已经解决了 谢谢大神！
