### ISSUE TITLE
问题一，使用柱状图，想要隐藏x轴，设置visible为false，x轴仍然显示。（或者将axis x的相关代码注释掉x轴也显示）。问题二，初始进入页面，表格超出边框变形。

### ISSUE THREAD

**Issue by imalextu** [alibaba/BizCharts#668]
- bizcharts Version:^3.4.1
- Platform or react version:^16.6.3
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/45706079/50475637-64dd1900-0a00-11e9-8196-5969cfa0a26d.png)
![image](https://user-images.githubusercontent.com/45706079/50475733-a372d380-0a00-11e9-9a57-e8c0bf31d5ef.png)

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by imalextu** [comment]
问题二已解决，https://github.com/alibaba/BizCharts/issues/279
问题一是由于axis包含其他的属性，导致x轴第一次加载时无法隐藏，注释掉即可，具体原因没细找。
![image](https://user-images.githubusercontent.com/45706079/50581814-23cd8480-0e98-11e9-8071-6e16290d59ac.png)

**Comment by wangjiakunlhy** [comment]
为什么柱状图设置了alias不显示呢？

**Comment by weepy3641** [comment]
@wangjiakunlhy 
如果有问题，可以提个新的 issue，这个先关了。
