### ISSUE TITLE
<Label />` must be wrapped in `<Geom />`我的<Label/>是在<Geom>里面放的，为什么报个错

### ISSUE THREAD

**Issue by MaZhengA** [alibaba/BizCharts#669]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@MaZhengA 
麻烦给个报错的 demo。你这么一句话我们也不知道什么意思。

**Comment by MaZhengA** [comment]
网速原因
