### ISSUE TITLE
Double Y Axis can not have same tick count always even if force to set same values in scale

### ISSUE THREAD

**Issue by ldf12345** [alibaba/BizCharts#671]
https://riddle.alibaba-inc.com/riddles/5acd8b96

As issue title, Double Y Axis can not have same tick count always even if force to set same values in scale. How to resolve it?

![image](https://user-images.githubusercontent.com/18192516/50518395-5ec66580-0af0-11e9-90f9-1ad3e79177fc.png)

**Comment by weepy3641** [comment]
@ldf12345 
可以配置下 scale 的 min max tickInterval 来做到两边刻度间距一致。

https://riddle.alibaba-inc.com/riddles/c13c21ee
