### ISSUE TITLE
后台返回数据中带时间戳时，使用'dodge'分组图会报错！dodge is not support linear attribute, please use category attribute!

### ISSUE THREAD

**Issue by MaZhengA** [alibaba/BizCharts#672]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/33256699/50532315-a1208e80-0b52-11e9-9b3c-d8eb9868c222.png)

**Comment by weepy3641** [comment]
@MaZhengA 
应该是你 color 的那个字段被默认解析为 linear 了。
要将他的scale配置为 cat 类型。

**Comment by shufangu** [comment]
> @MaZhengA
> 应该是你 color 的那个字段被默认解析为 linear 了。
> 要将他的scale配置为 cat 类型。

上图的group1 必须是string 类型的吗？number好想也有问题

**Comment by gaozhidf** [comment]
> > @MaZhengA
> > 应该是你 color 的那个字段被默认解析为 linear 了。
> > 要将他的scale配置为 cat 类型。
> 
> 上图的group1 必须是string 类型的吗？number好想也有问题

也遇到一样 的问题，number类型就会有问题，必须是string
