### ISSUE TITLE
最新版本烛型图有蓝色border？？看起来有点奇怪啊

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#673]
![image](https://user-images.githubusercontent.com/23026361/50536501-29715480-0b90-11e9-9c70-6db07959b8e2.png)

**Comment by ironicstone** [comment]
提供下版本号和示例demo

**Comment by houzip** [comment]
@houzip 我这是从官网图例上截的图

**Comment by Leslie2014** [comment]
现版本烛型图蓝色 border 是默认存在的。

**Comment by kevinyxyx** [comment]
请问怎么能关掉蓝色border么？设置 strokeOpacity为0会导致上下影线都没了 @Leslie2014
