### ISSUE TITLE
当数据量过大时slider的拖动会有明显的卡顿，非常影响操作

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#674]
当数据量过大时slider的拖动会有明显的卡顿，非常影响操作

**Comment by ironicstone** [comment]
量级多少？g2是基于canvas/svg的，数据量过大都会导致性能问题。你可以考虑数据降维或抽样来处理。或者slider用一份简单的数据，通过state来管理slider和chart之间的数据映射。

**Comment by guomh** [comment]
> 量级多少？g2是基于canvas/svg的，数据量过大都会导致性能问题。你可以考虑数据降维或抽样来处理。或者slider用一份简单的数据，通过state来管理slider和chart之间的数据映射。

能否详细说说数据降维或抽样的处理方法。以及slider的处理方法。多谢！！！ @ironicstone
