### ISSUE TITLE
legend哪个属性用来设置分类图例和连续图例

### ISSUE THREAD

**Issue by MaZhengA** [alibaba/BizCharts#676]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by MaZhengA** [comment]
找到办法了

**Comment by Madridspark** [comment]
麻烦问一下是用什么方法解决的
