### ISSUE TITLE
Tooltip triggerOn

### ISSUE THREAD

**Issue by racheldelman** [alibaba/BizCharts#678]
- bizcharts Version: 3.4.2
- Platform or react version: 16.5.2
- Codepen example: https://codepen.io/anon/pen/QzaZWa

I'm using the `Chart` component with a `Tooltip` and it works great. When clicking on the Chart, the tooltip shows up, however, I noticed that when I move the mouse off of the chart, the tooltip disappears. I was wondering if there's a way to have the tooltip stay there even after the mouse leaves.
I tried using the 'TriggerOn' option set to 'click' but that doesn't seem to work.
Any help would be much appreciated, thanks!

**Comment by ironicstone** [comment]
Try `Guide`. Tooltip appears when mouse cursor is over the chart.

**Comment by racheldelman** [comment]
@ironicstone thanks for the response! I would like the tooltip to stay on click and not move when the mouse moves

**Comment by ironicstone** [comment]
@racheldelman  Tooltip disappears when mouse moves out the chart by design.  You can try `Guide` to achieve the same effect.  Get the data when click and render a guide accordingly.

**Comment by racheldelman** [comment]
@ironicstone If I understand correctly that would mean recreating the tooltip component from scratch. Is there a way to override the `onMove` function to not trigger the disappearing of the tooltip?

**Comment by Leannechn** [comment]
Try `chart.showTooltip()` , see detail in https://www.yuque.com/antv/g2-docs/api-chart#lzegwt
