### ISSUE TITLE
数据格式化bug

### ISSUE THREAD

**Issue by sorryxc** [alibaba/BizCharts#682]
折线图如果将数据保留2位小数，Label就会错乱
![image](https://user-images.githubusercontent.com/43484514/50635761-6ffaf080-0f8e-11e9-8b83-65d44c23243d.png)

**Comment by ironicstone** [comment]
目测你是把数字格式化成字符串，变成分类数据了。建议使用各种formatter来格式化要展示的数据。参考: https://bizcharts.net/products/bizCharts/demo/detail?id=g2-bubble-text&selectedKey=%E6%A6%82%E8%A7%88
