### ISSUE TITLE
tooltip的htmlContent不生效

### ISSUE THREAD

**Issue by sorryxc** [alibaba/BizCharts#683]
`<Tooltip
                useHtml
                showTitle={false}
                crosshairs={{
                  type: 'y',
                  style: {
                    lineWidth: 1,
                    stroke: '#999',
                  }
                }}
                htmlTemplate={ (title, items) => {
                  return '<div class="g2-tooltip">'
                    +'<div class="g2-tooltip-title" style="margin-bottom: 4px;"/>'
                    +   '<ul class="g2-tooltip-list">'
                    +     '<li data-index={0}>'
                    +       '<span style="background-color:#f94a2d;width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>'
                    +         '消费总额: ' + items["消费总额"]
                    +       '</li>'
                    +       '<li data-index={1}>'
                    +         '<span style="background-color:#55bbff;width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>'
                    +         '扣除积分后消费额: ' + items["扣除积分后消费额"]
                    +       '</li>'
                    +       '<li data-index={2}>'
                    +         '<span style="background-color:#f8be21;width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>'
                    +         '积分会员规模: ' + items["user_amount"]
                    +       '</li>'
                    +    '</ul>'
                    +'</div>'
                } }
              />`

**Comment by jassonxian** [comment]
最后怎么解决的，我也遇到这样的问题，照着API写的，没生效
