### ISSUE TITLE
不设置<Chart />的animate属性(默认不是true, 文档说明默认值是true), 导致Geom的动画不生效

### ISSUE THREAD

**Issue by VoliBearCat** [alibaba/BizCharts#684]
- bizcharts Version: 3.4.2
- Platform or react version: 16.6
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/11676384/50669715-d836ea00-1001-11e9-8ded-bf894e8120ce.png)
- CodePen Link: https://codepen.io/anon/pen/wRydVX?editors=1111

https://bizcharts.net/products/bizCharts/api/chart#animate
![image](https://user-images.githubusercontent.com/11676384/50669855-bb4ee680-1002-11e9-86b3-7cc343af872a.png)

**Comment by ironicstone** [comment]
收到，文档问题。

**Comment by liunian** [comment]
从 `3.4.3` 后默认开启了动画，官网文档一版是对应到最新的版本
