### ISSUE TITLE
矩形树图有时无法完全填充canvas

### ISSUE THREAD

**Issue by mk-nickyang** [alibaba/BizCharts#686]
- bizcharts Version: 3.4.3
- Platform or react version: 16.6.3
- Mini Showcase(like screenshots): 

当数据不多时，矩形树图可以完全填充canvas
[![Screenshot from Gyazo](https://gyazo.com/7062d2f5021a70466c80567377fa86da/raw)](https://gyazo.com/7062d2f5021a70466c80567377fa86da)

当数据变多时，有时会出现比较大的空白区域，有时则不会 （已经设置过`padding={0}`）
[![Screenshot from Gyazo](https://gyazo.com/279d61e058e9cca7d50a731e5c3fb97b/raw)](https://gyazo.com/279d61e058e9cca7d50a731e5c3fb97b)

[![Screenshot from Gyazo](https://gyazo.com/965e1b49e8f1e0057021d2dc23bea726/raw)](https://gyazo.com/965e1b49e8f1e0057021d2dc23bea726)

- CodePen Link:
https://codepen.io/lucissa/pen/wRxoVW

请问这是一个bug吗？还是说树形的算法有时候就是这样的？

**Comment by ironicstone** [comment]
和布局算法有关。G2内置有六种，你可以选择合适的。

**Comment by mk-nickyang** [comment]
@ironicstone 换成treemapBinary解决了问题，多谢！
