### ISSUE TITLE
柱状图 Geom 设置 color 属性使 Tooltip 渲染的 name 错误

### ISSUE THREAD

**Issue by aprilandjan** [alibaba/BizCharts#688]
### 版本与环境
 macos, bizchart `3.4.2`, react `latest`

### 问题描述
参照官网的基础柱状图示例 <https://bizcharts.net/products/bizCharts/demo/detail?id=bar-basic-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE>, 默认情况下 Tooltip 显示的 name 是 y 轴名, 这个是正确的：
![image](https://user-images.githubusercontent.com/7011247/50960273-f8820f80-14ff-11e9-84f8-023ead0c30b1.png)

但是给 `Geom` 加上 color 属性尝试根据数据某维度的值条件改变 Bar 颜色时，Tooltip 显示的 name 会被 Geom 的 color 属性所影响：

```
const getBarColor = (year) => {
    if (year === '1957 年') {
      return 'red';
    }
    return 'blue';
}

<Geom 
    type="interval"
    position="year*sales"
    color={["year", getBarColor]}
/>
```

![image](https://user-images.githubusercontent.com/7011247/50960522-878f2780-1500-11e9-9059-53d33fd00fa0.png)

- CodePen Link:
<https://codepen.io/anon/pen/bOxMMK?&editable=true>

**Comment by ironicstone** [comment]
tooltip的color和geom绑定。方案：在geom上定义tooltip。chart上所有可视部分都是可以定制的，解决方案都很简单，出现问题定制就行了。

**Comment by aprilandjan** [comment]
@ironicstone 的确能通过其他方式定制 Tooltip 显示的内容。但是即便 Tooltip color 和 geom 绑定，Tooltip name 被错误的改成别的属性值了，也是个问题。

**Comment by ironicstone** [comment]
> @ironicstone 的确能通过其他方式定制 Tooltip 显示的内容。但是即便 Tooltip color 和 geom 绑定，Tooltip name 被错误的改成别的属性值了，也是个问题。

刚才没注意name也变了，确实是一个问题，我们排查一下。

**Comment by weepy3641** [comment]
@aprilandjan 
当增加 tooltip color 属性是数字字段时，tooltip 中的 key 改变是正常的，默认就是显示的字段分组名。
例如 demo：
https://bizcharts.net/products/bizCharts/demo/detail?id=bar-grouped-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE
