### ISSUE TITLE
指定downloadImage路径

### ISSUE THREAD

**Issue by Yangchunyu01** [alibaba/BizCharts#689]
bizchart生成图片后，如何指定下载图片路径
或者有没有其他的方式可以指定图片下载路径呢

**Comment by ironicstone** [comment]
不能。浏览器安全限制。

**Comment by Yangchunyu01** [comment]
> 不能。浏览器安全限制。

唯一能更改的只是图片的名称。下载的路径是浏览器的下载路径？是这样吗？

**Comment by ironicstone** [comment]
> > 不能。浏览器安全限制。
> 
> 唯一能更改的只是图片的名称。下载的路径是浏览器的下载路径？是这样吗？

是的
