### ISSUE TITLE
Document error(s)

### ISSUE THREAD

**Issue by occultskyrong** [alibaba/BizCharts#690]
- bizcharts Version: 3.4.1
- Platform or react version: -
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

当我在`https://bizcharts.net/index` 浏览文档时，发现了一些文档的小错误。
浏览器的信息
`UserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"`

在此一一列出：

- footer中首页的link错了

`index`拼写错误（难道拼错单词是ali的惯例？）0.0
<img width="1074" alt="1" src="https://user-images.githubusercontent.com/8370006/51012463-2b77e200-1598-11e9-9553-6ffbd4c1001c.png">

- `axis`中`title`错误

> https://bizcharts.net/products/bizCharts/api/axis#title

```javascript
const scale = {
 &nbsp;sales:{
    alias:'标题名称'
  }
};

<Chart scale={scale} >
  <Axis name="sold" title={title}/>
</Chart>
```
里面出现了非转义`&nbsp;`

- `axis`中`visible`重复

> https://bizcharts.net/products/bizCharts/api/axis#visible

```doc
描述：当前坐标轴对应数据源中的字段名(必填)，当前坐标轴是否需要可见，默认值true。
```
描述中重复了对`name`的描述。

**Comment by ironicstone** [comment]
多谢反馈。

**Comment by occultskyrong** [comment]
https://bizcharts.net/products/bizCharts/api/axis#label
坐标轴说明中坐标轴文本样式参数，重复参数`rotate`

```JavaScript
  offset: {number}, // 数值，设置坐标轴文本 label 距离坐标轴线的距离
  rotate: 30, // 旋转角度
  // 设置文本的显示样式，还可以是个回调函数，回调函数的参数为该坐标轴对应字段的数值
  rotate: 30, //文本旋转角度
```
