### ISSUE TITLE
[Question]: Chart scale max 有限制？

### ISSUE THREAD

**Issue by yoyo837** [alibaba/BizCharts#692]
- bizcharts Version: latest
- Platform or react version: latest
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/6134547/51071083-943d8800-1686-11e9-8bb4-13b7cf512f7b.png)

**Comment by ironicstone** [comment]
左padding太小了，调大点。

**Comment by yoyo837** [comment]
确认是这个问题。Thanks for your reply.
