### ISSUE TITLE
希望Chart支持排序功能

### ISSUE THREAD

**Issue by andy1247008998** [alibaba/BizCharts#693]
tansform已经支持sort进行排序，但是似乎Chart只能根据JSON的key名作为X或Y轴，无法补全排序之后的行号。
希望实现的功能：Chart根据单一字段(如xxxValue)排序，无视所有其他字段，然后按照1,2,3等顺序补全X轴。

已知：可以通过遍历数据源的方式手动增加字段，但是那么做不方便。

**Comment by ironicstone** [comment]
这个统一来数据层做吧，比如你例子里面的数据补全和排序等等。dataset提供的transform就是来干这个的。

**Comment by andy1247008998** [comment]
> 这个统一来数据层做吧，比如你例子里面的数据补全和排序等等。dataset提供的transform就是来干这个的。

问题在于transform支持增加一个新字段作为行号吗？

**Comment by weepy3641** [comment]
支持的，transfrom map 可以做任意增减。

**Comment by andy1247008998** [comment]
@weepy3641 我又来了。
我想transfrom map可能无法做到我希望的效果。
假设原始数据有两个字段，分别为name和value。
目标：增加一个字段rank，对应value从大到小排序。
transfrom map的确可以增加字段，但是它并不知道当前元素排第几。
transfrom sort-by的确可以排序，但是它好像并不能增加字段。
