### ISSUE TITLE
slider和guide如何共同使用

### ISSUE THREAD

**Issue by chenfeiyu01** [alibaba/BizCharts#694]
- bizcharts Version: 3.4.3
- slider Version: 2.1.0
- Platform or react version: 16.2.0
请问slider插件和guide共同存在时如何搭配使用。

已显示的guide无法在调整slider显示范围时隐藏，依旧会显示在已经不展示在页面中的位置。

正常显示情况如下：
![wx20190114-142832](https://user-images.githubusercontent.com/31460535/51099041-4f8e2a00-1809-11e9-9d3b-308301817a73.png)
调整slider之后情况如下：
![wx20190114-142906](https://user-images.githubusercontent.com/31460535/51099061-6e8cbc00-1809-11e9-92c9-822fc5e271a8.png)

**Comment by Leslie2014** [comment]
Hi，我看你上面第二张图调整左边的slider后，其中guide里的1和2不是消失了吗？也许我可能理解错你的意思，麻烦贴个 codepen 复现链接吧，方便我们排查问题：https://codepen.io/leslie2014/pen/xjJGER

**Comment by tli4** [comment]
我也有类似的问题，Guide在滑出视区的时候不会被隐藏，反而会挤压图表。我暂时的解决办法是
通过return undefined来阻止Guide被绘制
```Javascript
      start={(x, y) => {
        if (time >= ds.state.start && time <= ds.state.end) {
          return [Number(time), y.value.min];
        }
        return [undefined, undefined];
      }}
      end={(x, y) => {
        if (time >= ds.state.start && time <= ds.state.end) {
          return [Number(time), y.value.max];
        }
        return [undefined, undefined];
      }}
```
但是滑出视区后console里面会一直报NaN的错误，
在护士群里问了，说是要自己判断移出时区之后的条件，再unmount掉guide，

可是Slider的onChange里不能setState，不知道要怎么通过滑动slider来reRender，去unmount Guide，
同时看文档还有一个event listener，但首先这个不是实时更新的，其次这里还是不能触发UI的变化。不知道要怎么做。

**Comment by cc2333** [comment]
没人回答么
