### ISSUE TITLE
版本升级带来的问题

### ISSUE THREAD

**Issue by jassonxian** [alibaba/BizCharts#695]
- bizcharts Version: 3.4.3
- Platform or react version: 16.4.1
由3.1.10升级到最新版本报错了
![image](https://user-images.githubusercontent.com/21199561/51153550-9cc2d800-18ab-11e9-8911-7fa2de6dfd33.png)

**Comment by Leannechn** [comment]
3.1.10 到3.4.3 有些使用方式有不同，是否直接使用了g2的接口。需要找到对应的使用代码修复。
