### ISSUE TITLE
关于多条折线图结合的单轴图自定义Legend 的点击事件问题

### ISSUE THREAD

**Issue by Han-hui** [alibaba/BizCharts#696]
多条折线图 自定义legend
点击的时候 取不到 对应的那条折线geom.getYScale().field都是同一个值
我想做到点击一个同时显示多条的效果
如下图

![image](https://user-images.githubusercontent.com/16640436/51156458-a1d95480-18b6-11e9-96d9-17be9d0307ab.png)

**Comment by Leannechn** [comment]
抱歉不是很理解需求，如果是获取原生数据点，参考下面的代码  
```js
chart.on('click', (ev) => {
    const clickY = ev.y;
// 获取多个数据
const points= view1.getSnapRecords(ev)
// 获取单个数据
    const pointsSort = points.sort((a,b) => Math.abs(a.y - ev.y)  - Math.abs(b.y -ev.y));
    console.log(pointsSort[0]);
  })

```

**Comment by Han-hui** [comment]
我可能表达的不清楚，我的意思是自定义legend的事件 ，做到点击legend显示两条折线
比如我的legend有10个分类 但是其中两两数据是关联的，
我需要实现自定义legend只显示5个分类并且点击一个legend的时候同时出现关联的两条折线
不知道有没有表达清楚

**Comment by weepy3641** [comment]
@Han-hui 
legend 点击事件中自己去控制筛选需要显示和不需要显示的内容。
参考：
https://bizcharts.net/products/bizCharts/demo/detail?id=double-axes-legend&selectedKey=%E6%A6%82%E8%A7%88
