### ISSUE TITLE
legend  分类错误

### ISSUE THREAD

**Issue by Han-hui** [alibaba/BizCharts#697]
我的是分类 用的是timeCct
为啥会出现如下图
红色的地方
刚开始用不熟悉
请各位大神帮忙
![image](https://user-images.githubusercontent.com/16640436/51158117-ecaa9a80-18bd-11e9-84dd-4abcf7e23e02.png)

**Comment by weepy3641** [comment]
是连续 legend，你隐藏就行。
<Legend visible={falsw]e} />

**Comment by Han-hui** [comment]
哪个属性是隐藏连续图例
分类的不隐藏
现在设置了visible都没有了
