### ISSUE TITLE
htmlTemplate中的内容，调用downloadImage下载图片后，内容消失

### ISSUE THREAD

**Issue by Yangchunyu01** [alibaba/BizCharts#698]

**Comment by Yangchunyu01** [comment]
htmlTemplate={(text)=>{
      return '<div style="width:200px;height:200px;padding:50px"><svg viewBox="0 0 70 70" style="display:block;overflow:visible"><path style="fill:none" d="M 0,45 a 45,10 0 1,1 1,10 z" id="circle_1" /><text><textPath xlink:href="#circle_1">' + text + '</textPath></text></svg></div>';
}}

**Comment by Yangchunyu01** [comment]
htmlTemplate={(text)=>{
      return '<div style="width:200px;height:200px;padding:50px"><svg viewBox="0 0 70 70" style="display:block;overflow:visible"><path style="fill:none" d="M 0,45 a 45,10 0 1,1 1,10 z" id="circle_1" /><text><textPath xlink:href="#circle_1">' + text + '</textPath></text></svg></div>';
}}

**Comment by Yangchunyu01** [comment]
htmlTemplate中的内容，下载的图片没有htmlTemplate中定义的内容

**Comment by weepy3641** [comment]
html 内容无法导出。
