### ISSUE TITLE
legend 图表样式支持自定义，却总是被覆盖

### ISSUE THREAD

**Issue by syl34220** [alibaba/BizCharts#699]
- bizcharts Version:3.4.1
- Platform or react version:16.6.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by syl34220** [comment]
g2-legend={{
                            marginLeft: '0x',
                            marginTop: '20px',
                            overflow: 'hidden',
                            width: chartWidth - 120 + 'px',
                            left: 0,
                            top: '10px'
                        }}
很多属性都会被覆盖 自定义无效

**Comment by Yangchunyu01** [comment]
加上useHtml={true}试下呢
