### ISSUE TITLE
Chart init failed

### ISSUE THREAD

**Issue by joriewong** [alibaba/BizCharts#7]
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/map/drill-down

**Comment by weepy3641** [comment]
That is an know issue，when we fix it we will notify to you.

**Comment by weepy3641** [comment]
3.0.4 已经解决，github bizcharts 上的 drill-down demo 已经是修复后的了，可以实现地图下钻和联动。
data-set 版本必须 > 0.6.2.

站点上的 demo 稍后会更新。

**Comment by joriewong** [comment]
thx
