### ISSUE TITLE
多条折现图 如何设置tooltip 别名

### ISSUE THREAD

**Issue by cench** [alibaba/BizCharts#70]
例子中
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/line/series
不改变数据源情况下 Tooltip name 如何把Tokyo 和 London 改成 东京 和伦敦 ，
是否有设置别名的方法？

**Comment by weepy3641** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md

geom 上的 tooltip 属性可以控制 tooltip 显示格式及数据。

**Comment by BambooSword** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/api/geom.md 
看看文档，可以根据tooltip中city的值的不同来判断是显示 东京还是伦敦
<Geom type="line" position="month*temperature" size={2} color={'city'} tooltip={['temperature*city', (temperature, city)=>{
              if(city==="Tokyo"){city = 'ddd'}
    return {
	  name:city,
	  value: temperature
	}
  }]}/>

**Comment by cench** [comment]
@BambooSword  感谢！

**Comment by GodzillaHe** [comment]
通过该回调返回的tooltip上只能有一条信息了，多条信息如何设置呢？
