### ISSUE TITLE
矩形树图布局问题

### ISSUE THREAD

**Issue by mylxx** [alibaba/BizCharts#701]
请问这种图如何让数据从右上到左下依次变小
![63](https://user-images.githubusercontent.com/19658835/51423846-d9bb0180-1c00-11e9-881e-f89fa2cee7f4.png)
![310](https://user-images.githubusercontent.com/19658835/51424095-3ec42680-1c04-11e9-8bdc-2913ac6a4ac1.png)

**Comment by chengaiying** [comment]
同问

**Comment by Leannechn** [comment]
<Coord reflect="x" />

**Comment by mylxx** [comment]
感谢老哥
