### ISSUE TITLE
官网api zeroLineStyle 少了一个属性api

### ISSUE THREAD

**Issue by davy-gan** [alibaba/BizCharts#702]
在设置zeroLineStyle 的属性的时候需要设置一直 zeroLineStyle：true,不然就不会生效，但是官网上没给出这个api，而且官网上的demo在设置0轴样式时，也没加上这个属性，导致属性设置失败
https://bizcharts.net/products/bizCharts/api/axis#api
https://bizcharts.net/products/bizCharts/demo/detail?id=gallery-xaxis-zero-align&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE

复现的demo地址 https://riddle.alibaba-inc.com/riddles/c95a12b6

**Comment by Leslie2014** [comment]
感谢反馈~

**Comment by weepy3641** [comment]
@d
