### ISSUE TITLE
柱状图当某一条数据值特别大的时候 值较小的数据渲染出来的高度很小 无法实现点击onPlotClick事件跳转 

### ISSUE THREAD

**Issue by python-ljn** [alibaba/BizCharts#704]
- bizcharts Version:3.1.10
- Platform or react version:react ant design pro
当有某一条数据特别大的时候 柱状图会自适应，会将数据量小的记录对应的柱子 高度（或长度）很小，即使添加了onPlotClick事件，也无法实现点击（只有在那很小的那一部分才可以实现点击处理效果），而在此记录对应的轴线的这一列的其他未被数据填充的部分无法获取到此列的data对象 ，无法实现点击效果，请问有什么解决办法吗？无法贴代码，问题描述也很清楚了，此现象在API上也可以复现
https://bizcharts.net/products/bizCharts/demo/detail?id=bar-basic&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE

**Comment by dmdoit** [comment]
> 这种情况是可以考虑使用双Y轴的方式处理，将值很小的数据放在另一个Y轴做对比展示
![image](https://user-images.githubusercontent.com/19385704/59005915-02f7c980-8852-11e9-8284-6749871c3b56.png)
