### ISSUE TITLE
<Guide><Image /></Guide>调用downloadImg方法，Image有的可以下载，有的不能下载

### ISSUE THREAD

**Issue by Yangchunyu01** [alibaba/BizCharts#705]
{
                                    this.state.play["Score"][1].Result === "优秀" ? 
                                    <Image
                                        top={false}
                                        src={patleImg}
                                        start={['22.7%','-20']}
                                        width={50}
                                        height={50}
                                    />
                                    :
                                    ""
}

**Comment by Leslie2014** [comment]
麻烦提供更多的信息以便我们排查问题，请参考 issue 模板：

- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
> you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
