### ISSUE TITLE
为什么不给Chart提供一个className的接口啊？

### ISSUE THREAD

**Issue by CharlesMoone** [alibaba/BizCharts#71]
https://github.com/alibaba/BizCharts/blob/a72ee66deaa5c92ea96f91c46dafd0134c23dae2/src/components/Chart/index.jsx#L43

**Comment by weepy3641** [comment]
你想要 className 干啥？ 
你外层的 container 节点加上 classname 不可以？

**Comment by CharlesMoone** [comment]
看源码多出来一个div，所以想为啥不能直接在这个div上直接加，非要再包一层?

**Comment by BambooSword** [comment]
这个多出来的div是为了兼容react v16以前的版本，因为在v16之前，render必须返回有且只有一个父级jsx元素。

**Comment by BambooSword** [comment]
你好，我今天又验证了一下，的确没必要在Chart上多出一个外层div，我会向上反馈一下，看看是否要将其去掉。关于你说要跟Chart提供一个className的接口，我首先想了解的是，您是出于怎样的需求需要这样的接口？提供这样的接口意义何在？ @CharlesMoone

**Comment by weepy3641** [comment]
3.1.0 版本已经提供了 classname 和 style 接口。
详见 chart api 文档
https://github.com/alibaba/BizCharts/blob/master/doc/api/chart.md
