### ISSUE TITLE
图表，鼠标移动到图表上后，鼠标变为小手

### ISSUE THREAD

**Issue by liyunying** [alibaba/BizCharts#712]
![1548333388 1](https://user-images.githubusercontent.com/25221066/51678661-e7fd8900-2017-11e9-87d5-9d8f0354175e.png)

每个小气泡是可以点击筛选、过滤其他模块数据的，把鼠标移动到气泡上以后，如何变为小手？

**Comment by liyunying** [comment]
<Chart
                        onPlotEnter={ev => {
                          console.log(ev);
                          ev.toElement.style.cursor = 'pointer';
                        }}
                        onPlotClick={this.onPlotClick}
                        data={scatter}
                        scale={scale}
                        height={300}
                        width={400}
                        forceFit
                      >
我用onPointEnter没有什么效果，偶尔出来个小手，还是在空白区域。

**Comment by liyunying** [comment]
<Geom
            type="intervalStack"
            position="percent"
            // color={dimension}
            tooltip={tooltip}
            style={{
              cursor: 'pointer',
            }}
            color={[dimension, changeTheme]}
          >

修改Geom的style，进入区域是小手， 但是移除后还是小手，过一会才是箭头，变化有延迟。

**Comment by liunian** [comment]
可参考 #561 ，建议外层元素加特殊标示（如 `className="cursor-pointer"` 之类），然后添加如 `.cursor-pointer svg g { cursor: pointer; }` 的样式来控制
