### ISSUE TITLE
tooltip 自定义时 container 宽窄发生变化

### ISSUE THREAD

**Issue by HaveF** [alibaba/BizCharts#713]
- bizcharts Version:
bizcharts@3.2.2
另外在本地 3.4.3 版本也一样
- Platform or react version:
- Mini Showcase(like screenshots):

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
官方提供的原始股票图:
[Bizcharts-基于商业场景下的数据可视化解决方案](https://www.bizcharts.net/products/bizCharts/demo/detail?id=candlestick-basic&selectedKey=%E7%83%9B%E5%BD%A2%E5%9B%BE)
把其中的这行
```jsx
 <Tooltip showTitle={false} itemTpl='<li data-index={index}><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}{value}</li>' />
```
改成
```jsx
          itemTpl={
            '<li data-index={index}>'
            + '<span style="background-color:{color};" class="g2-tooltip-marker"/>'
            + '{name}{value}'
            + '</li>'
          }

```
tooltip的宽窄就变了
![image](https://user-images.githubusercontent.com/54462/51824467-5181de00-231d-11e9-8f18-43b585663a72.png)

[codepen 股票图](https://codepen.io/HaveF/pen/omLNRL)

**Comment by weepy3641** [comment]
@HaveF 
是你的语法问题，g2-tooltip-marker 之类的 classname 没有应用上去。
