### ISSUE TITLE
多条折线图，某一条数据只在tooltip中显示，且legend的onClick和onHover依然有效

### ISSUE THREAD

**Issue by HuazhenXia** [alibaba/BizCharts#716]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link: https://codepen.io/huazhenxia/pen/OdRedb
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

在图表中有三条线，但是只想要把difference只显示在tooltip中，legend中不需要显示。且legend中onClick和onHover依然有效。不知道怎么在legend中隐藏difference

尝试过：
1. 使用filter，然后difference在tooltip中就不见了。
2. legend定制之后，onClick失效，重写之后只在一个页面有效, 换其他页面就无效了。onHover实现不了，没有发现例子。
3. 使用legend的itemformatter，文本可以没有，marker一直都在。

不知道该怎么办了，求解密。

**Comment by weepy3641** [comment]
@HuazhenXia 
用两个 geom 可以实现。
1、将  difference 用一个 geom 显示，同时隐藏这个折线的 y 轴。
2、将其他折线用一个 geom 显示，同时显示此折线的 legend
2、将两个 geom 的 y轴的刻度统一。
