### ISSUE TITLE
读取 <Guide>下子组件<Guide.Line> 中 callback类型 的start/end 参数详细信息报错

### ISSUE THREAD

**Issue by tyawei** [alibaba/BizCharts#717]
详细如图所示，按照官网 https://bizcharts.net/products/bizCharts/api/guide#start 中介绍的两个参数，读取参数对象中key的对应值，报错信息如图四所示：
![line](https://user-images.githubusercontent.com/25874165/52037792-00672980-256b-11e9-96a8-7cd8441fef97.jpg)
![default](https://user-images.githubusercontent.com/25874165/52037809-0a892800-256b-11e9-8731-884c09b8117d.jpg)
![default](https://user-images.githubusercontent.com/25874165/52037821-0e1caf00-256b-11e9-9c14-5c20e6b88ede.jpg)
![default](https://user-images.githubusercontent.com/25874165/52037826-11179f80-256b-11e9-8267-faf89999f515.jpg)

**Comment by tyawei** [comment]
是读取方式不对还是其他情况？
同时按照 G2 官网上，Time 类型有个 getTicks() 静态方法，同样报错 xScale.getTicks() is not a function

**Comment by weepy3641** [comment]
xScale.date.getTicks() 可以使用。
