### ISSUE TITLE
bizcharts-plugin-slider，拖动触发 onChange，方法内触发 react 的setState方法报错。请确认一下是否是bug或者是否有这个优化计划

### ISSUE THREAD

**Issue by tyawei** [alibaba/BizCharts#718]
如组件 <Slider  onChange={this.handleChange} ... /> 
handleChange = ()=> { this.setState({ flag: false}) }，报错：
![slider](https://user-images.githubusercontent.com/25874165/52038450-53da7700-256d-11e9-9492-806fa9665444.jpg)

**Comment by weepy3641** [comment]
@tyawei  目前版本请不要在 change 中直接 setstate 。
如果一定要，建议用一个 timeout 之后再 setstate。

**Comment by tyawei** [comment]
> @tyawei 目前版本请不要在 change 中直接 setstate 。
> 如果一定要，建议用一个 timeout 之后再 setstate。

我自然是尝试过的，先不说timeout后 setState 变成同步事务，而且从初始化状态下拖动 slider ，slider 马上又会恢复到最左侧/右侧。如下图，在 onChange 中，滞后500毫秒，触发 setState， 一放鼠标，就返回。同时，虽然报错频率少了，但是还是存在
![default](https://user-images.githubusercontent.com/25874165/52158799-d468b700-26d6-11e9-8cf0-27e19b9deba6.jpg)

**Comment by Sukura7** [comment]
使用中也遇到了相同的问题。发现用lodash的debounce方法可以避免直接用setState带来的slider跳动问题。但是bizcharts-plugin-slider.min.js的报错仍然存在，只是频率少了。

**Comment by tyawei** [comment]
在 onchange 里面解决 setState 问题还是很有必要的，一些业务场景下，slider 滑动来切换 state 状态，可以有针对性的渲染、改变图表某一块地方。
目前我方项目上有这种场景，然而目前却只能通过 样式绝对定位，在onchange内判断条件来覆盖图表某一个地方，低级操作

**Comment by Sukura7** [comment]
> 在 onchange 里面解决 setState 问题还是很有必要的，一些业务场景下，slider 滑动来切换 state 状态，可以有针对性的渲染、改变图表某一块地方。
> 目前我方项目上有这种场景，然而目前却只能通过 样式绝对定位，在onchange内判断条件来覆盖图表某一个地方，低级操作
嗯，上条评论是想比较debounce跟setTimeOut，之前打成了setState，现已更正。我现在在项目中直接用了g2-plugin-slider来替代bizcharts-plugin-slider，然后在onGetG2Instance方法中获取到g2实例后，render slider，在g2 slider 的onChange中使用setState是没有问题。期待下一个版本能解决这一问题~

**Comment by LeeeeeeM** [comment]
有后续进展吗？
