### ISSUE TITLE
官方实例，渐变色面积图， geom color设置为渐进色 tooltip里面的item个数会有两倍。只想显示2个Asia和Africa

### ISSUE THREAD

**Issue by 1053061407** [alibaba/BizCharts#719]
- bizcharts Version:  3.4.3
- Platform or react version: react
- Mini Showcase(like screenshots):  
![image](https://user-images.githubusercontent.com/22407482/52108007-96668700-2633-11e9-9200-dbab24a13b34.png)

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@1053061407 
这是因为图表中有两个 geom，line 和 area，两个 geom 都显示 tooltip 所以重复了。
直接禁用一个geom 的  tooltip  即可。
```
          <Geom type="areaStack"  tooltip={false} position="year*value" color={['country', ['l (90) 0:rgba(0, 146, 255, 1) 1:rgba(0, 146, 255, 0.1)', 'l (90) 0:rgba(0, 268, 0, 1) 1:rgba(0, 268, 0, 0.1)']]} />

```

**Comment by 1053061407** [comment]
谢谢解答

**Comment by 2604150210** [comment]
那如果禁用一个，只保留另一个的话，那面积和折线的效果就只有一个了，我的需求是两个都要，怎么操作？请速回~~~
