### ISSUE TITLE
I need display null or empty values.

### ISSUE THREAD

**Issue by luchobonatti** [alibaba/BizCharts#721]
- bizcharts Version: 3.4.1
- Platform or react version: 16.6.3
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/33560821/52576581-1abcc500-2dff-11e9-9a02-8b365925f74e.png)

Hello!
I need to display empty values as points or dashed line. Can I do this?

**Comment by weepy3641** [comment]
@luchobonatti 
you can consult demo:
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-of-dashed&selectedKey=%E6%A6%82%E8%A7%88
