### ISSUE TITLE
LegendProps: incorrect typing of visible.

### ISSUE THREAD

**Issue by Meowu** [alibaba/BizCharts#722]
- bizcharts Version: 3.2.2
- Platform or react version:  16.7.2
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/16166258/52624281-5f248f80-2ee9-11e9-8e47-ea3dcc9d8d72.png)
- CodePen Link: no.
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

The typing of `visible` prop should be `boolean` instead of `string`.
I could not set `false` to hide specific legend, which may result in tslint warning and compile error.
By the way, I tried to set `visible={''}` , but it didn't work.

**Comment by weepy3641** [comment]
@Meowu 
first thanks ,  fixed in the version 3.4.3-beta.1.
