### ISSUE TITLE
slider 拖动时，其左右两端的值，与横坐标左右两端的刻度值不对应

### ISSUE THREAD

**Issue by tyawei** [alibaba/BizCharts#723]
具体而言，如 slider 为时间值，拖动 slider，横坐标联动 slider 进行变化。不过此时 slider 两端的时间值，与横坐标不对应。具体可见 bizcharts 官网案例 https://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-rain-and-flow&selectedKey=%E6%A6%82%E8%A7%88：
![default](https://user-images.githubusercontent.com/25874165/52628236-3359d780-2ef2-11e9-906a-0b28d66717c1.png)
![default](https://user-images.githubusercontent.com/25874165/52628238-35bc3180-2ef2-11e9-8cc8-1009e869da42.png)
同时，我方项目应用上，同样有类似的情形。还请确认是否是 bug，以及后续计划。

**Comment by weepy3641** [comment]
@tyawei 
不是 bug。
横坐标最左边 tooltip 显示的值是真是数据点的值，slider 拖动的那个时间点未必有数据，因此显示的是最靠近 slider 最左边时间的数据点值。

**Comment by tyawei** [comment]
@weepy3641 
你关闭得太快了。。。
我知道，离 slider 最近的地方有数据，而恰好那个时间可能没有数据。
但是，数据展示上，也和 slider 每次拖动的最小时间单位有关，而最小时间单位如何决定的，这里就可能有问题：
比如，我方横坐标和 slider 上的时间都精确到秒，的确有时候也没有数据，比如：理想情况从 :00 秒拖动到 :01  :02  :03 这些时间，但是实际上直接从 :00 最小拖动距离就直接到了 :02，再拖动到了 :04。
但是横坐标上，:01  :03  :05 处有数据，中间没数据。那么就出现情况：slider左侧 从 :00 拖动到 :02，此刻横坐标最左侧出现的并不是 :02，而是 :03，再拖动，slider 左侧可能是 :04 ，横坐标左侧则是 :05。
为什么 slider 就不能从 :00 到 :03 :05有数据处？偏偏还是离数据最近的地方？这不太合理吧？我相信，即使是以 分 为单位，同样存在这个问题
![1sss](https://user-images.githubusercontent.com/25874165/52831550-008d2a80-3110-11e9-9d16-0ace39d657ea.png)
![2sss](https://user-images.githubusercontent.com/25874165/52831553-0256ee00-3110-11e9-929b-c1559467a47e.png)
