### ISSUE TITLE
当geom的position的y值有多个时，会出现多个y轴

### ISSUE THREAD

**Issue by 1053061407** [alibaba/BizCharts#724]
- bizcharts Version: 3.4.3
- Platform or react version:
- Mini Showcase(like screenshots):  
![image](https://user-images.githubusercontent.com/22407482/52701848-26062100-2fb6-11e9-8db0-2def9272507c.png)

- CodePen Link:  https://codepen.io/1053061407/pen/LqBbWw

代码如下：（取自官方实例）
```
    <Geom type="interval" position="time*call" color="#ff8888" />
    <Geom type="interval" position="time*waiting" color="#3182bd" />
    <Geom
      type="line"
      position="time*people"
      color="#fdae6b"
      size={3}
      shape="smooth"
      />
    <Geom
      type="point"
      position="time*people"
      color="#fdae6b"
      size={3}
      shape="circle"
      />
```
当position的x*y的y有多个值时，如上的call，waiting，people。y轴会有三个轴。并且右边的两个轴及轴线是重叠的。而且此时设置Axis是无效的。期望是只渲染其中的两个(自己只要两个y轴)。或者是如何设置，使y轴不重叠。

因为我看g2官方的文档
![image](https://user-images.githubusercontent.com/22407482/52702437-1c30ed80-2fb7-11e9-97b9-4e11ba95d9c2.png)
y轴的个数是自动根据position来渲染的。这样就无法通过Axis标签来设置了。

**Comment by Leannechn** [comment]
图形的Y比例尺即position Y 对应了不同n个字段，所以是有n个比例尺。Axis是对已产生的比例尺进行配置成坐标轴。如果希望合并则需从数据上处理，将不同字段合并为一个相同name。

**Comment by 1053061407** [comment]
> 图形的Y比例尺即position Y 对应了不同n个字段，所以是有n个比例尺。Axis是对已产生的比例尺进行配置成坐标轴。如果希望合并则需从数据上处理，将不同字段合并为一个相同name。

请问将不同字段合并为一个相同name是什么意思呢？那这些字段在显示上还有什么区别呢？能否举个例子呢？

**Comment by Asence** [comment]
请问这个问题解决了吗  我现在也遇到了这个问题
