### ISSUE TITLE
legend图例异常显示

### ISSUE THREAD

**Issue by 1053061407** [alibaba/BizCharts#726]
- bizcharts Version:  3.4.3 
- Platform or react version: 
- Mini Showcase(like screenshots):  
- CodePen Link: https://codepen.io/1053061407/pen/YBJppg

上面的codepen链接是我把官网的[多条折线图](https://bizcharts.net/products/bizCharts/demo/detail?id=line-curved&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE)实例代码修改过后的代码。在代码的data中，我多加了一个字段，叫做arpu
![image](https://user-images.githubusercontent.com/22407482/52832443-8494e180-3113-11e9-874a-e72c54e3d980.png)
但是我并不想把arpu这个字段和Tokyo，London这两个字段共用一个y轴。于是我并没有在transform的fields里面加入这个字段
![image](https://user-images.githubusercontent.com/22407482/52832514-d0478b00-3113-11e9-98c1-fa4f15caa1c2.png)
然后我在下面多加了一个<Geom> 
```
<Geom
   type="line"
   position="month*arpu"
   size={2}
   color={['arpu', '#ff8888']}
   shape={"smooth"}
/>
```
color也和数据中的字段做了映射，结果图例就显示不正常了

![image](https://user-images.githubusercontent.com/22407482/52911776-9d53f180-32e3-11e9-9bee-fa8d185c97ae.png)
这个长长的滑动条是什么鬼。而且这个图例为啥和其他图例不一样。
@weepy3641 @Leslie2014

**Comment by weepy3641** [comment]
@1053061407 
这是因为你的 arpu 字段的值是数值类型，图表库默认解析为 linear 数据了，所以 legend 变成滑块。
如果想要分类图例，在 scale 中把 arpu 的type指定下就行。
```
const scale = {
  arpu: { type: 'cat' }
}

<Chart scale={scale} ... >
```

**Comment by 1053061407** [comment]
> arpu: { type: 'cat' }

@weepy3641 设置完你上面写的，效果就成这样了。
![image](https://user-images.githubusercontent.com/22407482/52924638-8a373500-3368-11e9-85ea-37b96d7461e4.png)

arpu这条折线也没了，legend也和其他legend不一样,还成了3个。你可以在我的codepen链接试一下

**Comment by RunningCoderLee** [comment]
我也遇到了相同的问题，请问这个 issue 有什么进展吗，另外这个问题并没有真正被解决，是否考虑重新打开这个 issue？ @weepy3641

**Comment by 1053061407** [comment]
![](https://user-images.githubusercontent.com/22407482/53390779-48913480-39cf-11e9-8db2-ae4c7169ee5e.png)
目前我是用legend的items属性来实现自己想要的图例，暂时只能这样了 @RunningCoderLee

**Comment by RunningCoderLee** [comment]
@1053061407 有完整的代码吗，你提到的这个解决方案是基于你原始 demo 那种形式，还是基于更改 arpu 的type 为 `cat` 的形式呢，如果是第二种，不是在图里没有 arpu 的线条吗？

**Comment by 1053061407** [comment]
@RunningCoderLee  你可以看看这个https://codepen.io/ssfxz/pen/MPpOMj?editors=1010 
 [demo](https://codepen.io/ssfxz/pen/MPpOMj?editors=1010) 和这个(issue)[https://github.com/alibaba/BizCharts/issues/606].差不多就能解决了。我没有设置arpu的type为cat。
