### ISSUE TITLE
transform的type为fold时，如何把fields中的字段分别渲染折线图，柱状图等

### ISSUE THREAD

**Issue by 1053061407** [alibaba/BizCharts#728]
- bizcharts Version: 3.2.4
- Platform or react version:
- Mini Showcase(like screenshots): 
- CodePen Link:  https://codepen.io/1053061407/pen/pGqGVg?&editable=true
![image](https://user-images.githubusercontent.com/22407482/52951241-3fdfa380-33bc-11e9-8e9e-182e3b45e193.png)

拿官方最简单的demo来说，为了London，Tokyo让他们共用一个y轴，只能把transform的type设置为fold。但我又想让London渲染成柱状图, Tokyo渲染成折线图，该怎么实现呢？现实场景中不止两个指标，为了让他们共用一个y轴，只能用type: fold。但是又想让他们渲染成不同类型的图。
@weepy3641

**Comment by weepy3641** [comment]
@1053061407 
必须要用两个 geom 实现你的需求，然后将两个轴的 scale 统一下，然后隐藏掉一个轴。

**Comment by 1053061407** [comment]
问题是实际场景中数据的值可能不是这么小(才几十），可能上千上万。你没办法将两个轴的scale设置的那么合理，让图表适应不同大小的数据啊。而且我后来也想到了这种办法。https://codepen.io/1053061407/pen/aXXLxL. 
![image](https://user-images.githubusercontent.com/22407482/53000741-01052880-3464-11e9-917a-2754618fc9cf.png)


Tokyo的轴是左边的轴，刻度是20.右边是London的y轴。我在scale里设置了tickInterval是20.
```
London: {
   tickInterval: 20
}
```
为啥展示效果是图上这样。官方文档不是写tickCount的默认值是5么。那么显示不应该和左边的y轴一样么？
@weepy3641

**Comment by weepy3641** [comment]
@1053061407 
ticks 个数配置并不是精准值，算法会计算出刻度值比较好的同时又接近 ticks 配置以及数据的最大最小范围的值。
建议你将两个 scale 的 min max 配置为一样，并且 nice 为false，应该可以刻度保持一致。

**Comment by ChiaJune** [comment]
@weepy3641 您好，请问这种图表该如何实现呢？
![chart](https://i.loli.net/2019/03/25/5c98ad00b98b7.jpg)
