### ISSUE TITLE
可否设置Y轴的数值显示格式？

### ISSUE THREAD

**Issue by francisfeng** [alibaba/BizCharts#730]
如图所示，有些图表的数值较大，G2 是否有一些配置，用于设置 Y 轴的格式？

比如用「4K」代替「4000」、「20K」代替「20000」。

我查了很多文档，发现都是设置 X 轴的 label 格式的，没有相关的 Y 轴配置，但之前用的 Echarts 是可以配置但。

![bar-chart-with-hight-numers.png](https://i.loli.net/2019/02/19/5c6bb872d4cc2.png)

**Comment by liunian** [comment]
可使用 Axis label 属性的 formatter
https://bizcharts.net/products/bizCharts/api/axis#label
