### ISSUE TITLE
请问现在是否还继续支持Bubble Map？

### ISSUE THREAD

**Issue by Doug44444444** [alibaba/BizCharts#731]
- bizcharts Version: 3.4.1
- Platform or react version: Ant Design Pro

希望可以使用世界地图来做标记，我看到之前好像支持，不知道现在是否还继续支持世界地图？

**Comment by weepy3641** [comment]
支持的。站点 demo 只是将世界地图气泡图的 demo 下线了。
你可以参考 antv 的demo，转化为 bizcharts 语法就行。
https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html
