### ISSUE TITLE
饼图鼠标hover上label如何显示tooltip？

### ISSUE THREAD

**Issue by Walker-Leee** [alibaba/BizCharts#732]
- bizcharts Version: 3.4.2
- Platform or react version: 16.2.0
- Mini Showcase(like screenshots): https://bizcharts.net/products/bizCharts/demo/detail?id=pie-multi-level&selectedKey=%E9%A5%BC%E5%9B%BE

![image](https://user-images.githubusercontent.com/20471090/53309401-86645f00-38e2-11e9-95f4-a4333deba1ff.png)
如何实现鼠标hover到label，显示提示信息。

**Comment by weepy3641** [comment]
@Walker-Leee
需要 label 事件和 g2 instance 的接口混合使用。
事件：
https://bizcharts.net/products/bizCharts/api/chart#%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%E4%BA%8B%E4%BB%B6
显示 tooltip：
https://www.yuque.com/antv/g2-docs/api-chart#lzegwt
获取 g2 chart instance
https://bizcharts.net/products/bizCharts/api/chart#ongetg2instance
