### ISSUE TITLE
堆叠柱状图显示汇总Label

### ISSUE THREAD

**Issue by zpfblockchains** [alibaba/BizCharts#735]
<Geom type="intervalStack"
                                position="月份*月均降雨量"
                                color={"name"}
                                style={{
                                    stroke: "#fff",
                                    lineWidth: 1
                                }} />
堆叠柱状图想要只显示汇总的Lable 要怎么写

**Comment by weepy3641** [comment]
@zpfblockchains 
需要你自己计算一个统计汇总字段出来，然后显示那个汇总字段即可。
