### ISSUE TITLE
bizcharts图例太多显示不全

### ISSUE THREAD

**Issue by qwaszx1230** [alibaba/BizCharts#739]
- bizcharts Version:3.4.3

![image](https://user-images.githubusercontent.com/22724660/53383308-23da9400-39b2-11e9-9094-67b2c3cce55d.png)

**Comment by ssfxz** [comment]
不建议饼图显示过多的项，没有实际应用价值，你可以将数据进行合并，将较小的项合并为“其他”。我认为一般限制在5-10项是合理的。

**Comment by ssfxz** [comment]
图例显示不全，可以使用自定义图例的方式处理，后面我们也会有这方面的优化
