### ISSUE TITLE
BizCharts展示双纵线&小数

### ISSUE THREAD

**Issue by XDorThanks** [alibaba/BizCharts#740]
折线图需要展示双纵线时需要在Chart标签添加Chart属性
`const scale = {
            mock: {
              min: 0,
              tickCount: 6,
              alias: 'xxx1',
            },
              mock1: {
              min: 0,
              max:1,
              tickCount: 6,//tickCount需要相同
              alias: 'xxx',
            },
          };`
其中一个纵线需要展示0-1的小数是需要有max,min属性做限定,并通过tickCount属性进行控制（nice算法的最优计算）

**Comment by weepy3641** [comment]
@XDorThanks 
不明白你有什么问题，麻烦说讲楚些。

**Comment by XDorThanks** [comment]
@weepy3641  风月让我提的一个issue。。。
