### ISSUE TITLE
bizcharts slider & dash line

### ISSUE THREAD

**Issue by liukevin82** [alibaba/BizCharts#741]
想請問各位，如何結合Slider以及dash line的呈現
實作過後如下圖
![image](https://user-images.githubusercontent.com/48010050/53398591-ed6a3c80-39e4-11e9-89f7-8480a3da5c3e.png)
![image](https://user-images.githubusercontent.com/48010050/53398612-f9ee9500-39e4-11e9-8c42-eb43d26c8495.png)
dash line 透過畫白色虛線的方式，交疊兩個view，完成部分虛線的功能
兩個View的data source不同
但slider data為originDV，originDV只能有一個data source
導致slider使第一個View的圖更新，但dash line的View無更新
要如何創建兩個chartDV source from originDV 且data source不相同呢?

附上codepen demo
https://codepen.io/liukevin82/pen/LaYqLm?editors=1010

參考範例
https://bizcharts.net/products/bizCharts/demo/detail?id=line-curved&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-area-large&selectedKey=%E6%A6%82%E8%A7%88
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-area-rainfall&selectedKey=%E6%A6%82%E8%A7%88
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-of-dashed&selectedKey=%E6%A6%82%E8%A7%88
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-rain-and-flow&selectedKey=%E6%A6%82%E8%A7%88
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-peking-aqi&selectedKey=%E6%A6%82%E8%A7%88

**Comment by weepy3641** [comment]
@liukevin82 
slider 主要是帮你将数据按照 slider 的 start end 过滤数据后，更新对应图表的数据。
你另一个view 想要更新，可以自己在 slider 的change 函数中自己去更新 view 的数据。
