### ISSUE TITLE
Geom的style属性可以给折线图线条加阴影吗

### ISSUE THREAD

**Issue by kafeihaoka** [alibaba/BizCharts#742]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ssfxz** [comment]
当然可以
Geom的style属性里可以支持绝大多数的原生Canvas的绘图属性
例如你的需求可以使用：shadowOffsetX、shadowOffsetY、shadowColor、shadowBlur等属性实现，具体作用与canvas里完全一致。

给你举个🌰：
<Geom type="interval" position="genre*sold" color="genre" style={{
      shadowColor: 'rgba(100,100,100,0.5)',
      shadowBlur:50,
   }}
/>

**Comment by kafeihaoka** [comment]
了解，多谢~
