### ISSUE TITLE
bizcharts多条Y轴

### ISSUE THREAD

**Issue by ivan86113** [alibaba/BizCharts#743]
要求显示多条Y轴，2条以上，该如何添加属性值？

**Comment by weepy3641** [comment]
@ivan86113 
两个 geom， y 不一样即可。
参考
https://bizcharts.net/products/bizCharts/demo/detail?id=double-axes-legend&selectedKey=%E6%A6%82%E8%A7%88

**Comment by JJoan0116** [comment]
@weepy3641  两根Y轴不能共用一个刻度线么？多个刻度线看上去好乱

**Comment by panlw** [comment]
请问，三组数据，一个左Y，两个右Y轴，怎么弄？
