### ISSUE TITLE
环图能画出如下样式吗？

### ISSUE THREAD

**Issue by Dogtiti** [alibaba/BizCharts#744]
![image](https://user-images.githubusercontent.com/38354472/53480511-5372c480-3ab6-11e9-868e-b85944b79f6d.png)
能画出这种带圆角的吗？

**Comment by weepy3641** [comment]
@Dogtiti  
默认唤醒图做不到这种形状，通过自定义图形可以的。
自定义图形可以参考下仪表盘 demo 的 指针定义。
https://bizcharts.net/products/bizCharts/demo/detail?id=gauge-color&selectedKey=%E4%BB%AA%E8%A1%A8%E7%9B%98
文档
https://bizcharts.net/products/bizCharts/api/shape
