### ISSUE TITLE
how to display modal overlay or alternate tooltip onClick

### ISSUE THREAD

**Issue by theCalibrius** [alibaba/BizCharts#745]
- bizcharts Version: 3.4.3
- Platform or react version: React 16.6.3

I've been trying to figure out how I can implement a click event callback when the user clicks on the image generated by Geom / shape elements.  I'm currently using a chart similar to this style:
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-bubble-image&selectedKey=%E6%A6%82%E8%A7%88

When a user clicks on one of the circle images, I would like for this to trigger an onClick callback.  

But I haven't found any documentation as to how I can define responses to click events.

I already have a tooltip displaying when the user hovers over the image, but I would like additional content to display when the user clicks.

How can I achieve this?

**Comment by weepy3641** [comment]
use chart's on${GeomType}Click evt.
like:
```
<Chart onPointClick={evt => {console.log(evt)}} />
```
api:
https://bizcharts.net/products/bizCharts/api/chart#%E5%9B%BE%E5%BD%A2%E5%85%83%E7%B4%A0%E4%BA%8B%E4%BB%B6
