### ISSUE TITLE
高亮饼图Hover部分的区域

### ISSUE THREAD

**Issue by xxxxxMiss** [alibaba/BizCharts#748]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

如何实现类似echarts中的[这种效果?](https://www.echartsjs.com/examples/editor.html?c=pie-doughnut)

**Comment by harry75369** [comment]
高亮的话，可以设置 geom 的 active 属性，https://bizcharts.net/products/bizCharts/api/geom#active

**Comment by weepy3641** [comment]
如果需要像 echarts 一样往外移动，暂时不支持。
