### ISSUE TITLE
Html 下面的html饼图中间的数据突然无法展示,之前是可以的，npm install以后就不行了，具体表现为刚加载的瞬间会出现，然后就没有了

### ISSUE THREAD

**Issue by gaochao-git** [alibaba/BizCharts#749]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@gaochao-git 
具体哪个 demo ？或者能否给个 codepen 链接。

**Comment by gaochao-git** [comment]
<Html
                        position={["50%", "50%"]}
                        html={'<div style="font-size:10px;text-align: center;width: 10em;">地域<br><span style="font-size:10px">' + '人口分布' + '</span></div>'}
                        alignX="middle"
                        alignY="middle"
                      />
                    </Guide>

**Comment by gaochao-git** [comment]
降级为3.4.3就好了

**Comment by gaochao-git** [comment]
这个bug什么时候可以修复？

**Comment by weepy3641** [comment]
@gaochao-git 
已经修复了，3.4.5.
