### ISSUE TITLE
折线图，折线效果不平滑

### ISSUE THREAD

**Issue by rumsky** [alibaba/BizCharts#750]
折线图折线效果不平滑
![image](https://user-images.githubusercontent.com/12367395/53944292-061bd600-40fa-11e9-85fb-09acde4e701c.png)

**Comment by Leannechn** [comment]
能提供具体的代码codepen么，看起来是数据的问题

**Comment by rumsky** [comment]
当横坐标数据是时间戳格式化以后的字符串会出现这样的问题，如果是时间戳就不会

**Comment by rumsky** [comment]
> 能提供具体的代码codepen么，看起来是数据的问题

当横坐标数据是时间戳格式化以后的字符串会出现这样的问题，如果是时间戳就不会

**Comment by weepy3641** [comment]
应该是时间数据的 scale type 默认解析为 time 了，事件戳是 cat 类型。
你可以将时间轴的 scale type 设置为 timeCat 试试，如果无效也没办法了，平滑效果不可能做到十全十美。
如果平滑不够好，建议直接用折线。
