### ISSUE TITLE
折线图，在某个点的数据为空时，线条会出现断开的情况，怎么让线条是连续的？

### ISSUE THREAD

**Issue by guanguanguo** [alibaba/BizCharts#751]
![default](https://user-images.githubusercontent.com/48321465/53959314-4b51ff00-411e-11e9-8416-00b3cb69120e.jpg)

**Comment by ssfxz** [comment]
如果某个点的数据为空，那个折线图就应该断开，不然数据表达会有歧义

**Comment by guanguanguo** [comment]
> 如果某个点的数据为空，那个折线图就应该断开，不然数据表达会有歧义

直接连上下一个数据点会比较好点，空值也不会表达出来。当有多个空数据的时候，就变成一段段的了，不太美观。如果能有个属性控制就比较好，按需求来显示连接还是断开

**Comment by ssfxz** [comment]
> > 如果某个点的数据为空，那个折线图就应该断开，不然数据表达会有歧义
> 
> 直接连上下一个数据点会比较好点，空值也不会表达出来。当有多个空数据的时候，就变成一段段的了，不太美观。如果能有个属性控制就比较好，按需求来显示连接还是断开

这是你的想当然，统计数据先要保证数据的正确性，其次才是美观。
如果是直接连上，表达的含义是有值的，这与实际情况不符。
在这个需求上我们调研了大量的场景，专业的数据可视化方案都是这么做的。

**Comment by ssfxz** [comment]
有一个例外场景是使用连续时间，那么是会连起来的，因为时间实际是维度而非度量

**Comment by fix777** [comment]
> > > 如果某个点的数据为空，那个折线图就应该断开，不然数据表达会有歧义
> > 
> > 
> > 直接连上下一个数据点会比较好点，空值也不会表达出来。当有多个空数据的时候，就变成一段段的了，不太美观。如果能有个属性控制就比较好，按需求来显示连接还是断开
> 
> 这是你的想当然，统计数据先要保证数据的正确性，其次才是美观。
> 如果是直接连上，表达的含义是有值的，这与实际情况不符。
> 在这个需求上我们调研了大量的场景，专业的数据可视化方案都是这么做的。

语气太强硬了吧，highcharts 是可以通过 API 来设置是否连接空点的，难道我们只能通过换用 highcharts 来实现这个需求吗？

**Comment by dubiao** [comment]
@ssfxz  其实连起来也不会导致语义有歧义。比如上图里，直接连起来两个断开的点，而中间不要画点，就可以正确地表达一种趋势。

实际使用中，如果有两种数据要放到一个图表中，但是他们的时间不一定都一样，断开就会不正确了。比如我现在的例子中，其实是两条数据，但只看到一条线，因为另一条线全是点点。

![image](https://user-images.githubusercontent.com/4001793/82663870-19fe1a00-9c63-11ea-933c-c91b4c68ca3e.png)

信号没有线，因为数据很稀松。
