### ISSUE TITLE
雷达图的数据都是小数时, 坐标轴的小数会失精度

### ISSUE THREAD

**Issue by x1nGoo** [alibaba/BizCharts#752]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/20261541/54003933-c05d1d00-418e-11e9-890b-f3c4b7ad1c04.png)
当我设置了 tickCount 为5的时候 坐标轴就会出现这种问题. 
codepen 我打开 显示不出图形, 

在线例子 https://bizcharts.net/products/bizCharts/demo/detail?id=radar-with-line&selectedKey=%E5%9C%B0%E5%9B%BE

代码: 
import React from "react";
import {
  G2,
  Chart,
  Geom,
  Axis,
  Tooltip,
  Coord,
  Label,
  Legend,
  View,
  Guide,
  Shape,
  Facet,
  Util
} from "bizcharts";
import DataSet from "@antv/data-set";

class Withline extends React.Component {
  render() {
    const { DataView } = DataSet;
	const data = [
      {name: "学校", label: "作出评价", value: 0.7},
      {name: "学校", label: "提取信息", value: 0.7},
      {name: "学校", label: "整体感知", value: 0.74},
      {name: "学校", label: "形成解释", value: 0.65},
      {name: "学校", label: "实际应用", value: 0},
      {name: "班级", label: "作出评价", value: 0.83},
      {name: "班级", label: "提取信息", value: 0.83},
      {name: "班级", label: "整体感知", value: 0.85},
      {name: "班级", label: "形成解释", value: 0.67},
      {name: "班级", label: "实际应用", value: 0},
      {name: "年级", label: "作出评价", value: 0.81},
      {name: "年级", label: "提取信息", value: 0.78},
      {name: "年级", label: "整体感知", value: 0.81},
      {name: "年级", label: "形成解释", value: 0.53},
      {name: "年级", label: "实际应用", value: 0}
    ]

   const scale = {
      value: {
        min: 0,
        tickCount: 5
      },
    };
   
    const defaultColors = [
      '#1890FF',
      '#FACC14',
      '#2FC25B',
      '#8543E0',
      '#F04864',
      '#13C2C2',
      '#fa8c16',
      '#a0d911',
    ];
    return (
      <div>
        <Chart
          height={window.innerHeight}
          data={data}
          padding={[20, 20, 95, 20]}
          scale={scale}
          forceFit
        >
          <Coord type="polar" radius={0.8} />
          <Axis
            name="label"
            line={null}
            tickLine={null}
            grid={{
              lineStyle: {
                lineDash: null
              },
              hideFirstLine: false
            }}
          />
          <Tooltip />
          <Axis
            name="value"
            line={null}
            tickLine={null}
            grid={{
              type: "polygon",
              lineStyle: {
                lineDash: null
              },
              alternateColor: "rgba(0, 0, 0, 0.04)"
            }}
          />
          <Legend name="user" marker="circle" offset={30} />
          <Geom type="line" position="label*value" color={['name', defaultColors]} size={2} />
          <Geom
            type="point"
            position="label*value"
            color={['name', defaultColors]}
            shape="circle"
            size={4}
            style={{
              stroke: "#fff",
              lineWidth: 1,
              fillOpacity: 1
            }}
          />
        </Chart>
      </div>
    );
  }
}

ReactDOM.render(<Withline />, mountNode)

**Comment by weepy3641** [comment]
@x1nGoo 
应该是你的 tickCount 配置引起的。可以去掉，或者
如果是比较高版本的 bizcharts ，可以在 scale 中配置下 minTickInterval：0.2，来定义最小刻度跨度尝试解决此问题。
