### ISSUE TITLE
服务端返回空数组时，Axis中alisa设置失效

### ISSUE THREAD

**Issue by maomaoChang** [alibaba/BizCharts#753]
- bizcharts Version: 3.4.3
- Platform or react version: 15.6.2
- Mini Showcase(like screenshots):
正常情况下：
![image](https://user-images.githubusercontent.com/32168003/54015946-58253000-41bc-11e9-8aff-716e571de898.png)

服务端返回空结果时：
![image](https://user-images.githubusercontent.com/32168003/54015986-7be87600-41bc-11e9-94d3-186a39d3644d.png)

React中代码如下：
![image](https://user-images.githubusercontent.com/32168003/54016082-c4a02f00-41bc-11e9-8170-870b0387cb5c.png)

**Comment by ssfxz** [comment]
经过定位是G2存在的问题，我们已经联系了G2的作者，会尽快修复发布

**Comment by maomaoChang** [comment]
@ssfxz 好的，谢谢
