### ISSUE TITLE
同一个视图下怎么控制某一个图例的显示和隐藏？现在好像只能显示所有或者都不显示？

### ISSUE THREAD

**Issue by xiangchunyu** [alibaba/BizCharts#754]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@xiangchunyu 
legend name 属性可以指定需要配置哪个 legend。
https://bizcharts.net/products/bizCharts/api/legend#name

**Comment by xiangchunyu** [comment]
> @xiangchunyu
> legend name 属性可以指定需要配置哪个 legend。
> https://bizcharts.net/products/bizCharts/api/legend#name

同一个视图下legend的name是相同的，无法区分呢
比如
<Chart width={600} height={400} data={data}>
    <Legend name="type" visible={true} />
    <Geom type="line" position="genre*sold" color="type" />
</Chart>
这个有多条线，但只想展示其中几条线的图例
