### ISSUE TITLE
堆叠柱状图设置 ticks 无效

### ISSUE THREAD

**Issue by aprilandjan** [alibaba/BizCharts#755]
- bizcharts Version `v3.4.2`:
- CodePen Link: https://codepen.io/anon/pen/JzyLpp?&editable=true

参考官网 [DEMO](<https://bizcharts.net/products/bizCharts/demo/detail?id=bar-stacked-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE>), 在此基础上，尝试给该图表自定义 [ticks](https://bizcharts.net/products/bizCharts/api/scale#ticks)，没有任何效果。具体情况如下：

1. 给 `Chart` 增加 ticks 的配置:

```jsx
const scale = {
  "月均降雨量": {
    ticks: [0, 10, 50],
  },
}
```

此时 ticks 没有生效。

2. 把 `Geom` 的 type 从堆叠图 `intervalStack` 替换为 `interval`， ticks 生效;
3. 仍然使用 `intervalStack`, 给 scale 又增加了一个 `max` 属性且 max 值大于最大的 y 轴值（参考 <https://github.com/alibaba/BizCharts/issues/734>):

```jsx
const scale = {
  "月均降雨量": {
    ticks: [0, 10, 50],
    max: 300,
  },
}
```

此时 ticks 才起作用。

总结：对于堆叠图直接设置 ticks 无效；但是当同时设置了 max 且 max 要大于数据的实际 y 轴最大值时, ticks 又生效了

**Comment by harry75369** [comment]
intervalStack 由于需要计算堆叠，因此在 ticks 上会有些特殊的考虑，导致你这边设置无效。

这是 G2 底层实现的问题，而非 Bizcharts 层面的 bug。在 G2 的示例中可可以复现这个问题：https://antv.alipay.com/zh-cn/g2/3.x/demo/column/grouped-column.html

建议向 G2 提起 issue

**Comment by aprilandjan** [comment]
@harry75369 嗯，看了 bizchart  源码发现很多配置基本都是直接给到 G2, 但一般对 G2 不了解或不关心组件库底层实现，所以 bizchart 这有很多可能来自 G2 的设定问题或 issue.

其实原本是想在堆叠图的 Y 坐标 grid 内单独加一条特定的标识线的，用 Guilde.Line 无法满足(堆叠 bar 左右侧默认留了空), 用 ticks 指定又有问题。后来还是通过额外增加一个 Axis 并单独指定 ticks 绘制此标识线以达成目标。为了让两个 Y 轴 scale 范围一致不得不去用 scale 去算一个 max 并手动指定给这两个 Y 轴，颇为不便。
