### ISSUE TITLE
candle烛型图，无法根据slider正常缩放

### ISSUE THREAD

**Issue by houzip** [alibaba/BizCharts#757]
candle烛型图的宽度无法像柱状图一样缩放

**Comment by harry75369** [comment]
参考 G2 的烛型图示例：https://antv.alipay.com/zh-cn/g2/3.x/demo/candlestick/basic.html

烛型图与柱状图是两种不同的 geom，实现不同，所以缩放的语义也有差异。Bizcharts 只是 G2 的 React 封装，语义上是与 G2 保持一致的。如有需要，可以在 G2 那边提 issue。
