### ISSUE TITLE
crosshairs渲染bug

### ISSUE THREAD

**Issue by fatalxiao** [alibaba/BizCharts#758]
官方示例：https://bizcharts.net/products/bizCharts/demo/detail?id=double-axes-legend
![image](https://user-images.githubusercontent.com/9260304/54171044-029a9d00-44b4-11e9-8d81-10e537c979cd.png)
rect crosshairs没有包含整个column区域

**Comment by weepy3641** [comment]
默认效果就是这样的。

**Comment by weepy3641** [comment]
@fatalxiao 
不好意思，之前没明白你的问题，tooltip 的矩形区域不对是有点问题，是双轴影响的。
修复方式为：
1、 禁用 line tooltip
2、在 chart ontooltipchange 中，主动加入 line 数据以供tooltip 显示。

demo：
https://codepen.io/anon/pen/MxVWmP
