### ISSUE TITLE
npm run demo fail

### ISSUE THREAD

**Issue by july-12** [alibaba/BizCharts#760]
when I execute command 'npm run demo' after cloning project in master branch I got blow error: 
![image](https://user-images.githubusercontent.com/920487/54248766-d137d500-4578-11e9-9576-94941338c6d6.png)

so I search [solutions](https://stackoverflow.com/questions/42060243/invalid-configuration-object-webpack-has-been-initialised-using-a-configuration), I update lower webpack@2.1.0-beta.22 and webpack-dev-server@2.1.0-beta.9 version, then solved it,  make it work now.
 
so I wonder which do I really need to fix this is problem by this way? (ps: my node v8.11.2)

**Comment by weepy3641** [comment]
we locked webpack-dev-server": "2.9.1", that's can fix this issue.
you can try the latest bizcharts code
