### ISSUE TITLE
Chart 设置了onPlotClick 事件之后 Geom的 select 属性失效

### ISSUE THREAD

**Issue by abramstyle** [alibaba/BizCharts#761]
- bizcharts Version: 3.4.5
- Platform or react version: 16.2.0
- Mini Showcase(like screenshots): 
- CodePen Link: no
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

我绘制了一个柱状图，在使用时会在每一条被选中的时候设置一个背景颜色，单纯给 Geom 设置 select 属性的时候是工作正常的，但是如果给 Chart 设置了 onPlotClick 属性，那么 Geom 的 select 就不会正常工作了。难道是 select 属性会被 onPlotClick 属性覆盖吗？

**Comment by abramstyle** [comment]
使用另一种方法解决了。

**Comment by heiniuhaha** [comment]
bizcharts v3.5.5 已修复此问题

![image](https://user-images.githubusercontent.com/668144/63257496-7b482580-c2ac-11e9-97ad-90e5bfc3e66b.png)


`
/**
 * 基础图表
 */

import React from 'react';
import ReactDOM from 'react-dom';
import { Chart, Geom, Axis } from 'bizcharts';

const data = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 }
];

const scales = {
  sold: { alias: '销售量' },
  genre: { alias: '游戏种类' }
};

const $mountNode = document.getElementById('mountNode');
ReactDOM.render((
  <Chart width={600} height={400} data={data} scale={scales} onPlotClick={ev=>{
      console.log(ev);
      $mountNode.append(`<p>${JSON.stringify(ev.data._origin)}</p>`);
    }}>>
    <Axis name="sold" />
    <Axis name="genre" />
    <Geom type="interval" position="genre*sold" color="genre" select={[true, {
    mode: 'single', // 选中模式，单选、多选
    style: { lineWidth:10}, // 选中后 shape 的样式
    cancelable: false, // 选中之后是否允许取消选中，默认允许取消选中
    animate: true// 选中是否执行动画，默认执行动画
  }]} />
  </Chart>
), $mountNode);
`

**Comment by heiniuhaha** [comment]
注意此处不要使用react的setState，会引起图表重渲染，引起图表事件实效
