### ISSUE TITLE
是否可以增加一个组织机构图

### ISSUE THREAD

**Issue by xiaopanghhh** [alibaba/BizCharts#762]
是否可以增加一个组织机构图

**Comment by weepy3641** [comment]
不明白你在说什么，请详细描述你的问题。

**Comment by xiaopanghhh** [comment]
![11174519-1c1e1cf5b5b44a9faa80d56ca8bc786b](https://user-images.githubusercontent.com/24469601/54349071-6f18c600-4685-11e9-8235-75f808035d57.png)
 

是否可以增加一个类似这样的图。

**Comment by weepy3641** [comment]
bizcharts 更多的是统计类图表，关系数据图表建议使用 G6
https://antv.alipay.com/zh-cn/g6/2.x/demo/index.html
