### ISSUE TITLE
修改主题效果未实时生效

### ISSUE THREAD

**Issue by july-12** [alibaba/BizCharts#764]
- bizcharts Version:  lastest
- Platform or react version:  react@16.8.3
- CodeSandBox Link: 
[![Edit 1j212z247](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1j212z247?fontsize=14)

调用setTheme修改主题之后，效果不是实时生效的吗？

**Comment by harry75369** [comment]
已经排查，是 G2 这边的问题。之后会持续跟进的
