### ISSUE TITLE
同时使用<Guide><Image /></Guide>和<Guide><Text /></Guide>时，Text文本不显示，Image显示

### ISSUE THREAD

**Issue by Yangchunyu01** [alibaba/BizCharts#769]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Yangchunyu01** [comment]
const { Image } = Guide;
const { Text } = Guide;
<Guide>
                        <Text 
                            top={true}
                            position={['50%','50%']}
                            content="26"
                            style={{
                                fill:'#666',
                                fontSize:'16',
                                fontWeight:'blod',
                            }}
                        />
</Guide>
<Guide>
<Image 
top={true}
                                                src={patleImg}
                                                start={['1.8%','-20']}
                                                width={50}
                                                height={50}
/>
</Guide>

**Comment by Yangchunyu01** [comment]
<Text />和<Image />必须在一个Guide中使用吗？

**Comment by weepy3641** [comment]
@Yangchunyu01 
guide 由于 g2 的更新限制，必须在一个 guide 中使用。
如果 text 不显示，麻烦给个完整的 codepen demo，靠代码细节无法排查问题。
