### ISSUE TITLE
地图卡顿

### ISSUE THREAD

**Issue by Mr-Grp** [alibaba/BizCharts#770]
是一个中国地图，以前用的json不是很大，但客户要求精准，换了一个 geojson 有点大，https://geo.datav.aliyun.com/areas/bound/100000_full.json
渲染的时候（初次加载或数据发生改变）会卡顿一下，有什么办法优化吗，或者有带南海群岛的还算标准的 没那么大的 geojson 吗

**Comment by weepy3641** [comment]
@Mr-Grp 
数据量大，卡顿正常。 我们这也没有地图数据，可以去高德这种专业地图站点下点地图 json。
