### ISSUE TITLE
导入bizcharts-plugin-slider时报错：Cannot read property 'Util' of undefined 

### ISSUE THREAD

**Issue by songchengen** [alibaba/BizCharts#774]
- bizcharts Version: 3.5.1
- bizcharts-plugin-slider Version: ^2.1.1-beta.1
- Platform or react version:  16.8.4

使用Slider 时提示异常，我引入bizcharts的Util模块后异常消失。

请问这是什么原因，我并没有用到Util模块。

**Comment by ironicstone** [comment]
1、建议把bizcharts和slider升级至最新版本试试看   2、提供复现case

**Comment by songchengen** [comment]
@ironicstone 感谢回复，本地的版本都是最新
复现地址： https://codesandbox.io/s/yvvknr5x6j?fontsize=14

**Comment by ironicstone** [comment]
@songchengen  bizcharts是slider的 peer dependency，所以还是要引入的。就好比bizcharts依赖react,所以需要引入react。

**Comment by songchengen** [comment]
这样子啊 = =好伐，感谢回复 @ironicstone

**Comment by remloyal** [comment]
请问下具体解决方法是什么？

**Comment by songchengen** [comment]
> 请问下具体解决方法是什么？

emmmm，年代久远，记不得了
