### ISSUE TITLE
Typescript中使用Shape.registerShape报错

### ISSUE THREAD

**Issue by SimpleSunLight** [alibaba/BizCharts#777]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

Shape.registerShape('interval', 'waterfall', {
          draw(cfg, container) {
            const attrs = getFillAttrs(cfg);
            let rectPath = getRectPath(cfg.points);
            rectPath = this.parsePath(rectPath);
            const interval = container.addShape('path', {
              attrs: Util.mix(attrs, {
                path: rectPath
              })
            });
            if (cfg.nextPoints) {
              let linkPath = [
                [ 'M', cfg.points[2].x, cfg.points[2].y ],
                [ 'L', cfg.nextPoints[0].x, cfg.nextPoints[0].y ]
              ];
              if (cfg.nextPoints[0].y === 0) {
                linkPath[1] = [ 'L', cfg.nextPoints[1].x, cfg.nextPoints[1].y ];
              }
              linkPath = this.parsePath(linkPath);
              container.addShape('path', {
                attrs:  {
                  path: linkPath,
                  stroke: 'rgba(0, 0, 0, 0.45)',
                  lineDash: [ 4, 2 ]
                }
              });
            }
            return interval;
          }
        });
在ts中无法显示效果图？

**Comment by ironicstone** [comment]
目前bizcharts/g2的ts声明文件不是很完备，如果是因为类型检查导致的error，可以忽略或者做类型提升。可能的话，欢迎给我们提pr，完善整个类型系统。

**Comment by SimpleSunLight** [comment]
还有传参的问题？ts中文件显示必须传，且const defaultAttrs = Shape.interval;中提示在Shape显示不存在interval

**Comment by ironicstone** [comment]
> 还有传参的问题？ts中文件显示必须传，且const defaultAttrs = Shape.interval;中提示在Shape显示不存在interval

应该没有Shape.interval吧。具体的api还是要参考一下文档，声明文件中不是很完整。
