### ISSUE TITLE
航线图显示错误？

### ISSUE THREAD

**Issue by ZhuoXin97** [alibaba/BizCharts#779]
- bizcharts Version:    "bizcharts": "^3.4.0"
- Platform or react version: "react": "^16.6.3",
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

官网上给了一个美国飞机航线图的
[demo](https://bizcharts.net/products/bizCharts/demo/detail?id=map-with-connection&selectedKey=%E5%9C%B0%E5%9B%BE)

我
把 航线注释了
把 mapDv 换成中国地图的 [Geojson ](http://www.ourd3js.com/wordpress/638/)
 ，这个绘制成功了
把airports 换成 
[
  {"name":"北京市","count":666,"lat":39.9299857781,"lon":116.395645038}
];

发现没有显示到之前绘制的中国地图的北京位置

![image](https://user-images.githubusercontent.com/20581165/55137718-a5b60c80-516c-11e9-8424-aee625d698e1.png)

此外修改尺寸的话 有时候绘制的地图会消失

具体代码

[index.zip](https://github.com/alibaba/BizCharts/files/3016661/index.zip)

**Comment by ironicstone** [comment]
1、确认不同view的值域范围是相同的，chart -> scale -> sync   2、确认数据格式是否符合输入标准  3、你的代码文件没有上传成功，建议在codesandbox或者codepen上搞个在线的demo

**Comment by ZhuoXin97** [comment]
> 1、确认不同view的值域范围是相同的，chart -> scale -> sync 2、确认数据格式是否符合输入标准 3、你的代码文件没有上传成功，建议在codesandbox或者codepen上搞个在线的demo

在线的demo   https://codesandbox.io/embed/7z9r6jnw50

**Comment by ZhuoXin97** [comment]
地图消失 那个没问题的 是我没考虑到异步加载问题

**Comment by ironicstone** [comment]
@ZhuoXin97  https://codesandbox.io/embed/xl5lxm38qz  改了一下，就是我说的那个问题，scale要加载chart上，不同view需要sync

**Comment by ZhuoXin97** [comment]
原来是这样 😂  谢谢亲
