### ISSUE TITLE
纵坐标能否把数字换成图片吗

### ISSUE THREAD

**Issue by chengang1111** [alibaba/BizCharts#780]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ironicstone** [comment]
可以的， 支持富文本，各种icon，img等，可以使用htmlTemplate来自定义。关键词： axis -> label -> htmlTemplate
