### ISSUE TITLE
堆叠图 Tooltip 只有一个鼠标放上去有tooltip提示，其他没有效果

### ISSUE THREAD

**Issue by SimpleSunLight** [alibaba/BizCharts#781]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

作用环境是在ts中的，不知道影不影响?

**Comment by ironicstone** [comment]
官网提供的demo没有类似的问题，和ts影响不大，因为声明文件并不会影响最终的编译文件。建议把bizcharts升级到最新版。如果还有问题的话，贴一下复现case的codesandbox或者codepen链接。
