### ISSUE TITLE
如何获取到x轴和y轴上的(0, 0)也就是原点在cavas画布的坐标

### ISSUE THREAD

**Issue by aeolusheath** [alibaba/BizCharts#782]
- bizcharts Version: 3.4.3
- Platform or react version: os is windows and  react version is 16.8.4

Chart组件的点击事件onPlotClick事件只能获取到当前点在画布上的坐标，不能获取到当前点在x轴y轴上的坐标。

可以拿到当前点 相对于 x轴和y轴上的(0, 0)这个坐标吗？

----

因为目前有一个需求，用g2-brush去选择一个范围，但是选择范围只能确定长度，不能确定精度，不能确定在x轴上起点在哪里，也就不能确定这个准确的范围，相对于x轴的总体长度。

**Comment by ironicstone** [comment]
可以尝试一下getXY方法。
