### ISSUE TITLE
Legend 自定义 items

### ISSUE THREAD

**Issue by 184455** [alibaba/BizCharts#783]
- bizcharts Version:3.1.5
- Platform or react version:16.2
我们正在按照Ui 还原页面，他们的需求是在饼图的下面把信息都展示出来，比如：把百分比数据在下面也展示一份，如图
![image](https://user-images.githubusercontent.com/30168717/55215136-b67d8580-5233-11e9-90c9-58a6b5ffe1da.png)
然后我在代码里面定义了这类型的数据，
{ name: '新建', value: '40', percent: '40', fill: '#3182bd', marker: 'shape' },
但是这个在我本地测试没有问题，但是发布生产版就加载不上数据。请问有解决的办法吗？

**Comment by ironicstone** [comment]
label是支持自定义的。生产版加载不上数据，可以先排查一下数据问题。可能的话，提供一下复现demo

**Comment by 184455** [comment]
我解决了，看了items定义的属性，给 items 传递一个函数就可以解决问题。
itemTpl?: string | ((param1?: string, param2?: string, param3?: boolean, index?: number) => string);
