### ISSUE TITLE
Legend 多的时候，显示不完全

### ISSUE THREAD

**Issue by tomgao365** [alibaba/BizCharts#784]
- bizcharts Version:3.x
- Platform or react version:16.x
- Mini Showcase(like screenshots):
- CodePen Link:
https://codepen.io/tomgao365/pen/gEVQwQ

**Comment by ironicstone** [comment]
可以选择legend分页或者滚动，legend支持自定义和翻页。

**Comment by duanbowen** [comment]
> 可以选择legend分页或者滚动，legend支持自定义和翻页。
你好，请问legend 如何手动设置为滚动方式而不是翻页方式？

**Comment by duanbowen** [comment]
@ironicstone  你好，请问如何设置legend的溢出方式为 滚动而不是翻页？

**Comment by ironicstone** [comment]
@duanbowen  用css，设置一个高度，然后overflow-y

**Comment by liunian** [comment]
可通过设置 padding 来留足够的空间 [chart#padding]( https://bizcharts.net/products/bizCharts/api/chart#padding)
或考虑把图例放到侧边来纵向排列（同样需要考虑 padding 空间）

关于图形的布局，可看 ![](https://img.alicdn.com/tfs/TB1G7_0bOqAXuNjy1XdXXaYcVXa-1148-542.png)
