### ISSUE TITLE
date-set排序在Chrome 73.0中无法生效

### ISSUE THREAD

**Issue by vVvlife** [alibaba/BizCharts#785]
- bizcharts Version: 3.4.5
- Platform or react version: react 16.6.3

**Comment by vVvlife** [comment]
![image](https://user-images.githubusercontent.com/20148964/55215388-98fceb80-5234-11e9-8fbe-dcc1f6096521.png)

**Comment by ironicstone** [comment]
提供一复现的demo吧，正常的js sort有同样的问题吗

**Comment by liunian** [comment]
由于没提供更多信息以供排查，暂关闭
