### ISSUE TITLE
Legend图例如何使用自定义图片?

### ISSUE THREAD

**Issue by lxsunbin** [alibaba/BizCharts#788]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by kreja** [comment]
可使用分类 html 自定义图例 https://bizcharts.net/products/bizCharts/api/legend#%E5%88%86%E7%B1%BB-html-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E4%BE%8B
