### ISSUE TITLE
purechart.jsx 的 height 为何一定要设置呢？并且只能设置为数字类型呢？

### ISSUE THREAD

**Issue by fengyun2** [alibaba/BizCharts#789]
- bizcharts Version:
3.5.2
- Platform or react version:
"react": "^16.8.6"
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/8147202/55603001-0069ec80-579b-11e9-97b4-b5873fb22141.png)

- CodePen Link:
- you can fork CodePen template form this: https://codepen.io/leslie2014/pen/xjJGER

<Chart> 为何不能根据父元素的高度自动适应呢？
![image](https://user-images.githubusercontent.com/8147202/55603080-71a99f80-579b-11e9-928c-2ec6f140a215.png)

**Comment by kreja** [comment]
关于高度自适应的讨论 https://github.com/antvis/g2/issues/227，目前还是只支持 px
