### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by yoster0520** [alibaba/BizCharts#79]
![image](https://user-images.githubusercontent.com/13730237/34476984-aa161da0-efd0-11e7-8df4-1bd6bb7f8da0.png)
TooltipController._getDefaultTooltipCfg
什么会导致使用中出现这种错误，我这的操作是，生成一个分面图，然后更改当前分面图的分面类型，就会触发这个错误。

```
<Chart
        height={this.props.height - 30}
        data={this.props.tableData.get('result').toJS()}
        forceFit
        // onPointClick={this._onClick}
      >
        <Tooltip showTitle={false} />
        <Legend
          position={legendConfig.position}
          offsetY={legendConfig.offsetY}
          offsetX={legendConfig.offsetX}
        />
        <Facet
          type={(facetConfig && facetConfig.type) || 'list'}
          fields={facetField.split(',')}
          cols={(facetConfig && facetConfig.size) || 3}
          padding={(facetConfig && facetConfig.padding) || 20}
        >
          {(view, facet) => {
            const data = facet.data;
            const dv = new DataSet()
              .createView()
              .source(data)
              .transform({
                type: 'percent',
                field: valueField,
                dimension: dimension,
                as: 'percent',
              });
            return (
              // eslint-disable-next-line no-plusplus
              <View data={dv} scale={cols} key={id++}>
                <Coord type="theta" innerRadius={0.35} />
                <Geom
                  type="intervalStack"
                  position="percent"
                  color={dimension}
                  style={{ lineWidth: 1 }}
                >
                  <Label content="percent" offset={-2} />
                </Geom>
              </View>
            );
          }}
        </Facet>
      </Chart>
```

**Comment by weepy3641** [comment]
@yoster0520   3.0.5版本吗？
3.1.0-beta 版本已经修复这个 bug 了，为了组件良好的扩展性， 3.1.0-beta 版本以后将不再支持,facet 组件中嵌套匿名函数的写法。
``` jsx
//不再支持
<Facet>
{
  (view, facet) => {
    return <View>...</View>
  }
}
</Facet>
// 支持以下写法
<Facet eachView={ (view, facet) => {} } />
// 或者, 以下这种写法需要等到这周发布 3.1.0 正式版
<Facet />
  <View>
     <Geom />
  </View>
</Facet>
```
详见： 
https://github.com/alibaba/BizCharts/blob/master/doc/api/facet.md

**Comment by yoster0520** [comment]
Thank you!

**Comment by yoster0520** [comment]
这周会发正式版吗。那我就先不生测试版了

On Jan 2, 2018 4:31 PM, HM <notifications@github.com> wrote:

@yoster0520<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyoster0520&data=02%7C01%7C%7C4e4bb0a00461464d4d3f08d551bb44ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636504787111161702&sdata=JKTnlz7e8CcTAsGux7AAHlVHitdKZtjL6rkctFsxG0g%3D&reserved=0> 3.0.5版本吗？
3.1.0-beta 版本已经修复这个 bug 了，为了组件良好的扩展性， 3.1.0-beta 版本以后将不再支持,facet 组件中嵌套匿名函数的写法。

//不再支持
<Facet>
{
  (view, facet) => {
    return <View>...</View>
  }
}
</Facet>
// 支持以下写法
<Facet eachView={ (view, facet) => {} } />
// 或者, 以下这种写法需要等到这周发布 3.1.0 正式版
<Facet />
  <View>
     <Geom />
  </View>
</Facet>

详见：
https://github.com/alibaba/BizCharts/blob/master/doc/api/facet.md<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falibaba%2FBizCharts%2Fblob%2Fmaster%2Fdoc%2Fapi%2Ffacet.md&data=02%7C01%7C%7C4e4bb0a00461464d4d3f08d551bb44ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636504787111161702&sdata=iBqIQ4lbVE79mHe7j0R3A0ZEjcJGmqFcjcCKeJKpQkQ%3D&reserved=0>

**Comment by weepy3641** [comment]
@yoster0520 
会的，这回有发 3.1.0 的正式版。

**Comment by yoster0520** [comment]
@weepy3641 3.1.0-beta.6支持下面写法吗？
```
//不再支持
<Facet>
{
  (view, facet) => {
    return <View>...</View>
  }
}
</Facet>
// 支持以下写法
//支持方式1
<Facet eachView={ (view, facet) => {} } />
// 支持方式2, 这种写法需要等到这周发布 3.1.0 正式版
<Facet />
  <View>
     <Geom />
  </View>
</Facet>
```

**Comment by weepy3641** [comment]
@yoster0520 
是的，facet 中嵌套匿名函数的写法 3.1.x版本将不再支持。
仅支持 eachView 属性或者 Facet 嵌套 View 组件。

匿名函数这种写法非常不利于扩展，g2 后续的发展中很可能 facet 套facet，view嵌套view。
同时在实现这种写法时实际上是将eachView 的 callback function 中传入的 view 及 facet 参数传给了组件。 这种实现依赖于 react组件创建及生命周期函数的执行 与 g2 eachView callback的执行穿插在一起。非常不利于封装。

**Comment by yoster0520** [comment]
好的

**Comment by weepy3641** [comment]
3.1.0 版本已经发布并修复如上bug。
