### ISSUE TITLE
为什么数据源变的时时候，图表不刷新？

### ISSUE THREAD

**Issue by zhouyao1994** [alibaba/BizCharts#790]
当我使用bizcharts的时候，
为什么点击按钮，修改数据源之后，图表不联动呢？
在consol.log 中显示数据已经改变，为什么图表没有动呢？

https://codepen.io/zhouyao/pen/xeEKqV?editors=0011

```js

        const { Chart, Axis, Geom, Tooltip } = window.BizCharts;
        var data = [
          { year: "1991", value: 5 },
          { year: "1992", value: 4 },
          { year: "1993", value: 3.5 },
          { year: "1994", value: 5 },
          { year: "1995", value: 4.9 },
          { year: "1996", value: 6 },
          { year: "1997", value: 7 },
          { year: "1998", value: 9 },
          { year: "1999", value: 13 }
        ];
        const cols = {
          'value': { min: 0 },
          'year': {range: [ 0 , 1] }
        };
        const click=()=>{
          data[0].value=3;
        }
        ReactDOM.render((
          <div>
            <button onClick={click}>change data</button>
          <Chart height={400} data={data} scale={cols} forceFit>
            <Axis name="year" />
            <Axis name="value" />
            <Tooltip crosshairs={{type : "y"}}/>
            <Geom type="line" position="year*value" size={2} />
            <Geom type='point' position="year*value" size={4} shape={'circle'} style={{ stroke: '#fff', lineWidth: 1}} />
          </Chart>
            </div>
        ), document.getElementById("mountNode"));
    
```

**Comment by longearshortail** [comment]
bizchart的例程只有显示图标这一项功能，要想实时更新得用生命周期方法。
想了解可以看他们写的教程。

https://www.yuque.com/ant-design/course/fd5af7

**Comment by weepy3641** [comment]
@zhouyao1994 
为了防止数据量过大，防止对比属性变化花太多时间，
数据改变用的是 reference 的比较，直接给数组内容，但 reference 没变，不会触发更新。

想要数据变化建议直接修改 data reference。或者拿到 chart 实例，调用 chart.changeData 接口。

**Comment by zhouyao1994** [comment]
好的，谢谢！

**Comment by GQMai** [comment]
> @zhouyao1994
> 为了防止数据量过大，防止对比属性变化花太多时间，
> 数据改变用的是 reference 的比较，直接给数组内容，但 reference 没变，不会触发更新。
> 
> 想要数据变化建议直接修改 data reference。或者拿到 chart 实例，调用 chart.changeData 接口。

请问在Ant Design Pro中如何获取chart实例？
谢谢。

**Comment by binglo** [comment]
> 好的，谢谢！

请问这是如何解决呢

**Comment by binglo** [comment]
> 直接

请教一下，我的页面上有多个图表，我将图表数据存放在数组中，data={data[i]}这种形式，那么我该如何解决

**Comment by zhouyao1994** [comment]
> > 好的，谢谢！
> 
> 请问这是如何解决呢

在react中,不能直接更改数据, 应该将数据设置为 state,更新state才会对图表进行刷新,
建议看下react的[最佳实践.](https://zh-hans.reactjs.org/docs/thinking-in-react.html)
