### ISSUE TITLE
Geom of type point with poor performance

### ISSUE THREAD

**Issue by andy1247008998** [alibaba/BizCharts#794]
- bizcharts Version: ^3.5.2
- Platform or react version:Ant Design Pro Latest
- Mini Showcase(like screenshots):

I need to render over 10k points in one chart.
`<Geom type="line"` works well, but `<Geom type="point"` takes forever to render itself.

**Comment by kreja** [comment]
A recommend upper limit is 5k points.
Related to https://github.com/alibaba/BizCharts/issues/499

**Comment by andy1247008998** [comment]
It is possible to fix this issue?

**Comment by liunian** [comment]
@andy1247008998 5k almost reach the limit of scatter plot by now, change `shape="circle"` to `shape="square"` may get better performance.
