### ISSUE TITLE
<Legend /> How to set its height?

### ISSUE THREAD

**Issue by andy1247008998** [alibaba/BizCharts#796]
- bizcharts Version: Latest
- Platform or react version: Ant Design Pro

`<Legend height={xxx} />` won't work.

![Jietu20190414-043708](https://user-images.githubusercontent.com/7299189/56085010-092f8200-5e6f-11e9-8a1c-6fb137fec20d.jpg)

**Comment by kreja** [comment]
What effect do you want? The prop `height` is only for continuous legend. See [legend#height](https://bizcharts.net/products/bizCharts/api/legend#height).

**Comment by liunian** [comment]
@andy1247008998 If you mean more space for legend, you can set [padding prop of chart](https://bizcharts.net/products/bizCharts/api/chart#padding)
