### ISSUE TITLE
<Geom color="country" /> in reverse order

### ISSUE THREAD

**Issue by andy1247008998** [alibaba/BizCharts#797]
- bizcharts Version: Latest
- Platform or react version: Ant Design Pro

https://bizcharts.net/products/bizCharts/demo/detail?id=area-stacked&selectedKey=%E9%9D%A2%E7%A7%AF%E5%9B%BE

I'd like to place `Asia` at the bottom and `Oceania` on the top.

**Comment by kreja** [comment]
This is based on the order of dataSource, you can make a sort with [DataSet](https://bizcharts.net/products/bizCharts/api/transform#sort-by-%E6%8C%89%E5%AD%97%E6%AE%B5%E6%8E%92%E5%BA%8F).
