### ISSUE TITLE
关于坐标轴是否能同时显示时间段以及日期

### ISSUE THREAD

**Issue by HSdiana** [alibaba/BizCharts#799]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by HSdiana** [comment]
https://cdn.space.9am.tech/issu/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-04-16%20%E4%B8%8A%E5%8D%8811.06.53.png

**Comment by weepy3641** [comment]
目前的版本无法支持。
