### ISSUE TITLE
柱状图的柱子无法设置最小高度

### ISSUE THREAD

**Issue by Alice2222** [alibaba/BizCharts#800]
- bizcharts Version: 3.4.3
- Platform or react version: 16.7.0
- Mini Showcase(like screenshots): 
![WechatIMG2068](https://user-images.githubusercontent.com/21191777/56184150-bbbc3c00-604b-11e9-9354-7aafb45ade35.jpeg)
- CodePen Link: 无
期望：有类似echart的barMinHeight的属性来设置柱子的最小高度

**Comment by weepy3641** [comment]
柱子的高度都是根据数据来的，目前不提供最小高度配置。

**Comment by seainhand** [comment]
这个着实需要一个最小高度 尤其是有点击事件的时候 太矮了点不到
