### ISSUE TITLE
TypeError: context.createId is not a function

### ISSUE THREAD

**Issue by rumsky** [alibaba/BizCharts#802]
- bizcharts Version:3.4.3
- Platform or react version:16.7.0
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/12367395/56195630-ecaa6a00-6067-11e9-8a4d-df138403fa0f.png)

**Comment by Leslie2014** [comment]
请在  https://codepen.io/leslie2014/pen/xjJGER  这个模板上做修改提供一个可复现的链接，以方便我们排查问题.
