### ISSUE TITLE
legend不显示，并且无法设置label

### ISSUE THREAD

**Issue by lcynnn435** [alibaba/BizCharts#803]
- bizcharts Version:3.4.3
- Platform :antd pro
- Mini Showcase(like screenshots):
- CodePen Link:https://codepen.io/veg_cn/pen/YMEozj

不知道为什么，legend不显示
并且在eachview里无法设置每个图的label（也许是可以的，但是没找到=，=）
请不吝赐教。
![image](https://user-images.githubusercontent.com/22272213/56196878-4d3aa680-606a-11e9-858b-d44d7a9aebe3.png)

**Comment by lcynnn435** [comment]
ah..label可以直接在eachview的view上设置.label('area');即可。。
legend问题还是无法解决。

**Comment by Leslie2014** [comment]
你好，你上面给的 CodePen demo 打开不了，麻烦提供一个可复现的链接吧，方便我们排查问题。

**Comment by lcynnn435** [comment]
import React from "react";
import {
  G2,
  Chart,
  Geom,
  Axis,
  Tooltip,
  Coord,
  Label,
  Legend,
  View,
  Guide,
  Shape,
  Facet,
  Util
} from "bizcharts";
import DataSet from "@antv/data-set";

class Labelline extends React.Component {
  render() {
    const { DataView } = DataSet;
    let data= [
      {
        type: '网评',
        '市区': 5,
        '东区': 15,
        '高新区': 35,
      },
      {
        type: '网宣',
        '市区': 15,
        '东区': 35,
        '高新区': 35,
      },
      {
        type: '舆情',
        '市区': 25,
        '东区': 15,
        '高新区': 35,
      },
     
    ];
    const dv = new DataSet.View().source(data);
    dv.transform({
      type: "fold",
      fields: [           
        '市区',
        '东区',
        '高新区',
      ],
      // 展开字段集
      key: "area",
      value: "count"
    }).transform({
      type: "percent",
      field: "count",
      dimension: "area",
      groupBy: ["type"],
      as: ["percent"]
    })
    return (
      <div>
         <Chart height={300} data={dv} forceFit padding={0}>
                <Legend  />
                  <Tooltip showTitle={false}/>
                  <Facet
                    type="list"
                    cols={3}
                    fields={['type']}
                    showTitle={true}
                    padding={0}
                    eachView={(view, facet) => {
                      window.o1=view;
                      view.coord('theta', {
                        radius: 0.8,
                        innerRadius: 0.4,
                      });
                      view
                        .intervalStack()
                        .position('count')
                        .color('area');
                      view.guide().html({
                        position: ['50%', '50%'],
                        html:
                          '<div style="color:#8c8c8c;font-size: 14px;text-align: center;width: 10em;">' +
                          facet.data[0].type +
                          '</div>',
                        alignX: 'middle',
                        alignY: 'middle',
                      });
                    }}
                  >
                   {/* <Label
                      content="percent"
                      formatter={(val, item) => {
                        return item.point.item + ": " + val;
                      }}
                   /> */}
                  </Facet>
                </Chart>
      </div>
    );
  }
}

ReactDOM.render(<Labelline />, mountNode)
