### ISSUE TITLE
slider可以控制滑块的范围吗？只左右滑动，不能伸缩怎么设置

### ISSUE THREAD

**Issue by HSdiana** [alibaba/BizCharts#804]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by wo-de-ping-er** [comment]
> * bizcharts Version:
> * Platform or react version:
> * Mini Showcase(like screenshots):
> * CodePen Link:
> * you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

请问你是怎么解决的？我这边也需要固定滑块的宽度，但是没有找到相应的API。
