### ISSUE TITLE
Axis上title={null}或者title={false}无效

### ISSUE THREAD

**Issue by SimpleSunLight** [alibaba/BizCharts#806]
<Axiis name="demo" title={null}>
无效，且在ts中title值只有object，按照api来说应该是
title?:object | null | boolean

**Comment by liunian** [comment]
在[官网 demo](https://bizcharts.net/products/bizCharts/demo/detail?id=bar-grouped-column&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE) 中测试，`null` 和 `false` 能隐藏 axis title。
还请提供下 bizcharts 的版本以及无效的 demo（最好能提供 codepen demo）

TS，如果考虑开启到 `strictNullChecks`，那么地区需要补充 `null` 进去，我们

**Comment by SimpleSunLight** [comment]
demo为官网的柱状图第一个,其他信息如图？



------------------ 原始邮件 ------------------
发件人: "liunian"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 中午11:24
收件人: "alibaba/BizCharts"<BizCharts@noreply.github.com>;
抄送: "Alex"<1778291978@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/BizCharts] Axis上title={null}或者title={false}无效 (#806)




在官网 demo 中测试，null 和 false 能隐藏 axis title。
 还请提供下 bizcharts 的版本以及无效的 demo（最好能提供 codepen demo）
 
TS，如果考虑开启到 strictNullChecks，那么地区需要补充 null 进去，我们
