### ISSUE TITLE
bizchart 的图表在 scale 的容器内，导致 tip 位置不对

### ISSUE THREAD

**Issue by teazean** [alibaba/BizCharts#808]
- bizcharts Version: 3.4.1 或者 3.5.2
- Platform or react version: 
     - MacOS 10.14.4 
     - Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- Mini Showcase(like screenshots): 
![bizchat](https://user-images.githubusercontent.com/4465253/56711309-c918ab00-675c-11e9-83f0-7bb348159005.gif)

- CodePen Link: https://codepen.io/teazean/pen/VNVrRo

**Comment by liunian** [comment]
需要等待 G2 那边处理  https://github.com/antvis/g2/issues/912

**Comment by liunian** [comment]
可参考改临时方案看看

https://github.com/antvis/g2/issues/912#issuecomment-498099293
