### ISSUE TITLE
怎么设置y轴刻度值不能有小数？

### ISSUE THREAD

**Issue by MaZhengA** [alibaba/BizCharts#810]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
@MaZhengA 
可以配置下 scale 的 minTickInterval : 1 来解决你的问题。

**Comment by luffyZh** [comment]
@weepy3641 设置了minTickInterval但是还是出现了小数，因为间隔变成了 1.5 > 1 。是不是同时配置了tickCount和nice:false的原因？有什么解决办法吗？

![图片](https://user-images.githubusercontent.com/17840558/70121464-9434e500-16a9-11ea-86d4-76600dfdd956.png)

```
 value: {
        formatter: (val) => `${val}人`,
        minTickInterval : 1,
        tickCount: 5,
        min: 0,
        nice: false
      },
```

**Comment by xmsz** [comment]
我也是这个情况 最后怎么解决的？

**Comment by bouquetrender** [comment]
如果刻度值有小数就将刻度隐藏

```js
  const label = {
    formatter: (text: any, dim: any) => {
      if (text.split('.')[1]) {
        return ''
      } else {
        return text
      }
    },
  }
```

```jsx
<Axis name="vote" label={label} />
```
