### ISSUE TITLE
请问支持滑动、放大缩小等手势操作吗？

### ISSUE THREAD

**Issue by Flying-Bullet** [alibaba/BizCharts#811]
请问支持滑动、放大缩小等手势操作吗？或者有什么方法可以解决大量数据需要绘制、又可以查看具体某个点的情况呢，

**Comment by weepy3641** [comment]
slider 的 demo 可以参考下。
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-area-large&selectedKey=%E6%A6%82%E8%A7%88
