### ISSUE TITLE
设置padding之后，height无效？

### ISSUE THREAD

**Issue by xiaohuoni** [alibaba/BizCharts#814]
问题一，图标的辅助线，始终不知道怎么去掉。
![image](https://user-images.githubusercontent.com/11746742/56793566-e3c35080-683e-11e9-8319-a95a2936dcaf.png)
问题二，当画布比较小的时候，整体图标偏右
![image](https://user-images.githubusercontent.com/11746742/56793640-081f2d00-683f-11e9-874d-6033a4b6b163.png)
问题三，因为整体偏右问题，设置了padding，发现height失效了
![image](https://user-images.githubusercontent.com/11746742/56793879-93002780-683f-11e9-8248-c643a27b7eac.png)
图中绿色是外层高度

**Comment by weepy3641** [comment]
1、 虚线是轴的 grid 线，去掉参考 grid 文档
https://bizcharts.net/products/bizCharts/api/axis#grid

2、可以尝试用 padding="auto" 解决，图表的 高度包括 padding，padding 配置太大会影响到图表高度高度。
