### ISSUE TITLE
无意义且有害的错误边界

### ISSUE THREAD

**Issue by vipcxj** [alibaba/BizCharts#820]
现在的ErrorBoundary不仅无用，反而有害，因为这个错误边界直接将错误抛弃，甚至都没`console.error`，还阻碍了错误继续向上级组件传递，导致即使上级组件定义ErrorBoundary也毫无作用，一旦发生错误，根本无从查起。至少加个`console.error(error, info)`吧~

**Comment by weepy3641** [comment]
下个版本会改进下 error 提示处理。
