### ISSUE TITLE
如何设置x坐标刻度不包含零刻度

### ISSUE THREAD

**Issue by wqjiao** [alibaba/BizCharts#823]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
没明白你的意思，麻烦说的详细些。

**Comment by wqjiao** [comment]
我自己没看清API，现在弄好了，不好意思哈
