### ISSUE TITLE
是否可支持饼图的选中区块

### ISSUE THREAD

**Issue by SaundersDong** [alibaba/BizCharts#825]
现在饼图没有默认的选择效果, 在事件里加入选中需要重新绘制, 并且本身的transform和animate动画效果也丢失了, 没有文档参考, 有点麻烦;

之前的配置:
<Geom
  select={[true, {
    mode: 'single' || 'multiple', // 选中模式，单选、多选
    style: { }, // 选中后 shape 的样式
    cancelable: true | false, // 选中之后是否允许取消选中，默认允许取消选中
    animate: true | false // 选中是否执行动画，默认执行动画
  }]}
/>

期望增加
<Geom select={['cate', cate => cate === '期待选择的区块']} />

能不能融合以上两种, 做更人性化一些的优化呢

**Comment by weepy3641** [comment]
解决办法参考 issue：
https://github.com/alibaba/BizCharts/issues/188

**Comment by abellee** [comment]
要命 我是不是用了假的bizcharts
![image](https://user-images.githubusercontent.com/707615/71362320-af23b680-25d0-11ea-8d45-c49afd01fa07.png)
