### ISSUE TITLE
can not see the diagram demos

### ISSUE THREAD

**Issue by LiuTaotao123** [alibaba/BizCharts#826]
When I open the page and want to scan the diagram demo, there are many errors on the console, so what I can see is only a blank page and cannot see anything about the diagram. Hope you can fix this bug earlier. Thanks so much.

**Comment by liunian** [comment]
@LiuTaotao123 Works for me. Would you provide the url?

**Comment by LiuTaotao123** [comment]
https://bizcharts.net/products/bizCharts/demo

https://user-images.githubusercontent.com/20948100/57362751-0ac04180-71b2-11e9-85c9-2fd6a9f858c6.png
