### ISSUE TITLE
Tooltip组件设置 htmlContent 后控制台报错

### ISSUE THREAD

**Issue by Cyrilszq** [alibaba/BizCharts#832]
- bizcharts Version: 3.5.1
- Platform or react version:
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/17585588/57599666-10d76900-758a-11e9-8253-3bd8d71c5105.png)

- CodePen Link: https://codepen.io/cyrilszq-the-bold/pen/BeLowR

看到 CHANGELOG 中这个问题在 3.5.1 版本有修复过，但我在 codepen 使用了3.5.1 版本依然出现报错。

> fix(HtmlTooltip): 在特定场景下HtmlTooltip.hide()时大概率获取不到container

**Comment by Cyrilszq** [comment]
看了一下 g2 的仓库，这个问题应该是在 3.5.3 版本修复的，目前 BizCharts 依赖的还是 3.5.2 版本，所以会报错，麻烦看下要不要升级一下依赖版本。

**Comment by XinYueXiao** [comment]
https://juejin.im/post/5ced02ce518825334a390f50

**Comment by weepy3641** [comment]
fix at bizcharts 3.5.3

**Comment by XinYueXiao** [comment]
![image](https://user-images.githubusercontent.com/31272499/58679480-3b049580-8396-11e9-9aaa-dd780aa8b45c.png)
