### ISSUE TITLE
bizcharts会默认去除重复数据   这个有没有API可以控制？  我这边有个需求是允许重复数据出现。

### ISSUE THREAD

**Issue by wo-de-ping-er** [alibaba/BizCharts#837]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by wo-de-ping-er** [comment]
能帮忙解答一下这个问题吗

**Comment by weepy3641** [comment]
无法关闭自动去重的功能，如果需要出现重复数据，建议你自己做点数据处理。
将数据处理为不一样，显示后可以格式为一样的显示即可。
