### ISSUE TITLE
如何实现类似股票那样的双轴呢

### ISSUE THREAD

**Issue by sooboy** [alibaba/BizCharts#838]
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/848440/57925230-114d6800-78da-11e9-9980-404840b1d498.png)

类似股票那样的双轴，又一个价格轴和百分比轴 但是它们其实是同一个数据，只是百分比轴是相对于前一天的收盘价。
这样图表如何画呢？

**Comment by sooboy** [comment]
目前画了两个相同的Line解决的，不知道有没有更好方法

**Comment by weepy3641** [comment]
bizcharts 中画双轴就是用两个 geom，y不同即可。

**Comment by jiandandkl** [comment]
const scale = {
    value: { type: 'linear-strict', min: 0, tickCount: 5 },
    rate: { type: 'linear-strict', min: 0, tickCount: 5 }
  };
