### ISSUE TITLE
图形元素事件没反应

### ISSUE THREAD

**Issue by deaththekidx** [alibaba/BizCharts#839]
图形元素事件
类型：Function
描述：图形元素事件属性名 = on + 图形元素名称 + 基础事件名，总计220种组合。
示例：onPointClick, onAxisLabelClick;
图形点击事件，onAxisTitleClick , onAxisLabelClick 没反应
版本：3.5.2，3.5.3-beta,
换回老版本可用，3.1.2，3.2.2 都可以。

**Comment by ironicstone** [comment]
新版本中已修复,尝试升级到最新版本
