### ISSUE TITLE
Cannot retrieve G2 API `interact` through onGetG2Instance

### ISSUE THREAD

**Issue by licaomeng** [alibaba/BizCharts#841]
- BizCharts Version: 3.5.2
- Platform or react version: React v15.0.2
- Case of issue:
I would like to bind some G2 events on BizCharts, so I try to use BizCharts API **onGetG2Instance** to get the chart instance, but function **interact** cannot be found.

- Detail use case as below:
```
<Chart onGetG2Instance={chart => {
  chart.interact('drag', {
     type: 'XY'
  }).interact('zoom', {
     type: 'XY'
  });
}}>

```

**Comment by weepy3641** [comment]
@licaomeng 
最新版本已经修复。

**Comment by licaomeng** [comment]
Thank you for your reply.

**Comment by simararora2** [comment]
It is still failing for me -
<Chart onGetG2Instance={chart => {
> 101 | 		chart.interact('drag', {
  102 | 			type: 'XY'
  103 | 		}).interact('zoom', {
  104 | 			type: 'XY'

**Comment by licaomeng** [comment]
Make sure your BizCharts version is latest, or you can try v3.5.5, which works well on my side.

**Comment by simararora2** [comment]
Yes. My version is 3.5.5. I just checked for BizCharts version.

**Comment by simararora2** [comment]
This us the code I am using , if it helps :  
<Chart height={400} padding={[10, 30, 60, 40]} data={[1]}
								   scale={cols}
								   forceFit onGetG2Instance={chart => {
						chart.interact('drag', {
							type: 'XY'
						}).interact('zoom', {
							type: 'XY'
						});
			}}>
				<Legend
					custom={true}
					items={[
						{value: 'Optimal RIs', marker: {symbol: 'square', fill: '#A0BDCB', radius: 5}},
						{value: 'Analysis period', marker: {symbol: 'square', fill: '#44a3fc', radius: 5}},
						{value: 'Usage', marker: {symbol: 'hyphen', stroke: '#8BC34A', radius: 5, lineWidth: 3}},
						{value: 'Actual RIs', marker: {symbol: 'hyphen', stroke: '#FF9800', radius: 5, lineWidth: 3}},
						{value: 'Standard RIs', marker: {symbol: 'hyphen', stroke: '#FF0000', radius: 5, lineWidth: 3}}
					]}
				/>

				<Tooltip
                    crosshairs={{
                        type: "line"
                    }}
                />

				<View data={data}>
					<Axis name="timestamp" />
					<Axis name="value" grid={null} visible={false}/>

					<Geom
						type={"line"}
						position="timestamp*value"
						size={2}
						color={['key', ['#8BC34A', '#FF9800', '#FF0000', '#607D8B']]}
						shape={'hv'}
						tooltip={['timestamp*value*key', (t, v, k) => {
							return {
								name: k,
								title: new Date(t).toLocaleString(),
								value: v
							}
						}]}
					/>
				</View>

				<View data={blocks}>
					<Geom type="area" position="timestamp*value" color={['key', ['#A0BDCB', '#44a3fc']]} />
				</View>



			</Chart>

**Comment by licaomeng** [comment]
Please look here: https://codepen.io/licaomeng_1470378114/pen/qeoMpg?editors=1010
It uses online BizChart lib **v3.5.4**

Please double check your dev version. You could try `rm -rf ./node_modules` & perform `npm install`

**Comment by simararora2** [comment]
I cannot say it doesnt work in codepen - but for me it just doesnt seem to work 
<img width="1289" alt="Screenshot 2019-08-08 at 3 51 26 PM" src="https://user-images.githubusercontent.com/52563209/62695745-8cfc1400-b9f4-11e9-8b85-b3031c42171d.png">
Is there some other config i am missing ?

**Comment by simararora2** [comment]
![Screenshot 2019-08-08 at 3 56 06 PM](https://user-images.githubusercontent.com/52563209/62696140-6c808980-b9f5-11e9-8915-d87712794de7.png)
This is the error I get

**Comment by licaomeng** [comment]
You could comment out irrelevant code to locate the root of the problem.
