### ISSUE TITLE
当type为 timeCat 时，设置 tickCount=20,坐标轴分布不均匀

### ISSUE THREAD

**Issue by rumsky** [alibaba/BizCharts#842]
- bizcharts Version:
3.5.2
- Platform or react version:
16.8.6
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/12367395/58232962-7509e200-7d6d-11e9-8d23-ddd57b19707a.png)

const scale = {
      time: {
        type: 'timeCat',
        formatter: time => formatDate(time, 'HH:mm'),
        tickCount: 20
      }
}

**Comment by weepy3641** [comment]
15:00 跟前面的刻度间距无法整除做到均匀刻度，因此合并显示。
