### ISSUE TITLE
Export chart as pdf, png or svg

### ISSUE THREAD

**Issue by gotagoodfeeling123** [alibaba/BizCharts#843]
Can you export a chart as an image/pdf/svg? Would be super helpful. Thanks!

**Comment by kreja** [comment]
Yes, can download image via [downloadImage](https://bizcharts.net/products/bizCharts/docs/qa?from=search#%E5%9B%BE%E8%A1%A8%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E4%B8%BA%E5%9B%BE%E7%89%87%E6%A0%BC%E5%BC%8F%EF%BC%9F)
