### ISSUE TITLE
如何下载demo到本地跑起来

### ISSUE THREAD

**Issue by baiban0312** [alibaba/BizCharts#845]
- bizcharts Version:^3.4.4
- Platform or react version:^16.2.0
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
bizcharts的例子里改没有问题，但是按照例子配置就会报错。所以我想可不可以下载demo再在本地跑，排错

**Comment by baiban0312** [comment]
https://bizcharts.net/products/bizCharts/demo/detail?id=pie-donut&selectedKey=%E9%A5%BC%E5%9B%BE
按照这个demo改，本地会问题。其他表试过一个，没有问题

**Comment by weepy3641** [comment]
@baiban0312 
demo 仓库都是在内部，无法直接下载。
一般出现本地有问题，站点没问题，可以对比下 bizcharts 的版本。
