### ISSUE TITLE
柱状图 添加了 scale={{x: {type:'timeCat'}}} 后X轴为时间的显示有问题

### ISSUE THREAD

**Issue by LIUsiri** [alibaba/BizCharts#848]
- bizcharts Version:3.4.3
- CodePen Link:https://codepen.io/anon/pen/MdXJXb
x轴的数据为2015-01 添加后变成2015-01-01了 如果我去掉的话又会报 dodge is not support linear attribute, please use category attribute!

**Comment by Oscar19921030** [comment]
同样出现了这样问题，暂时无解。。

**Comment by weepy3641** [comment]
并列柱状图不支持 x 轴 scale 类型是时间。可以改为 ‘cat’

scale={{x: {type:'cat'}}}
