### ISSUE TITLE
请问下这个可不可以让Y 轴反方向绘制？

### ISSUE THREAD

**Issue by QuanhuQiu** [alibaba/BizCharts#849]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
请问下这个可不可以让Y 轴反方向绘制？

**Comment by weepy3641** [comment]
可以参考下坐标系的文档
https://bizcharts.net/products/bizCharts/api/coord
