### ISSUE TITLE
分面图怎么共用一个坐标系

### ISSUE THREAD

**Issue by cadeeper** [alibaba/BizCharts#85]
同一行的图，都是使用的各自的坐标系，看上去不同数量的线图高度却是一样的。如何同一行的图都共用一个坐标系？

**Comment by weepy3641** [comment]
将同一行的图中所有 y 轴 scale 的 min、max 配置成一样即可。
这样就可以同行对比比较了，facet 也是这样做的。

**Comment by cadeeper** [comment]
@weepy3641 3.1.0最新beta版本无法显示分面图的标题
