### ISSUE TITLE
使用BizCharts踩的坑

### ISSUE THREAD

**Issue by XinYueXiao** [alibaba/BizCharts#850]
https://juejin.im/post/5ced02ce518825334a390f50

**Comment by heiniuhaha** [comment]
非常赞，基于你的实践新增了官网区块；

https://bizcharts.net/products/bizCharts/demo/detail?id=radar-with-line&selectedKey=雷达图
![image](https://user-images.githubusercontent.com/668144/58694902-afefc380-83c6-11e9-88e3-60928ca50d9b.png)

https://bizcharts.net/products/bizCharts/demo/detail?id=bar-label&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE
![image](https://user-images.githubusercontent.com/668144/58696169-969c4680-83c9-11e9-8f40-3a7dd3ed5a9b.png)

**Comment by XinYueXiao** [comment]
好的，收到



------------------ 原始邮件 ------------------
发件人: "宋建敏"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 下午5:29
收件人: "alibaba/BizCharts"<BizCharts@noreply.github.com>; 
抄送: "初念"<903199174@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/BizCharts] 使用BizCharts踩的坑 (#850)




Closed #850.

**Comment by XinYueXiao** [comment]
缩略图好像没有更新





------------------ 原始邮件 ------------------
发件人: "宋建敏"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 下午5:29
收件人: "alibaba/BizCharts"<BizCharts@noreply.github.com>; 
抄送: "初念"<903199174@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/BizCharts] 使用BizCharts踩的坑 (#850)




非常赞，基于你的实践新增了官网区块；
 
https://bizcharts.net/products/bizCharts/demo/detail?id=radar-with-line&selectedKey=雷达图
 
 
https://bizcharts.net/products/bizCharts/demo/detail?id=bar-label&selectedKey=%E6%9F%B1%E7%8A%B6%E5%9B%BE
