### ISSUE TITLE
如何确定Geom是横坐标还是纵坐标的？

### ISSUE THREAD

**Issue by codepandy** [alibaba/BizCharts#851]
demo如下：
https://bizcharts.net/products/bizCharts/demo/detail?id=line-series&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE

横纵坐标是如何确定使用哪个Geom的？

**Comment by weepy3641** [comment]
geom 上的 position = ‘x*y’.
当存在多个 geom，如果 position 配置为一样，那么各个轴会合并，为同一根轴。
