### ISSUE TITLE
如何对legend重命名？

### ISSUE THREAD

**Issue by codepandy** [alibaba/BizCharts#852]
legend使用的字段的名称，如何重命名啊？比如字段叫“name”，我想显示成“姓名”

**Comment by heiniuhaha** [comment]
参考 https://bizcharts.net/products/bizCharts/demo/detail?id=radar-with-line&selectedKey=%E9%9B%B7%E8%BE%BE%E5%9B%BE

```
const cols = {
      score: {
        min: 0,
        max: 80,
      },
      user: { formatter: val => ({ a: '当前岗位组成', b: '优化后岗位组成' }[val]) },
    };
```

![image](https://user-images.githubusercontent.com/668144/58557565-36829480-8251-11e9-9171-9b1c27472f1a.png)
