### ISSUE TITLE
axis x轴的值如果是时间的话 会从空格处截断 只显示前面一段

### ISSUE THREAD

**Issue by Alice2222** [alibaba/BizCharts#853]
- bizcharts Version: 3.2.2
- Platform or react version: 16.0.0
- Mini Showcase(like screenshots):
- CodePen Link: https://codepen.io/alice2222/pen/araLxo

**Comment by weepy3641** [comment]
配置下时间的显示格式即可：
https://codepen.io/anon/pen/pmQPPP
```
const cols = {
          'value': { min: 0 },
          'year': {
            type: 'time',
            mask:'YY-MM-DD HH:mm:SS'
          }
        };
```

**Comment by Holybasil** [comment]
> 配置下时间的显示格式即可：
> https://codepen.io/anon/pen/pmQPPP
> 
> ```
> const cols = {
>           'value': { min: 0 },
>           'year': {
>             type: 'time',
>             mask:'YY-MM-DD HH:mm:SS'
>           }
>         };
> ```

这里应该是 `YYYY-MM-DD HH:mm:ss`
