### ISSUE TITLE
多个饼图

### ISSUE THREAD

**Issue by lisasslisa** [alibaba/BizCharts#855]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by lisasslisa** [comment]
多个饼图 大小怎么统一啊

**Comment by weepy3641** [comment]
@lisasslisa 
需要你自己配，将饼图的宽度、高度、padding 配置为一致。
