### ISSUE TITLE
使用折线图时，如何设置Y轴坐标值得范围（如坐标从1开始）

### ISSUE THREAD

**Issue by wensenli** [alibaba/BizCharts#856]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
y 轴 scale 配置下。
```
scale = {
  y: { min: 1, nice: false },
}
```
