### ISSUE TITLE
Workflow / Flowchart Example

### ISSUE THREAD

**Issue by ubreddy** [alibaba/BizCharts#858]
- bizcharts Version: 3.5.2
- Platform or react version: 16.8.6
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

Are there any examples how to draw a simple flowchart/ workflow graph? where nodes with rectangle labels are connected by directed arrows(lines)  with edge labels?

Could not find in the example set.

**Comment by ironicstone** [comment]
For graph visualization,  you can try G6, link: https://antv.alipay.com/zh-cn/g6/3.x/index.html

**Comment by ubreddy** [comment]
Thank you.
