### ISSUE TITLE
柱状图如何实现柱的显示颜色不同

### ISSUE THREAD

**Issue by JediBai** [alibaba/BizCharts#860]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
![H` M$WCYU8_{U63UYI)839I](https://user-images.githubusercontent.com/31715147/58691460-9e0a2280-83be-11e9-9d01-b583ee470fa6.png)
实现类似的柱状图，不同的柱的颜色显示不同，这个需要如何实现？

**Comment by weepy3641** [comment]
麻烦仔细看下 geom 的 color 属性。

**Comment by JediBai** [comment]
geom 加上 ['num', '#ff0000-#00ff00'] 实现，回答速度真快，赞
