### ISSUE TITLE
onClick event for axis title

### ISSUE THREAD

**Issue by georgerichmond** [alibaba/BizCharts#861]
Is there any kind of onClick event for the axis title? The use case would be to click the title to then show a popup to allow the user to change the settings for the axis.

Thank you

**Comment by ironicstone** [comment]
Sure, there's bunch of events on all the chart's elements. For more detail,  check this out: https://github.com/alibaba/BizCharts/blob/master/doc_en/api/chart.md#13geometry-events

**Comment by georgerichmond** [comment]
Super, thank you :)
