### ISSUE TITLE
关于onPlotClick只有点击阴影区域才可以拿到data的疑问

### ISSUE THREAD

**Issue by dmdoit** [alibaba/BizCharts#863]
- bizcharts Version: v3.4.4
- Platform or react version: v16.7.0
![image](https://user-images.githubusercontent.com/19385704/59006077-c5e00700-8852-11e9-89dd-b66bd0cf080f.png)

![image](https://user-images.githubusercontent.com/19385704/59006082-ce384200-8852-11e9-890e-e5bf593b46f8.png)

**Comment by ironicstone** [comment]
onPlotClick获取当前点击位置，配合chart实例上的getSnapRecords食用，参考：https://www.yuque.com/antv/g2-docs/api-chart#getSnapRecords

**Comment by dmdoit** [comment]
> onPlotClick获取当前点击位置，配合chart实例上的getSnapRecords食用，参考：https://www.yuque.com/antv/g2-docs/api-chart#getSnapRecords

BizCharts文档里没看到有getSnapRecords的用法

**Comment by dmdoit** [comment]
> > onPlotClick获取当前点击位置，配合chart实例上的getSnapRecords食用，参考：https://www.yuque.com/antv/g2-docs/api-chart#getSnapRecords
> 
> BizCharts文档里没看到有getSnapRecords的用法

chart.getSnapRecords在react里应该怎么使用呢？
`
onPlotClick={evt => {
  console.log('22', evt);
  const records = getSnapRecords({x: evt.x, y: evt.y});
  console.log(records);
}}
`
我这样写应该怎么在react中调用getSnapRecords

**Comment by dmdoit** [comment]
参考这篇解决 https://github.com/alibaba/BizCharts/issues/364
