### ISSUE TITLE
x轴时间显示一条让柱状图展示在中间

### ISSUE THREAD

**Issue by zxy7** [alibaba/BizCharts#864]
- bizcharts Version:^3.1.10
- Platform or react version:^16.4.1
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/19514239/59097537-6700b780-8950-11e9-947c-316a1380ecd8.png)

数据为多条时x轴按时间type:"time"展示,数据为一条时不加 type，让这条数据展示在中间

```js
const scale = {
  time: {
        alias: "时间",
        type: "time",   
        formatter: text => moment(text).format("YYYY-MM-DD HH:mm:ss")
  },
  count: { alias: "数量" }
};
```

- CodePen Link:https://codesandbox.io/s/bizcharts-s763w

**Comment by ironicstone** [comment]
问题描述不清。另外，报错显示的是数据的问题，时间戳不对

**Comment by zxy7** [comment]
> 问题描述不清。另外，报错显示的是数据的问题，时间戳不对

数据为多条时x轴按时间戳type:"time"展示,数据为一条时不加 type，把时间戳转成字符串让这条数据展示在中间，切换时会报错

**Comment by ironicstone** [comment]
时间戳和数据格式改一下就好了， 参考：  https://codesandbox.io/s/bizcharts-74ph9

**Comment by zxy7** [comment]
> 时间戳和数据格式改一下就好了， 参考： https://codesandbox.io/s/bizcharts-74ph9

timeCat间隔均匀分布，需要用time看出时间间隔，不能用timeCat，参考：https://codesandbox.io/s/bizcharts-s763w   
我想知道的点是为什么这两个chart单独写就可以，第三个chart会报错？

**Comment by ironicstone** [comment]
第一次回答就说过了啊，你的时间戳类型不对，我的例子把把你的toString都去了，至于类型type是否是time或者timeCat这个无所谓。

**Comment by zxy7** [comment]
> 第一次回答就说过了啊，你的时间戳类型不对，我的例子把把你的toString都去了，至于类型type是否是time或者timeCat这个无所谓。

那为什么给chart加了key值就OK了呢

**Comment by liunian** [comment]
@zxy7 和 bizcharts 和底层 g2 的关联有关系。大致来说是如果没有 key 属性，那么是同一个 react 元素，走的是 prop 变更的流程，流转到 g2 上，目前会 data 先更新，但 scale 还是旧的，这个时候数据是 string 类型，但 scale 用的是 time 类型，转换为时间时出错（如果不出错的后，最终状态会变为 data 和 scale 都用最新的，这个时候会正常渲染）。

而添加 key 属性，会生成新的 react 实例，所以不会导致这个时候 data 和 scale 要求类型不匹配的问题，所以也不会出错。

而一旦出错后，切换 data 和 scale 没能恢复正常，这个 bizcharts 大概下周会更新修复这个问题。
