### ISSUE TITLE
给条形图设置圆角无效

### ISSUE THREAD

**Issue by ArcherKay** [alibaba/BizCharts#866]
用api文档中的plotBackground属性设置radius，条形图没有显示呈圆角

**Comment by kreja** [comment]
这是”图表绘图区域的边框和背景样式“，不是柱状图形的。
圆角柱状图需要自定义 shape 实现，参考 [圆角柱状图](https://bizcharts.net/products/bizCharts/demo/detail?from=search&id=other-rounded-column-chart&selectedKey=%E5%85%B6%E4%BB%96%E5%9B%BE%E8%A1%A8)

**Comment by ArcherKay** [comment]
> 这是”图表绘图区域的边框和背景样式“，不是柱状图形的。
> 圆角柱状图需要自定义 shape 实现，参考 [圆角柱状图](https://bizcharts.net/products/bizCharts/demo/detail?from=search&id=other-rounded-column-chart&selectedKey=%E5%85%B6%E4%BB%96%E5%9B%BE%E8%A1%A8)

谢谢，解决了
