### ISSUE TITLE
南丁格尔玫瑰环图情况下,labelLine属性不起作用

### ISSUE THREAD

**Issue by suwu150** [alibaba/BizCharts#869]
- bizcharts Version:     "bizcharts": "3.1.3-beta.2",
- Platform or react version:     "react": "16.2.0",
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/20339760/59488283-b9daf180-8eb1-11e9-8f90-d87531491413.png)

- CodePen Link: [https://codepen.io/suwu150/pen/wLKyJR?editors=0110](https://codepen.io/suwu150/pen/wLKyJR?editors=0110)

按照文档中配置的方法进行配置,不起作用,而且会直接报错

**Comment by suwu150** [comment]
大佬,麻烦看看这个问题

**Comment by ssfxz** [comment]
新版已修复
