### ISSUE TITLE
如果使用数字做数据key的话，当key为5，显示起来会在中间多一条记录

### ISSUE THREAD

**Issue by aisriver** [alibaba/BizCharts#875]
- bizcharts Version:^3.5.1
- Platform or react version:^16.8.5
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/28559304/59651641-1e9d9100-91bd-11e9-8a82-e47fec212018.png)
![image](https://user-images.githubusercontent.com/28559304/59651651-29f0bc80-91bd-11e9-9ce4-018000314ef4.png)
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
没明白你的意思，麻烦描述详细些，最好给个 codepen 的 demo。
