### ISSUE TITLE
图表transform:scale()放大后，变虚

### ISSUE THREAD

**Issue by dashixiong** [alibaba/BizCharts#876]
- bizcharts Version: 3.5.4
- Platform or react version: 16.7.0
- CodePen Link: https://codepen.io/anon/pen/BgpoGV

做响应式大屏，以某一屏幕尺寸为准，其他尺寸使用transform:scale()来适配，发现当对图表进行放大时，图表本身及其坐标轴刻度值都会发虚 变模糊，见codepen实例，这个有办法解决吗

**Comment by lxzy-yun** [comment]
我遇到的是Tooltip组件的鼠标跟随错位了

**Comment by ssfxz** [comment]
图表的绘制是位图，因此transform:scale()是会变虚的，同时也会出现指针偏移的问题，不建议使用transform:scale()，你可以直接在配置中指定大一些的图表尺寸来解决
