### ISSUE TITLE
Chart 配置 forceFit 后 初始化时应自动根据父级宽度渲染

### ISSUE THREAD

**Issue by a876691666** [alibaba/BizCharts#877]
- bizcharts Version: now version
- Platform or react version: 16.8.x

配置了forceFit，但是初始化的时候也应该自动计算才对，不应该在面对多图形、大数据量的场景时卡住只渲染500宽。
用户上来看见就是会觉得很突兀
- `”刚上来的时候为什么图形只显示一半？`
- `这个图的数据是否有问题？“`

这个问题是每个图形我都自己获取父级box宽度交给Chart组件来解决，我觉得不合理。
且在侧边显示legent时，自行计算宽度会很难控制

**Comment by Leannechn** [comment]
版本 大于3.5.8 和 最新版本已修复

**Comment by EGBAR** [comment]
@Leannechn  这个在bizcharts@4.0 中仍然存在， 即使设置了父组件宽度 autoFit会从一半开始fit到最终宽度。 有什么办法可以解决吗？
