### ISSUE TITLE
设置forcefit后在第一次渲染会发生重绘（瞬间闪动）

### ISSUE THREAD

**Issue by yuhan0709** [alibaba/BizCharts#881]
- bizcharts Version: 3.5.4(亲测3.4.3中不会出现这个问题)
- Platform or react version: IOS10.14.5 、react@16.3.2
- Mini Showcase(like screenshots):
才刷新（会明显由1变成2
![image](https://user-images.githubusercontent.com/23137528/60087666-0a830200-9770-11e9-8a5b-4b7af23054b8.png)

![image](https://user-images.githubusercontent.com/23137528/60087684-140c6a00-9770-11e9-8eaf-ed8421589454.png)

- CodePen Link: https://bizcharts.net/products/bizCharts/demo/detail?id=pie-donut&selectedKey=%E9%A5%BC%E5%9B%BE
（官方例子中也会出现此问题）

**Comment by mancoxu** [comment]
和楼上同样的问题：设置 forcefit 后，默认宽度不全屏，效果很突兀
   * bizcharts Version: 3.5.4
   * Platform or react version: IOS10.14.5 、react@16.3.2
   * Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/15724205/60088767-cee93780-9771-11e9-9d17-c585072ed886.png)
   ![image](https://user-images.githubusercontent.com/15724205/60088806-db6d9000-9771-11e9-8b8a-2728ea9e5bdf.png)
   * CodePen Link: https://bizcharts.net/products/bizCharts/demo/detail?id=g2-area-null&selectedKey=%E6%A6%82%E8%A7%88 （官方例子）

**Comment by wangxingkang** [comment]
@yuhan0709 有没有兴趣维护 https://github.com/alitajs/rc-charts

**Comment by lx70770** [comment]
遇到了同样的问题  Mac上不会抖动  Windows上必现

**Comment by wangxingkang** [comment]
维护不是很积极啊

**Comment by yuhan0709** [comment]
> @yuhan0709 有没有兴趣维护 https://github.com/alitajs/rc-charts

其实可以去掉forsefit，自己写window.resize方法

**Comment by lx70770** [comment]
升级到3.5.3解决了

**Comment by cosloli** [comment]
遇到同样的问题，尝试了3.5.4和3.5.5，都会出现错误，只能回退到3.5.3

**Comment by cosloli** [comment]
> 升级到3.5.3解决了

这是降级吧...
