### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by gajus** [alibaba/BizCharts#885]
The README.md of this library states:

> New charting and visualization library has been released: 
 http://bizcharts.net/products/bizCharts.
>
> Please move to it and we won't maintain the old version soon.
> 
> More details about BizCharts

The website it links to does not include English description. It is not clear if this code base is for the new charting visualisation library or if there is another library that I should be using.

**Comment by hankaibo** [comment]
It seems to be a KPI project.

**Comment by weepy3641** [comment]
@gajus 
Sorry， We didn't make it clear.
It means we won't maintain the old bizcharts's web site. One year ago we took the bizcharts old web site offline.
" http://bizcharts.net/products/bizCharts " is the bizcharts's web site which we  maintain now.

There has always been one bizcharts library，and we will maintain and upgrade all the time。
https://www.npmjs.com/package/bizcharts

**Comment by gajus** [comment]
Do you plan to have English version of the website?
