### ISSUE TITLE
柱状图如何添加平均线？

### ISSUE THREAD

**Issue by dezio31** [alibaba/BizCharts#889]
- bizcharts Version:"bizcharts": "^3.5.4"
- Platform or react version:"react": "^16.8.6"

柱状图如何添加平均线？

**Comment by wo-de-ping-er** [comment]
> * bizcharts Version:"bizcharts": "^3.5.4"
> * Platform or react version:"react": "^16.8.6"
> 
> 柱状图如何添加平均线？

请问一下  这个平均线你是怎么实现的啊？
