### ISSUE TITLE
两条折现，添加cross，只能对一条有效

### ISSUE THREAD

**Issue by Viyozc** [alibaba/BizCharts#892]
- bizcharts Version: latest
- Platform or react version: 16.8.6
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
![image](https://user-images.githubusercontent.com/20371707/60481498-27fc2280-9cc0-11e9-914a-89e1822aa8fc.png)
两条折现，添加cross，只能对一条有效？

**Comment by ssfxz** [comment]
十字准心cross就是指定位到某一个点的。
