### ISSUE TITLE
tooltip的shared为false时，对于堆叠柱状图的维度信息无法显示

### ISSUE THREAD

**Issue by lidasong** [alibaba/BizCharts#895]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by lidasong** [comment]
![image](https://user-images.githubusercontent.com/6766855/60660292-06e72d80-9e8a-11e9-8000-6663d90bf214.png)

**Comment by lidasong** [comment]
codePen地址：https://codepen.io/lidasong/pen/vqaGWa

**Comment by ssfxz** [comment]
![image](https://user-images.githubusercontent.com/8744196/60661026-a1943c00-9e8b-11e9-8000-4067e42a979f.png)

**Comment by ssfxz** [comment]
geom中的tooltip属性就是自定义tooltip中的每一行
当你关闭了shared后 ，tooltip中就只有一行数据了（因为相同维度不共享显示）
因此在这张图中，有两个维度一个度量，你可以像默认的方式，title中显示一个维度，一行中显示一个维度一个度量（就是你截图中的样子）
也可以像我截图的，在一行中自定义tooltip的内容，使用方法如图。
需要说明的是：tooltip参数第一项的字符串，可以是数据集中有的任意字段，顺序都无所谓，对应的数据会在后面的回调函数中传递。

ps： 大松是你！

**Comment by lidasong** [comment]
哈哈，大变熟人，geom里面可以配置多行显示吗，当然shared还是false

**Comment by ssfxz** [comment]
这样的话就只能通过自定义tooltip实现了，参考https://bizcharts.net/products/bizCharts/api/tooltip#g2-tooltip-list-item
