### ISSUE TITLE
tooltip自定义多一行信息是否可以做到呢？

### ISSUE THREAD

**Issue by IrisPierce** [alibaba/BizCharts#896]
tooltip自定义多一行信息是否可以做到呢？
- bizcharts Version: 最新版
- Platform or react version: 16
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
tooltip自定义多一行信息是否可以做到呢？
比如
第一行一般为：某一个时间
第二行一般为：某个城市有多少摄氏度
如果我需要多一行信息：天气预报来源软件

**Comment by izumiiAoba** [comment]
<Geom>的tooltip属性和<Tooltip>的itemTpl属性配合使用可以实现自定义，详细的可以去看看官方的api

**Comment by Keillion** [comment]
```tsx
<Point position={"date*y"}
  tooltip={[`date*y`,(date,y)=>({
    title: date+"<br>A new line in middle",
    name: "value",
    value: y,
  })]}
/>
```
我是类似这样做的。
但还是期待有个更好的方案。

**Comment by izumiiAoba** [comment]
谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Keillion"<notifications@github.com&gt;; 
发送时间: 2020年2月25日(星期二) 中午11:47
收件人: "alibaba/BizCharts"<BizCharts@noreply.github.com&gt;; 
抄送: "林北"<524123601@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/BizCharts] tooltip自定义多一行信息是否可以做到呢？ (#896)



<Point position={"date*y"}   tooltip={[`date*y`,(date,y)=&gt;({     title: date+"<br&gt;A new line in middle",     name: "value",     value: y,   })]} /&gt;
 
我是类似这样做的。
 但还是期待有个更好的方案。

**Comment by Leannechn** [comment]
bizcharts@4.x 版本支持如下react写法
```js
<Tooltip>
{ (title, items) => 
  return <div>....</div>
}
</Tooltip>
```
