### ISSUE TITLE
tooltip markerGroup 自定义样式

### ISSUE THREAD

**Issue by pot-code** [alibaba/BizCharts#897]
- bizcharts Version: 3.5.4-beta.0
- Platform or react version: macos, 16.4.0-0
- Mini Showcase(like screenshots):
- CodePen Link:

在 Geom `type` 为 line，tooltip 的 `crosshairs` 为 `y` 时，鼠标 hover 会在垂线上显示圆点，看文档介绍这个圆点叫 `markerGroup`。

文档的介绍应该是无法自定义它的样式的，源码也显示样式都是 hard-coded

```js
Util.each(markerItems, item => {
  markerGroup.addShape('marker', {
    color: item.color,
    attrs: Util.mix({
      // fix: Theme.tooltipMarker invalid
      fill: item.color,
      symbol: 'circle',
      shadowColor: item.color
    }, markerCfg, {
      x: item.x,
      y: item.y
    })
  });
});
this.set('markerItems', markerItems);
```

请问后期是否会提供它的自定义设置功能呢？目前有办法进行 hack 吗？

**Comment by ggleo08** [comment]
类似问题：
需求是隐藏 tooltip 的marker，设置了  hideMarkers 但并没有达到隐藏marker的效果
`<Tooltip crosshairs hideMarkers />`
