### ISSUE TITLE
Typo in the line chart demo

### ISSUE THREAD

**Issue by zixu-zhao** [alibaba/BizCharts#898]
- bizcharts Version: 3.5.4
- Platform or react version: N/A
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/15257767/60827730-d7cd0680-a17e-11e9-9cdf-dbbf4decde69.png)
- CodePen Link: https://codepen.io/pen/?&editable=true
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

TYPO!

**Comment by liunian** [comment]
@ZZhaoTireless thanks

@Leannechn [此 demo 里](https://bizcharts.net/products/bizCharts/demo/detail?id=g2-line-of-dashed&selectedKey=%E6%8A%98%E7%BA%BF%E5%9B%BE)的 `toInterge` 应该修正为 `toInteger`
