### ISSUE TITLE
Can I use BizCharts without DataSet?

### ISSUE THREAD

**Issue by mingChen2017** [alibaba/BizCharts#9]
I notice most of BizCharts example with DataSet ,such as https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/bar/stacked.
How can I use BizCharts without DataSet?

**Comment by weepy3641** [comment]
Bizcharts and Dataset are two independent package，you can just install bizcharts package  if you don't need dataset.

https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/start.md

Dataset is an type of data which is supported by BizCharts's  Chart component,  the Chart component also support json array data. You can just use json array data.

https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/data.md

**Comment by weepy3641** [comment]
Sometime some specific chart need some specific transform data， dataset surpport the mostly useful data transform operation.  
Also you can transform data by yourself, it's up to you.

https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/dataset.md
https://github.com/alibaba/BizCharts/blob/master/doc/api/dataset.md
https://github.com/alibaba/BizCharts/blob/master/doc/api/transform.md

**Comment by mingChen2017** [comment]
谢谢老哥 已经解决 给你个爱的拥抱
