### ISSUE TITLE
chart父容器设置css zoom，鼠标碰撞检测出问题

### ISSUE THREAD

**Issue by apoliszk** [alibaba/BizCharts#900]
- bizcharts Version: 3.5.4
- Platform or react version: 16.0.0
- CodePen Link:
[https://codepen.io/apoliszk/pen/wLRzEG](https://codepen.io/apoliszk/pen/wLRzEG)
#mountNode设置css zoom后，Chart tooltip显示不出来

**Comment by liunian** [comment]
可参考改临时方案看看

https://github.com/antvis/g2/issues/912#issuecomment-498099293
