### ISSUE TITLE
y轴刻度异常，整数没问题，浮点数则有问题

### ISSUE THREAD

**Issue by yutong16** [alibaba/BizCharts#901]
- bizcharts Version: 3.1.10
- Platform or react version: 16.4.1
- Mini Showcase(like screenshots): 
![image](https://user-images.githubusercontent.com/22187744/60937654-bcd7cf00-a303-11e9-801c-a1bbc5a699be.png)
- CodePen Link:none
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by yutong16** [comment]
y轴的scales只配置了tickCount, 目前只测试浮点数会出现异常。请问各位有类似的处理经验吗？

**Comment by liunian** [comment]
@yutong16 最后能提供下可供浮现的例子

**Comment by woshilaoge** [comment]
遇到了一样的问题呢 第一个刻度值0 第二个 2.4 就三个 4.8 第四个就是 7.1999999999了

**Comment by liunian** [comment]
@woshilaoge 能提供下相应 demo 吗？

**Comment by liunian** [comment]
@yutong16 @woshilaoge 是做刻度分配时碰到的浮点数运算问题，目前可以在列定义里面 加个formatter，格式化一下数据

参考 https://github.com/antvis/g2/issues/146

**Comment by woshilaoge** [comment]
@liunian  恩恩，我们目前是这么做的，但是有一个问题就是 我如果要是能在 formatter 函数里，找到 当前y 轴的 间隔数值就好了 比如我那个 2.4 ，这样我们写 formatter 函数时，可以针对性的处理。不然数值是不可控的，都不知道 toFixed 到几位。

**Comment by yutong16** [comment]
这个问题当时解决了，是数据计算的问题。
