### ISSUE TITLE
tooltips的htmlContent自定义不生效，源码未处理htmlContent。

### ISSUE THREAD

**Issue by IrisPierce** [alibaba/BizCharts#903]
- bizcharts Version:新版本
- Platform or react version:16
- Mini Showcase(like screenshots):
htmlContent：不生效
![image](https://user-images.githubusercontent.com/22979291/61096685-10285980-a48b-11e9-9b59-9eabdf774c96.png)
源码：处理htmlContent
![image](https://user-images.githubusercontent.com/22979291/61096726-2fbf8200-a48b-11e9-969f-1b56cc0f57cf.png)

![image](https://user-images.githubusercontent.com/22979291/61096703-1c141b80-a48b-11e9-80a2-486d858d6659.png)
源码：有处理这两个属性。
    containerTpl?: string;
    itemTpl?: string;

- CodePen Link: https://codepen.io/iriswang514/pen/NZoqGd

**Comment by gh2049** [comment]
+1

**Comment by Sayid1** [comment]
他们处理issues是不是很慢啊？

**Comment by XinYueXiao** [comment]
https://juejin.im/post/5ced02ce518825334a390f50
第二个

**Comment by weepy3641** [comment]
https://codepen.io/anon/pen/MNoQrr

需要手写 css 可以解决问题。
