### ISSUE TITLE
我需要一个双Y轴, 五个数据的图标

### ISSUE THREAD

**Issue by 755966092** [alibaba/BizCharts#909]
我现在有一个需求, 就是 
![image](https://user-images.githubusercontent.com/22684309/61366979-47e53600-a8bd-11e9-842b-8594b7e817cc.png)

大概图就是这样的 , 
折线是百分比, 数据要按左边的
柱状图是具体数值, 数据要按右边的, 
怎样才能实现这样的呢, 案例没找到, 好难

**Comment by 755966092** [comment]
已经找到了解决方案

**Comment by catXiaoXiao** [comment]
> 已经找到了解决方案

请问怎么解决的
