### ISSUE TITLE
Export chart as PDF

### ISSUE THREAD

**Issue by stuck1233333** [alibaba/BizCharts#910]
Can we export chart as pdf?

**Comment by weepy3641** [comment]
No, support export chart as png or svg. 
https://bizcharts.net/products/bizCharts/docs/qa#%E5%9B%BE%E8%A1%A8%E5%A6%82%E4%BD%95%E4%BF%9D%E5%AD%98%E4%B8%BA%E5%9B%BE%E7%89%87%E6%A0%BC%E5%BC%8F%EF%BC%9F
