### ISSUE TITLE
Circle Packing使用时圆形和圆形相交

### ISSUE THREAD

**Issue by suwu150** [alibaba/BizCharts#918]
- bizcharts Version:
- Platform or react version:
```
react16.0.0.production.min.js
3.1.5/BizCharts.min.js
```
Circle Packing使用时圆形和圆形相交,使用不同的数据时表现的相切和相交的效果不一致,有时候两个圆会离得很远,我在使用padding调整的时候,会覆盖掉一部分图形,希望提供下有关这个组件的数据格式要求文档
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/20339760/61851678-3964d300-aeea-11e9-89c0-54d78608c377.png)

- CodePen Link:
[https://codepen.io/suwu150/pen/wVWqZE?editors=1000](https://codepen.io/suwu150/pen/wVWqZE?editors=1000)

[https://codepen.io/suwu150/pen/MNebKw](https://codepen.io/suwu150/pen/MNebKw)

我使用官网的演示代码仅仅对数据源进行简单的替换数据之后,就会出现越界的情况,下面是演示地址:
[https://codepen.io/suwu150/pen/NQRMNg](https://codepen.io/suwu150/pen/NQRMNg)

**Comment by weepy3641** [comment]
数据需要调整下，如果要完全相切，智能叶子结点 value 存在，祖先结点 value 要么不填，要么等于子孙结点值的综合。
