### ISSUE TITLE
貌似有些子元素的迭代并未加上 `key` 

### ISSUE THREAD

**Issue by nikogu** [alibaba/BizCharts#92]
![image](https://user-images.githubusercontent.com/1179603/34658277-b627f6da-f468-11e7-9f47-1ba51d5c5715.png)

- v3.1.0

如果自己手动加上 key 就好了，比如：`<Axis key="axis-x" />`

**Comment by weepy3641** [comment]
@nikogu 
bizcharts 内部不会默认加 key ，需要用户自己加。。。

**Comment by nikogu** [comment]
又好了，无法重现，玄学编程。
