### ISSUE TITLE
使用react.setState更新页面其它内容的时候会打断chart里使用dataview.source()更新数据产生的动画，直接渲染chart的新状态。

### ISSUE THREAD

**Issue by ranhuan** [alibaba/BizCharts#923]
- bizcharts Version: latest
- Platform or react version: 16.6.3
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

这个情况是正常的吗，可否避免。

**Comment by ssfxz** [comment]
应该是你通过什么方式销毁了之前的图表重新创建了，你如果保持图表的组件不会被remove，那么是不会发生你描述的这种情况的
