### ISSUE TITLE
固定柱状图横轴高度

### ISSUE THREAD

**Issue by melin** [alibaba/BizCharts#926]
三个柱状图排列一行，由于横轴高度不一致，导致图表大小不一致，不协调，能够固定横轴高度，文字长了省略掉，鼠标放上去可以显示全部文字
![image](https://user-images.githubusercontent.com/1145830/62282812-ce377580-b482-11e9-9a14-b895f6ab0c2f.png)

**Comment by ssfxz** [comment]
横轴高度可以通过chart中的padding配置，文字长短可以自行处理源数据，hover显示全部文字的需求目前我们还不支持
