### ISSUE TITLE
Geom的Style Props，fill不生效，改为fillStyle后生效

### ISSUE THREAD

**Issue by xxxxxccc** [alibaba/BizCharts#931]
版本：
"@antv/g2": "^3.5.8-beta.1"
"bizcharts": "^3.5.5"

**Comment by weepy3641** [comment]
api 本就是这样的名字。
canvas 的图形绘制 api 中填充色也是叫 fillStyle

**Comment by xxxxxccc** [comment]
> api 本就是这样的名字。
> canvas 的图形绘制 api 中填充色也是叫 fillStyle

![image](https://user-images.githubusercontent.com/21255012/63321701-147e4700-c354-11e9-8b8e-129f0758fd15.png)
