### ISSUE TITLE
对不起，我是一个新手，我想请教一下水球图内部得波浪如何改变波长或频率

### ISSUE THREAD

**Issue by cuiyimeng** [alibaba/BizCharts#934]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ssfxz** [comment]
这个水波图的样式是注册在g2底层实现的，因此你不能改变，不过你BizCharts提供了自定义shape的能力，因此你可以尝试自己绘制想要的图形

水波图的实现可参考G2中的实现：https://github.com/antvis/g2/blob/master/src/geom/shape/interval.js#L604

**Comment by cuiyimeng** [comment]
> 这个水波图的样式是注册在G2底层实现的，因此你不能改变，不过你BizCharts提供了自定义形状的能力，因此你可以尝试自己绘制想要的图形
> 
> 水波图的实现可参考G2中的实现：[https](https://github.com/antvis/g2/blob/master/src/geom/shape/interval.js#L604)：[//github.com/antvis/g2/blob/master/src/geom/shape/interval.js#L604](https://github.com/antvis/g2/blob/master/src/geom/shape/interval.js#L604)

非常感谢您
