### ISSUE TITLE
雷达图的网格设置交替的背景色，不支持文档中给出十六进制格式

### ISSUE THREAD

**Issue by LinkChenzy** [alibaba/BizCharts#935]
- bizcharts Version:3.5.4
- Platform or react version:16.8.6
- Demo:https://bizcharts.net/products/bizCharts/demo/detail?id=radar-basic&selectedKey=%E9%9B%B7%E8%BE%BE%E5%9B%BE
- api:https://bizcharts.net/products/bizCharts/api/axis#grid
按照官方api给的列子，中间的线消失了，如下图：
![image](https://user-images.githubusercontent.com/30339294/62998759-14d39980-be9f-11e9-9a39-eed0408e05e2.png)
改变颜色的格式为rgab模式后才能正常的显示：
![image](https://user-images.githubusercontent.com/30339294/62998829-451b3800-be9f-11e9-965e-49fdf93e6a1b.png)

**Comment by ssfxz** [comment]
因为目前的grid间隔填充色的zindex是在axis之上的，因此轴线被100%不透明度的颜色盖住了。
你使用rgba可以生效的原因是开启了alpha通道
如果坚持使用HTML颜色字符串，你也可以使用带有a通道的字符串，例如："#FFFA"

另外，我们也在考虑将grid间隔的zindex下调，感谢反馈。
