### ISSUE TITLE
时间  位置

### ISSUE THREAD

**Issue by nianxiongdi** [alibaba/BizCharts#938]
- bizcharts Version:
   * 3.5.5
- Platform or react version:
   * 16.8.4
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/41629087/63090571-4e370280-bf8e-11e9-99a1-e7c6216b304f.png)

- CodePen Link:
    * https://codesandbox.io/s/magical-yonath-xgu32

**Comment by weepy3641** [comment]
x 轴 scale 被识别为连续时间类型了，配置为离散时间类型即可。
```
const scale = {
  date: {
    type: 'timeCat',
    alias: "date",
    // type: 'time',
    formatter: t => moment(t).format("MM-DD")
  }
};
```
