### ISSUE TITLE
ToolTip为什么无法添加点击事件？

### ISSUE THREAD

**Issue by Peng1713** [alibaba/BizCharts#939]
- bizcharts Version:^3.5.5
- Platform or react version:^16.6.3
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

需要在折线图表的ToolTip上添加一个点击事件，但一直没效果，不知道是不支持还是我写的有问题，请帮忙解答。。

**Comment by weepy3641** [comment]
tooltip 上可以添加任意 html 元素以及事件。
改下下 tooltip 的 html 模版即可，如果有问题，麻烦给个完整的 demo 链接。
https://bizcharts.net/products/bizCharts/api/tooltip#htmltooltip-%E5%B1%9E%E6%80%A7
