### ISSUE TITLE
希望增加在图表没有数据的时候依然显示坐标轴的选项

### ISSUE THREAD

**Issue by YourWildDad** [alibaba/BizCharts#94]
我不想要**暂无数据**这四个空空的大字，如果当前图表没有数据，第一眼看到的人都不知道这里曾经有个图表。
希望需求能被采纳。
祝越办越好。

**Comment by weepy3641** [comment]
1、在没有数据的情况下，G2 不会默认显示图表坐标轴，需要用户自己配置 ticks。
2、chart 组件没有数据的时候显示 “暂无数据”  是我们这边很多用户的需求，因此不会改变。
如果你不想显示 “暂无数据” `<Chart  placeHolder={...}/>` 的 placeHolder 属性可以更改显示内容。

**Comment by weepy3641** [comment]
@YourWildDad 
我这尝试了下， data=[1] 的情况下会显示两根轴，你如果要显示轴可以这样做。
data=[] 或者 data=null 时 g2会显示一根轴线，bizcharts 里面禁止了，显示暂无数据，我下个版本会开放下，允许数据是空数组，但 data=null 显示暂无数据会保留，兼容老用户的使用。

**Comment by YourWildDad** [comment]
好的，感谢。

**Comment by weepy3641** [comment]
3.1.1 已经支持了。

**Comment by YourWildDad** [comment]
好的，我马上试一下。
