### ISSUE TITLE
请教一下k线图里面同时有均线数据怎么公用一个y轴 

### ISSUE THREAD

**Issue by hengkx** [alibaba/BizCharts#940]
- bizcharts Version:latest
- Platform or react version:reactt
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

设置成一样的min,max 可以保证 y轴的 展示一样，但是不能动态改变

**Comment by ssfxz** [comment]
如果你使用的是https://bizcharts.net/products/bizCharts/demo/detail?id=box-basic&selectedKey=%E7%AE%B1%E5%BD%A2%E5%9B%BE 中的五分位数据的话，那么y轴一定是共用的
如果不是五分位的话，推荐你使用Guide中的辅助线绘制均线，这样也是共用y轴的
