### ISSUE TITLE
自定义图例及点击事件，点击图例后shape隐藏，但tooltip上数据未隐藏

### ISSUE THREAD

**Issue by jiayangkai** [alibaba/BizCharts#941]
- bizcharts Version:3.5.5
- Platform or react version:16.8.4
- Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/10016813/63247114-d5d68700-c296-11e9-8b2b-8f710bb4e342.png)
- Link: https://codesandbox.io/s/sharp-johnson-w3r6c?fontsize=14

自定义图例及点击事件，点击图例，对应的shape隐藏，但是tooltip上该条线对应的值依然显示。
效果如图，可点击链接，里边有复现示例

**Comment by weepy3641** [comment]
legend 是自定义的，因此图表内部感知不到你要隐藏数据项的意图。
如果要隐藏，可以使用 onTooltipChange 结合你当前的 legend 状态隐藏内容，
https://bizcharts.net/products/bizCharts/api/chart#ontooltipchange

**Comment by jiayangkai** [comment]
@weepy3641 网站实例：https://bizcharts.net/products/bizCharts/demo/detail?id=g2-double-axes&selectedKey=%E6%A6%82%E8%A7%88
该示例展示了自定义图例点击事件，并未在onTooltipChange中做数据处理，为什么图表自动隐藏了指定数据项
