### ISSUE TITLE
时间戳坐标轴，自动把时分秒给删除？

### ISSUE THREAD

**Issue by lddlww** [alibaba/BizCharts#943]
我的时间数据为："2019-08-20 00:02:27"  是字符串
 <Axis name="time" label={{formatter:(val:string)=>{
                console.log("in axis time:",val)
                val
}}}/>

打印出来数据为：2019-08-20，直接把时分秒给去掉了？

**Comment by ssfxz** [comment]
如果是时间scale的话，参考： https://bizcharts.net/products/bizCharts/api/scale#mask

**Comment by lddlww** [comment]
@ssfxz 
const scale = {
        time:{
            type:'time',
        },
    }

<Chart data={dv} scale={scale}>

以上设置：没有生效，是配置有误么？

**Comment by Znonymous29** [comment]
也遇到相同的问题，查了一下[文档](https://bizcharts.net/product/BizCharts4/category/62/page/77)，时间scale里提到当数据第一个值为 YYYY-MM-DD HH:mm:ss 类型当数据时，会自动按照'YYYY-MM-DD'进行格式化
