### ISSUE TITLE
柱状图添加平均线需要使用哪个属性？

### ISSUE THREAD

**Issue by wo-de-ping-er** [alibaba/BizCharts#947]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
guide line 组件。
https://bizcharts.net/products/bizCharts/api/guide#line
