### ISSUE TITLE
<Geom />组件的position属性不支持多属性

### ISSUE THREAD

**Issue by a12366456** [alibaba/BizCharts#95]
能否提供类似color属性多个字段合成属性值的回调函数

**Comment by weepy3641** [comment]
下个版本支持。

**Comment by weepy3641** [comment]
@a12366456   
position 字段是用来指定 geom x、y属性所绑定的数据句字段，即数据决定了空间位置，具体的空间位置是由 G2 自适应布局计算出来的。
目前支持 sale * year  这样的写法，下个版本会支持 ['sale', 'year'] 数组形式的写法，你说的回调函数是怎样的？ 是想要根据特定数据去返回空间坐标？

**Comment by a12366456** [comment]
在空间位置x，y需要由多个字段决定时，数据类似[{year:2017,moth:1,count:10}]，我需要x由year和month共同决定，期待的写法position={['year*month', (year,month)=>{return year+"年"+month+"月";},
count
  ]}

**Comment by weepy3641** [comment]
@a12366456 
你说的这种写法支持不了哦， 首先G2 就是不支持的，bizcharts 的层面无法支持这种定制。
