### ISSUE TITLE
有计划支持鼠标在图表数据展示区间选择范围可以缩放时间区间吗？

### ISSUE THREAD

**Issue by malusama** [alibaba/BizCharts#953]
类似 highcharts 的这个图表
https://www.highcharts.com/demo/line-time-series

鼠标在图表数据展示区间选择范围可以缩放时间区间。
相比现在的slider插件的方案感觉体验好不少，操作也更流畅直接

**Comment by weepy3641** [comment]
已经有了，demo地址：
https://bizcharts.net/products/bizCharts/demo/detail?id=g2-brush-line&selectedKey=%E6%A6%82%E8%A7%88

**Comment by Holybasil** [comment]
demo 地址直接跳到概览页了
