### ISSUE TITLE
forceFit 开启事，图表第一次出现会有宽度超出屏幕，然后正常的动画。

### ISSUE THREAD

**Issue by weepy3641** [alibaba/BizCharts#954]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by Leannechn** [comment]
版本 > 3.5.8 之后的版本中已修复
