### ISSUE TITLE
坐标显示问题

### ISSUE THREAD

**Issue by JediBai** [alibaba/BizCharts#955]
- bizcharts Version: 3.2.0
- Platform or react version: React-antd 3.8.0
- Mini Showcase(like screenshots):
![6J$%TBIDRA4A$GA9@VC)EUO](https://user-images.githubusercontent.com/31715147/64216888-79f23c00-ceed-11e9-8bfc-8d40b7c53305.png)
- 需求：坐标能否实现图中这样竖显示的文本效果

**Comment by ironicstone** [comment]
可以用<Label />的htmlTemplate，配合html和css很容易就做到了。

**Comment by JediBai** [comment]
> 可以用的htmlTemplate，配合html和css很容易就做到了。

能提供一个“栗”子么

**Comment by JediBai** [comment]
const label = {
      offset: 25,
      htmlTemplate(text, item, index) {
     	return '<div style="height: 20px">'+text +'</div>';
      }
    };

解决了
