### ISSUE TITLE
请问如何设置Guide text position？

### ISSUE THREAD

**Issue by kzabc** [alibaba/BizCharts#956]
`  <Guide>
                {/*x: (4) [0.16666666666666666, 0.525, 0.525, 0.16666666666666666]*/}
                {/*y: (4) [0.625, 0.625, 0.25, 0.25]*/}
                <Text
                  position={
                   [[0.16666666666666666, 0.525, 0.525, 0.16666666666666666],[0.625, 0.625, 0.25, 0.25]]
                  }
                  />
              </Guide>`

**Comment by ironicstone** [comment]
参考：https://bizcharts.net/products/bizCharts/api/guide#position
