### ISSUE TITLE
 bizcharts  有没有类似的ant pro design中的编辑器

### ISSUE THREAD

**Issue by kzabc** [alibaba/BizCharts#959]
![WeChata2af51d4bd9fa69f645270f388aa9411](https://user-images.githubusercontent.com/42925731/64403978-fb43fd00-d0ac-11e9-8c52-e20de0346c95.png)

**Comment by ironicstone** [comment]
暂时没有。

**Comment by Leannechn** [comment]
试一下 https://github.com/alibaba/GGEditor
