### ISSUE TITLE
如何展现分组柱状图,只能用dateSet处理吗,多个Geom柱状是堆叠起来的,设置adjust属性和type属性都显示堆叠

### ISSUE THREAD

**Issue by SaundersDong** [alibaba/BizCharts#97]

**Comment by weepy3641** [comment]
可以的。
如下是 g2 2.0 的实现，可以换成 bizcharts 去做。
http://antvis.github.io/g2/demo/04-bar/clustered-stacked-bar.html

下周 bizcharts 站点会加上这个 demo。

**Comment by SaundersDong** [comment]
好的,谢谢

**Comment by weepy3641** [comment]
@SaundersDong 
站点有这个demo，分组堆叠柱状图。
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/clustered-stacked
