### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by rex11458** [alibaba/BizCharts#98]
BizCharts ^3.0.5
react ^16.0.21

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getStyle (BizCharts.js?d7f9:6115)
    at Object.getWidth (BizCharts.js?d7f9:6153)
    at Chart.forceFit (BizCharts.js?d7f9:34984)
    at method (BizCharts.js?d7f9:1134)

**Comment by weepy3641** [comment]
What's the version of Bizcharts,  you can see the version in  node-modules bizcharts's package.json file.
Make sure the version > 3.1.0. 
Only BizCharts  > 3.1.0 is compatible with React16.
