### ISSUE TITLE
希望添加GuideHtml元素事件！！！！！！！！

### ISSUE THREAD

**Issue by wangjingithub** [alibaba/BizCharts#985]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by xiazhigithub** [comment]
请问你找到解决办法了吗

**Comment by ironicstone** [comment]
既然是html，直接使用dom事件即可
