### ISSUE TITLE
折线图，数据中key为日期，渲染错误

### ISSUE THREAD

**Issue by fatalxiao** [alibaba/BizCharts#988]
如果数据的`key`为普通字符串，可正确渲染（CodePen 例子中使用 `getData()` 生成的数据）
```
const data = [
    {cat: 'cat1', a: 1, b: 2, c: 3},
    {cat: 'cat2', a: 2, b: 4, c: 6},
    {cat: 'cat3', a: 3, b: 6, c: 9}
];
```
![image](https://user-images.githubusercontent.com/9260304/66629056-33ea6f80-ec33-11e9-98c0-5fb8e15f8245.png)

但如果`key`为日期字符串，渲染错误（CodePen 例子中使用 `getDateData()` 生成的数据）
```
const data = [
    {cat: 'cat1', '2019-07-01': 1, '2019-07-02': 2, '2019-07-03': 3},
    {cat: 'cat2', '2019-07-01': 2, '2019-07-02': 4, '2019-07-03': 6},
    {cat: 'cat3', '2019-07-01': 3, '2019-07-02': 6, '2019-07-03': 9}
];
```
![image](https://user-images.githubusercontent.com/9260304/66629086-4cf32080-ec33-11e9-8ab4-3c372453bfbb.png)

- CodePen Link: https://codepen.io/fatalxiao/pen/mddeGdO

**Comment by Leannechn** [comment]
默认日期类型的数据会解析成‘time’类型的比例尺。所以需要指定一下scale的type

<Chart scale={{ 'type': { type: 'cat' } }} .... />

scale={{ [字段名]: { type: cat-分类比例尺 } }}

**Comment by fatalxiao** [comment]
可以了，谢谢！
