### ISSUE TITLE
Cannot resolve dependency './factoryWithThrowingShims'

### ISSUE THREAD

**Issue by imdragonet** [alibaba/BizCharts#99]
node_modules/bizcharts/umd/BizCharts.js:328:27: Cannot resolve dependency './factoryWithThrowingShims'

**Comment by kiangtengl** [comment]
How did you resolve this?

**Comment by imdragonet** [comment]
I haven't resolve this. I am not quit sure about this so I closed.

**Comment by imdragonet** [comment]
https://github.com/prescottprue/react-redux-firebase/issues/128

make prop-types a peerDependency resolved this problem

**Comment by imdragonet** [comment]
I'll reopen this again. 
According to https://webpack.js.org/configuration/externals/ , prop-types should be added in webpack.config.js I tried locally and it works as expected.

**Comment by weepy3641** [comment]
@imdragonet   
bizcharts build  prop-types  in its packages。
so you means prop-types should be no be packed in  and use prop-types  externals？

**Comment by imdragonet** [comment]
Yes, as described in webpack's documentation, you should not package prop-types into your bundle, cause bizCharts is a library

**Comment by weepy3641** [comment]
Ok， Thanks。
Bizcharts will use prop-types as external lib in the next version 。

**Comment by weepy3641** [comment]
fix at 3.1.3
