### ISSUE TITLE
label 的 htmlTemplate 能否使用 react 组件

### ISSUE THREAD

**Issue by anran758** [alibaba/BizCharts#993]
- bizcharts Version: ^3.4.3
- Platform or react version:^16.7.0
- Mini Showcase(like screenshots):
- CodePen Link: https://codesandbox.io/s/confident-water-yvdom
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

---

问题已解决

**Comment by xclw2000** [comment]
咋解决的也不说一下
