### ISSUE TITLE
坐标轴刻度个数设置

### ISSUE THREAD

**Issue by yuexianqiang** [alibaba/BizCharts#994]
- bizcharts Version: 3.5.2
- Platform or react version:  react 16.8.6
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER
现有数据90条，横轴刻度显示如20191016，纵轴是数值，横轴设置刻度个数为10  tickCount: 10，
未生效，图例上刻度个数为9
![image](https://user-images.githubusercontent.com/27284446/67075649-2b0f1600-f1be-11e9-962f-41262c66205d.png)

**Comment by HoneyYue** [comment]
我现在也遇到相同得问题  tickCount 和 minLimit 同时设置了  x轴坐标点要不多了 要不就少了 很奇怪

**Comment by yuexianqiang** [comment]
> 我现在也遇到相同得问题 tickCount 和 minLimit 同时设置了 x轴坐标点要不多了 要不就少了 很奇怪

解决了吗

**Comment by HoneyYue** [comment]
没有  玩了大半个下午了 不知道怎么弄

**Comment by ironicstone** [comment]
@HoneyYue @yuexianqiang   底层计算逻辑是尽量找出显示比较nice的ticks，所以和tickCount并不总一致。如果你想完全控制每一个tick，可以在scale里配置ticks， 参考: https://bizcharts.net/products/bizCharts/api/chart?from=search#scale

**Comment by yuexianqiang** [comment]
> @HoneyYue @yuexianqiang 底层计算逻辑是尽量找出显示比较nice的ticks，所以和tickCount并不总一致。如果你想完全控制每一个tick，可以在scale里配置ticks， 参考: https://bizcharts.net/products/bizCharts/api/chart?from=search#scale

我现在的横轴数据是动态的，设置ticks还需要再去手动筛选一遍横轴显示的项！ 后期会考虑横轴数据强行均分吗？

**Comment by Leannechn** [comment]
tickCount是一个参考值。因为比如100，tick3，那么刻度会出现除不尽的小数。这时候就会进行调整，调整到一个接近3且合适的值。所以，要锁定刻度个数，那么只能项目默认接受出现除不尽的小数，并自行优化。且默认情况下轴刻度label，不改进行保留n位小数，tick轴是个标尺会影响图形绘制。

**Comment by arlendp** [comment]
那请问实际的tickCount怎么计算出来的呢，或者说有接口能获取到实际绘制出来的tickCount数吗

**Comment by kevinlvhsl** [comment]
tickCount 算法应该还有点问题。
传scale  time类型时
数据为 1号~24号的连续天数，tickCount: 5,     只展示了1，和24 两个ticks。
整除时一般都会有问题。
是否可以把ticks 参数加一个函数类型让用户自己定，ticks: () =>{ return [...]}

**Comment by chenxuanhanhao** [comment]
mark

**Comment by Leannechn** [comment]
#1334

**Comment by haohuaZhang** [comment]
tickMethod,https://www.bookstack.cn/read/g2-4.x/4f7256badbceaf9d.md#time
