### ISSUE TITLE
折线图7000点以上会严重卡顿，这个有解决方案么？

### ISSUE THREAD

**Issue by vn-liu** [alibaba/BizCharts#995]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by ironicstone** [comment]
数据量大了都会有问题。我试了2w点还好，可以把对应的geom的size调小点试试，参考：https://codesandbox.io/s/k5x3v51x1r?from-embed
