### ISSUE TITLE
堆积柱状图，数据总数大于一百，如何控制纵坐标只显示到一百，设置max不生效，请问一下，这个如何解决？

### ISSUE THREAD

**Issue by wo-de-ping-er** [alibaba/BizCharts#997]
- bizcharts Version:
- Platform or react version:
- Mini Showcase(like screenshots):
- CodePen Link:
- you can fork CodePen template from this: https://codepen.io/leslie2014/pen/xjJGER

**Comment by weepy3641** [comment]
不支持哦。
